
JAM.startProfile('load');
function v12(){document.forms[0].elements[0].value=" "}function v11(){try{JAM.startProfile('compute');windowExtract();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v10(){var v15=document.main_form.main_submit;JAM.call(v15.focus,v15,[],JAM.policy.p9)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p9)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v19=i<arrayOfTitles.length;v19;){v19=arrayOfTitles[i];v19=-1==JAM.call(v19.search,v19,[/\S/],JAM.policy.p9);v19||(v19=arrayOfSequences[i],(v19=-1==JAM.call(v19.search,v19,[/\S/],JAM.policy.p9))||(v19=arrayOfSequences[i].length!=lengthOfAlign));if(v19)return alert("There is a problem with the alignment format."),
!1;i+=1;v19=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v430=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p9);v430||(v430=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p9),v430||(v430=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p9),v430||(v430=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p9))||(v430=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p9))));return v430?(alert("The codon table has been entered incorrectly."),!1):
!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p9)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v24=z<arrayOfPatterns.length;v24;){v24=arrayOfPatterns[z];if(-1==JAM.call(v24.search,v24,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v24=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v24=0,v33=v24<arrayOfPatterns.length;v33;){var v33=z,v28=v24,v886=arrayOfPatterns[v24],v886=JAM.call(v886.match,v886,[/\/.+\//],JAM.policy.p9)+"gi",v886=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v886+" }"):JAM.call(eval,null,[v886]);v33[v28]=v886;v33=codon;v28=v24;v886=arrayOfPatterns[v24];v886=JAM.call(v886.match,v886,[/=[a-zA-Z\*]/],JAM.policy.p9);v886=JAM.call(v886.toString,
v886,[],JAM.policy.p9);v33[v28]=v886;v33=codon;v28=v24;v886=codon[v24];v886=JAM.call(v886.replace,v886,[/=/g,""],JAM.policy.p9);v33[v28]=v886;v24+=1;v33=v24<arrayOfPatterns.length}arrayOfPatterns=0;for(v24=arrayOfPatterns<=testSequence.length-3;v24;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p9);v24=0;for(v33=v24<z.length;v33;){if(-1!=JAM.call(codon.search,codon,[z[v24]],JAM.policy.p9)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v24+=1;v33=v24<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v24=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v42=z<arrayOfPatterns.length;v42;){v42=arrayOfPatterns[z];if(-1!=JAM.call(v42.search,v42,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p9))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v42=z<arrayOfPatterns.length}z=0;for(v42=z<arrayOfPatterns.length;v42;){for(var v42=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v45=j<arrayOfPatterns.length;v45;){v45=arrayOfPatterns[j];if(-1!=JAM.call(v45.search,v45,[v42],JAM.policy.p9))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v45=j<arrayOfPatterns.length}z+=1;v42=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v49=z<arrayOfPatterns.length;v49;){v49=arrayOfPatterns[z];if(-1==JAM.call(v49.search,v49,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v49=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v887=getSequenceFromFasta(text);return JAM.call(v887.replace,v887,[/[^A-Za-z]/g,""],JAM.policy.p9).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/2/g,"R"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/M/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/B/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p9);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p9)}
function closeForm(){var v54=outputWindow.document;JAM.call(v54.write,v54,["</form>"],JAM.policy.p9);return!0}function closePre(){var v55=outputWindow.document;JAM.call(v55.write,v55,["</div>"],JAM.policy.p9);v55=outputWindow.document;JAM.call(v55.write,v55,["</pre>\n"],JAM.policy.p9)}function closeTextArea(){var v57=outputWindow.document;JAM.call(v57.write,v57,["</textarea>"],JAM.policy.p9);return!0}
function closeWindow(){var v58=outputWindow.document;JAM.call(v58.write,v58,["</body>\n</html>\n"],JAM.policy.p9);outputWindow.status="Done.";v58=outputWindow.document;JAM.call(v58.close,v58,[],JAM.policy.p9)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p9);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p9)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v62=i<alignArray.length;v62;){v62=alignArray[i];if(-1==JAM.call(v62.search,v62,[/[^\s]+\s/],JAM.policy.p9))return alert("There is a problem with the alignment format."),!1;i+=1;v62=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p9)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p9);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p9)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9))for(var v64=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);v64;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p9),v64=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(){var fastaSequenceTitle=title,sequence=newProtein,stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v82=j<arrayOfPatterns.length;v82;){var v82=geneticCodeMatchExp,v81=j,v888=arrayOfPatterns[j],v888=JAM.call(v888.match,v888,[/\/.+\//],JAM.policy.p9)+"gi",v888=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v888+" }"):JAM.call(eval,null,[v888]);v82[v81]=v888;j+=1;v82=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v88=j<arrayOfPatterns.length;v88;){var v88=geneticCodeMatchResult,v85=j,v752=arrayOfPatterns[j],v752=JAM.call(v752.match,v752,[/=[a-zA-Z\*]/],JAM.policy.p9),v752=JAM.call(v752.toString,v752,[],JAM.policy.p9);v88[v85]=v752;v88=geneticCodeMatchResult;v85=j;v752=geneticCodeMatchResult[j];v752=JAM.call(v752.replace,v752,[/=/g,""],JAM.policy.p9);v88[v85]=v752;j+=1;v88=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(lengthOut){for(var components="ACDEFGHIKLMNPQRSTVWY".split(""),sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p9),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p9),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p9));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p9);v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p9),v518||(v518=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p9))||(v518=
-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p9))))))))));return v518?!1:!0}function openForm(){var v114=outputWindow.document;JAM.call(v114.write,v114,['<form action="">\n'],JAM.policy.p9);return!0}function openPre(){var v115=outputWindow.document;JAM.call(v115.write,v115,["<pre>"],JAM.policy.p9);v115=outputWindow.document;JAM.call(v115.write,v115,['<div class="pre">'],JAM.policy.p9)}
function openTextArea(){var v117=outputWindow.document;JAM.call(v117.write,v117,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p9);return!0}function openWindow(title){_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v118=outputWindow.document;JAM.call(v118.write,v118,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p9)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v126=outputWindow.document;JAM.call(v126.write,v126,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p9)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p9)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p9)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p9)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}
function removeNonProteinAllowDegen(){var sequence=newProtein;return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p9)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p9)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p9)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p9)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p9)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p9),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p9),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p10));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p9);for(var j=theNumber.length,v135=j<lengthOfColumn;v135;)tempString+=" ",j+=1,v135=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p9);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p9))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p9);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p9)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p9)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v533=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v533||(v533=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v533||(v533=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v533=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v533?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p9)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p9)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v538=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v538||(v538=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v538||(v538=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v538=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v538?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v539=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v539||(v539=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v539||(v539=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v539=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v539?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v541=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v541||(v541=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v541||(v541=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v541=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v541?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v163=startBase<stopBase;v163;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v163=1,v160=v163<=basePerLine/groupSize;v160;){for(v160=k<groupSize;v160;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v160=k<groupSize;startBase+=groupSize;k=0;lineOfText+=
sepChar;v163+=1;v160=v163<=basePerLine/groupSize}v163=outputWindow.document;JAM.call(v163.write,v163,[lineOfText+"\n"],JAM.policy.p9);lineOfText="";v163=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v546=0>adjustment;v546&&(v546=0<=adjusted);v546&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v173=j<=basePerLine/groupSize;v173;){for(v173=k<groupSize;v173&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v173=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v173=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v206=j<=basePerLine/groupSize;v206;){for(v206=k<groupSize;v206&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v206=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v206=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p9)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p9));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v563=sequence.length<=firstIndexToMutate;v563||(v563=0>lastIndexToMutate)||(v563=lastIndexToMutate<=firstIndexToMutate);v563&&(numMut=0);v563=0;for(randNum=v563<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*randNum],JAM.policy.p9);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p9);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p9)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p9)}v563+=1;randNum=v563<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p9);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p9),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p9);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p9)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p9);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p9)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p9);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p9);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p9));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v582=matchPosition>=lowerLimit;v582&&(v582=matchPosition<upperLimit);v582&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p9)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p9));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p9);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p9);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p9)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p9);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v261=outputWindow.document;JAM.call(v261.write,v261,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);v261=outputWindow.document;JAM.call(v261.write,v261,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p9);for(var v261=0,v272=v261<arrayOfItems.length;v272;){var v272=0,v591=arrayOfItems[v261],v591=
JAM.call(v591.match,v591,[/\/[^\/]+\//],JAM.policy.p9)+"gi",v591=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v591+" }"):JAM.call(eval,null,[v591]);-1!=JAM.call(sequence.search,sequence,[v591],JAM.policy.p9)&&(v272=JAM.call(sequence.match,sequence,[v591],JAM.policy.p9).length);var v591=0,v796=originalLength+1,v1010=arrayOfItems[v261];0<v796-parseFloat(JAM.call(v1010.match,v1010,[/\d+/],JAM.policy.p9))&&(v591=100*v272,v796=originalLength+1,v1010=arrayOfItems[v261],v591/=v796-parseFloat(JAM.call(v1010.match,
v1010,[/\d+/],JAM.policy.p9)));v796=outputWindow.document;v1010=arrayOfItems[v261];v1010=JAM.call(v1010.match,v1010,[/\([^\(]+\)\b/],JAM.policy.p9);v1010=JAM.call(v1010.toString,v1010,[],JAM.policy.p9);JAM.call(v796.write,v796,["<tr><td>"+JAM.call(v1010.replace,v1010,[/\(|\)/g,""],JAM.policy.p9)+"</td><td>"+v272+"</td><td>"+JAM.call(v591.toFixed,v591,[2],JAM.policy.p9)+"</td></tr>\n"],JAM.policy.p9);v261+=1;v272=v261<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,
originalLength,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*tempChar],JAM.policy.p9),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p9),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p9),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p9),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p9),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p9);return!0}
function windowExtract(){var theDocument=document,maxInput=5E5,ranges=[];if(!1!=testScript()){var v603=!1==checkFormElement(theDocument.forms[0].elements[0]);v603||(v603=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxInput),v603||(v603=!1==checkFormElement(theDocument.forms[0].elements[1]),v603||(v603=!1==checkFormElement(theDocument.forms[0].elements[3]),v603||(v603=theDocument.forms[0].elements[1].value,v603=!1==verifyMaxDigits(JAM.call(v603.replace,v603,[/[^\d]/g,""],JAM.policy.p9),
maxInput),v603||(v603=theDocument.forms[0].elements[3].value,v603=!1==verifyMaxDigits(JAM.call(v603.replace,v603,[/[^\d]/g,""],JAM.policy.p9),maxInput))))));if(!v603){var maxInput=theDocument.forms[0].elements[1].value,maxInput=parseInt(JAM.call(maxInput.replace,maxInput,[/[^\d]/g,""],JAM.policy.p9)),v603=theDocument.forms[0].elements[3].value,v603=parseInt(JAM.call(v603.replace,v603,[/[^\d]/g,""],JAM.policy.p9)),orientation=theDocument.forms[0].elements[2].value,start,end;"ending"==orientation?(end=
v603,start=end-maxInput+1):"starting"==orientation?(start=v603,end=start+maxInput-1):"centered"==orientation&&(start=v603-JAM.call(Math.round,Math,[maxInput/2],JAM.policy.p9)+1,end=start+maxInput-1);JAM.call(ranges.push,ranges,[new Range(start,end)],JAM.policy.p9);openWindow("Window Extractor Protein");openPre();start=getArrayOfFasta(theDocument.forms[0].elements[0].value);end=0;for(maxInput=end<start.length;maxInput;)newProtein=getSequenceFromFasta(start[end]),title=getTitleFromFasta(start[end]),
newProtein=removeNonProteinAllowDegen(),maxInput=outputWindow.document,JAM.call(maxInput.write,maxInput,[getFastaTitleFromTitleAndSequence()],JAM.policy.p9),writeSequenceRanges(ranges,theDocument.forms[0].elements[7].options[theDocument.forms[0].elements[7].selectedIndex].value),end+=1,maxInput=end<start.length;closePre();closeWindow()}}}
function rangeExtract(theDocument){var maxInput=5E5,matchFound=!1,ranges=[];if(!1==testScript())return!1;var v614=!1==checkFormElement(theDocument.forms[0].elements[0]);v614||((maxInput=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxInput))||(maxInput=!1==checkFormElement(theDocument.forms[0].elements[1])),v614=maxInput);if(v614)return!1;var maxInput=theDocument.forms[0].elements[1].value,v614=JAM.call(maxInput.split,maxInput,[/,/],JAM.policy.p9),arrayOfStartAndEnd,maxInput=0;for(arrayOfStartAndEnd=
maxInput<v614.length;arrayOfStartAndEnd;)arrayOfStartAndEnd=v614[maxInput],arrayOfStartAndEnd=JAM.call(arrayOfStartAndEnd.split,arrayOfStartAndEnd,[/\.\./],JAM.policy.p9),1==arrayOfStartAndEnd.length?(matchFound=!0,JAM.call(ranges.push,ranges,[new Range(arrayOfStartAndEnd[0],arrayOfStartAndEnd[0])],JAM.policy.p9)):2==arrayOfStartAndEnd.length&&(matchFound=!0,JAM.call(ranges.push,ranges,[new Range(arrayOfStartAndEnd[0],arrayOfStartAndEnd[1])],JAM.policy.p9)),maxInput+=1,arrayOfStartAndEnd=maxInput<
v614.length;if(!1==matchFound)return alert("No ranges were entered."),!1;openWindow("Range Extractor Protein");openPre();matchFound=getArrayOfFasta(theDocument.forms[0].elements[0].value);maxInput=0;for(v614=maxInput<matchFound.length;v614;)newProtein=getSequenceFromFasta(matchFound[maxInput]),title=getTitleFromFasta(matchFound[maxInput]),newProtein=removeNonProteinAllowDegen(),v614=outputWindow.document,JAM.call(v614.write,v614,[getFastaTitleFromTitleAndSequence()],JAM.policy.p9),writeSequenceRanges(ranges,
theDocument.forms[0].elements[5].options[theDocument.forms[0].elements[5].selectedIndex].value),maxInput+=1,v614=maxInput<matchFound.length;closePre();closeWindow();return!0}
function writeSequenceRanges(ranges,segmentType){for(var sequence=newProtein,rangeGroup=new RangeGroup(segmentType),center_base=JAM.call(Math.round,Math,[sequence.length/2],JAM.policy.p9),i=0,v334=i<ranges.length;v334;){var v334=ranges[i],v818=ranges[i].start,v818=JAM.call(v818.toString,v818,[],JAM.policy.p9),v818=JAM.call(v818.replace,v818,[/start|begin/gi,1],JAM.policy.p9);v334.start=v818;v334=ranges[i];v818=ranges[i].start;v818=JAM.call(v818.toString,v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,
v818,[/stop|end/gi,sequence.length],JAM.policy.p9);v334.start=v818;v334=ranges[i];v818=ranges[i].start;v818=JAM.call(v818.toString,v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/length/gi,sequence.length],JAM.policy.p9);v334.start=v818;v334=ranges[i];v818=ranges[i].start;v818=JAM.call(v818.toString,v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/middle|center|centre/gi,center_base],JAM.policy.p9);v334.start=v818;v334=ranges[i];v818=ranges[i].stop;v818=JAM.call(v818.toString,v818,
[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/start|begin/gi,1],JAM.policy.p9);v334.stop=v818;v334=ranges[i];v818=ranges[i].stop;v818=JAM.call(v818.toString,v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/stop|end/gi,sequence.length],JAM.policy.p9);v334.stop=v818;v334=ranges[i];v818=ranges[i].stop;v818=JAM.call(v818.toString,v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/length/gi,sequence.length],JAM.policy.p9);v334.stop=v818;v334=ranges[i];v818=ranges[i].stop;v818=JAM.call(v818.toString,
v818,[],JAM.policy.p9);v818=JAM.call(v818.replace,v818,[/middle|center|centre/gi,center_base],JAM.policy.p9);v334.stop=v818;try{var v329=ranges[i],v949=ranges[i].start,v826=JAM.call(v949.toString,v949,[],JAM.policy.p9),v642=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v826+" }"):JAM.call(eval,null,[v826]),v1221=parseInt(v642);v329.start=v1221}catch(e){alert("Could not evaluate the following expression: "+ranges[i].start);return}try{var v331=ranges[i],v950=ranges[i].stop,v828=JAM.call(v950.toString,
v950,[],JAM.policy.p9),v644=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v828+" }"):JAM.call(eval,null,[v828]),v1222=parseInt(v644);v331.stop=v1222}catch(e$$0){alert("Could not evaluate the following expression: "+ranges[i].stop);return}JAM.call(rangeGroup.addRange,rangeGroup,[ranges[i]],JAM.policy.p9);i+=1;v334=i<ranges.length}JAM.call(rangeGroup.writeRanges,rangeGroup,[sequence],JAM.policy.p9)}
function getSequence(sequence){var problem=!1,warnings=[];this.start==this.stop?(1>this.start&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is less than 1"],JAM.policy.p9)),this.start>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is greater than the sequence length"],JAM.policy.p9))):(1>this.start&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is less than 1"],JAM.policy.p9)),1>this.stop&&
(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.stop+" is less than 1"],JAM.policy.p9)),this.start>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is greater than the sequence length"],JAM.policy.p9)),this.stop>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.stop+" is greater than the sequence length"],JAM.policy.p9)),this.start>this.stop&&(problem=!0,JAM.call(warnings.push,warnings,["stop position is less than start position in range "+
this.start+" to "+this.stop],JAM.policy.p9)));return problem?(alert("An entry was skipped because of the following:\n"+JAM.call(warnings.join,warnings,[",\n"],JAM.policy.p9)),!1):this.start==this.stop?JAM.call(sequence.charAt,sequence,[this.start-1],JAM.policy.p9):JAM.call(sequence.substring,sequence,[this.start-1,this.stop],JAM.policy.p9)}function getTitle(){return this.start==this.stop?"&gt;residue "+this.start:"&gt;residue "+this.start+" to "+this.stop}
function Range(start,stop){this.start=start;this.stop=stop}function addRange(range){var v359=this.ranges;JAM.call(v359.push,v359,[range],JAM.policy.p9)}
function writeRanges(sequence){function v9(str,p1,offset,s){return JAM.call(sequence.substring,sequence,[offset,offset+p1.length],JAM.policy.p9)}function v8(str,p1,p2,offset,s){return p1+JAM.call(sequence.substring,sequence,[p1.length,p1.length+p2.length],JAM.policy.p9)}function v7(str,p1,offset,s){return getRandomSequence(p1.length)}function v6(str,p1,p2,offset,s){return p1+getRandomSequence(p2.length)}function v5(str,p1,offset,s){return JAM.call(p1.toLowerCase,p1,[],JAM.policy.p9)}function v4(str,
p1,p2,offset,s){return p1+JAM.call(p2.toLowerCase,p2,[],JAM.policy.p9)}function v3(str,p1,offset,s){return JAM.call(p1.toUpperCase,p1,[],JAM.policy.p9)}function v2(str,p1,p2,offset,s){return p1+JAM.call(p2.toUpperCase,p2,[],JAM.policy.p9)}var sequenceArray=[];if("new_sequence"==this.type){for(var i=0,v373=i<this.ranges.length;v373;)v373=this.ranges[i],""!=JAM.call(v373.getSequence,v373,[sequence],JAM.policy.p9)&&(v373=this.ranges[i],JAM.call(sequenceArray.push,sequenceArray,[JAM.call(v373.getSequence,
v373,[sequence],JAM.policy.p9)],JAM.policy.p9)),i+=1,v373=i<this.ranges.length;i=outputWindow.document;JAM.call(i.write,i,[addReturns(JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10))+"\n\n"],JAM.policy.p9);return!0}if("separate"==this.type){i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(sequenceArray=outputWindow.document,v373=this.ranges[i],JAM.call(sequenceArray.write,
sequenceArray,[JAM.call(v373.getTitle,v373,[],JAM.policy.p9)+"\n"],JAM.policy.p9),sequenceArray=outputWindow.document,v373=this.ranges[i],JAM.call(sequenceArray.write,sequenceArray,[addReturns(JAM.call(v373.getSequence,v373,[sequence],JAM.policy.p9))+"\n\n"],JAM.policy.p9)),i+=1,sequenceArray=i<this.ranges.length;return!0}if("uppercased"==this.type){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],
""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v373="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,sequence,[v373,v2],JAM.policy.p9)):(v373="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,sequence,[v373,v3],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;i=outputWindow.document;
JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9);return!0}if("lowercased"==this.type){sequence=JAM.call(sequence.toUpperCase,sequence,[],JAM.policy.p9);i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v373="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,
sequence,[v373,v4],JAM.policy.p9)):(v373="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,sequence,[v373,v5],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;i=outputWindow.document;JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9);return!0}if("randomized"==this.type){i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],
JAM.policy.p9)&&(1<this.ranges[i].start?(v373="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,sequence,[v373,v6],JAM.policy.p9)):(v373="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequence=JAM.call(sequence.replace,sequence,[v373,v7],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;i=outputWindow.document;JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9);
return!0}if("preserved"==this.type){sequenceArray=getRandomSequence(sequence.length);i=0;for(v373=i<this.ranges.length;v373;)v373=this.ranges[i],""!=JAM.call(v373.getSequence,v373,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v373="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),sequenceArray=JAM.call(sequenceArray.replace,sequenceArray,[v373,v8],JAM.policy.p9)):(v373="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v373=RegExp(v373),
sequenceArray=JAM.call(sequenceArray.replace,sequenceArray,[v373,v9],JAM.policy.p9))),i+=1,v373=i<this.ranges.length;i=outputWindow.document;JAM.call(i.write,i,[addReturns(sequenceArray)+"\n\n"],JAM.policy.p9);return!0}}function RangeGroup(type){this.type=type;this.ranges=type=[]}new Range(0,0);Range.prototype.getSequence=getSequence;Range.prototype.getTitle=getTitle;new RangeGroup("","");RangeGroup.prototype.addRange=addRange;RangeGroup.prototype.writeRanges=writeRanges;
JAM.set(document,"onload",v10);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p9),"onclick",v11);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p9),"onclick",v12);

JAM.stopProfile('load');
