
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" ";document.forms[0].elements[4].value=" "}function v3(){try{JAM.startProfile('compute');fuzzySearchProtein();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){var v8=document.main_form.main_submit;JAM.call(v8.focus,v8,[],JAM.policy.p15)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p15)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v12=i<arrayOfTitles.length;v12;){v12=arrayOfTitles[i];v12=-1==JAM.call(v12.search,v12,[/\S/],JAM.policy.p15);v12||(v12=arrayOfSequences[i],(v12=-1==JAM.call(v12.search,v12,[/\S/],JAM.policy.p15))||(v12=arrayOfSequences[i].length!=lengthOfAlign));if(v12)return alert("There is a problem with the alignment format."),
!1;i+=1;v12=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v438=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p15);v438||(v438=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p15),v438||(v438=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p15),v438||(v438=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p15))||(v438=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p15))));return v438?(alert("The codon table has been entered incorrectly."),
!1):!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p15)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v17=z<arrayOfPatterns.length;v17;){v17=arrayOfPatterns[z];if(-1==JAM.call(v17.search,v17,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p15)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v17=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v17=0,v26=v17<arrayOfPatterns.length;v26;){var v26=z,v21=v17,v974=arrayOfPatterns[v17],v974=JAM.call(v974.match,v974,[/\/.+\//],JAM.policy.p15)+"gi",v974=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v974+" }"):JAM.call(eval,null,[v974]);v26[v21]=v974;v26=codon;v21=v17;v974=arrayOfPatterns[v17];v974=JAM.call(v974.match,v974,[/=[a-zA-Z\*]/],JAM.policy.p15);v974=JAM.call(v974.toString,
v974,[],JAM.policy.p15);v26[v21]=v974;v26=codon;v21=v17;v974=codon[v17];v974=JAM.call(v974.replace,v974,[/=/g,""],JAM.policy.p15);v26[v21]=v974;v17+=1;v26=v17<arrayOfPatterns.length}arrayOfPatterns=0;for(v17=arrayOfPatterns<=testSequence.length-3;v17;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p15);v17=0;for(v26=v17<z.length;v26;){if(-1!=JAM.call(codon.search,codon,[z[v17]],JAM.policy.p15)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v17+=1;v26=v17<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v17=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v35=z<arrayOfPatterns.length;v35;){v35=arrayOfPatterns[z];if(-1!=JAM.call(v35.search,v35,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p15))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v35=z<arrayOfPatterns.length}z=0;for(v35=z<arrayOfPatterns.length;v35;){for(var v35=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v38=j<arrayOfPatterns.length;v38;){v38=arrayOfPatterns[j];if(-1!=JAM.call(v38.search,v38,[v35],JAM.policy.p15))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v38=j<arrayOfPatterns.length}z+=1;v35=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v42=z<arrayOfPatterns.length;v42;){v42=arrayOfPatterns[z];if(-1==JAM.call(v42.search,v42,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p15)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v42=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v975=getSequenceFromFasta(text);return JAM.call(v975.replace,v975,[/[^A-Za-z]/g,""],JAM.policy.p15).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p15);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],
JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p15);dnaSequence=
JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"R"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/M/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],
JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/B/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p15);dnaSequence=
JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p15);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p15);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p15)}
function closeForm(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</form>"],JAM.policy.p15);return!0}function closePre(){var v48=outputWindow.document;JAM.call(v48.write,v48,["</div>"],JAM.policy.p15);v48=outputWindow.document;JAM.call(v48.write,v48,["</pre>\n"],JAM.policy.p15)}function closeTextArea(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</textarea>"],JAM.policy.p15);return!0}
function closeWindow(){var v51=outputWindow.document;JAM.call(v51.write,v51,["</body>\n</html>\n"],JAM.policy.p15);outputWindow.status="Done.";v51=outputWindow.document;JAM.call(v51.close,v51,[],JAM.policy.p15)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p15);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p15);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p15)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v55=i<alignArray.length;v55;){v55=alignArray[i];if(-1==JAM.call(v55.search,v55,[/[^\s]+\s/],JAM.policy.p15))return alert("There is a problem with the alignment format."),!1;i+=1;v55=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p15)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p15);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p15);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p15);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p15)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p15))for(var v57=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p15);v57;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p15),v57=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p15);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p15)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p15)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p15)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v75=j<arrayOfPatterns.length;v75;){var v75=geneticCodeMatchExp,v74=j,v976=arrayOfPatterns[j],v976=JAM.call(v976.match,v976,[/\/.+\//],JAM.policy.p15)+"gi",v976=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v976+" }"):JAM.call(eval,null,[v976]);v75[v74]=v976;j+=1;v75=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v81=j<arrayOfPatterns.length;v81;){var v81=geneticCodeMatchResult,v78=j,v780=arrayOfPatterns[j],v780=JAM.call(v780.match,v780,[/=[a-zA-Z\*]/],JAM.policy.p15),v780=JAM.call(v780.toString,v780,[],JAM.policy.p15);v81[v78]=v780;v81=geneticCodeMatchResult;v78=j;v780=geneticCodeMatchResult[j];v780=JAM.call(v780.replace,v780,[/=/g,""],JAM.policy.p15);v81[v78]=v780;j+=1;v81=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p15)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p15)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p15)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p15)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p15)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p15)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p15)*components.length],JAM.policy.p15),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p15),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p16)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p15)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p15));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p15)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p15),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p15),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p15),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p15),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p15));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p15);v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p15),v526||(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p15))||
(v526=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p15))))))))));return v526?!1:!0}function openForm(){var v107=outputWindow.document;JAM.call(v107.write,v107,['<form action="">\n'],JAM.policy.p15);return!0}function openPre(){var v108=outputWindow.document;JAM.call(v108.write,v108,["<pre>"],JAM.policy.p15);v108=outputWindow.document;JAM.call(v108.write,v108,['<div class="pre">'],JAM.policy.p15)}
function openTextArea(){var v110=outputWindow.document;JAM.call(v110.write,v110,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p15);return!0}function openWindow(){var title="Fuzzy Protein DNA";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p16);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p15);var v111=outputWindow.document;JAM.call(v111.write,v111,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p15);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p15)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p15));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p15);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p16);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p15);var v119=outputWindow.document;JAM.call(v119.write,v119,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p15);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p15)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p15));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p15);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p15)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p15)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p15)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p15)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p15)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p15)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p15)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p15)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p15)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p15)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p15),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p15),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p16));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p15);for(var j=theNumber.length,v128=j<lengthOfColumn;v128;)tempString+=" ",j+=1,v128=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p15);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p15))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p15);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p15)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p15)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p15))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v541=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p15);v541||(v541=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p15),v541||(v541=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p15))||(v541=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p15)));return v541?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p15))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p15)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p15)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v546=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p15);v546||(v546=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p15),v546||(v546=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p15))||(v546=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p15)));return v546?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v547=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p15);v547||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p15),v547||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p15))||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p15)));return v547?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p15)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v549=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p15);v549||(v549=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p15),v549||(v549=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p15))||(v549=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p15)));return v549?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p15)?(alert("The file has no defined features."),!1):
!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v156=startBase<stopBase;v156;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v156=1,v153=v156<=basePerLine/groupSize;v153;){for(v153=k<groupSize;v153;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p15),k+=1,v153=k<groupSize;startBase+=groupSize;k=0;lineOfText+=sepChar;
v156+=1;v153=v156<=basePerLine/groupSize}v156=outputWindow.document;JAM.call(v156.write,v156,[lineOfText+"\n"],JAM.policy.p15);lineOfText="";v156=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v554=0>adjustment;v554&&(v554=0<=adjusted);v554&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v166=j<=basePerLine/groupSize;v166;){for(v166=k<groupSize;v166&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p15),k+=1,v166=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v166=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p15),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p15),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p15))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p15),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p15),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p15))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p15),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p15),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p15),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p15)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v199=j<=basePerLine/groupSize;v199;){for(v199=k<groupSize;v199&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p15),k+=1,v199=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v199=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p15)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p15)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p15),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p15));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v571=sequence.length<=firstIndexToMutate;v571||(v571=0>lastIndexToMutate)||(v571=lastIndexToMutate<=firstIndexToMutate);v571&&(numMut=0);v571=0;for(randNum=v571<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p15)*randNum],JAM.policy.p15);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p15);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p15)*components.length],JAM.policy.p15),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p15)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p15)}v571+=1;randNum=v571<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p15);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p15)*components.length],JAM.policy.p15),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p15),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p15);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p15).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p15)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p15),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p15);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p15);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p15)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p15);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p15);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p15));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p15);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v590=matchPosition>=lowerLimit;v590&&(v590=matchPosition<upperLimit);v590&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p15)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p15)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p15));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p15);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p15);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p15)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p15);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p15);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v254=outputWindow.document;JAM.call(v254.write,v254,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p15);v254=outputWindow.document;JAM.call(v254.write,v254,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p15);for(var v254=0,v265=v254<arrayOfItems.length;v265;){var v265=0,v599=arrayOfItems[v254],
v599=JAM.call(v599.match,v599,[/\/[^\/]+\//],JAM.policy.p15)+"gi",v599=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v599+" }"):JAM.call(eval,null,[v599]);-1!=JAM.call(sequence.search,sequence,[v599],JAM.policy.p15)&&(v265=JAM.call(sequence.match,sequence,[v599],JAM.policy.p15).length);var v599=0,v824=originalLength+1,v1097=arrayOfItems[v254];0<v824-parseFloat(JAM.call(v1097.match,v1097,[/\d+/],JAM.policy.p15))&&(v599=100*v265,v824=originalLength+1,v1097=arrayOfItems[v254],v599/=v824-parseFloat(JAM.call(v1097.match,
v1097,[/\d+/],JAM.policy.p15)));v824=outputWindow.document;v1097=arrayOfItems[v254];v1097=JAM.call(v1097.match,v1097,[/\([^\(]+\)\b/],JAM.policy.p15);v1097=JAM.call(v1097.toString,v1097,[],JAM.policy.p15);JAM.call(v824.write,v824,["<tr><td>"+JAM.call(v1097.replace,v1097,[/\(|\)/g,""],JAM.policy.p15)+"</td><td>"+v265+"</td><td>"+JAM.call(v599.toFixed,v599,[2],JAM.policy.p15)+"</td></tr>\n"],JAM.policy.p15);v254+=1;v265=v254<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,
originalLength,["</tbody></table>\n"],JAM.policy.p15);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p15)*tempChar],JAM.policy.p15),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p15),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p15),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p15),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p15),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p15);return!0}
function fuzzySearchProtein(){var theDocument=document,targetSequence="",targetTitle="",querySequence="",queryTitle="",targetTitle=2E3,targetSequence=30;if(!1!=testScript()&&(querySequence=!1==checkFormElement(theDocument.forms[0].elements[0]),querySequence||(targetTitle=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,targetTitle),targetTitle||(targetTitle=!1==checkFormElement(theDocument.forms[0].elements[1]))||(targetTitle=!1==checkSequenceLength(theDocument.forms[0].elements[1].value,
targetSequence)),querySequence=targetTitle),!querySequence)){var MATRIX=theDocument.forms[0].elements[5].options[theDocument.forms[0].elements[5].selectedIndex].value,GAP_PENALTY=parseInt(theDocument.forms[0].elements[6].options[theDocument.forms[0].elements[6].selectedIndex].value),HITS=parseInt(theDocument.forms[0].elements[7].options[theDocument.forms[0].elements[7].selectedIndex].value);openWindow();openPre();targetSequence=getSequenceFromFasta(theDocument.forms[0].elements[0].value);targetSequence=
removeNonProtein(targetSequence);targetTitle=getTitleFromFasta(theDocument.forms[0].elements[0].value);querySequence=getSequenceFromFasta(theDocument.forms[0].elements[1].value);querySequence=removeNonProtein(querySequence);queryTitle="query";theDocument=outputWindow.document;JAM.call(theDocument.write,theDocument,[getFuzzySearchTitle(targetTitle,targetSequence,queryTitle,querySequence)],JAM.policy.p15);-1!=JAM.call(targetSequence.search,targetSequence,[/./],JAM.policy.p15)&&(targetSequence=JAM.call(targetSequence.match,
targetSequence,[/./g],JAM.policy.p15));-1!=JAM.call(querySequence.search,querySequence,[/./],JAM.policy.p15)&&(querySequence=JAM.call(querySequence.match,querySequence,[/./g],JAM.policy.p15));0==targetSequence.length?alert("The sequence contains no protein residues."):0==querySequence.length?alert("The query sequence contains no protein residues."):(_fuzzySearchProtein(queryTitle,querySequence,targetTitle,targetSequence,MATRIX,GAP_PENALTY,HITS),closePre(),closeWindow())}}
function _fuzzySearchProtein(queryTitle,querySequence,targetTitle,targetSequence,matrix,gapPenalty,hits){var scoringMatrix;"pam30"==matrix?scoringMatrix=new Pam30:"pam70"==matrix?scoringMatrix=new Pam70:"blosum80"==matrix?scoringMatrix=new Blosum80:"blosum62"==matrix?scoringMatrix=new Blosum62:"blosum45"==matrix&&(scoringMatrix=new Blosum45);matrix=new ScoreSet;JAM.call(matrix.setScoreSetParam,matrix,[scoringMatrix,gapPenalty,hits],JAM.policy.p15);hits=new FuzzySearch;JAM.call(hits.initializeMatrix,
hits,[querySequence,targetSequence,matrix],JAM.policy.p15);JAM.call(hits.search,hits,[],JAM.policy.p15);hits=JAM.call(hits.getHits,hits,[],JAM.policy.p15);if(0<hits.length)for(querySequence=0,targetSequence=querySequence<hits.length;targetSequence;)targetSequence=outputWindow.document,JAM.call(targetSequence.write,targetSequence,[">"+queryTitle+" from "+hits[querySequence].startM+" to "+hits[querySequence].endM+"\n"],JAM.policy.p15),targetSequence=outputWindow.document,JAM.call(targetSequence.write,
targetSequence,[hits[querySequence].sequenceM+"\n"],JAM.policy.p15),targetSequence=outputWindow.document,JAM.call(targetSequence.write,targetSequence,[">"+targetTitle+" from "+hits[querySequence].startN+" to "+hits[querySequence].endN+"\n"],JAM.policy.p15),targetSequence=outputWindow.document,JAM.call(targetSequence.write,targetSequence,[hits[querySequence].sequenceN+"\n"],JAM.policy.p15),targetSequence=outputWindow.document,JAM.call(targetSequence.write,targetSequence,["Score: "+hits[querySequence].score+
"\n\n"],JAM.policy.p15),querySequence+=1,targetSequence=querySequence<hits.length;else queryTitle=outputWindow.document,JAM.call(queryTitle.write,queryTitle,["No hits were obtained.\n\n"],JAM.policy.p15)}function getScore(r1,r2){var v308=this.scoringMatrix;return JAM.call(v308.scoringMatrix_getScore,v308,[r1,r2],JAM.policy.p15)}function setScoreSetParam(scoringMatrix,gapPenalty,hits){this.scoringMatrix=scoringMatrix;this.gap=gapPenalty;this.hits=hits}function ScoreSet(){}
function scoringMatrix_getScore(r1,r2){r1=JAM.call(r1.toLowerCase,r1,[],JAM.policy.p15);r2=JAM.call(r2.toLowerCase,r2,[],JAM.policy.p15);if(null==this.scoreHash[r1+r2])throw"Unrecognized residue pair: "+r1+", "+r2+".";return this.scoreHash[r1+r2]}
function scoringMatrix_fillHash(matrix){var v313=matrix[0],v313=JAM.call(v313.split,v313,[/\s+/],JAM.policy.p15),cells,i=1;for(cells=i<matrix.length;cells;){cells=matrix[i];cells=JAM.call(cells.split,cells,[/\s+/],JAM.policy.p15);for(var j=1,v317=j<v313.length+1;v317;){var v317=this.scoreHash,v852=cells[0],v852=JAM.call(v852.toLowerCase,v852,[],JAM.policy.p15),v853=v313[j-1],v852=v852+JAM.call(v853.toLowerCase,v853,[],JAM.policy.p15),v853=parseInt(cells[j]);JAM.set(v317,v852,v853,JAM.policy.p6);j+=
1;v317=j<v313.length+1}i+=1;cells=i<matrix.length}}function ScoringMatrix(){this.scoreHash={}}
function Blosum62(){var matrix="A  R  N  D  C  Q  E  G  H  I  L  K  M  F  P  S  T  W  Y  V;A  4 -1 -2 -2  0 -1 -1  0 -2 -1 -1 -1 -1 -2 -1  1  0 -3 -2  0;R -1  5  0 -2 -3  1  0 -2  0 -3 -2  2 -1 -3 -2 -1 -1 -3 -2 -3;N -2  0  6  1 -3  0  0  0  1 -3 -3  0 -2 -3 -2  1  0 -4 -2 -3;D -2 -2  1  6 -3  0  2 -1 -1 -3 -4 -1 -3 -3 -1  0 -1 -4 -3 -3;C  0 -3 -3 -3  9 -3 -4 -3 -3 -1 -1 -3 -1 -2 -3 -1 -1 -2 -2 -1;Q -1  1  0  0 -3  5  2 -2  0 -3 -2  1  0 -3 -1  0 -1 -2 -1 -2;E -1  0  0  2 -4  2  5 -2  0 -3 -3  1 -2 -3 -1  0 -1 -3 -2 -2;G  0 -2  0 -1 -3 -2 -2  6 -2 -4 -4 -2 -3 -3 -2  0 -2 -2 -3 -3;H -2  0  1 -1 -3  0  0 -2  8 -3 -3 -1 -2 -1 -2 -1 -2 -2  2 -3;I -1 -3 -3 -3 -1 -3 -3 -4 -3  4  2 -3  1  0 -3 -2 -1 -3 -1  3;L -1 -2 -3 -4 -1 -2 -3 -4 -3  2  4 -2  2  0 -3 -2 -1 -2 -1  1;K -1  2  0 -1 -3  1  1 -2 -1 -3 -2  5 -1 -3 -1  0 -1 -3 -2 -2;M -1 -1 -2 -3 -1  0 -2 -3 -2  1  2 -1  5  0 -2 -1 -1 -1 -1  1;F -2 -3 -3 -3 -2 -3 -3 -3 -1  0  0 -3  0  6 -4 -2 -2  1  3 -1;P -1 -2 -2 -1 -3 -1 -1 -2 -2 -3 -3 -1 -2 -4  7 -1 -1 -4 -3 -2;S  1 -1  1  0 -1  0  0  0 -1 -2 -2  0 -1 -2 -1  4  1 -3 -2 -2;T  0 -1  0 -1 -1 -1 -1 -2 -2 -1 -1 -1 -1 -2 -1  1  5 -2 -2  0;W -3 -3 -4 -4 -2 -2 -3 -2 -2 -3 -2 -3 -1  1 -4 -3 -2 11  2 -3;Y -2 -2 -2 -3 -2 -1 -2 -3  2 -1 -1 -2 -1  3 -3 -2 -2  2  7 -1;V  0 -3 -3 -3 -1 -2 -2 -3 -3  3  1 -2  1 -1 -2 -2  0 -3 -1  4".split(";");JAM.call(this.scoringMatrix_fillHash,
this,[matrix],JAM.policy.p15)}
function Blosum45(){var matrix="A  R  N  D  C  Q  E  G  H  I  L  K  M  F  P  S  T  W  Y  V;A  5 -2 -1 -2 -1 -1 -1  0 -2 -1 -1 -1 -1 -2 -1  1  0 -2 -2  0;R -2  7  0 -1 -3  1  0 -2  0 -3 -2  3 -1 -2 -2 -1 -1 -2 -1 -2;N -1  0  6  2 -2  0  0  0  1 -2 -3  0 -2 -2 -2  1  0 -4 -2 -3;D -2 -1  2  7 -3  0  2 -1  0 -4 -3  0 -3 -4 -1  0 -1 -4 -2 -3;C -1 -3 -2 -3 12 -3 -3 -3 -3 -3 -2 -3 -2 -2 -4 -1 -1 -5 -3 -1;Q -1  1  0  0 -3  6  2 -2  1 -2 -2  1  0 -4 -1  0 -1 -2 -1 -3;E -1  0  0  2 -3  2  6 -2  0 -3 -2  1 -2 -3  0  0 -1 -3 -2 -3;G  0 -2  0 -1 -3 -2 -2  7 -2 -4 -3 -2 -2 -3 -2  0 -2 -2 -3 -3;H -2  0  1  0 -3  1  0 -2 10 -3 -2 -1  0 -2 -2 -1 -2 -3  2 -3;I -1 -3 -2 -4 -3 -2 -3 -4 -3  5  2 -3  2  0 -2 -2 -1 -2  0  3;L -1 -2 -3 -3 -2 -2 -2 -3 -2  2  5 -3  2  1 -3 -3 -1 -2  0  1;K -1  3  0  0 -3  1  1 -2 -1 -3 -3  5 -1 -3 -1 -1 -1 -2 -1 -2;M -1 -1 -2 -3 -2  0 -2 -2  0  2  2 -1  6  0 -2 -2 -1 -2  0  1;F -2 -2 -2 -4 -2 -4 -3 -3 -2  0  1 -3  0  8 -3 -2 -1  1  3  0;P -1 -2 -2 -1 -4 -1  0 -2 -2 -2 -3 -1 -2 -3  9 -1 -1 -3 -3 -3;S  1 -1  1  0 -1  0  0  0 -1 -2 -3 -1 -2 -2 -1  4  2 -4 -2 -1;T  0 -1  0 -1 -1 -1 -1 -2 -2 -1 -1 -1 -1 -1 -1  2  5 -3 -1  0;W -2 -2 -4 -4 -5 -2 -3 -2 -3 -2 -2 -2 -2  1 -3 -4 -3 15  3 -3;Y -2 -1 -2 -2 -3 -1 -2 -3  2  0  0 -1  0  3 -3 -2 -1  3  8 -1;V  0 -2 -3 -3 -1 -3 -3 -3 -3  3  1 -2  1  0 -3 -1  0 -3 -1  5".split(";");JAM.call(this.scoringMatrix_fillHash,
this,[matrix],JAM.policy.p15)}
function Blosum80(){var matrix="A  R  N  D  C  Q  E  G  H  I  L  K  M  F  P  S  T  W  Y  V;A  5 -2 -2 -2 -1 -1 -1  0 -2 -2 -2 -1 -1 -3 -1  1  0 -3 -2  0;R -2  6 -1 -2 -4  1 -1 -3  0 -3 -3  2 -2 -4 -2 -1 -1 -4 -3 -3;N -2 -1  6  1 -3  0 -1 -1  0 -4 -4  0 -3 -4 -3  0  0 -4 -3 -4;D -2 -2  1  6 -4 -1  1 -2 -2 -4 -5 -1 -4 -4 -2 -1 -1 -6 -4 -4;C -1 -4 -3 -4  9 -4 -5 -4 -4 -2 -2 -4 -2 -3 -4 -2 -1 -3 -3 -1;Q -1  1  0 -1 -4  6  2 -2  1 -3 -3  1  0 -4 -2  0 -1 -3 -2 -3;E -1 -1 -1  1 -5  2  6 -3  0 -4 -4  1 -2 -4 -2  0 -1 -4 -3 -3;G  0 -3 -1 -2 -4 -2 -3  6 -3 -5 -4 -2 -4 -4 -3 -1 -2 -4 -4 -4;H -2  0  0 -2 -4  1  0 -3  8 -4 -3 -1 -2 -2 -3 -1 -2 -3  2 -4;I -2 -3 -4 -4 -2 -3 -4 -5 -4  5  1 -3  1 -1 -4 -3 -1 -3 -2  3;L -2 -3 -4 -5 -2 -3 -4 -4 -3  1  4 -3  2  0 -3 -3 -2 -2 -2  1;K -1  2  0 -1 -4  1  1 -2 -1 -3 -3  5 -2 -4 -1 -1 -1 -4 -3 -3;M -1 -2 -3 -4 -2  0 -2 -4 -2  1  2 -2  6  0 -3 -2 -1 -2 -2  1;F -3 -4 -4 -4 -3 -4 -4 -4 -2 -1  0 -4  0  6 -4 -3 -2  0  3 -1;P -1 -2 -3 -2 -4 -2 -2 -3 -3 -4 -3 -1 -3 -4  8 -1 -2 -5 -4 -3;S  1 -1  0 -1 -2  0  0 -1 -1 -3 -3 -1 -2 -3 -1  5  1 -4 -2 -2;T  0 -1  0 -1 -1 -1 -1 -2 -2 -1 -2 -1 -1 -2 -2  1  5 -4 -2  0;W -3 -4 -4 -6 -3 -3 -4 -4 -3 -3 -2 -4 -2  0 -5 -4 -4 11  2 -3;Y -2 -3 -3 -4 -3 -2 -3 -4  2 -2 -2 -3 -2  3 -4 -2 -2  2  7 -2;V  0 -3 -4 -4 -1 -3 -3 -4 -4  3  1 -3  1 -1 -3 -2  0 -3 -2  4".split(";");JAM.call(this.scoringMatrix_fillHash,
this,[matrix],JAM.policy.p15)}
function Pam70(){var matrix="A   R   N   D   C   Q   E   G   H   I   L   K   M   F   P   S   T   W   Y   V;A   5  -4  -2  -1  -4  -2  -1   0  -4  -2  -4  -4  -3  -6   0   1   1  -9  -5  -1;R  -4   8  -3  -6  -5   0  -5  -6   0  -3  -6   2  -2  -7  -2  -1  -4   0  -7  -5;N  -2  -3   6   3  -7  -1   0  -1   1  -3  -5   0  -5  -6  -3   1   0  -6  -3  -5;D  -1  -6   3   6  -9   0   3  -1  -1  -5  -8  -2  -7 -10  -4  -1  -2 -10  -7  -5;C  -4  -5  -7  -9   9  -9  -9  -6  -5  -4 -10  -9  -9  -8  -5  -1  -5 -11  -2  -4;Q  -2   0  -1   0  -9   7   2  -4   2  -5  -3  -1  -2  -9  -1  -3  -3  -8  -8  -4;E  -1  -5   0   3  -9   2   6  -2  -2  -4  -6  -2  -4  -9  -3  -2  -3 -11  -6  -4;G   0  -6  -1  -1  -6  -4  -2   6  -6  -6  -7  -5  -6  -7  -3   0  -3 -10  -9  -3;H  -4   0   1  -1  -5   2  -2  -6   8  -6  -4  -3  -6  -4  -2  -3  -4  -5  -1  -4;I  -2  -3  -3  -5  -4  -5  -4  -6  -6   7   1  -4   1   0  -5  -4  -1  -9  -4   3;L  -4  -6  -5  -8 -10  -3  -6  -7  -4   1   6  -5   2  -1  -5  -6  -4  -4  -4   0;K  -4   2   0  -2  -9  -1  -2  -5  -3  -4  -5   6   0  -9  -4  -2  -1  -7  -7  -6;M  -3  -2  -5  -7  -9  -2  -4  -6  -6   1   2   0  10  -2  -5  -3  -2  -8  -7   0;F  -6  -7  -6 -10  -8  -9  -9  -7  -4   0  -1  -9  -2   8  -7  -4  -6  -2   4  -5;P   0  -2  -3  -4  -5  -1  -3  -3  -2  -5  -5  -4  -5  -7   7   0  -2  -9  -9  -3;S   1  -1   1  -1  -1  -3  -2   0  -3  -4  -6  -2  -3  -4   0   5   2  -3  -5  -3;T   1  -4   0  -2  -5  -3  -3  -3  -4  -1  -4  -1  -2  -6  -2   2   6  -8  -4  -1;W  -9   0  -6 -10 -11  -8 -11 -10  -5  -9  -4  -7  -8  -2  -9  -3  -8  13  -3 -10;Y  -5  -7  -3  -7  -2  -8  -6  -9  -1  -4  -4  -7  -7   4  -9  -5  -4  -3   9  -5;V  -1  -5  -5  -5  -4  -4  -4  -3  -4   3   0  -6   0  -5  -3  -3  -1 -10  -5   6".split(";");JAM.call(this.scoringMatrix_fillHash,
this,[matrix],JAM.policy.p15)}
function Pam30(){var matrix="A   R   N   D   C   Q   E   G   H   I   L   K   M   F   P   S   T   W   Y   V;A   6  -7  -4  -3  -6  -4  -2  -2  -7  -5  -6  -7  -5  -8  -2   0  -1 -13  -8  -2;R  -7   8  -6 -10  -8  -2  -9  -9  -2  -5  -8   0  -4  -9  -4  -3  -6  -2 -10  -8;N  -4  -6   8   2 -11  -3  -2  -3   0  -5  -7  -1  -9  -9  -6   0  -2  -8  -4  -8;D  -3 -10   2   8 -14  -2   2  -3  -4  -7 -12  -4 -11 -15  -8  -4  -5 -15 -11  -8;C  -6  -8 -11 -14  10 -14 -14  -9  -7  -6 -15 -14 -13 -13  -8  -3  -8 -15  -4  -6;Q  -4  -2  -3  -2 -14   8   1  -7   1  -8  -5  -3  -4 -13  -3  -5  -5 -13 -12  -7;E  -2  -9  -2   2 -14   1   8  -4  -5  -5  -9  -4  -7 -14  -5  -4  -6 -17  -8  -6;G  -2  -9  -3  -3  -9  -7  -4   6  -9 -11 -10  -7  -8  -9  -6  -2  -6 -15 -14  -5;H  -7  -2   0  -4  -7   1  -5  -9   9  -9  -6  -6 -10  -6  -4  -6  -7  -7  -3  -6;I  -5  -5  -5  -7  -6  -8  -5 -11  -9   8  -1  -6  -1  -2  -8  -7  -2 -14  -6   2;L  -6  -8  -7 -12 -15  -5  -9 -10  -6  -1   7  -8   1  -3  -7  -8  -7  -6  -7  -2;K  -7   0  -1  -4 -14  -3  -4  -7  -6  -6  -8   7  -2 -14  -6  -4  -3 -12  -9  -9;M  -5  -4  -9 -11 -13  -4  -7  -8 -10  -1   1  -2  11  -4  -8  -5  -4 -13 -11  -1;F  -8  -9  -9 -15 -13 -13 -14  -9  -6  -2  -3 -14  -4   9 -10  -6  -9  -4   2  -8;P  -2  -4  -6  -8  -8  -3  -5  -6  -4  -8  -7  -6  -8 -10   8  -2  -4 -14 -13  -6;S   0  -3   0  -4  -3  -5  -4  -2  -6  -7  -8  -4  -5  -6  -2   6   0  -5  -7  -6;T  -1  -6  -2  -5  -8  -5  -6  -6  -7  -2  -7  -3  -4  -9  -4   0   7 -13  -6  -3;W -13  -2  -8 -15 -15 -13 -17 -15  -7 -14  -6 -12 -13  -4 -14  -5 -13  13  -5 -15;Y  -8 -10  -4 -11  -4 -12  -8 -14  -3  -6  -7  -9 -11   2 -13  -7  -6  -5  10  -7;V  -2  -8  -8  -8  -6  -7  -6  -5  -6   2  -2  -9  -1  -8  -6  -6  -3 -15  -7   7".split(";");JAM.call(this.scoringMatrix_fillHash,
this,[matrix],JAM.policy.p15)}function Node(){this.alreadyMatched=!1}
function initializeMatrix(sequenceOne,sequenceTwo,scoreSet){this.scoreSet=scoreSet;this.M=sequenceOne;this.N=sequenceTwo;this.score=0;this.nodes=sequenceOne=Array(this.M.length+1);sequenceOne=0;for(sequenceTwo=sequenceOne<this.nodes.length;sequenceTwo;){sequenceTwo=this.nodes;scoreSet=sequenceOne;var v1247=Array(this.N.length+1);sequenceTwo[scoreSet]=v1247;sequenceTwo=0;for(scoreSet=sequenceTwo<this.nodes[sequenceOne].length;scoreSet;){scoreSet=this.nodes[sequenceOne];var v1247=sequenceTwo,v1248=
new Node;scoreSet[v1247]=v1248;sequenceTwo+=1;scoreSet=sequenceTwo<this.nodes[sequenceOne].length}sequenceOne+=1;sequenceTwo=sequenceOne<this.nodes.length}this.nodes[0][0].value=0;sequenceOne=1;for(sequenceTwo=sequenceOne<this.nodes.length;sequenceTwo;)this.nodes[sequenceOne][0].value=this.nodes[sequenceOne-1][0].value,this.nodes[sequenceOne][0].tracebackI=sequenceOne-1,this.nodes[sequenceOne][0].tracebackJ=0,sequenceOne+=1,sequenceTwo=sequenceOne<this.nodes.length;sequenceTwo=1;for(sequenceOne=sequenceTwo<
this.nodes[0].length;sequenceOne;)this.nodes[0][sequenceTwo].value=this.nodes[0][sequenceTwo-1].value,this.nodes[0][sequenceTwo].tracebackI=0,this.nodes[0][sequenceTwo].tracebackJ=sequenceTwo-1,sequenceTwo+=1,sequenceOne=sequenceTwo<this.nodes[0].length}
function dumpMatrix(){var v335=outputWindow.document;JAM.call(v335.write,v335,["Dynamic programming matrix i="+this.nodes.length+" and j="+this.nodes[0].length],JAM.policy.p15);v335=outputWindow.document;JAM.call(v335.write,v335,["\n"],JAM.policy.p15);for(var v335=0,v348=v335<this.nodes.length;v348;){for(var v348=0,v346=v348<this.nodes[v335].length;v346;){var v346=this.nodes[v335][v348].tracebackI,traceJ=this.nodes[v335][v348].tracebackJ;void 0==v346&&(v346="u");void 0==traceJ&&(traceJ="u");v346=
"("+v335+","+v348+")["+v346+","+traceJ+"]="+this.nodes[v335][v348].value;traceJ=outputWindow.document;JAM.call(traceJ.write,traceJ,[rightNum(v346,"",20," ")],JAM.policy.p15);v348+=1;v346=v348<this.nodes[v335].length}v348=outputWindow.document;JAM.call(v348.write,v348,["\n"],JAM.policy.p15);v335+=1;v348=v335<this.nodes.length}v335=outputWindow.document;JAM.call(v335.write,v335,["\n"],JAM.policy.p15)}
function updateMatrix(){for(var i=1,v390=i<this.nodes.length;v390;){for(var v390=1,v389=v390<this.nodes[0].length;v389;){var b,c;if(this.nodes[i][v390].alreadyMatched)c=b=v389=0;else{(v389=i==this.nodes.length-1)&&(v389=v390==this.nodes[0].length-1);if(v389){v389=this.nodes[i-1][v390].value;b=this.nodes[i][v390-1].value;c=this.nodes[i-1][v390-1].value;var v678=this.scoreSet}else i==this.nodes.length-1?(v389=this.nodes[i-1][v390].value-this.scoreSet.gap,b=this.nodes[i][v390-1].value):(v389=v390==this.nodes[0].length-
1?this.nodes[i-1][v390].value:this.nodes[i-1][v390].value-this.scoreSet.gap,b=this.nodes[i][v390-1].value-this.scoreSet.gap),c=this.nodes[i-1][v390-1].value,v678=this.scoreSet;c+=JAM.call(v678.getScore,v678,[this.M[i-1],this.N[v390-1]],JAM.policy.p15)}(v678=v389>b)&&(v678=v389>c);v678?(this.nodes[i][v390].value=v389,this.nodes[i][v390].tracebackI=i-1,this.nodes[i][v390].tracebackJ=v390):((v678=b>c)&&(v678=b>v389),v678?(this.nodes[i][v390].value=b,this.nodes[i][v390].tracebackI=i):(this.nodes[i][v390].value=
c,this.nodes[i][v390].tracebackI=i-1),this.nodes[i][v390].tracebackJ=v390-1);0>this.nodes[i][v390].value&&(this.nodes[i][v390].value=0,this.nodes[i][v390].tracebackI=void 0,this.nodes[i][v390].tracebackJ=void 0);v390+=1;v389=v390<this.nodes[0].length}i+=1;v390=i<this.nodes.length}this.score=this.nodes[this.nodes.length-1][this.nodes[0].length-1].value}
function search(){var v1249=[];this.hits=v1249;for(var v1249=0,v415=v1249<this.scoreSet.hits;v415;){JAM.call(this.updateMatrix,this,[],JAM.policy.p15);for(var v415=0,maxNodeI=void 0,maxNodeJ=void 0,i=1,v395=i<this.nodes.length;v395;){for(var v395=1,v394=v395<this.nodes[0].length;v394;)this.nodes[i][v395].value>v415&&(v415=this.nodes[i][v395].value,maxNodeI=i,maxNodeJ=v395),v395+=1,v394=v395<this.nodes[0].length;i+=1;v395=i<this.nodes.length}if(0==v415)break;var v415=maxNodeI,i=maxNodeJ,currentNode=
this.nodes[maxNodeI][maxNodeJ],maxNodeI=[],maxNodeJ=[],v395=currentNode.value,endN=v394=void 0,v733=void 0!=currentNode.tracebackI;for(v733&&(v733=void 0!=currentNode.tracebackJ);v733;){(v733=0==v415)||(v733=0==i);if(v733)break;(v733=currentNode.tracebackI==v415-1)&&(v733=currentNode.tracebackJ==i-1);v733?(void 0==v394&&(v394=v415,endN=i),JAM.call(maxNodeI.push,maxNodeI,[this.M[v415-1]],JAM.policy.p15),JAM.call(maxNodeJ.push,maxNodeJ,[this.N[i-1]],JAM.policy.p15)):currentNode.tracebackJ==i-1?void 0!=
v394&&(JAM.call(maxNodeI.push,maxNodeI,["-"],JAM.policy.p15),JAM.call(maxNodeJ.push,maxNodeJ,[this.N[i-1]],JAM.policy.p15)):void 0!=v394&&(JAM.call(maxNodeI.push,maxNodeI,[this.M[v415-1]],JAM.policy.p15),JAM.call(maxNodeJ.push,maxNodeJ,["-"],JAM.policy.p15));this.nodes[v415][i].value=0;this.nodes[v415][i].alreadyMatched=!0;v415=currentNode.tracebackI;i=currentNode.tracebackJ;currentNode=this.nodes[currentNode.tracebackI][currentNode.tracebackJ];(v733=void 0!=currentNode.tracebackI)&&(v733=void 0!=
currentNode.tracebackJ)}maxNodeI=JAM.call(maxNodeI.reverse,maxNodeI,[],JAM.policy.p15);maxNodeJ=JAM.call(maxNodeJ.reverse,maxNodeJ,[],JAM.policy.p15);currentNode=this.hits;JAM.call(currentNode.push,currentNode,[new Hit(JAM.call(maxNodeI.join,maxNodeI,[""],JAM.policy.p16),JAM.call(maxNodeJ.join,maxNodeJ,[""],JAM.policy.p16),v395,v415+1,v394,i+1,endN)],JAM.policy.p15);v1249+=1;v415=v1249<this.scoreSet.hits}}function getHits(){return this.hits}function FuzzySearch(){}
function Hit(sequenceM,sequenceN,score,startM,endM,startN,endN){this.sequenceM=sequenceM;this.sequenceN=sequenceN;this.score=score;this.startM=startM;this.endM=endM;this.startN=startN;this.endN=endN}new ScoreSet;ScoreSet.prototype.getScore=getScore;ScoreSet.prototype.setScoreSetParam=setScoreSetParam;new ScoringMatrix;ScoringMatrix.prototype.scoringMatrix_getScore=scoringMatrix_getScore;ScoringMatrix.prototype.scoringMatrix_fillHash=scoringMatrix_fillHash;var v420=Blosum62,v1250=new ScoringMatrix;
v420.prototype=v1250;var v421=Blosum45,v1251=new ScoringMatrix;v421.prototype=v1251;var v422=Blosum80,v1252=new ScoringMatrix;v422.prototype=v1252;var v423=Pam30,v1253=new ScoringMatrix;v423.prototype=v1253;new FuzzySearch;FuzzySearch.prototype.initializeMatrix=initializeMatrix;FuzzySearch.prototype.updateMatrix=updateMatrix;FuzzySearch.prototype.search=search;FuzzySearch.prototype.getHits=getHits;FuzzySearch.prototype.dumpMatrix=dumpMatrix;JAM.set(document,"onload",v2);
JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p15),"onclick",v3);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p15),"onclick",v4);

JAM.stopProfile('load');
