
JAM.startProfile('load');
function v7(){document.forms[0].elements[0].value=" ";document.forms[0].elements[4].value=" "}function v6(){try{JAM.startProfile('compute');revTrans();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v5(){var v11=document.main_form.main_submit;JAM.call(v11.focus,v11,[],JAM.policy.p9)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p9)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v15=i<arrayOfTitles.length;v15;){v15=arrayOfTitles[i];v15=-1==JAM.call(v15.search,v15,[/\S/],JAM.policy.p9);v15||(v15=arrayOfSequences[i],(v15=-1==JAM.call(v15.search,v15,[/\S/],JAM.policy.p9))||(v15=arrayOfSequences[i].length!=lengthOfAlign));if(v15)return alert("There is a problem with the alignment format."),
!1;i+=1;v15=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v439=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p9);v439||(v439=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p9),v439||(v439=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p9),v439||(v439=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p9))||(v439=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p9))));return v439?(alert("The codon table has been entered incorrectly."),!1):
!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p9)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v20=z<arrayOfPatterns.length;v20;){v20=arrayOfPatterns[z];if(-1==JAM.call(v20.search,v20,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v20=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v20=0,v29=v20<arrayOfPatterns.length;v29;){var v29=z,v24=v20,v870=arrayOfPatterns[v20],v870=JAM.call(v870.match,v870,[/\/.+\//],JAM.policy.p9)+"gi",v870=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v870+" }"):JAM.call(eval,null,[v870]);v29[v24]=v870;v29=codon;v24=v20;v870=arrayOfPatterns[v20];v870=JAM.call(v870.match,v870,[/=[a-zA-Z\*]/],JAM.policy.p9);v870=JAM.call(v870.toString,
v870,[],JAM.policy.p9);v29[v24]=v870;v29=codon;v24=v20;v870=codon[v20];v870=JAM.call(v870.replace,v870,[/=/g,""],JAM.policy.p9);v29[v24]=v870;v20+=1;v29=v20<arrayOfPatterns.length}arrayOfPatterns=0;for(v20=arrayOfPatterns<=testSequence.length-3;v20;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p9);v20=0;for(v29=v20<z.length;v29;){if(-1!=JAM.call(codon.search,codon,[z[v20]],JAM.policy.p9)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v20+=1;v29=v20<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v20=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v38=z<arrayOfPatterns.length;v38;){v38=arrayOfPatterns[z];if(-1!=JAM.call(v38.search,v38,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p9))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v38=z<arrayOfPatterns.length}z=0;for(v38=z<arrayOfPatterns.length;v38;){for(var v38=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v41=j<arrayOfPatterns.length;v41;){v41=arrayOfPatterns[j];if(-1!=JAM.call(v41.search,v41,[v38],JAM.policy.p9))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v41=j<arrayOfPatterns.length}z+=1;v38=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v45=z<arrayOfPatterns.length;v45;){v45=arrayOfPatterns[z];if(-1==JAM.call(v45.search,v45,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v45=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v871=getSequenceFromFasta(text);return JAM.call(v871.replace,v871,[/[^A-Za-z]/g,""],JAM.policy.p9).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/2/g,"R"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/M/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/B/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p9);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p9)}
function closeForm(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</form>"],JAM.policy.p9);return!0}function closePre(){var v51=outputWindow.document;JAM.call(v51.write,v51,["</div>"],JAM.policy.p9);v51=outputWindow.document;JAM.call(v51.write,v51,["</pre>\n"],JAM.policy.p9)}function closeTextArea(){var v53=outputWindow.document;JAM.call(v53.write,v53,["</textarea>"],JAM.policy.p9);return!0}
function closeWindow(){var v54=outputWindow.document;JAM.call(v54.write,v54,["</body>\n</html>\n"],JAM.policy.p9);outputWindow.status="Done.";v54=outputWindow.document;JAM.call(v54.close,v54,[],JAM.policy.p9)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p9);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p9)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v58=i<alignArray.length;v58;){v58=alignArray[i];if(-1==JAM.call(v58.search,v58,[/[^\s]+\s/],JAM.policy.p9))return alert("There is a problem with the alignment format."),!1;i+=1;v58=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p9)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p9);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p9)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9))for(var v60=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);v60;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p9),v60=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v78=j<arrayOfPatterns.length;v78;){var v78=geneticCodeMatchExp,v77=j,v872=arrayOfPatterns[j],v872=JAM.call(v872.match,v872,[/\/.+\//],JAM.policy.p9)+"gi",v872=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v872+" }"):JAM.call(eval,null,[v872]);v78[v77]=v872;j+=1;v78=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v84=j<arrayOfPatterns.length;v84;){var v84=geneticCodeMatchResult,v81=j,v733=arrayOfPatterns[j],v733=JAM.call(v733.match,v733,[/=[a-zA-Z\*]/],JAM.policy.p9),v733=JAM.call(v733.toString,v733,[],JAM.policy.p9);v84[v81]=v733;v84=geneticCodeMatchResult;v81=j;v733=geneticCodeMatchResult[j];v733=JAM.call(v733.replace,v733,[/=/g,""],JAM.policy.p9);v84[v81]=v733;j+=1;v84=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(sequence){var fastaSequenceTitle=title,stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p9),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p9),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p9));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p9);v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p9),v527||(v527=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p9))||(v527=
-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p9))))))))));return v527?!1:!0}function openForm(){var v110=outputWindow.document;JAM.call(v110.write,v110,['<form action="">\n'],JAM.policy.p9);return!0}function openPre(){var v111=outputWindow.document;JAM.call(v111.write,v111,["<pre>"],JAM.policy.p9);v111=outputWindow.document;JAM.call(v111.write,v111,['<div class="pre">'],JAM.policy.p9)}
function openTextArea(){var v113=outputWindow.document;JAM.call(v113.write,v113,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p9);return!0}function openWindow(){var title="Reverse Translate";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v114=outputWindow.document;JAM.call(v114.write,v114,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p9)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v122=outputWindow.document;JAM.call(v122.write,v122,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p9)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p9)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p9)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p9)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p9)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p9)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p9)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p9)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p9)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p9),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p9),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p10));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p9);for(var j=theNumber.length,v131=j<lengthOfColumn;v131;)tempString+=" ",j+=1,v131=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p9);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p9))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p9);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p9)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p9)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v542=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v542||(v542=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v542||(v542=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v542=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v542?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p9)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p9)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v547=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v547||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v547||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v547=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v547?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v548=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v548||(v548=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v548||(v548=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v548=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v548?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v550=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v550||(v550=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v550||(v550=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v550=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v550?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v159=startBase<stopBase;v159;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v159=1,v156=v159<=basePerLine/groupSize;v156;){for(v156=k<groupSize;v156;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v156=k<groupSize;startBase+=groupSize;k=0;lineOfText+=
sepChar;v159+=1;v156=v159<=basePerLine/groupSize}v159=outputWindow.document;JAM.call(v159.write,v159,[lineOfText+"\n"],JAM.policy.p9);lineOfText="";v159=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v555=0>adjustment;v555&&(v555=0<=adjusted);v555&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v169=j<=basePerLine/groupSize;v169;){for(v169=k<groupSize;v169&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v169=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v169=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v202=j<=basePerLine/groupSize;v202;){for(v202=k<groupSize;v202&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v202=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v202=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p9)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p9));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v572=sequence.length<=firstIndexToMutate;v572||(v572=0>lastIndexToMutate)||(v572=lastIndexToMutate<=firstIndexToMutate);v572&&(numMut=0);v572=0;for(randNum=v572<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*randNum],JAM.policy.p9);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p9);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p9)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p9)}v572+=1;randNum=v572<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p9);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p9),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p9);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p9)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p9);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p9)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p9);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p9);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p9));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v591=matchPosition>=lowerLimit;v591&&(v591=matchPosition<upperLimit);v591&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p9)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p9));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p9);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p9);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p9)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p9);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v257=outputWindow.document;JAM.call(v257.write,v257,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);v257=outputWindow.document;JAM.call(v257.write,v257,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p9);for(var v257=0,v268=v257<arrayOfItems.length;v268;){var v268=0,v600=arrayOfItems[v257],v600=
JAM.call(v600.match,v600,[/\/[^\/]+\//],JAM.policy.p9)+"gi",v600=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v600+" }"):JAM.call(eval,null,[v600]);-1!=JAM.call(sequence.search,sequence,[v600],JAM.policy.p9)&&(v268=JAM.call(sequence.match,sequence,[v600],JAM.policy.p9).length);var v600=0,v777=originalLength+1,v982=arrayOfItems[v257];0<v777-parseFloat(JAM.call(v982.match,v982,[/\d+/],JAM.policy.p9))&&(v600=100*v268,v777=originalLength+1,v982=arrayOfItems[v257],v600/=v777-parseFloat(JAM.call(v982.match,
v982,[/\d+/],JAM.policy.p9)));v777=outputWindow.document;v982=arrayOfItems[v257];v982=JAM.call(v982.match,v982,[/\([^\(]+\)\b/],JAM.policy.p9);v982=JAM.call(v982.toString,v982,[],JAM.policy.p9);JAM.call(v777.write,v777,["<tr><td>"+JAM.call(v982.replace,v982,[/\(|\)/g,""],JAM.policy.p9)+"</td><td>"+v268+"</td><td>"+JAM.call(v600.toFixed,v600,[2],JAM.policy.p9)+"</td></tr>\n"],JAM.policy.p9);v257+=1;v268=v257<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,originalLength,
["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*tempChar],JAM.policy.p9),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p9),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p9),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p9),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p9),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p9);return!0}
function revTrans(){var theDocument=document,newProtein="",maxInput=2E4;if(!1!=testScript()){var v612=!1==checkFormElement(theDocument.forms[0].elements[0]);v612||((maxInput=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxInput))||(maxInput=!1==checkCodonTable(theDocument.forms[0].elements[4].value)),v612=maxInput);if(!v612&&(maxInput=makeCodonTable(theDocument.forms[0].elements[4].value),!1!=maxInput)){openWindow();openPre();theDocument=getArrayOfFasta(theDocument.forms[0].elements[0].value);
v612=0;for(newProtein=v612<theDocument.length;newProtein;){newProtein=getSequenceFromFasta(theDocument[v612]);title=getTitleFromFasta(theDocument[v612]);var newProtein=removeNonProteinAllowX(newProtein),v286=outputWindow.document;JAM.call(v286.write,v286,[getInfoFromTitleAndSequence(newProtein)],JAM.policy.p9);writeRevTransSeqNoDegen(newProtein,maxInput);v286=outputWindow.document;JAM.call(v286.write,v286,["\n"],JAM.policy.p9);writeRevTransSeqDegen(newProtein,maxInput);v286=outputWindow.document;
JAM.call(v286.write,v286,["\n"],JAM.policy.p9);v286=outputWindow.document;JAM.call(v286.write,v286,["Graph of base probabilities:\n"],JAM.policy.p9);writeRevTransGraph(newProtein,maxInput);newProtein=outputWindow.document;JAM.call(newProtein.write,newProtein,["\n\n"],JAM.policy.p9);v612+=1;newProtein=v612<theDocument.length}closePre();closeWindow()}}}
function writeRevTransSeqNoDegen(protein,codonTable){var title$$0=title;function v2(str,p1,offset,s){str=codonTable;p1=JAM.call(p1.toString,p1,[],JAM.policy.p9);aminoAcid=str[JAM.call(p1.toLowerCase,p1,[],JAM.policy.p9)];return aminoAcid.mostCommonCodon}var aminoAcid;protein=JAM.call(protein.replace,protein,[/\*/g,"z"],JAM.policy.p9);protein=JAM.call(protein.replace,protein,[/(.)/g,v2],JAM.policy.p9);var v295=outputWindow.document;JAM.call(v295.write,v295,["&gt;reverse translation of "+title$$0+" to a "+
protein.length+" base sequence of most likely codons.\n"],JAM.policy.p9);title$$0=outputWindow.document;JAM.call(title$$0.write,title$$0,[addReturns(protein)],JAM.policy.p9);title$$0=outputWindow.document;JAM.call(title$$0.write,title$$0,["\n"],JAM.policy.p9)}
function writeRevTransSeqDegen(protein,codonTable){var title$$0=title;function v3(str,p1,offset,s){str=codonTable;p1=JAM.call(p1.toString,p1,[],JAM.policy.p9);aminoAcid=str[JAM.call(p1.toLowerCase,p1,[],JAM.policy.p9)];return aminoAcid.degenCodon}var aminoAcid;protein=JAM.call(protein.replace,protein,[/\*/g,"z"],JAM.policy.p9);protein=JAM.call(protein.replace,protein,[/(.)/g,v3],JAM.policy.p9);var v302=outputWindow.document;JAM.call(v302.write,v302,["&gt;reverse translation of "+title$$0+" to a "+
protein.length+" base sequence of consensus codons.\n"],JAM.policy.p9);title$$0=outputWindow.document;JAM.call(title$$0.write,title$$0,[addReturns(protein)],JAM.policy.p9);title$$0=outputWindow.document;JAM.call(title$$0.write,title$$0,["\n"],JAM.policy.p9)}
function writeRevTransGraph(protein,codonTable){function v4(str,p1,offset,s){s=codonTable;p1=JAM.call(p1.toString,p1,[],JAM.policy.p9);aminoAcid=s[JAM.call(p1.toLowerCase,p1,[],JAM.policy.p9)];return"<b>"+(offset+1)+"_"+str+"_first</b>\n"+aminoAcid.rulerPosOne+"<b>"+(offset+1)+"_"+str+"_second</b>\n"+aminoAcid.rulerPosTwo+"<b>"+(offset+1)+"_"+str+"_third</b>\n"+aminoAcid.rulerPosThree+"\n"}var aminoAcid;protein=JAM.call(protein.replace,protein,[/\*/g,"z"],JAM.policy.p9);protein=JAM.call(protein.replace,
protein,[/(.)/g,v4],JAM.policy.p9);var v310=outputWindow.document;JAM.call(v310.write,v310,[protein],JAM.policy.p9)}
function makeCodonTable(gcgTable){gcgTable=JAM.call(gcgTable.replace,gcgTable,[/[^\.]*\.\./,""],JAM.policy.p9);var tableArray=JAM.call(gcgTable.split,gcgTable,[/[\f\n\r]/],JAM.policy.p9),re=/(\w+)\s+(\w+)\s+(\S+)\s+(\S+)\s+(\S+)/g,matchArray;gcgTable=new CodonTable;var i=0;for(matchArray=i<tableArray.length;matchArray;){for(var v314=matchArray=JAM.call(re.exec,re,[tableArray[i]],JAM.policy.p9);v314;){try{var v314=gcgTable,v792=matchArray[1],v311=v314[JAM.call(v792.toLowerCase,v792,[],JAM.policy.p9)];
JAM.call(v311.addCodon,v311,[new Codon(matchArray[2],parseFloat(matchArray[3]),parseFloat(matchArray[4]),parseFloat(matchArray[5]))],JAM.policy.p9)}catch(e){return alert("There is a problem with a line of the codon table: "+matchArray[1]+" "+matchArray[2]+" "+matchArray[3]+" "+matchArray[4]+" "+matchArray[4]),!1}v314=matchArray=JAM.call(re.exec,re,[tableArray[i]],JAM.policy.p9)}i+=1;matchArray=i<tableArray.length}v792=gcgTable.a;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.c;
JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.d;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.e;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.f;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.g;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.h;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.i;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.k;JAM.call(v792.determineBaseFreq,
v792,[],JAM.policy.p9);v792=gcgTable.l;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.m;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.n;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.p;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.q;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.r;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.s;JAM.call(v792.determineBaseFreq,v792,
[],JAM.policy.p9);v792=gcgTable.t;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.v;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.w;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.y;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.z;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.x;JAM.call(v792.determineBaseFreq,v792,[],JAM.policy.p9);v792=gcgTable.x;v311=[0.25,0.25,0.25,0.25];v792.baseFreqPosOne=
v311;v792=gcgTable.x;v311=[0.25,0.25,0.25,0.25];v792.baseFreqPosTwo=v311;v792=gcgTable.x;v311=[0.25,0.25,0.25,0.25];v792.baseFreqPosThree=v311;v792=gcgTable.a;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.c;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.d;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.e;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.f;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.g;JAM.call(v792.fillRuler,v792,
[],JAM.policy.p9);v792=gcgTable.h;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.i;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.k;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.l;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.m;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.n;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.p;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.q;JAM.call(v792.fillRuler,v792,
[],JAM.policy.p9);v792=gcgTable.r;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.s;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.t;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.v;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.w;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.y;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.z;JAM.call(v792.fillRuler,v792,[],JAM.policy.p9);v792=gcgTable.x;JAM.call(v792.fillRuler,v792,
[],JAM.policy.p9);return gcgTable}
function CodonTable(){var v1139=new AminoAcid;this.a=v1139;this.c=v1139=new AminoAcid;this.d=v1139=new AminoAcid;this.e=v1139=new AminoAcid;this.f=v1139=new AminoAcid;this.g=v1139=new AminoAcid;this.h=v1139=new AminoAcid;this.i=v1139=new AminoAcid;this.k=v1139=new AminoAcid;this.l=v1139=new AminoAcid;this.m=v1139=new AminoAcid;this.n=v1139=new AminoAcid;this.p=v1139=new AminoAcid;this.q=v1139=new AminoAcid;this.r=v1139=new AminoAcid;this.s=v1139=new AminoAcid;this.t=v1139=new AminoAcid;this.v=v1139=
new AminoAcid;this.w=v1139=new AminoAcid;this.y=v1139=new AminoAcid;this.z=v1139=new AminoAcid;this.x=v1139=new AminoAcid;this.ala=this.a;this.cys=this.c;this.asp=this.d;this.glu=this.e;this.phe=this.f;this.gly=this.g;this.his=this.h;this.ile=this.i;this.lys=this.k;this.leu=this.l;this.met=this.m;this.asn=this.n;this.pro=this.p;this.gln=this.q;this.arg=this.r;this.ser=this.s;this.thr=this.t;this.val=this.v;this.trp=this.w;this.tyr=this.y;this.end=this.z;this.xaa=this.x}
function fillRuler(){var markG="gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",markA="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",markT="TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",markC="CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC";this.rulerPosOne=JAM.call(this.getRuler,
this,[this.baseFreqPosOne[0],markG],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosOne[1],markA],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosOne[2],markT],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosOne[3],markC],JAM.policy.p9);this.rulerPosTwo=JAM.call(this.getRuler,this,[this.baseFreqPosTwo[0],markG],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosTwo[1],markA],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosTwo[2],markT],JAM.policy.p9)+
JAM.call(this.getRuler,this,[this.baseFreqPosTwo[3],markC],JAM.policy.p9);this.rulerPosThree=JAM.call(this.getRuler,this,[this.baseFreqPosThree[0],markG],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosThree[1],markA],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosThree[2],markT],JAM.policy.p9)+JAM.call(this.getRuler,this,[this.baseFreqPosThree[3],markC],JAM.policy.p9);JAM.call(this.setMostCommonCodon,this,[],JAM.policy.p9);JAM.call(this.setDegenCodon,this,[],JAM.policy.p9)}
function getRuler(freq,mark){return JAM.call(mark.substring,mark,[0,1],JAM.policy.p9)+JAM.call(mark.substring,mark,[0,freq*mark.length],JAM.policy.p9)+" "+JAM.call(freq.toFixed,freq,[2],JAM.policy.p9)+"\n"}function addCodon(codon){var v370=this.codons;JAM.call(v370.push,v370,[codon],JAM.policy.p9)}
function determineBaseFreq(){JAM.call(this.fixFraction,this,[],JAM.policy.p9);for(var i=0,v395=i<this.codons.length;v395;)v395=this.codons[i].sequence,"g"==JAM.call(v395.charAt,v395,[0],JAM.policy.p9)?this.baseFreqPosOne[0]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"a"==JAM.call(v395.charAt,v395,[0],JAM.policy.p9)?this.baseFreqPosOne[1]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"t"==JAM.call(v395.charAt,v395,[0],JAM.policy.p9)?this.baseFreqPosOne[2]+=this.codons[i].fraction:
(v395=this.codons[i].sequence,"c"==JAM.call(v395.charAt,v395,[0],JAM.policy.p9)&&(this.baseFreqPosOne[3]+=this.codons[i].fraction)))),v395=this.codons[i].sequence,"g"==JAM.call(v395.charAt,v395,[1],JAM.policy.p9)?this.baseFreqPosTwo[0]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"a"==JAM.call(v395.charAt,v395,[1],JAM.policy.p9)?this.baseFreqPosTwo[1]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"t"==JAM.call(v395.charAt,v395,[1],JAM.policy.p9)?this.baseFreqPosTwo[2]+=this.codons[i].fraction:
(v395=this.codons[i].sequence,"c"==JAM.call(v395.charAt,v395,[1],JAM.policy.p9)&&(this.baseFreqPosTwo[3]+=this.codons[i].fraction)))),v395=this.codons[i].sequence,"g"==JAM.call(v395.charAt,v395,[2],JAM.policy.p9)?this.baseFreqPosThree[0]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"a"==JAM.call(v395.charAt,v395,[2],JAM.policy.p9)?this.baseFreqPosThree[1]+=this.codons[i].fraction:(v395=this.codons[i].sequence,"t"==JAM.call(v395.charAt,v395,[2],JAM.policy.p9)?this.baseFreqPosThree[2]+=this.codons[i].fraction:
(v395=this.codons[i].sequence,"c"==JAM.call(v395.charAt,v395,[2],JAM.policy.p9)&&(this.baseFreqPosThree[3]+=this.codons[i].fraction)))),i+=1,v395=i<this.codons.length;return!0}function fixFraction(){for(var perThouTotal=0,i=0,v397=i<this.codons.length;v397;)perThouTotal+=this.codons[i].perThou,i+=1,v397=i<this.codons.length;if(0==perThouTotal)return!1;i=0;for(v397=i<this.codons.length;v397;)this.codons[i].fraction=this.codons[i].perThou/perThouTotal,i+=1,v397=i<this.codons.length;return!0}
function setMostCommonCodon(){for(var highestFraction=0,highestCodon="nnn",i=0,v404=i<this.codons.length;v404;)this.codons[i].fraction>highestFraction&&(highestFraction=this.codons[i].fraction,highestCodon=this.codons[i].sequence),i+=1,v404=i<this.codons.length;this.mostCommonCodon=highestCodon}function setDegenCodon(){this.degenCodon=getConsensusBase(this.baseFreqPosOne)+getConsensusBase(this.baseFreqPosTwo)+getConsensusBase(this.baseFreqPosThree)}
function getConsensusBase(baseFreq){var g,a,t,c;0<baseFreq[0]&&(g=!0);0<baseFreq[1]&&(a=!0);0<baseFreq[2]&&(t=!0);0<baseFreq[3]&&(c=!0);(baseFreq=!g)&&(baseFreq=!a)&&(baseFreq=!c)&&(baseFreq=!t);if(baseFreq)return"n";(baseFreq=g)&&(baseFreq=a)&&(baseFreq=c&&t);if(baseFreq)return"n";(baseFreq=a)&&(baseFreq=c&&t);if(baseFreq)return"h";(baseFreq=a)&&(baseFreq=g&&t);if(baseFreq)return"d";(baseFreq=c)&&(baseFreq=g&&t);return baseFreq?"b":a&&c?"m":g&&t?"k":a&&t?"w":g&&c?"s":c&&t?"y":a&&g?"r":t?"t":g?"g":
c?"c":a?"a":!0}function AminoAcid(){var v1161=[];this.codons=v1161;this.baseFreqPosOne=v1161=[0,0,0,0];this.baseFreqPosTwo=v1161=[0,0,0,0];this.baseFreqPosThree=v1161=[0,0,0,0]}function Codon(sequence,number,perThou,fraction){this.sequence=sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);this.number=number;this.perThou=perThou;this.fraction=fraction}new AminoAcid;AminoAcid.prototype.fillRuler=fillRuler;AminoAcid.prototype.getRuler=getRuler;AminoAcid.prototype.addCodon=addCodon;
AminoAcid.prototype.determineBaseFreq=determineBaseFreq;AminoAcid.prototype.fixFraction=fixFraction;AminoAcid.prototype.setMostCommonCodon=setMostCommonCodon;AminoAcid.prototype.setDegenCodon=setDegenCodon;AminoAcid.prototype.getConsensusBase=getConsensusBase;JAM.set(document,"onload",v5);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p9),"onclick",v6);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p9),"onclick",v7);

JAM.stopProfile('load');
