
JAM.startProfile('load');
function v12(){document.forms[0].elements[0].value=" ";document.forms[0].elements[1].value=" "}function v11(){try{JAM.startProfile('compute');rangeExtract();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v10(){var v16=document.main_form.main_submit;JAM.call(v16.focus,v16,[],JAM.policy.p9)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p9)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v20=i<arrayOfTitles.length;v20;){v20=arrayOfTitles[i];v20=-1==JAM.call(v20.search,v20,[/\S/],JAM.policy.p9);v20||(v20=arrayOfSequences[i],(v20=-1==JAM.call(v20.search,v20,[/\S/],JAM.policy.p9))||(v20=arrayOfSequences[i].length!=lengthOfAlign));if(v20)return alert("There is a problem with the alignment format."),
!1;i+=1;v20=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v432=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p9);v432||(v432=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p9),v432||(v432=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p9),v432||(v432=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p9))||(v432=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p9))));return v432?(alert("The codon table has been entered incorrectly."),!1):
!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p9)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v25=z<arrayOfPatterns.length;v25;){v25=arrayOfPatterns[z];if(-1==JAM.call(v25.search,v25,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v25=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v25=0,v34=v25<arrayOfPatterns.length;v34;){var v34=z,v29=v25,v891=arrayOfPatterns[v25],v891=JAM.call(v891.match,v891,[/\/.+\//],JAM.policy.p9)+"gi",v891=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v891+" }"):JAM.call(eval,null,[v891]);v34[v29]=v891;v34=codon;v29=v25;v891=arrayOfPatterns[v25];v891=JAM.call(v891.match,v891,[/=[a-zA-Z\*]/],JAM.policy.p9);v891=JAM.call(v891.toString,
v891,[],JAM.policy.p9);v34[v29]=v891;v34=codon;v29=v25;v891=codon[v25];v891=JAM.call(v891.replace,v891,[/=/g,""],JAM.policy.p9);v34[v29]=v891;v25+=1;v34=v25<arrayOfPatterns.length}arrayOfPatterns=0;for(v25=arrayOfPatterns<=testSequence.length-3;v25;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p9);v25=0;for(v34=v25<z.length;v34;){if(-1!=JAM.call(codon.search,codon,[z[v25]],JAM.policy.p9)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v25+=1;v34=v25<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v25=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v43=z<arrayOfPatterns.length;v43;){v43=arrayOfPatterns[z];if(-1!=JAM.call(v43.search,v43,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p9))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v43=z<arrayOfPatterns.length}z=0;for(v43=z<arrayOfPatterns.length;v43;){for(var v43=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v46=j<arrayOfPatterns.length;v46;){v46=arrayOfPatterns[j];if(-1!=JAM.call(v46.search,v46,[v43],JAM.policy.p9))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v46=j<arrayOfPatterns.length}z+=1;v43=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v50=z<arrayOfPatterns.length;v50;){v50=arrayOfPatterns[z];if(-1==JAM.call(v50.search,v50,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v50=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v892=getSequenceFromFasta(text);return JAM.call(v892.replace,v892,[/[^A-Za-z]/g,""],JAM.policy.p9).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/2/g,"R"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/M/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/B/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p9);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p9)}
function closeForm(){var v55=outputWindow.document;JAM.call(v55.write,v55,["</form>"],JAM.policy.p9);return!0}function closePre(){var v56=outputWindow.document;JAM.call(v56.write,v56,["</div>"],JAM.policy.p9);v56=outputWindow.document;JAM.call(v56.write,v56,["</pre>\n"],JAM.policy.p9)}function closeTextArea(){var v58=outputWindow.document;JAM.call(v58.write,v58,["</textarea>"],JAM.policy.p9);return!0}
function closeWindow(){var v59=outputWindow.document;JAM.call(v59.write,v59,["</body>\n</html>\n"],JAM.policy.p9);outputWindow.status="Done.";v59=outputWindow.document;JAM.call(v59.close,v59,[],JAM.policy.p9)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p9);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p9)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v63=i<alignArray.length;v63;){v63=alignArray[i];if(-1==JAM.call(v63.search,v63,[/[^\s]+\s/],JAM.policy.p9))return alert("There is a problem with the alignment format."),!1;i+=1;v63=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p9)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p9);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p9)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9))for(var v65=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);v65;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p9),v65=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(sequence){var fastaSequenceTitle=title,stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v83=j<arrayOfPatterns.length;v83;){var v83=geneticCodeMatchExp,v82=j,v893=arrayOfPatterns[j],v893=JAM.call(v893.match,v893,[/\/.+\//],JAM.policy.p9)+"gi",v893=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v893+" }"):JAM.call(eval,null,[v893]);v83[v82]=v893;j+=1;v83=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v89=j<arrayOfPatterns.length;v89;){var v89=geneticCodeMatchResult,v86=j,v758=arrayOfPatterns[j],v758=JAM.call(v758.match,v758,[/=[a-zA-Z\*]/],JAM.policy.p9),v758=JAM.call(v758.toString,v758,[],JAM.policy.p9);v89[v86]=v758;v89=geneticCodeMatchResult;v86=j;v758=geneticCodeMatchResult[j];v758=JAM.call(v758.replace,v758,[/=/g,""],JAM.policy.p9);v89[v86]=v758;j+=1;v89=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(lengthOut){for(var components=["g","a","c","t"],sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p9),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p9),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p9));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p9);v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p9),v520||(v520=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p9))||(v520=
-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p9))))))))));return v520?!1:!0}function openForm(){var v115=outputWindow.document;JAM.call(v115.write,v115,['<form action="">\n'],JAM.policy.p9);return!0}function openPre(){var v116=outputWindow.document;JAM.call(v116.write,v116,["<pre>"],JAM.policy.p9);v116=outputWindow.document;JAM.call(v116.write,v116,['<div class="pre">'],JAM.policy.p9)}
function openTextArea(){var v118=outputWindow.document;JAM.call(v118.write,v118,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p9);return!0}function openWindow(){var title="Range Extractor DNA";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v119=outputWindow.document;JAM.call(v119.write,v119,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p9)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v127=outputWindow.document;JAM.call(v127.write,v127,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p9)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p9)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p9)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p9)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p9)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p9)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p9)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p9)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p9)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p9),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p9),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p10));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p9);for(var j=theNumber.length,v136=j<lengthOfColumn;v136;)tempString+=" ",j+=1,v136=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p9);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p9))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p9);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p9)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p9)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v535=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v535||(v535=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v535||(v535=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v535=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v535?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p9)&&alert("The sequence contains non-DNA characters, which will be omitted.")}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p9)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v540=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v540||(v540=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v540||(v540=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v540=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v540?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v541=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v541||(v541=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v541||(v541=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v541=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v541?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v543=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v543||(v543=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v543||(v543=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v543=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v543?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v164=startBase<stopBase;v164;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v164=1,v161=v164<=basePerLine/groupSize;v161;){for(v161=k<groupSize;v161;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v161=k<groupSize;startBase+=groupSize;k=0;lineOfText+=
sepChar;v164+=1;v161=v164<=basePerLine/groupSize}v164=outputWindow.document;JAM.call(v164.write,v164,[lineOfText+"\n"],JAM.policy.p9);lineOfText="";v164=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v548=0>adjustment;v548&&(v548=0<=adjusted);v548&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v174=j<=basePerLine/groupSize;v174;){for(v174=k<groupSize;v174&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v174=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v174=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v207=j<=basePerLine/groupSize;v207;){for(v207=k<groupSize;v207&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v207=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v207=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p9)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p9));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v565=sequence.length<=firstIndexToMutate;v565||(v565=0>lastIndexToMutate)||(v565=lastIndexToMutate<=firstIndexToMutate);v565&&(numMut=0);v565=0;for(randNum=v565<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*randNum],JAM.policy.p9);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p9);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p9)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p9)}v565+=1;randNum=v565<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p9);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p9),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p9);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p9)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p9);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p9)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p9);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p9);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p9));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v584=matchPosition>=lowerLimit;v584&&(v584=matchPosition<upperLimit);v584&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p9)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p9));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p9);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p9);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p9)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p9);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v262=outputWindow.document;JAM.call(v262.write,v262,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);v262=outputWindow.document;JAM.call(v262.write,v262,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p9);for(var v262=0,v273=v262<arrayOfItems.length;v273;){var v273=0,v593=arrayOfItems[v262],v593=
JAM.call(v593.match,v593,[/\/[^\/]+\//],JAM.policy.p9)+"gi",v593=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v593+" }"):JAM.call(eval,null,[v593]);-1!=JAM.call(sequence.search,sequence,[v593],JAM.policy.p9)&&(v273=JAM.call(sequence.match,sequence,[v593],JAM.policy.p9).length);var v593=0,v802=originalLength+1,v1013=arrayOfItems[v262];0<v802-parseFloat(JAM.call(v1013.match,v1013,[/\d+/],JAM.policy.p9))&&(v593=100*v273,v802=originalLength+1,v1013=arrayOfItems[v262],v593/=v802-parseFloat(JAM.call(v1013.match,
v1013,[/\d+/],JAM.policy.p9)));v802=outputWindow.document;v1013=arrayOfItems[v262];v1013=JAM.call(v1013.match,v1013,[/\([^\(]+\)\b/],JAM.policy.p9);v1013=JAM.call(v1013.toString,v1013,[],JAM.policy.p9);JAM.call(v802.write,v802,["<tr><td>"+JAM.call(v1013.replace,v1013,[/\(|\)/g,""],JAM.policy.p9)+"</td><td>"+v273+"</td><td>"+JAM.call(v593.toFixed,v593,[2],JAM.policy.p9)+"</td></tr>\n"],JAM.policy.p9);v262+=1;v273=v262<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,
originalLength,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*tempChar],JAM.policy.p9),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p9),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p9),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p9),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p9),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p9);return!0}
function rangeExtract(){var theDocument=document,newDna="",maxInput=5E5,matchFound=!1,ranges=[];if(!1!=testScript()&&(newDna=!1==checkFormElement(theDocument.forms[0].elements[0]),newDna||((maxInput=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxInput))||(maxInput=!1==checkFormElement(theDocument.forms[0].elements[1])),newDna=maxInput),!newDna)){var maxInput=theDocument.forms[0].elements[1].value,newDna=JAM.call(maxInput.split,maxInput,[/,/],JAM.policy.p9),arrayOfStartAndEnd,maxInput=
0;for(arrayOfStartAndEnd=maxInput<newDna.length;arrayOfStartAndEnd;)arrayOfStartAndEnd=newDna[maxInput],arrayOfStartAndEnd=JAM.call(arrayOfStartAndEnd.split,arrayOfStartAndEnd,[/\.\./],JAM.policy.p9),1==arrayOfStartAndEnd.length?(matchFound=!0,JAM.call(ranges.push,ranges,[new Range(arrayOfStartAndEnd[0],arrayOfStartAndEnd[0])],JAM.policy.p9)):2==arrayOfStartAndEnd.length?(matchFound=!0,JAM.call(ranges.push,ranges,[new Range(arrayOfStartAndEnd[0],arrayOfStartAndEnd[1])],JAM.policy.p9)):alert("The following range entry was ignored: "+
newDna[maxInput]),maxInput+=1,arrayOfStartAndEnd=maxInput<newDna.length;if(!1==matchFound)alert("No ranges were entered.");else{openWindow();openPre();matchFound=getArrayOfFasta(theDocument.forms[0].elements[0].value);maxInput=0;for(newDna=maxInput<matchFound.length;newDna;)newDna=getSequenceFromFasta(matchFound[maxInput]),title=getTitleFromFasta(matchFound[maxInput]),verifyDna(newDna),newDna=removeNonDna(newDna),arrayOfStartAndEnd=outputWindow.document,JAM.call(arrayOfStartAndEnd.write,arrayOfStartAndEnd,
[getFastaTitleFromTitleAndSequence(newDna)],JAM.policy.p9),writeSequenceRanges(newDna,ranges,theDocument.forms[0].elements[5].options[theDocument.forms[0].elements[5].selectedIndex].value,theDocument.forms[0].elements[6].options[theDocument.forms[0].elements[6].selectedIndex].value),maxInput+=1,newDna=maxInput<matchFound.length;closePre();closeWindow()}}}
function writeSequenceRanges(sequence,ranges,strand,segmentType){strand=new RangeGroup(strand,segmentType);segmentType=JAM.call(Math.round,Math,[sequence.length/2],JAM.policy.p9);for(var i=0,v317=i<ranges.length;v317;){var v317=ranges[i],v816=ranges[i].start,v816=JAM.call(v816.toString,v816,[],JAM.policy.p9),v816=JAM.call(v816.replace,v816,[/start|begin/gi,1],JAM.policy.p9);v317.start=v816;v317=ranges[i];v816=ranges[i].start;v816=JAM.call(v816.toString,v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,
v816,[/stop|end/gi,sequence.length],JAM.policy.p9);v317.start=v816;v317=ranges[i];v816=ranges[i].start;v816=JAM.call(v816.toString,v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/length/gi,sequence.length],JAM.policy.p9);v317.start=v816;v317=ranges[i];v816=ranges[i].start;v816=JAM.call(v816.toString,v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/middle|center|centre/gi,segmentType],JAM.policy.p9);v317.start=v816;v317=ranges[i];v816=ranges[i].stop;v816=JAM.call(v816.toString,v816,
[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/start|begin/gi,1],JAM.policy.p9);v317.stop=v816;v317=ranges[i];v816=ranges[i].stop;v816=JAM.call(v816.toString,v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/stop|end/gi,sequence.length],JAM.policy.p9);v317.stop=v816;v317=ranges[i];v816=ranges[i].stop;v816=JAM.call(v816.toString,v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/length/gi,sequence.length],JAM.policy.p9);v317.stop=v816;v317=ranges[i];v816=ranges[i].stop;v816=JAM.call(v816.toString,
v816,[],JAM.policy.p9);v816=JAM.call(v816.replace,v816,[/middle|center|centre/gi,segmentType],JAM.policy.p9);v317.stop=v816;try{var v312=ranges[i],v946=ranges[i].start,v824=JAM.call(v946.toString,v946,[],JAM.policy.p9),v635=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v824+" }"):JAM.call(eval,null,[v824]),v1186=parseInt(v635);v312.start=v1186}catch(e){alert("Could not evaluate the following expression: "+ranges[i].start);return}try{var v314=ranges[i],v947=ranges[i].stop,v826=JAM.call(v947.toString,
v947,[],JAM.policy.p9),v637=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v826+" }"):JAM.call(eval,null,[v826]),v1187=parseInt(v637);v314.stop=v1187}catch(e$$0){alert("Could not evaluate the following expression: "+ranges[i].stop);return}JAM.call(strand.addRange,strand,[ranges[i]],JAM.policy.p9);i+=1;v317=i<ranges.length}JAM.call(strand.writeRanges,strand,[sequence],JAM.policy.p9)}
function getSequence(sequence){var problem=!1,warnings=[];this.start==this.stop?(1>this.start&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is less than 1"],JAM.policy.p9)),this.start>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is greater than the sequence length"],JAM.policy.p9))):(1>this.start&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is less than 1"],JAM.policy.p9)),1>this.stop&&
(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.stop+" is less than 1"],JAM.policy.p9)),this.start>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.start+" is greater than the sequence length"],JAM.policy.p9)),this.stop>sequence.length&&(problem=!0,JAM.call(warnings.push,warnings,["position value of "+this.stop+" is greater than the sequence length"],JAM.policy.p9)),this.start>this.stop&&(problem=!0,JAM.call(warnings.push,warnings,["stop position is less than start position in range "+
this.start+" to "+this.stop],JAM.policy.p9)));return problem?(alert("An entry was skipped because of the following:\n"+JAM.call(warnings.join,warnings,[",\n"],JAM.policy.p9)),!1):this.start==this.stop?JAM.call(sequence.charAt,sequence,[this.start-1],JAM.policy.p9):JAM.call(sequence.substring,sequence,[this.start-1,this.stop],JAM.policy.p9)}function getTitle(){return this.start==this.stop?"&gt;base "+this.start:"&gt;base "+this.start+" to "+this.stop}
function Range(start,stop){this.start=start;this.stop=stop}function addRange(range){var v342=this.ranges;JAM.call(v342.push,v342,[range],JAM.policy.p9)}
function writeRanges(sequence){function v9(str,p1,offset,s){return JAM.call(sequence.substring,sequence,[offset,offset+p1.length],JAM.policy.p9)}function v8(str,p1,p2,offset,s){return p1+JAM.call(sequence.substring,sequence,[p1.length,p1.length+p2.length],JAM.policy.p9)}function v7(str,p1,offset,s){return getRandomSequence(p1.length)}function v6(str,p1,p2,offset,s){return p1+getRandomSequence(p2.length)}function v5(str,p1,offset,s){return JAM.call(p1.toLowerCase,p1,[],JAM.policy.p9)}function v4(str,
p1,p2,offset,s){return p1+JAM.call(p2.toLowerCase,p2,[],JAM.policy.p9)}function v3(str,p1,offset,s){return JAM.call(p1.toUpperCase,p1,[],JAM.policy.p9)}function v2(str,p1,p2,offset,s){return p1+JAM.call(p2.toUpperCase,p2,[],JAM.policy.p9)}var sequenceArray=[];if("new_sequence"==this.type){for(var i=0,v356=i<this.ranges.length;v356;)v356=this.ranges[i],""!=JAM.call(v356.getSequence,v356,[sequence],JAM.policy.p9)&&(v356=this.ranges[i],JAM.call(sequenceArray.push,sequenceArray,[JAM.call(v356.getSequence,
v356,[sequence],JAM.policy.p9)],JAM.policy.p9)),i+=1,v356=i<this.ranges.length;"reverse"==this.strand?(i=outputWindow.document,JAM.call(i.write,i,[addReturns(reverse(complement(JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10))))+"\n\n"],JAM.policy.p9)):(i=outputWindow.document,JAM.call(i.write,i,[addReturns(JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10))+"\n\n"],JAM.policy.p9));return!0}if("separate"==this.type){i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=
this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(sequenceArray=outputWindow.document,v356=this.ranges[i],JAM.call(sequenceArray.write,sequenceArray,[JAM.call(v356.getTitle,v356,[],JAM.policy.p9)+"\n"],JAM.policy.p9),"reverse"==this.strand?(sequenceArray=outputWindow.document,v356=this.ranges[i],JAM.call(sequenceArray.write,sequenceArray,[reverse(complement(addReturns(JAM.call(v356.getSequence,v356,[sequence],JAM.policy.p9))))+"\n\n"],JAM.policy.p9)):
(sequenceArray=outputWindow.document,v356=this.ranges[i],JAM.call(sequenceArray.write,sequenceArray,[addReturns(JAM.call(v356.getSequence,v356,[sequence],JAM.policy.p9))+"\n\n"],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;return!0}if("uppercased"==this.type){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&
(1<this.ranges[i].start?(v356="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequence=JAM.call(sequence.replace,sequence,[v356,v2],JAM.policy.p9)):(v356="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequence=JAM.call(sequence.replace,sequence,[v356,v3],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;"reverse"==this.strand?(i=outputWindow.document,JAM.call(i.write,i,[reverse(complement(addReturns(sequence)))+
"\n\n"],JAM.policy.p9)):(i=outputWindow.document,JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9));return!0}if("lowercased"==this.type){sequence=JAM.call(sequence.toUpperCase,sequence,[],JAM.policy.p9);i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v356="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+
"})",v356=RegExp(v356),sequence=JAM.call(sequence.replace,sequence,[v356,v4],JAM.policy.p9)):(v356="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequence=JAM.call(sequence.replace,sequence,[v356,v5],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;"reverse"==this.strand?(i=outputWindow.document,JAM.call(i.write,i,[reverse(complement(addReturns(sequence)))+"\n\n"],JAM.policy.p9)):(i=outputWindow.document,JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9));
return!0}if("randomized"==this.type){i=0;for(sequenceArray=i<this.ranges.length;sequenceArray;)sequenceArray=this.ranges[i],""!=JAM.call(sequenceArray.getSequence,sequenceArray,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v356="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequence=JAM.call(sequence.replace,sequence,[v356,v6],JAM.policy.p9)):(v356="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequence=
JAM.call(sequence.replace,sequence,[v356,v7],JAM.policy.p9))),i+=1,sequenceArray=i<this.ranges.length;"reverse"==this.strand?(i=outputWindow.document,JAM.call(i.write,i,[reverse(complement(addReturns(sequence)))+"\n\n"],JAM.policy.p9)):(i=outputWindow.document,JAM.call(i.write,i,[addReturns(sequence)+"\n\n"],JAM.policy.p9));return!0}if("preserved"==this.type){sequenceArray=getRandomSequence(sequence.length);i=0;for(v356=i<this.ranges.length;v356;)v356=this.ranges[i],""!=JAM.call(v356.getSequence,
v356,[sequence],JAM.policy.p9)&&(1<this.ranges[i].start?(v356="(.{"+(this.ranges[i].start-1)+"})\\B(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequenceArray=JAM.call(sequenceArray.replace,sequenceArray,[v356,v8],JAM.policy.p9)):(v356="(.{"+(this.ranges[i].stop-this.ranges[i].start+1)+"})",v356=RegExp(v356),sequenceArray=JAM.call(sequenceArray.replace,sequenceArray,[v356,v9],JAM.policy.p9))),i+=1,v356=i<this.ranges.length;"reverse"==this.strand?(i=outputWindow.document,
JAM.call(i.write,i,[reverse(complement(addReturns(sequenceArray)))+"\n\n"],JAM.policy.p9)):(i=outputWindow.document,JAM.call(i.write,i,[addReturns(sequenceArray)+"\n\n"],JAM.policy.p9));return!0}}function RangeGroup(strand,type){this.strand=strand;this.type=type;var v1188=[];this.ranges=v1188}new Range(0,0);Range.prototype.getSequence=getSequence;Range.prototype.getTitle=getTitle;new RangeGroup("","");RangeGroup.prototype.addRange=addRange;RangeGroup.prototype.writeRanges=writeRanges;
JAM.set(document,"onload",v10);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p9),"onclick",v11);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p9),"onclick",v12);

JAM.stopProfile('load');
