
JAM.startProfile('load');
function v112(callback){this.callback=callback;"MSIE"==midori.browserType&&(callback=document.body,JAM.set(JAM.call(callback.appendChild,callback,[document.createElement("div")]),"innerHTML",'<iframe id="midori_history" style="position: absolute; width: 1px; height: 1px"></iframe>'));JAM.call(setInterval,null,[this.onChange,250])}
function v111(){var newLoc=window.location.toString(),v117;v117="MSIE"==midori.browserType?JAM.call(midori.get,midori,["#midori_history"]).contentWindow.document.getElementById("me").innerText:-1!=newLoc.indexOf("#")?newLoc.match(/#(.+)$/)[1]:"";if("MSIE"==midori.browserType)(newLoc=midoriHistory.oldItem!=v117)&&(newLoc=JAM.call(midori.inArray,midori,[v117,midoriHistory.history])),newLoc&&(midoriHistory.oldItem=v117,JAM.call(midoriHistory.modifyLocation,midoriHistory,[v117]),JAM.call(midoriHistory.callback,
midoriHistory,[v117]));else{var v680=midoriHistory.oldLoc!=newLoc;v680&&(v680=JAM.call(midori.inArray,midori,[v117,midoriHistory.history]));v680&&(midoriHistory.oldLoc=newLoc,JAM.call(midoriHistory.callback,midoriHistory,[v117]))}}function v110(item){for(var history=this.history,i=0,len=history.length,v124=i<len;v124;)history[i]==item&&(history.splice(i,1),i==len&&(this.last=history[history.length-1])),i+=1,v124=i<len;this.history=history}
function v109(item){if(item!=this.last&&(this.history.push(item),JAM.call(this.modifyLocation,this,[item]),this.last=item,"MSIE"==midori.browserType)){var iframe=JAM.call(midori.get,midori,["#midori_history"]).contentWindow.document;iframe.open('javascript: "<html></html>"');JAM.call(iframe.write,iframe,['<html><body><div id="me">'+item+"</div></body></html>"]);iframe.close()}}
function v108(item){var loc=window.location.toString(),v131=window;item=-1==loc.indexOf("#")?loc+"#"+item:JAM.call(loc.replace,loc,[/#.+/,"#"+item]);v131.location=item}
function v107(){function v106(obj){function v105(o){function v104(e){var me=JAM.call(midori.getEventTarget,midori,[e]);me.blur();JAM.call(midoriTab.select,midoriTab,[me]);JAM.call(midori.preventDefault,midori,[e])}JAM.call(o.setAttribute,o,["tabset",obj.id]);"tab-selected"==o.parentNode.className&&(JAM.set(midoriTab.selectedTabs,obj.id,o,JAM.policy.p2),JAM.call(midoriTab.select,midoriTab,[o,!0]));JAM.call(midori.addEventListener,midori,[o,"click",v104])}var v136=JAM.call(midori.get,midori,["#"+obj.id+
" a"]);JAM.call(v136.apply,v136,[v105])}var v137=JAM.call(midori.get,midori,[".tab-set"]);JAM.call(v137.apply,v137,[v106])}
function v103(obj,noAnim){var tabSet=obj.getAttribute("tabset");this.selectedTabs[tabSet]&&(this.selectedTabs[tabSet].parentNode.className="",JAM.call(midori.get,midori,["#"+this.selectedTabs[tabSet].hash.substr(1)]).style.display="none");JAM.set(this.selectedTabs,tabSet,obj,JAM.policy.p2);obj.parentNode.className="tab-selected";noAnim?JAM.call(midori.get,midori,["#"+obj.hash.substr(1)]).style.display="block":JAM.call(midoriFX.show,midoriFX,[obj.hash.substr(1)])}
function v102(e){midoriPopup.hide()}function v101(e){midoriPopup.hide()}function v100(){null!=this.activePopup&&(this.hideCallback&&JAM.call(this.hideCallback,this,[this]),JAM.call(midoriFX.hide,midoriFX,[this.popupId]),this.activePopup=null)}
function v99(vars){"undefined"==typeof vars.x&&(vars.x=5);"undefined"==typeof vars.y&&(vars.y=-5);this.popupId=vars.popupId;var popup=JAM.call(midori.get,midori,["#"+vars.popupId]),dims=midori.getWindowDims(),v150;v150=vars.showAtMousePos?JAM.call(midori.getMousePos,midori,[vars.event]):JAM.call(midori.getPos,midori,[vars.obj]);popup.style.display="block";this.activePopup&&(this.activePopup.style.display="none");vars.obj.blur();dims.windowWidth<v150.x+popup.offsetWidth+vars.x&&(v150.x-=popup.offsetWidth);
for(var v156=v150.y+popup.offsetHeight+vars.y-dims.scrollTop>dims.windowHeight;v156;)v150.y-=popup.offsetHeight+20,v156=v150.y+popup.offsetHeight+vars.y-dims.scrollTop>dims.windowHeight;JAM.call(midori.setStyles,midori,[popup,{left:v150.x+vars.x+"px",top:v150.y+vars.y+vars.obj.offsetHeight+"px"}]);this.activePopup=popup;vars.noAnim?popup.style.display="block":JAM.call(midoriFX.show,midoriFX,[this.popupId]);vars.event&&JAM.call(midori.preventDefault,midori,[vars.event]);vars.showCallback&&JAM.call(vars.showCallback,
vars,[this]);this.hideCallback=vars=vars.hideCallback?vars.hideCallback:!1}
function v98(containerId,targetId,correction){function v97(){JAM.call(midoriFX.sliderToWithAnim,midoriFX,[intervalKey,container,targetPos])}var container=JAM.call(midori.get,midori,["#"+containerId]),targetPos=JAM.call(midori.getPos,midori,[JAM.call(midori.get,midori,["#"+targetId]),container]).x;containerId=container.style.marginLeft?Math.abs(parseInt(container.style.marginLeft,10)):0;var intervalKey=Math.random();this.lastIntervalId&&clearInterval(this.lastIntervalId);targetId=this.intervals;correction=
intervalKey;var v1104;v1104=containerId>targetPos?-1:1;var v723=JAM.call(setInterval,null,[v97,15]);introspect(JAM.policy.p2)targetId[correction]={targetPos:containerId,direction:v1104,intervalId:v723};this.lastIntervalId=this.intervals[intervalKey].intervalId}
function v96(intervalKey,container,targetPos){intervalKey=this.intervals[intervalKey];targetPos=Math.abs(targetPos-intervalKey.targetPos);var v173=intervalKey;v173.targetPos+=Math.round(targetPos/8)*intervalKey.direction;container.style.marginLeft=-intervalKey.targetPos+"px";4>targetPos&&clearInterval(intervalKey.intervalId)}
function v95(id,correction){function v94(){JAM.call(midoriFX.scrollToWithAnim,midoriFX,[intervalKey,targetPos])}var v177=JAM.call(midori.getPos,midori,[JAM.call(midori.get,midori,["#"+id])]).y,v728;v728=correction?correction:0;var targetPos=v177+v728,intervalKey=Math.random(),dims=midori.getWindowDims(),v177=this.intervals;v728=intervalKey;var dims=dims.scrollTop,v730=JAM.call(setInterval,null,[v94,15]);introspect(JAM.policy.p2)v177[v728]={scrollPos:dims,intervalId:v730}}
function v93(intervalKey,targetPos){if(10<Math.abs(targetPos-this.intervals[intervalKey].scrollPos)){var v181=this.intervals[intervalKey];v181.scrollPos+=Math.round((targetPos-this.intervals[intervalKey].scrollPos)/8);scrollTo(0,this.intervals[intervalKey].scrollPos)}else clearInterval(this.intervals[intervalKey].intervalId)}
function v92(id,callback,constantSpeed,horiz){function v91(){JAM.call(midoriFX.hideWithAnim,midoriFX,[vars])}var v185;v185=horiz?"width":"height";id=JAM.call(midori.get,midori,["#"+id]);var outsideSize=JAM.call(this.getOutsideSize,this,[id,v185]),v187=Math.random();horiz=horiz?id.offsetWidth:id.offsetHeight;var vars={intervalKey:v187,element:id,outsideSize:outsideSize,elementSize:horiz-outsideSize,callback:callback,constantSpeed:constantSpeed,what:v185};id.style.overflow="hidden";callback=this.intervals;
constantSpeed=vars.intervalKey;horiz=JAM.call(setInterval,null,[v91,40]);introspect(JAM.policy.p2)callback[constantSpeed]={intervalId:horiz}}
function v90(vars){var v737;v737="width"==vars.what?vars.element.offsetWidth:vars.element.offsetHeight;v737-=vars.outsideSize;v737=vars.constantSpeed?vars.oldSize-4:Math.round(v737/1.5);2<v737?(JAM.set(vars.element.style,vars.what,v737.toString()+"px",JAM.policy.p2),vars.element.style.opacity=v737/50):(clearInterval(this.intervals[vars.intervalKey].intervalId),vars.element.style.display="none",JAM.set(vars.element.style,vars.what,vars.elementSize.toString()+"px",JAM.policy.p2),vars.element.style.opacity=
1,vars.callback&&JAM.call(vars.callback,vars,[vars.element]))}
function v89(id,callback,horiz){function v88(){JAM.call(midoriFX.showWithAnim,midoriFX,[vars])}var v206;v206=horiz?"width":"height";id=JAM.call(midori.get,midori,["#"+id]);var vars={intervalKey:Math.random(),element:id,callback:callback,what:v206};JAM.call(midori.setStyles,midori,[id,{overflow:"hidden",visibility:"hidden",display:"block"}]);callback=vars;horiz=horiz?id.offsetWidth:id.offsetHeight;callback.elementSize=horiz-JAM.call(this.getOutsideSize,this,[id,v206]);JAM.call(midori.setStyles,midori,
[id,{display:"none",visibility:"visible"}]);horiz=this.intervals;v206=vars.intervalKey;callback=JAM.call(setInterval,null,[v88,40]);introspect(JAM.policy.p2)horiz[v206]={newSize:0,intervalId:callback}}
function v87(vars){var v212;v212=this.intervals[vars.intervalKey].newSize?!1:!0;var v213=this.intervals[vars.intervalKey];v213.newSize+=Math.round((vars.elementSize-this.intervals[vars.intervalKey].newSize)/2);this.intervals[vars.intervalKey].newSize<vars.elementSize?JAM.set(vars.element.style,vars.what,this.intervals[vars.intervalKey].newSize.toString()+"px",JAM.policy.p2):(clearInterval(this.intervals[vars.intervalKey].intervalId),JAM.set(vars.element.style,vars.what,vars.elementSize.toString()+
"px",JAM.policy.p2),vars.element.style.overflow="visible",vars.callback&&JAM.call(vars.callback,vars,[vars.element]));v212&&(vars.element.style.display="block")}function v86(element,what){var v224;v224="width"==what?element.offsetWidth:element.offsetHeight;JAM.set(element.style,what,v224.toString()+"px",JAM.policy.p2);var v766;v766="width"==what?element.offsetWidth:element.offsetHeight;v766-=v224;JAM.set(element.style,what,(v224-v766).toString()+"px",JAM.policy.p2);return v766}
function v85(obj,highlightClass,removeAll){function v84(o){var className=o.className.split(" "),v231=o;o=className[className.length-1]==highlightClass?o.className.substr(0,o.className.length-highlightClass.length-1):removeAll?o.className:o.className+" "+highlightClass;v231.className=o}obj=JAM.call(this.get,this,["td",obj]);JAM.call(obj.apply,obj,[v84])}
function v83(obj,stopAt){var xPos=0,yPos=0,v233;stopAt=v233=stopAt?stopAt.offsetParent:null;for(v233=obj.offsetParent!=stopAt;v233;)xPos+=obj.offsetLeft,yPos+=obj.offsetTop-obj.scrollTop,obj=obj.offsetParent,v233=obj.offsetParent!=stopAt;return{x:xPos,y:yPos}}
function v82(){return"MSIE"==this.browserType?{windowWidth:document.documentElement.clientWidth,windowHeight:document.documentElement.clientHeight,scrollTop:document.documentElement.scrollTop}:{windowWidth:window.innerWidth,windowHeight:window.innerHeight,scrollTop:window.scrollY}}
function v81(vars){var v242=vars,v1640=vars.required.split(",");v242.required=v1640;var v242=JAM.call(this.get,this,["#"+vars.formId]),v1640=!1,fieldName,fieldType,fieldStyle,i=0,numFields=vars.required.length;for(fieldName=i<numFields;fieldName;){if(fieldName=JAM.call(this.trim,this,[vars.required[i]]))fieldName=JAM.call(this.get,this,["#"+fieldName]),fieldType=fieldStyle="checkbox"==fieldName.type.toLowerCase()?"c":"t",fieldStyle="c"==fieldType?fieldName.parentNode.style:fieldName.style,fieldStyle.backgroundColor=
"",(fieldType="c"==fieldType)&&(fieldType=!fieldName.checked),fieldType||(fieldType=""==JAM.call(this.trim,this,[fieldName.value])),fieldType&&(fieldStyle.backgroundColor="#FAA",v1640=!0);i+=1;fieldName=i<numFields}i=JAM.call(this.get,this,["#"+vars.formId+"-status"]);numFields=v1640?vars.message:"";JAM.set(i,"innerHTML",numFields);i=vars.callback?vars.callback():"";(i=!1===i)||(i=v1640);if(i)return vars.event&&JAM.call(this.preventDefault,this,[vars.event]),!1;vars.event||v242.submit()}
function v80(element,cb,callback){cb.checked?JAM.set(element,"innerHTML",element.innerHTML+1):0==JAM.set(element,"innerHTML",element.innerHTML-1)&&JAM.set(element,"innerHTML","");callback&&JAM.call(callback,null,[element.innerHTML])}function v79(obj,maxWidth){function v78(o){o.width>maxWidth&&(o.style.msInterpolationMode&&(o.style.msInterpolationMode="bicubic"),o.width=maxWidth)}var v262;maxWidth=v262=maxWidth?maxWidth:400;v262=JAM.call(this.get,this,["img",obj]);JAM.call(v262.apply,v262,[v78])}
function v77(obj,maxLen){function v76(o){if(3==o.nodeType){for(var chunks=o.data.split(" "),shortened=!1,i=0,numChunks=chunks.length,v271=i<numChunks;v271;){if((stLen=chunks[i].length)>maxLen){var diffLen=Math.floor(stLen-maxLen),startPos=Math.floor(stLen/2-diffLen/2),shortened=chunks,v271=i,v795=chunks[i].substr(0,startPos)+"...",diffLen=chunks[i].substr(startPos+diffLen);introspect(JAM.policy.p2)shortened[v271]=v795+diffLen;shortened=!0}i+=1;v271=i<numChunks}shortened&&(chunks=JAM.call(midori.implode,
midori,[" ",chunks]),o.data=chunks)}}var v273;maxLen=v273=maxLen?maxLen-3:45;JAM.call(this.each,this,[obj,v76])}function v75(v,a){for(var i=0,numA=a.length,v275=i<numA;v275;){(v275=null!=v)&&(v275=a[i].constructor==Array);v275&&(v275=v.constructor==Array);v275&&(v275=a[i].toString()==v.toString());v275||(v275=a[i]==v);if(v275)return!0;i+=1;v275=i<numA}}
function v74(glue,a){if("object"!=typeof a)return a;var o="",v799=a.length;v799&&(v799=!a.propertyIsEnumerable("length"));if(v799)for(var v799=0,numA=a.length,v277=v799<numA;v277;)o+=glue+a[v799],v799+=1,v277=v799<numA;else for(numA in a)o+=glue+a[numA];return o.substr(glue.length)}function v73(a1,a2){for(var uniqA2=[],i=0,numA2=a2.length,v282=i<numA2;v282;)JAM.call(this.inArray,this,[a2[i],a1])||uniqA2.push(a2[i]),i+=1,v282=i<numA2;return a1.concat(uniqA2)}
function v72(range){var v803=Math.random();range=range?range:1E5;return Math.floor(v803*range)}function v71(st){return JAM.call(st.replace,st,[/^\s+|\s+$/g,""])}function v70(st,params){if(!params)return st;for(var matches=st.match(/:[A-Za-z0-9_]+/g).sort().reverse(),i=0,numMatches=matches.length,v288=i<numMatches;v288;)st=JAM.call(st.replace,st,[matches[i],params[matches[i].substr(1)]]),i+=1,v288=i<numMatches;return st}
function v69(parentNode,prefix,a){for(var k in a)if("object"==typeof a[k])JAM.call(this.convertToFields,this,[parentNode,prefix+"["+k+"]",a[k]]);else{var el=document.createElement("input");JAM.call(this.setAttributes,this,[el,{type:"hidden",name:prefix+"["+k+"]",value:a[k]}]);JAM.call(parentNode.appendChild,parentNode,[el])}}
function v68(name,value,expires,path,domain){introspect(JAM.policy.p1)setCookieSentinel=!0;var today=new Date,v293=document;name=name+"="+escape(value)+"; expires="+today.toUTCString(today.setSeconds(expires));path=path?"; path="+path:"";path=name+path;domain=domain?"; domain="+domain:"";introspect(JAM.policy.p2)v293.cookie=path+domain}
function v67(cookieName){for(var cookies=document.cookie.split("; "),i=0,numCookies=cookies.length,v298=i<numCookies;v298;){v298=cookies[i].split("=");if(v298[0]==cookieName)return cookieName=v298[1],unescape(JAM.call(cookieName.replace,cookieName,[/\+/g," "]));i+=1;v298=i<numCookies}}function v66(cursorPos){return cursorPos="MSIE"==this.browserType?cursorPos.htmlText:cursorPos.toString()}
function v65(target){if("MSIE"!=this.browserType)return target.getSelection();target==window&&(target=document);var cursorPos=target.selection.createRange();if("Control"!=target.selection.type)return cursorPos}function v64(o,v){"MSIE"==this.browserType?o.style.styleFloat=v:o.style.cssFloat=v}function v63(o){return o="MSIE"==this.browserType?o.style.styleFloat:o.style.cssFloat}function v62(event){event.preventDefault?event.preventDefault():window.event.returnValue=!1}
function v61(event){event.stopPropagation?event.stopPropagation():window.event.cancelBubble=!0}function v60(event){var v829=event.targetTouches;v829&&(v829=event.targetTouches.length);if(v829)return{x:event.targetTouches[0].pageX,y:event.targetTouches[0].pageY};v829=event.pageX;v829||(v829=event.pageY);return v829?{x:event.pageX,y:event.pageY}:{x:event.clientX+document.documentElement.scrollLeft-document.body.clientLeft,y:event.clientY+document.documentElement.scrollTop-document.body.clientTop}}
function v59(event){event=event.target?event.target:event.srcElement;3==event.nodeType&&(event=event.parentNode);return event}function v58(){this.readyTimer&&clearInterval(this.readyTimer);for(var i=0,numE=this.domReady.length,v322=i<numE;v322;)this.domReady[i](),i+=1,v322=i<numE}
function v57(target,eventType,listenerFunc){function v56(){function v55(){"complete"==this.readyState&&midori.runReadyEvents()}JAM.call(document.write,document,['<script id="midori_onload" src="javascript: {}" defer="true">\x3c/script>']);JAM.set(JAM.call(this.get,this,["#midori_onload"]),"onreadystatechange",v55)}function v54(){function v53(){/loaded|complete/.test(document.readyState)&&midori.runReadyEvents()}var v1642=JAM.call(setInterval,null,[v53,10]);this.readyTimer=v1642}this.safariReady=v54;
this.msieReady=v56;if(target.addEventListener){if("ready"==eventType)switch(this.browserType){case "Safari":this.domReady.push(listenerFunc);this.readyTimer||this.safariReady();return;case "Opera":case "Gecko":eventType="DOMContentLoaded";break;default:eventType="load"}JAM.call(target.addEventListener,target,[eventType,listenerFunc,!1])}else"ready"==eventType?(this.domReady.length||this.msieReady(),this.domReady.push(listenerFunc)):JAM.call(target.attachEvent,target,["on"+eventType,listenerFunc])}
function v52(obj){return obj.parentNode.removeChild(obj)}function v51(obj,attrList){for(var i in attrList)"className"==i?obj.className=attrList[i]:JAM.call(obj.setAttribute,obj,[i,attrList[i]])}function v50(obj,styleList){for(var i in styleList)"float"==i?JAM.call(this.setFloat,this,[obj,styleList[i]]):JAM.set(obj.style,i,styleList[i],JAM.policy.p2)}
function v49(stylesheet,rule,property){var values=[];stylesheet=document.styleSheets[stylesheet];stylesheet=stylesheet.rules?stylesheet.rules:stylesheet.cssRules;rule=rule.toLowerCase();property="Safari"==this.browserType?JAM.call(property.replace,property,[/([A-Z])/,"-$1"]).toLowerCase():property.toLowerCase();for(var i=0,numRules=stylesheet.length,v353=i<numRules;v353;){(v353="*"==rule)||(v353=stylesheet[i].selectorText.toLowerCase()==rule);if(v353)for(var j in stylesheet[i].style)if("Safari"==
this.browserType){if((v353=stylesheet[i].style[j].toLowerCase)&&(v353=stylesheet[i].style[j].toLowerCase()==property),v353)if("*"==rule)JAM.set(values,stylesheet[i].selectorText,value,JAM.policy.p2);else return stylesheet[i].style[stylesheet[i].style[j]]}else if(j.toLowerCase()==property)if("*"==rule)JAM.set(values,stylesheet[i].selectorText,stylesheet[i].style[j],JAM.policy.p2);else return stylesheet[i].style[j];i+=1;v353=i<numRules}return values}
function v48(selectorText,startAt){function v47(p){for(var i=0,numObjs=this.length,v355=i<numObjs;v355;)"function"==typeof p?JAM.call(p,null,[this[i]]):(v355="this[i]."+p,JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v355+" }"):JAM.call(eval,null,[v355])),i+=1,v355=i<numObjs}var selectors=JAM.call(this.parseSelectors,this,[selectorText]),numS=selectors.elements.length;startAt||(startAt=document);if(1==numS){var idMatch=selectors.elements[0].match(/^[a-z0-9*]*#([^,:]+)$/i),v1188=idMatch;
v1188&&(v1188=""==selectors.attrs[0]);v1188&&(v1188=""==selectors.separators);if(v1188)return document.getElementById(idMatch[1])}var idMatch=JAM.call(this.getMatches,this,[startAt,selectors.elements[0],selectors.attrs[0]]),v1188=[],newObjs,separator,i$$0=1;for(newObjs=i$$0<numS;newObjs;){newObjs=[];separator=JAM.call(this.trim,this,[selectors.separators[i$$0-1]]);if(","==separator)v1188=JAM.call(this.concatUnique,this,[v1188,idMatch]),idMatch=JAM.call(this.getMatches,this,[startAt,selectors.elements[i$$0],
selectors.attrs[i$$0]]);else{separator=">"==separator?!0:!1;for(var j=0,numObjs$$0=idMatch.length,v370=j<numObjs$$0;v370;)JAM.call(this.inArray,this,[idMatch[j],newObjs])||(newObjs=JAM.call(this.concatUnique,this,[newObjs,JAM.call(this.getMatches,this,[idMatch[j],selectors.elements[i$$0],selectors.attrs[i$$0]]),separator])),j+=1,v370=j<numObjs$$0;idMatch=newObjs}i$$0+=1;newObjs=i$$0<numS}v1188=JAM.call(this.concatUnique,this,[v1188,idMatch]);v1188.apply=v47;return v1188}
function v46(target,s,a,oneLevelOnly){function v45(me){var v878=!numA;v878&&(v878=!pseudo);if(v878)matches.push(me);else{var v878=!0,v879=numA;v879&&(v879=!JAM.call(this.processAttrs,this,[me,a,exprs]));v879&&(v878=!1);(v879=pseudo)&&(v879=!JAM.call(this.processPseudo,this,[me,pSelector,pA,pB]));v879&&(v878=!1);v878&&matches.push(me)}}this.pCache={};var matches=[],exprs=[],chunks,pseudo,pSelector,pOption,pA,pB;this.postProcess=v45;pOption=0;var numA=a.length;for(chunks=pOption<numA;chunks;){chunks=
a[pOption].match(/([a-z0-9_-]+)\s*([=^$*|!]{0,2})\s*"?([^"]*)"?$/i);introspect(JAM.policy.p2)a[pOption]=chunks[1];switch(chunks[2]){case "=":var v377=exprs,v378=pOption;chunks=new RegExp("^"+chunks[3]+"$","i");introspect(JAM.policy.p2)v377[v378]=chunks;break;case "^=":v377=exprs;v378=pOption;chunks=new RegExp("^"+chunks[3],"i");introspect(JAM.policy.p2)v377[v378]=chunks;break;case "$=":v377=exprs;v378=pOption;chunks=new RegExp(chunks[3]+"$","i");introspect(JAM.policy.p2)v377[v378]=chunks;break;case "*=":v377=
exprs;v378=pOption;chunks=new RegExp(chunks[3],"i");introspect(JAM.policy.p2)v377[v378]=chunks;break;case "&=":v377=exprs;v378=pOption;chunks=new RegExp("^"+chunks[3]+"$|^"+chunks[3]+"\\s|\\s"+chunks[3]+"\\s|\\s"+chunks[3]+"$","i");introspect(JAM.policy.p2)v377[v378]=chunks;break;case "!=":introspect(JAM.policy.p2)exprs[pOption]=chunks[3]}pOption+=1;chunks=pOption<numA}if(-1!=s.indexOf(":")){chunks=s.split(":");s=chunks[0];pseudo=chunks[1].match(/([a-z-]+)\(?([a-z0-9+-]*)\)?/i);pSelector=pseudo[1].toLowerCase();
switch(pOption=pseudo[2].toLowerCase()){case "odd":pOption="2n+1";break;case "even":pOption="2n"}chunks=pOption.match(/([0-9+-]*)(n?)([0-9+-]*)/i);pOption=chunks[2]?chunks[1]?"-"==chunks[1]?-1:chunks[1]:1:0;pA=parseInt(pOption);chunks[3]?pOption=chunks[3]:((pOption=chunks[1])&&(pOption=!chunks[2]),pOption=pOption?chunks[1]:0);pB=parseInt(pOption)}if(-1!=s.indexOf("#"))JAM.call(this.postProcess,this,[document.getElementById(s.substr(s.indexOf("#")+1))]);else if(-1!=s.indexOf("."))for(chunks=s.split("."),
pOption=s.substr(chunks[0].length+1),pOption=JAM.call(pOption.replace,pOption,["."," "]),v377=new RegExp("^"+pOption+"$|^"+pOption+"\\s|\\s"+pOption+"\\s|\\s"+pOption+"$","i"),pOption=chunks[0]?chunks[0]:"*",s=target.getElementsByTagName(pOption),pOption=0,chunks=s.length,v378=pOption<chunks;v378;)(v378=!oneLevelOnly)&&(v378=v377.test(s[pOption].className)),v378||((v378=oneLevelOnly)&&(v378=v377.test(s[pOption].className)),v378&&(v378=s[pOption].parentNode==target)),v378&&JAM.call(this.postProcess,
this,[s[pOption]]),pOption+=1,v378=pOption<chunks;else if((pOption="*"==s)||(pOption=/^[A-Za-z0-9]+$/.test(s)),pOption)for(pOption=0,s=target.getElementsByTagName(s),chunks=s.length,v377=pOption<chunks;v377;)v377=!oneLevelOnly,v377||(v377=oneLevelOnly)&&(v377=s[pOption].parentNode==target),v377&&JAM.call(this.postProcess,this,[s[pOption]]),pOption+=1,v377=pOption<chunks;return matches}
function v44(match,pSelector,pA,pB){var pCache,nodeKey,parentChildren=[],pI=0;(nodeKey=match.parentNode.getAttribute("midorinodekey"))||(nodeKey=match.parentNode,JAM.call(nodeKey.setAttribute,nodeKey,["midorinodekey",nodeKey=Math.random().toString().substr(2)]));if(pCache=this.pCache[nodeKey])parentChildren=pCache.parentChildren,pI=pCache.pI;else{for(pCache=match.parentNode.firstChild;pCache;)1==pCache.nodeType&&parentChildren.push(pCache),pCache=pCache.nextSibling;JAM.set(this.pCache,nodeKey,{parentChildren:parentChildren,
pI:0},JAM.policy.p2)}pCache=parentChildren.length;switch(pSelector){case "first-child":if(match==parentChildren[0])return!0;break;case "last-child":if(match==parentChildren[pCache-1])return!0;break;case "only-child":if(1==pCache)return!0}if("nth-child"==pSelector){pSelector=pA*pI+pB;pB=-50;var v905=-50<pSelector;for(v905&&(v905=pSelector<=pCache);v905;){(v905=0<=pSelector)&&(v905=parentChildren[pSelector-1]==match);if(v905)return match=this.pCache[nodeKey],pA=0<=pA?pI+1:0,match.pI=pA,!0;pI+=1;pSelector+=
pA;if(pSelector==pB)break;pB=pSelector;(v905=-50<pSelector)&&(v905=pSelector<=pCache)}}}function v43(match,a,exprs){var i=0,numA=a.length,attr;for(attr=i<numA;attr;){attr="class"==a[i]?match.className?match.className:null:match.getAttribute(a[i]);switch(typeof exprs[i]){case "undefined":if(null==attr)return!1;break;case "string":if(attr==exprs[i])return!1;break;default:if(!exprs[i].test(attr))return!1}i+=1;attr=i<numA}return!0}
function v42(selectorText){selectorText=JAM.call(this.trim,this,[selectorText]).split("");for(var sI=-1,bracketContent="",elements=[],attrs=[],separators=[],inSelector=!1,inBrackets=!1,inQuotes=!1,i=0,len=selectorText.length,v437=i<len;v437;){if(inSelector)if(inBrackets)switch(selectorText[i]){case '"':inQuotes=!inQuotes;break;case "]":inQuotes||(attrs[sI].push(bracketContent),inBrackets=!1,bracketContent="");break;case "\\":bracketContent+=selectorText[i+=1];break;default:bracketContent+=selectorText[i]}else switch(selectorText[i]){case "[":inBrackets=
!0;break;case " ":case ">":case ",":inSelector=!1;introspect(JAM.policy.p2)separators[sI]=selectorText[i];break;case "\\":var v437=elements[sI],v919=selectorText[i+=1];introspect(JAM.policy.p2)elements[sI]=v437+v919;break;default:v437=elements[sI];v919=selectorText[i];introspect(JAM.policy.p2)elements[sI]=v437+v919}else switch(selectorText[i]){case " ":case ">":case ",":v437=separators[sI];v919=selectorText[i];introspect(JAM.policy.p2)separators[sI]=v437+v919;break;default:inSelector=!0;v437=sI+=
1;introspect(JAM.policy.p2)elements[v437]=selectorText[i];introspect(JAM.policy.p2)attrs[sI]=[]}i+=1;v437=i<len}return{elements:elements,attrs:attrs,separators:separators}}
function v41(obj,direction){var sibling=obj;if("next"==direction){var v924=sibling;v924&&(v924=3==sibling.nodeType);do(v924=sibling=sibling.nextSibling)&&(v924=3==sibling.nodeType);while(v924)}else if("prev"==direction){(v924=sibling)&&(v924=3==sibling.nodeType);do(v924=sibling=sibling.previousSibling)&&(v924=3==sibling.nodeType);while(v924)}return sibling=sibling==obj?!1:sibling}
function v40(parentObj,callBack,depthFirst){for(parentObj=parentObj.firstChild;parentObj;)depthFirst||JAM.call(callBack,null,[parentObj]),parentObj.firstChild&&JAM.call(this.each,this,[parentObj,callBack,depthFirst]),depthFirst&&JAM.call(callBack,null,[parentObj]),parentObj=parentObj.nextSibling}
function midoriTableSelection(vars){function v4(){var numRowIds=this.rowIds.length;if("none"==JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"header-cb"]).style.display){JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"header-cb"]).style.display="";for(var i=0,v452=i<numRowIds;v452;)v452=this.rowIds[i],JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"cb_"+v452]).style.display="",JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"cb_"+v452]).firstChild.checked&&JAM.call(midori.highlightRow,
midori,[JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+v452]),this.vars.rowHighlight]),i+=1,v452=i<numRowIds;vars.showCallback&&JAM.call(vars.showCallback,vars,[this])}else{JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"header-cb"]).style.display="none";i=0;for(v452=i<numRowIds;v452;)JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+"cb_"+this.rowIds[i]]).style.display="none",JAM.call(midori.highlightRow,midori,[JAM.call(midori.get,midori,["#"+this.vars.rowPrefix+this.rowIds[i]]),this.vars.rowHighlight,
!0]),i+=1,v452=i<numRowIds;vars.hideCallback&&JAM.call(vars.hideCallback,vars,[this])}}function v3(o){function v2(e){JAM.call(midori.highlightRow,midori,[JAM.call(midori.get,midori,["#"+vars.rowPrefix+id]),vars.rowHighlight]);JAM.call(midori.saveCheckboxState,midori,[JAM.call(midori.get,midori,["#"+vars.tableId+"_cb_parent"]),el]);this.value=id}function v1(c){className=c.className}var td,el,id,className;td=JAM.call(midori.get,midori,["td:last-child",o]);JAM.call(td.apply,td,[v1]);id=o.id.substr(vars.rowPrefix.length);
td=document.createElement("td");td.style.display="none";JAM.call(midori.setAttributes,midori,[td,{id:vars.rowPrefix+"cb_"+id,className:className}]);el=document.createElement("input");JAM.call(midori.setAttributes,midori,[el,{name:vars.checkboxName,type:"checkbox",value:id}]);JAM.call(midori.addEventListener,midori,[el,"click",v2]);JAM.call(td.appendChild,td,[el]);JAM.call(o.appendChild,o,[td]);thisObj.rowIds.push(id)}function v0(e){var id,el,isChecked;e=0;var numIds=thisObj.rowIds.length;for(id=e<
numIds;id;)id=thisObj.rowIds[e],el=JAM.call(midori.get,midori,["#"+vars.rowPrefix+"cb_"+id]).firstChild,isChecked=el.checked,el.checked=!isChecked,isChecked=isChecked?"":id,el.value=isChecked,JAM.call(midori.highlightRow,midori,[JAM.call(midori.get,midori,["#"+vars.rowPrefix+id]),vars.rowHighlight]),JAM.call(midori.saveCheckboxState,midori,[JAM.call(midori.get,midori,["#"+vars.tableId+"_cb_parent"]),el]),e+=1,id=e<numIds}this.vars=vars;this.rowIds=[];var thisObj=this,cb=document.createElement("input");
JAM.call(cb.setAttribute,cb,["type","checkbox"]);JAM.call(midori.addEventListener,midori,[cb,"click",v0]);var firstTh=JAM.call(midori.get,midori,["#"+vars.tableId+" th"])[0],th=document.createElement("th");JAM.call(midori.setAttributes,midori,[th,{id:vars.rowPrefix+"header-cb",align:"left",className:firstTh.className}]);JAM.call(th.appendChild,th,[cb]);th.style.display="none";cb=firstTh.parentNode;JAM.call(cb.appendChild,cb,[th]);th=document.createElement("div");th.id=vars.tableId+"_cb_parent";cb=
document.body;JAM.call(cb.appendChild,cb,[th]);th=JAM.call(midori.get,midori,["#"+vars.tableId+' tr[id^="'+vars.rowPrefix+'"]']);JAM.call(th.apply,th,[v3]);this.toggle=v4}
function midoriDragDrop(containerId,dropCallback){function v18(e){JAM.call(thisObj.mouseUp,thisObj,[e])}function v17(e){JAM.call(thisObj.mouseMove,thisObj,[e])}function v16(e){thisObj.doneDragging&&JAM.call(midori.preventDefault,midori,[e])}function v15(e){JAM.call(thisObj.mouseUp,thisObj,[e])}function v14(e){JAM.call(thisObj.mouseMove,thisObj,[e])}function v13(o,dragged,spacer){if(/drop-target/.test(o.obj.className))return o=o.obj,dragged=spacer?spacer:dragged,JAM.call(o.appendChild,o,[dragged]);
var v1246="next"==o.where;v1246&&(v1246=!o.obj.nextSibling);v1246?(o=o.obj.parentNode,dragged=spacer?spacer:dragged,o=JAM.call(o.appendChild,o,[dragged])):(v1246=o.obj.parentNode,dragged=spacer?spacer:dragged,o="prev"==o.where?o.obj:o.obj.nextSibling,o=JAM.call(v1246.insertBefore,v1246,[dragged,o]));return o}function v12(event){this.doneDragging=!1;if(this.dragged){var objCoords,v960=this.mouseMoved;v960&&(v960=objCoords=JAM.call(this.findPlace,this,[event,!0]));v960&&(JAM.call(this.dropCallback,
this,[objCoords,this.dragged]),this.doneDragging=!0);this.dragged&&(this.spacer.style.display="none",JAM.call(midori.setStyles,midori,[this.dragged,{position:"",opacity:"1"}]),JAM.call(this.init,this,[this.container]))}}function v11(event){var v963=!this.dragged;v963||(v963=/drop-target/.test(this.dragged.className));v963||(JAM.call(midori.preventDefault,midori,[event]),this.lastMousePos=v963=JAM.call(midori.getMousePos,midori,[event]),this.mouseMoved=!0,JAM.call(midori.setStyles,midori,[this.dragged,
{position:"absolute",left:v963.x-this.mouseOffset.x+"px",top:v963.y-this.mouseOffset.y+"px"}]),JAM.call(midori.setFloat,midori,[this.spacer,JAM.call(midori.getFloat,midori,[this.dragged])]),(v963=event=JAM.call(this.findPlace,this,[event]))&&(v963=JAM.call(this.dropCallback,this,[event,this.dragged,this.spacer])),v963?(JAM.call(midori.setStyles,midori,[this.spacer,{display:"block",height:this.dragged.offsetHeight+"px"}]),JAM.call(midori.getFloat,midori,[this.spacer])&&(this.spacer.style.width=this.dragged.offsetWidth+
"px")):this.spacer.style.display="none")}function v10(parentObj){function v9(o){if(/draggable/.test(o.className)){j=0;for(var v513=j<numObjs;v513;){if(thisObj.objs[j]==o){JAM.set(thisObj.objs,j,"",JAM.policy.p2);break}j+=1;v513=j<numObjs}}}var j,numObjs=this.objs.length;JAM.call(midori.each,midori,[parentObj,v9,!0]);j=0;for(var v517=j<numObjs;v517;){if(this.objs[j]==parentObj){JAM.set(this.objs,j,"",JAM.policy.p2);break}j+=1;v517=j<numObjs}}function v8(event,mouseUp){var v518;if(v518=mouseUp)v518=
event.targetTouches;v518=v518?this.lastMousePos:JAM.call(midori.getMousePos,midori,[event]);var obj,objCoords;if(!this.objsCoords.length){var i=0,numObjs=this.objs.length;for(obj=i<numObjs;obj;){var v978=obj=this.objs[i];v978&&(v978=objCoords=JAM.call(midori.getPos,midori,[obj]));v978&&this.objsCoords.push({obj:obj,x:objCoords.x,y:objCoords.y,width:obj.offsetWidth,height:obj.offsetHeight});i+=1;obj=i<numObjs}}i=0;numObjs=this.objsCoords.length;for(objCoords=i<numObjs;objCoords;){if(objCoords=this.objsCoords[i]){(obj=
v518.x>=objCoords.x)&&(obj=v518.x<=objCoords.x+objCoords.width);obj&&(obj=v518.y>=objCoords.y)&&(obj=v518.y<=objCoords.y+objCoords.height);if(!obj){i+=1;objCoords=i<numObjs;continue}i=objCoords;v518=JAM.call(midori.getFloat,midori,[objCoords.obj])?v518.x<objCoords.x+objCoords.width/2?"prev":"next":v518.y<objCoords.y+objCoords.height/2?"prev":"next";i.where=v518;return objCoords}i+=1;objCoords=i<numObjs}}function v7(){function v6(o){function v5(e){var mousePos=JAM.call(midori.getMousePos,midori,[e]),
me=JAM.call(midori.getEventTarget,midori,[e]);if(!/not-draggable/.test(me.className)){for(var v531=!/draggable/.test(me.className);v531;)me=me.parentNode,v531=!/draggable/.test(me.className);v531=JAM.call(midori.getPos,midori,[me]);thisObj.dragged=me;thisObj.mouseOffset={x:mousePos.x-v531.x,y:mousePos.y-v531.y};/drop-target/.test(o.className)||(me.style.opacity=".5",JAM.call(midori.preventBubble,midori,[e]),JAM.call(midori.preventDefault,midori,[e]));JAM.call(thisObj.removeDraggedObj,thisObj,[me])}}
var v1274=/not-draggable/.test(o.className);v1274||(v1274=!/draggable/.test(o.className));v1274||(v1274="none"==o.style.display);if(!v1274){thisObj.objs.push(o);for(var v1274=0,v539=2>v1274;v539;)JAM.call(midori.addEventListener,midori,[o,["mousedown","touchstart"][v1274],v5]),v1274+=1,v539=2>v1274}}this.objs=[];this.objsCoords=[];this.mouseMoved=!1;this.dragged=null;JAM.call(midori.each,midori,[this.container,v6,!0])}var thisObj=this,v1648=JAM.call(midori.get,midori,["#"+containerId]);this.container=
v1648;this.init=v7;this.findPlace=v8;this.removeDraggedObj=v10;this.mouseMove=v11;this.mouseUp=v12;this.defaultDropCallback=v13;JAM.call(midori.addEventListener,midori,[this.container,"mousemove",v14]);JAM.call(midori.addEventListener,midori,[this.container,"mouseup",v15]);JAM.call(midori.addEventListener,midori,[this.container,"click",v16]);JAM.call(midori.addEventListener,midori,[this.container,"touchmove",v17]);JAM.call(midori.addEventListener,midori,[this.container,"touchend",v18]);this.spacer=
v1648=document.createElement("div");JAM.set(this.spacer,"innerHTML","&nbsp;");JAM.call(midori.setAttributes,midori,[this.spacer,{id:"midori_dd_spacer"+midori.uniqid(),className:"midori-dd-spacer"}]);this.dropCallback=v1648=dropCallback?dropCallback:this.defaultDropCallback;this.init()}
function midoriAjax(callback){var params="",cache=!0;function v20(where,what,verb,headers){var cachedValue;this.cacheKey=where+"?"+what;var v997=cache;v997&&(v997=null!=(cachedValue=this.cache[this.cacheKey]));if(v997)this.responseText=cachedValue,JAM.call(this.runCallback,this,["",!0]);else{JAM.set(this.request,"onreadystatechange",this.runCallback);verb?(verb=1==verb?"GET":verb,verb=JAM.call(midori.trim,midori,[verb.toUpperCase()])):verb="POST";cachedValue=this.request;JAM.call(midori.inArray,midori,
[verb,["POST","PUT"]])||(v997=what?"?"+what:"",where+=v997);cachedValue.open(verb,where,!0);JAM.call(midori.inArray,midori,[verb,["POST","PUT"]])&&(this.request.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=utf-8"),this.request.setRequestHeader("Content-length",what.length),this.request.setRequestHeader("Connection","close"));if(headers)for(where=0,cachedValue=headers.length,v997=where<cachedValue;v997;)this.request.setRequestHeader(headers[where][0],headers[where][1]),
where+=1,v997=where<cachedValue;headers=this.request;what=JAM.call(midori.inArray,midori,[verb,["POST","PUT"]])?what:null;headers.send(what)}}function v19(event,cached){if(!cached){if(4!=thisObj.request.readyState)return;thisObj.responseText=thisObj.request.responseText;thisObj.responseXML=thisObj.request.responseXML;thisObj.status=thisObj.request.status;JAM.set(thisObj.cache,thisObj.cacheKey,thisObj.responseText,JAM.policy.p2)}JAM.call(thisObj.callback,thisObj,[params])}var thisObj=this;this.cache=
{};this.callback=callback;try{var v1650=new XMLHttpRequest;this.request=v1650}catch(e){try{var v1651=new ActiveXObject("Msxml2.XMLHTTP");this.request=v1651}catch(e$$0){this.request=callback=new ActiveXObject("Microsoft.XMLHTTP")}}this.runCallback=v19;this.post=v20}
function midoriAutoComplete(vars){function v32(){function v31(e){JAM.call(thisObj.process,thisObj,[e])}function v30(e){if(13==e.keyCode)return!1}function v29(e){13==e.keyCode&&JAM.call(midori.preventDefault,midori,[e])}function v28(){if(thisObj.ajax.responseText){var v577;"string"==typeof thisObj.ajax.responseText?(v577="("+thisObj.ajax.responseText+")",v577=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v577+" }"):JAM.call(eval,null,[v577])):v577=thisObj.ajax.responseText;JAM.set(thisObj.suggestions,
v577.snippet,v577.result,JAM.policy.p2);JAM.call(thisObj.showSuggestions,thisObj,[v577.snippet])}}vars.separator||(vars.separator="");this.ajaxCallback=v28;var v1653=midori.uniqid();this.uniqid=v1653;this.obj=v1653=JAM.call(midori.get,midori,["#"+vars.id]);this.oldContent=this.content=this.obj.value;this.suggestions=[];this.ajax=v1653="string"==typeof vars.fileName?new midoriAjax(this.ajaxCallback):{};if("Gecko"!=this.browserType){v1653=this.obj;JAM.call(midori.addEventListener,midori,[v1653,"keypress",
v29]);for(var v587=null!=v1653.parentNode;v587;)v1653=v1653.parentNode,"form"==v1653.nodeName.toLowerCase()&&JAM.call(midori.addEventListener,midori,[v1653,"keypress",v30]),v587=null!=v1653.parentNode}v1653=this.obj;JAM.call(v1653.setAttribute,v1653,["autocomplete","off"]);JAM.call(midori.addEventListener,midori,[this.obj,"keyup",v31])}function v27(snippet){var pos=0,i;for(i in this.suggestions[snippet])if((pos+=1)==this.suggestionPos){var pos=this.obj,v1022=this.obj.value;i=vars.callback?JAM.call(vars.callback,
vars,[this.suggestions[snippet][i]]):this.suggestions[snippet][i];snippet=JAM.call(v1022.replace,v1022,[snippet,i]);pos.value=snippet;break}this.oldContent=this.content=this.obj.value;this.obj.focus()}function v26(suggestionPos){var v1290="#"+this.popupId+" .",v1454=vars.suggestionSelectedClass,v1290=JAM.call(midori.get,midori,[v1290+JAM.call(v1454.replace,v1454,[" ","."])]);JAM.call(v1290.apply,v1290,["className = '"+vars.suggestionClass+"'"]);JAM.call(midori.get,midori,["#midori_suggestion"+this.uniqid+
"_"+suggestionPos]).className=vars.suggestionSelectedClass;this.suggestionPos=suggestionPos}function v25(snippet){var suggestions=this.suggestions[snippet],html="",properties=[],i=0,j=0,k="";for(i in suggestions){if(vars.htmlTemplate)for(k in suggestions[i])JAM.set(properties,k,suggestions[i][k],JAM.policy.p2);var v1456='<a id="midori_suggestion'+this.uniqid+"_"+(j+=1)+'" class="'+vars.suggestionClass+'" href="#">',v1547;v1547=vars.htmlTemplate?JAM.call(midori.replace,midori,[vars.htmlTemplate,properties]):
suggestions[i];html+=v1456+v1547+"</a>\n"}if(html){this.snippet=snippet;this.suggestionPos=0;this.numSuggestions=j;this.popup&&JAM.call(midori.removeNode,midori,[this.popup]);this.popupId="midori_suggestions"+this.uniqid;this.popup=suggestions=document.createElement("div");JAM.call(midori.setAttributes,midori,[this.popup,{id:this.popupId,className:"popup"}]);suggestions=document.body;JAM.call(suggestions.appendChild,suggestions,[this.popup]);JAM.set(this.popup,"innerHTML",html);j=0;for(i in this.suggestions[snippet])JAM.call(this.addProperties,
this,[j+=1,snippet]);JAM.call(midoriPopup.show,midoriPopup,[{obj:this.obj,popupId:this.popupId,x:0,y:0,noAnim:!0}]);this.obj.focus()}else midoriPopup.hide()}function v24(id,snippet){function v23(e){JAM.call(thisObj.replaceSnippet,thisObj,[snippet]);JAM.call(midori.preventDefault,midori,[e])}function v22(e){JAM.call(thisObj.highlightSuggestion,thisObj,[id])}var obj=JAM.call(midori.get,midori,["#midori_suggestion"+this.uniqid+"_"+id]);JAM.call(midori.addEventListener,midori,[obj,"mouseover",v22]);JAM.call(midori.addEventListener,
midori,[obj,"click",v23])}function v21(event){var v1034=this.popup;v1034&&(v1034=this.popup==midoriPopup.activePopup);if(v1034)switch(event.keyCode){case 27:case 37:case 39:midoriPopup.hide();break;case 13:JAM.call(this.replaceSnippet,this,[this.snippet]);midoriPopup.hide();break;case 38:(v1034=this.suggestionPos)&&(v1034=1!=this.suggestionPos);v1034&&JAM.call(this.highlightSuggestion,this,[this.suggestionPos-1]);break;case 40:this.suggestionPos!=this.numSuggestions&&JAM.call(this.highlightSuggestion,
this,[this.suggestionPos+1])}else vars.callback2&&JAM.call(vars.callback2,vars,[event]);this.content=this.obj.value;(v1034=this.content==this.oldContent)||(v1034=JAM.call(midori.inArray,midori,[event.keyCode,[13,38,40]]));if(!v1034){for(var changed=!1,v1034=0,len=this.content.length,v629=v1034<len;v629;){if(this.content.charAt(v1034)!=this.oldContent.charAt(v1034)){changed=!0;break}v1034+=1;v629=v1034<len}(changed=!changed)&&(changed=this.oldContent.length<len);if(!changed){this.content.charAt(v1034)==
vars.separator&&(v1034=8==event.keyCode?v1034-1:v1034+1);changed=v1034;for(event=0<changed;event;){if(this.content.charAt(changed)==vars.separator){changed+=1;break}changed-=1;event=0<changed}event=this.content.substr(changed,v1034-changed);changed=v1034;for(v629=changed<len;v629&&this.content.charAt(changed)!=vars.separator;)changed+=1,v629=changed<len;event+=this.content.substr(v1034,changed-v1034);event=JAM.call(midori.trim,midori,[event]);event.length>=vars.minChars&&("string"==typeof vars.fileName?
(v1034=this.ajax,JAM.call(v1034.post,v1034,[vars.fileName,vars.params+JAM.call(midori.trim,midori,[event])])):(v1034=this.ajax,len=JAM.call(vars.fileName,vars,[vars.params+JAM.call(midori.trim,midori,[event])]),v1034.responseText=len,this.ajaxCallback()));this.oldContent=this.content}}}var thisObj=this;this.process=v21;this.addProperties=v24;this.showSuggestions=v25;this.highlightSuggestion=v26;this.replaceSnippet=v27;this.init=v32;this.init()}
function midoriInlineEdit(vars){function v39(){if("on"==this.myObj.getAttribute("editing")){var v1317=this.editObj.value,v1317=JAM.call(v1317.replace,v1317,["\n",""]);if(v1317=JAM.call(midori.trim,midori,[JAM.call(v1317.replace,v1317,["\r",""])])){var v649=this.myObj;JAM.call(v649.setAttribute,v649,["editing","off"]);JAM.set(this.myObj,"innerHTML","");JAM.set(this.myObj,"innerHTML",v1317);vars.callback&&JAM.call(vars.callback,vars,[v1317,this.myObj])}else this.editObj.value=""}}function v38(){"on"==
this.myObj.getAttribute("editing")&&this.editObj.select()}function v37(){function v36(e){thisObj.save()}function v35(e){var v1062=13==e.keyCode;v1062||(v1062=27==e.keyCode);v1062&&thisObj.save()}function v34(e){JAM.call(midori.preventBubble,midori,[e])}var v1063="on"==this.myObj.getAttribute("editing");v1063||(v1063=JAM.call(midori.get,midori,[this.input,this.myObj])[0]);if(!v1063){var v1063=this.myObj.innerHTML,value=JAM.call(v1063.replace,v1063,[/"/g,"&quot;"]),v1063=this.myObj;if(vars.textArea){var v1595=
this.myObj.parentNode.offsetWidth,v1618;v1618=vars.x?vars.x:32;v1595=v1595-v1618+"px";v1618=this.myObj.parentNode.offsetHeight;var v1620;v1620=vars.y?vars.y:32;value=JAM.call(midori.replace,midori,['<textarea style="width: :w; height: :h; overflow: auto">:value</textarea>',{w:v1595,h:v1618-v1620+"px",value:value}])}else v1595=vars.size?vars.size:"",v1618=vars.maxlen?vars.maxlen:"",value=JAM.call(midori.replace,midori,['<input type="text" size=":size" maxlength=":maxlen" value=":value" />',{size:v1595,
maxlen:v1618,value:value}]);JAM.set(v1063,"innerHTML",value);this.editObj=JAM.call(midori.get,midori,[this.input,this.myObj])[0];this.editObj.focus();this.editObj.focus();v1063=this.myObj;JAM.call(v1063.setAttribute,v1063,["editing","on"]);JAM.call(midori.addEventListener,midori,[this.editObj,"mousedown",v34]);JAM.call(midori.addEventListener,midori,[this.editObj,"keyup",v35]);JAM.call(midori.addEventListener,midori,[this.editObj,"blur",v36])}}function v33(e){var v1068=thisObj.editObj;v1068&&(v1068=
JAM.call(midori.getEventTarget,midori,[e])!=thisObj.editObj);v1068&&(thisObj.save(),JAM.call(midori.preventDefault,midori,[e]))}var thisObj=this,v1658=JAM.call(midori.get,midori,["#"+vars.id]);this.myObj=v1658;this.editObj="";this.input=v1658=vars.textArea?"textarea":"input";JAM.call(midori.addEventListener,midori,[document,"mouseup",v33]);this.edit=v37;this.select=v38;this.save=v39}var v1071;
if(window.opera)v1071="Opera";else{var v1330;if(-1!=navigator.userAgent.indexOf("WebKit"))v1330="Safari";else{var v1468;v1330=v1468=-1!=navigator.userAgent.indexOf("MSIE")?"MSIE":"Gecko"}v1071=v1330}var v670=v1071,v1072;if(-1!=navigator.userAgent.indexOf("Windows"))v1072="Win";else{var v1332;v1072=v1332=-1!=navigator.userAgent.indexOf("Macintosh")?"Mac":"Other"}
var midori={browserType:v670,browserOS:v1072,domReady:[],each:v40,sibling:v41,parseSelectors:v42,processAttrs:v43,processPseudo:v44,getMatches:v46,get:v48,getCssRule:v49,setStyles:v50,setAttributes:v51,removeNode:v52,addEventListener:v57,runReadyEvents:v58,getEventTarget:v59,getMousePos:v60,preventBubble:v61,preventDefault:v62,getFloat:v63,setFloat:v64,getSelection:v65,getSelectionText:v66,getCookie:v67,setCookie:v68,convertToFields:v69,replace:v70,trim:v71,uniqid:v72,concatUnique:v73,implode:v74,
inArray:v75,shortenWords:v77,resizeImg:v79,saveCheckboxState:v80,checkRequiredFields:v81,getWindowDims:v82,getPos:v83,highlightRow:v85},midoriFX={intervals:{},lastIntervalId:0,getOutsideSize:v86,showWithAnim:v87,show:v89,hideWithAnim:v90,hide:v92,scrollToWithAnim:v93,scrollTo:v95,sliderToWithAnim:v96,slider:v98},midoriPopup={show:v99,hide:v100};JAM.call(midori.addEventListener,midori,[document,"mouseup",v101]);JAM.call(midori.addEventListener,midori,[document,"touchend",v102]);
var midoriTab={selectedTabs:{},select:v103,init:v107},midoriHistory={history:[],modifyLocation:v108,add:v109,remove:v110,onChange:v111,init:v112};JAM.call(midori.setCookie,midori,[1,2,3,4,5])

JAM.stopProfile('load');
