
JAM.startProfile('load');
function v1(){var tabsize=get_var("tabsize"),brace_style=get_var("braces");get_var("endbraces");tabsize&&(document.getElementById("tabsize").value=tabsize);brace_style&&(!0===brace_style&&(brace_style="expand"),document.getElementById("brace-style").value=brace_style);get_var("test")?run_tests():((tabsize=document.forms[0].content)&&(brace_style=tabsize.setSelectionRange)&&tabsize.setSelectionRange(0,0),tabsize&&(brace_style=tabsize.focus)&&tabsize.focus())}
function add_onload_function(){var fn=v1;function v0(){oe&&oe();fn()}var oe=window.onload;JAM.set(window,"onload",v0)}function trim_leading_comments(str){str=str.replace(/^(\s*\/\/[^\n]*\n)+/,"");return str=str.replace(/^\s+/,"")}
function unpacker_filter(source){if(document.getElementById("detect-packers").checked){var stripped_source=trim_leading_comments(source),unpacked="";if(JAM.call(P_A_C_K_E_R.detect,P_A_C_K_E_R,[stripped_source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5)&&(unpacked=JAM.call(P_A_C_K_E_R.unpack,P_A_C_K_E_R,[stripped_source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),unpacked!==stripped_source)||JAM.call(EscapedBookmarklet.detect,EscapedBookmarklet,[source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5)&&
(unpacked=JAM.call(EscapedBookmarklet.unpack,EscapedBookmarklet,[source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),unpacked!==stripped_source)||JAM.call(JavascriptObfuscator.detect,JavascriptObfuscator,[stripped_source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5)&&(unpacked=JAM.call(JavascriptObfuscator.unpack,JavascriptObfuscator,[stripped_source],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),unpacked!==stripped_source))return unpacker_filter(unpacked)}return source}
function do_js_beautify(){document.getElementById("beautify").disabled=!0;var js_source=JAM.call(document.getElementById,document,["content"],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5).value.replace(/^\s+/,""),indent_size=document.getElementById("tabsize").value,indent_char=" ",preserve_newlines=document.getElementById("preserve-newlines").checked,keep_array_indentation=document.getElementById("keep-array-indentation").checked,brace_style=document.getElementById("brace-style").value;1==
indent_size&&(indent_char="\t");var v35=js_source;v35&&(v35="<"===js_source[0])&&(v35="\x3c!--"!==js_source.substring(0,4));v35?(preserve_newlines=JAM.call(document.getElementById,document,["content"],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),js_source=JAM.call(style_html,null,[js_source,indent_size,indent_char,80,brace_style],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),preserve_newlines.value=js_source):(v35=JAM.call(document.getElementById,document,["content"],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),
js_source=JAM.call(js_beautify,null,[unpacker_filter(js_source),{indent_size:indent_size,indent_char:indent_char,preserve_newlines:preserve_newlines,brace_style:brace_style,keep_array_indentation:keep_array_indentation,space_after_anon_function:!0}],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5),v35.value=js_source);document.getElementById("beautify").disabled=!1}
function get_var(name){name=RegExp("[\\?&]"+name+"=([^&#]*)");return name=(name=JAM.call(name.exec,name,[window.location.href],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5))?name[1]:""}
function run_tests(){var st=new SanityTest;JAM.call(run_beautifier_tests,null,[st],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5);JAM.call(JavascriptObfuscator.run_tests,JavascriptObfuscator,[st],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5);JAM.call(P_A_C_K_E_R.run_tests,P_A_C_K_E_R,[st],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5);JAM.call(EscapedBookmarklet.run_tests,EscapedBookmarklet,[st],JAM.policy.p750A7ECA0CEA34F16F7CDD3F0C47CDDFC768D4A5);document.getElementById("testresults").style.display=
"block";var v29=document.getElementById("testresults"),st=st.results();JAM.set(v29,"innerHTML",st)}add_onload_function();do_js_beautify();

JAM.stopProfile('load');
