
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" ";document.forms[0].elements[4].value=" "}function v3(){try{JAM.startProfile('compute');multiRevTrans();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){var v8=document.main_form.main_submit;JAM.call(v8.focus,v8,[],JAM.policy.p9)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p9)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v12=i<arrayOfTitles.length;v12;){v12=arrayOfTitles[i];v12=-1==JAM.call(v12.search,v12,[/\S/],JAM.policy.p9);v12||(v12=arrayOfSequences[i],(v12=-1==JAM.call(v12.search,v12,[/\S/],JAM.policy.p9))||(v12=arrayOfSequences[i].length!=lengthOfAlign));if(v12)return alert("There is a problem with the alignment format."),
!1;i+=1;v12=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v458=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p9);v458||(v458=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p9),v458||(v458=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p9),v458||(v458=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p9))||(v458=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p9))));return v458?(alert("The codon table has been entered incorrectly."),!1):
!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p9)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v17=z<arrayOfPatterns.length;v17;){v17=arrayOfPatterns[z];if(-1==JAM.call(v17.search,v17,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v17=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v17=0,v26=v17<arrayOfPatterns.length;v26;){var v26=z,v21=v17,v958=arrayOfPatterns[v17],v958=JAM.call(v958.match,v958,[/\/.+\//],JAM.policy.p9)+"gi",v958=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v958+" }"):JAM.call(eval,null,[v958]);v26[v21]=v958;v26=codon;v21=v17;v958=arrayOfPatterns[v17];v958=JAM.call(v958.match,v958,[/=[a-zA-Z\*]/],JAM.policy.p9);v958=JAM.call(v958.toString,
v958,[],JAM.policy.p9);v26[v21]=v958;v26=codon;v21=v17;v958=codon[v17];v958=JAM.call(v958.replace,v958,[/=/g,""],JAM.policy.p9);v26[v21]=v958;v17+=1;v26=v17<arrayOfPatterns.length}arrayOfPatterns=0;for(v17=arrayOfPatterns<=testSequence.length-3;v17;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p9);v17=0;for(v26=v17<z.length;v26;){if(-1!=JAM.call(codon.search,codon,[z[v17]],JAM.policy.p9)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v17+=1;v26=v17<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v17=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v35=z<arrayOfPatterns.length;v35;){v35=arrayOfPatterns[z];if(-1!=JAM.call(v35.search,v35,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p9))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v35=z<arrayOfPatterns.length}z=0;for(v35=z<arrayOfPatterns.length;v35;){for(var v35=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v38=j<arrayOfPatterns.length;v38;){v38=arrayOfPatterns[j];if(-1!=JAM.call(v38.search,v38,[v35],JAM.policy.p9))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v38=j<arrayOfPatterns.length}z+=1;v35=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v42=z<arrayOfPatterns.length;v42;){v42=arrayOfPatterns[z];if(-1==JAM.call(v42.search,v42,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v42=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v959=getSequenceFromFasta(text);return JAM.call(v959.replace,v959,[/[^A-Za-z]/g,""],JAM.policy.p9).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/2/g,"R"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/M/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/B/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p9);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p9)}
function closeForm(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</form>"],JAM.policy.p9);return!0}function closePre(){var v48=outputWindow.document;JAM.call(v48.write,v48,["</div>"],JAM.policy.p9);v48=outputWindow.document;JAM.call(v48.write,v48,["</pre>\n"],JAM.policy.p9)}function closeTextArea(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</textarea>"],JAM.policy.p9);return!0}
function closeWindow(){var v51=outputWindow.document;JAM.call(v51.write,v51,["</body>\n</html>\n"],JAM.policy.p9);outputWindow.status="Done.";v51=outputWindow.document;JAM.call(v51.close,v51,[],JAM.policy.p9)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p9);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p9)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v55=i<alignArray.length;v55;){v55=alignArray[i];if(-1==JAM.call(v55.search,v55,[/[^\s]+\s/],JAM.policy.p9))return alert("There is a problem with the alignment format."),!1;i+=1;v55=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p9)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p9);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p9)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9))for(var v57=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);v57;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p9),v57=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v75=j<arrayOfPatterns.length;v75;){var v75=geneticCodeMatchExp,v74=j,v960=arrayOfPatterns[j],v960=JAM.call(v960.match,v960,[/\/.+\//],JAM.policy.p9)+"gi",v960=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v960+" }"):JAM.call(eval,null,[v960]);v75[v74]=v960;j+=1;v75=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v81=j<arrayOfPatterns.length;v81;){var v81=geneticCodeMatchResult,v78=j,v814=arrayOfPatterns[j],v814=JAM.call(v814.match,v814,[/=[a-zA-Z\*]/],JAM.policy.p9),v814=JAM.call(v814.toString,v814,[],JAM.policy.p9);v81[v78]=v814;v81=geneticCodeMatchResult;v78=j;v814=geneticCodeMatchResult[j];v814=JAM.call(v814.replace,v814,[/=/g,""],JAM.policy.p9);v81[v78]=v814;j+=1;v81=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p9),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p9),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p9));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p9);v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p9),v546||(v546=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p9))||(v546=
-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p9))))))))));return v546?!1:!0}function openForm(){var v107=outputWindow.document;JAM.call(v107.write,v107,['<form action="">\n'],JAM.policy.p9);return!0}function openPre(){var v108=outputWindow.document;JAM.call(v108.write,v108,["<pre>"],JAM.policy.p9);v108=outputWindow.document;JAM.call(v108.write,v108,['<div class="pre">'],JAM.policy.p9)}
function openTextArea(){var v110=outputWindow.document;JAM.call(v110.write,v110,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p9);return!0}function openWindow(){var title="Multi Rev Trans";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v111=outputWindow.document;JAM.call(v111.write,v111,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p9)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v119=outputWindow.document;JAM.call(v119.write,v119,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p9)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p9)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p9)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p9)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p9)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p9)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p9)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p9)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p9)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p9),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p9),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p10));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p9);for(var j=theNumber.length,v128=j<lengthOfColumn;v128;)tempString+=" ",j+=1,v128=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p9);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p9))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p9);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p9)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p9)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v561=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v561||(v561=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v561||(v561=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v561=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v561?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p9)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p9)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v566=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v566||(v566=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v566||(v566=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v566=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v566?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v567=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v567||(v567=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v567||(v567=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v567=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v567?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v569=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v569||(v569=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v569||(v569=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v569=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v569?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v156=startBase<stopBase;v156;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v156=1,v153=v156<=basePerLine/groupSize;v153;){for(v153=k<groupSize;v153;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v153=k<groupSize;startBase+=groupSize;k=0;lineOfText+=
sepChar;v156+=1;v153=v156<=basePerLine/groupSize}v156=outputWindow.document;JAM.call(v156.write,v156,[lineOfText+"\n"],JAM.policy.p9);lineOfText="";v156=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v574=0>adjustment;v574&&(v574=0<=adjusted);v574&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v166=j<=basePerLine/groupSize;v166;){for(v166=k<groupSize;v166&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v166=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v166=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v199=j<=basePerLine/groupSize;v199;){for(v199=k<groupSize;v199&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v199=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v199=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p9)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p9));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v591=sequence.length<=firstIndexToMutate;v591||(v591=0>lastIndexToMutate)||(v591=lastIndexToMutate<=firstIndexToMutate);v591&&(numMut=0);v591=0;for(randNum=v591<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*randNum],JAM.policy.p9);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p9);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p9)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p9)}v591+=1;randNum=v591<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p9);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p9),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p9);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p9)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p9);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p9)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p9);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p9);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p9));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v610=matchPosition>=lowerLimit;v610&&(v610=matchPosition<upperLimit);v610&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p9)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p9));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p9);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p9);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p9)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p9);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v254=outputWindow.document;JAM.call(v254.write,v254,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);v254=outputWindow.document;JAM.call(v254.write,v254,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p9);for(var v254=0,v265=v254<arrayOfItems.length;v265;){var v265=0,v619=arrayOfItems[v254],v619=
JAM.call(v619.match,v619,[/\/[^\/]+\//],JAM.policy.p9)+"gi",v619=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v619+" }"):JAM.call(eval,null,[v619]);-1!=JAM.call(sequence.search,sequence,[v619],JAM.policy.p9)&&(v265=JAM.call(sequence.match,sequence,[v619],JAM.policy.p9).length);var v619=0,v858=originalLength+1,v1072=arrayOfItems[v254];0<v858-parseFloat(JAM.call(v1072.match,v1072,[/\d+/],JAM.policy.p9))&&(v619=100*v265,v858=originalLength+1,v1072=arrayOfItems[v254],v619/=v858-parseFloat(JAM.call(v1072.match,
v1072,[/\d+/],JAM.policy.p9)));v858=outputWindow.document;v1072=arrayOfItems[v254];v1072=JAM.call(v1072.match,v1072,[/\([^\(]+\)\b/],JAM.policy.p9);v1072=JAM.call(v1072.toString,v1072,[],JAM.policy.p9);JAM.call(v858.write,v858,["<tr><td>"+JAM.call(v1072.replace,v1072,[/\(|\)/g,""],JAM.policy.p9)+"</td><td>"+v265+"</td><td>"+JAM.call(v619.toFixed,v619,[2],JAM.policy.p9)+"</td></tr>\n"],JAM.policy.p9);v254+=1;v265=v254<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,
originalLength,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*tempChar],JAM.policy.p9),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p9),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p9),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p9),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p9),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p9);return!0}
function multiRevTrans(){var theDocument=document,maxInput=2E4,alignArray=[],titleArray=[],sequenceArray=[];if(!1!=testScript()&&(alignArray=!1==checkFormElement(theDocument.forms[0].elements[0]),alignArray||((maxInput=!1==checkTextLength(theDocument.forms[0].elements[0].value,maxInput))||(maxInput=!1==checkCodonTable(theDocument.forms[0].elements[4].value)),alignArray=maxInput),!alignArray&&(theAlignment="X"+theDocument.forms[0].elements[0].value,alignArray=JAM.call(theAlignment.split,theAlignment,
[/[>%#]/],JAM.policy.p9),!1!=earlyCheckAlign(alignArray)))){for(var maxInput=1,v294=maxInput<alignArray.length;v294;){var v294=titleArray,v281=maxInput-1,v635=alignArray[maxInput],v635=JAM.call(v635.match,v635,[/[^\f\n\r]+[\f\n\r]/],JAM.policy.p9);v294[v281]=v635;v294=titleArray;v281=maxInput-1;v635=titleArray[maxInput-1];v635=filterFastaTitle(JAM.call(v635.toString,v635,[],JAM.policy.p9));v635=JAM.call(v635.replace,v635,[/[\f\n\r]/g,""],JAM.policy.p9);v294[v281]=v635;v294=titleArray;v281=maxInput-
1;v635=titleArray[maxInput-1];v635=JAM.call(v635.substring,v635,[0,20],JAM.policy.p9);v294[v281]=v635;1==maxInput?longestTitle=titleArray[maxInput-1].length:titleArray[maxInput-1].length>longestTitle&&(longestTitle=titleArray[maxInput-1].length);v294=sequenceArray;v281=maxInput-1;v635=alignArray[maxInput];v635=JAM.call(v635.replace,v635,[/[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9);v294[v281]=v635;v294=sequenceArray;v281=maxInput-1;v635=filterAlignSeq(sequenceArray[maxInput-1]);v294[v281]=v635;maxInput+=
1;v294=maxInput<alignArray.length}theDocument=makeCodonTable(theDocument.forms[0].elements[4].value);if(!1!=theDocument){openWindow();maxInput=0;for(alignArray=maxInput<titleArray.length;alignArray;)alignArray=outputWindow.document,JAM.call(alignArray.write,alignArray,[getInfoFromTitleAndSequence(titleArray[maxInput],sequenceArray[maxInput])],JAM.policy.p9),maxInput<titleArray.length-1&&(alignArray=outputWindow.document,JAM.call(alignArray.write,alignArray,['<div class="info">Combined with:</div>\n'],
JAM.policy.p9)),maxInput+=1,alignArray=maxInput<titleArray.length;openPre();writeConsensusSeq(sequenceArray,theDocument);titleArray=outputWindow.document;JAM.call(titleArray.write,titleArray,["\n"],JAM.policy.p9);writeMultiRevTrans(sequenceArray,theDocument);closePre();closeWindow()}}}
function writeConsensusSeq(sequenceArray,codonTable){var consensusSeq=[],aminoAcid,firstG,firstA,firstT,firstC,secondG,secondA,secondT,secondC,thirdG,thirdA,thirdT,thirdC,i=0;for(firstG=i<sequenceArray[0].length;firstG;){for(var j=thirdC=thirdT=thirdA=thirdG=secondC=secondT=secondA=secondG=firstC=firstT=firstA=firstG=0,v319=j<sequenceArray.length;v319;){v319=sequenceArray[j];v319="-"==JAM.call(v319.charAt,v319,[i],JAM.policy.p9);v319||(v319=sequenceArray[j],v319="."==JAM.call(v319.charAt,v319,[i],
JAM.policy.p9));if(v319)firstG+=0.25,firstA+=0.25,firstT+=0.25,firstC+=0.25,secondG+=0.25,secondA+=0.25,secondT+=0.25,secondC+=0.25,thirdG+=0.25,thirdA+=0.25,thirdT+=0.25,thirdC+=0.25;else{try{var v319=codonTable,v1005=sequenceArray[j],v877=JAM.call(v1005.charAt,v1005,[i],JAM.policy.p9),v653=JAM.call(v877.toString,v877,[],JAM.policy.p9);aminoAcid=v319[JAM.call(v653.toLowerCase,v653,[],JAM.policy.p9)]}catch(e){consensusSeq=sequenceArray[j];alert("A codon table entry wasn't found for "+JAM.call(consensusSeq.charAt,
consensusSeq,[i],JAM.policy.p9));return}firstG+=aminoAcid.baseFreqPosOne[0];firstA+=aminoAcid.baseFreqPosOne[1];firstT+=aminoAcid.baseFreqPosOne[2];firstC+=aminoAcid.baseFreqPosOne[3];secondG+=aminoAcid.baseFreqPosTwo[0];secondA+=aminoAcid.baseFreqPosTwo[1];secondT+=aminoAcid.baseFreqPosTwo[2];secondC+=aminoAcid.baseFreqPosTwo[3];thirdG+=aminoAcid.baseFreqPosThree[0];thirdA+=aminoAcid.baseFreqPosThree[1];thirdT+=aminoAcid.baseFreqPosThree[2];thirdC+=aminoAcid.baseFreqPosThree[3]}j+=1;v319=j<sequenceArray.length}JAM.call(consensusSeq.push,
consensusSeq,[_getConsensusBase([firstG,firstA,firstT,firstC])],JAM.policy.p9);JAM.call(consensusSeq.push,consensusSeq,[_getConsensusBase([secondG,secondA,secondT,secondC])],JAM.policy.p9);JAM.call(consensusSeq.push,consensusSeq,[_getConsensusBase([thirdG,thirdA,thirdT,thirdC])],JAM.policy.p9);i+=1;firstG=i<sequenceArray[0].length}i=outputWindow.document;JAM.call(i.write,i,["&gt;reverse translation of alignment to a "+consensusSeq.length+" base sequence of consensus codons.\n"],JAM.policy.p9);i=outputWindow.document;
JAM.call(i.write,i,[addReturns(JAM.call(consensusSeq.join,consensusSeq,[""],JAM.policy.p10))],JAM.policy.p9);consensusSeq=outputWindow.document;JAM.call(consensusSeq.write,consensusSeq,["\n"],JAM.policy.p9)}
function writeMultiRevTrans(sequenceArray,codonTable){var markG="gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",markA="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",markT="TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",markC="CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",markLength=
markG.length,aminoAcid,columnSeq,firstG,firstA,firstT,firstC,secondG,secondA,secondT,secondC,thirdG,thirdA,thirdT,thirdC,i=0;for(thirdC=i<sequenceArray[0].length;thirdC;){columnSeq="";for(var j=thirdC=thirdT=thirdA=thirdG=secondC=secondT=secondA=secondG=firstC=firstT=firstA=firstG=0,v347=j<sequenceArray.length;v347;){v347=sequenceArray[j];columnSeq+=JAM.call(v347.charAt,v347,[i],JAM.policy.p9);v347=sequenceArray[j];v347="-"==JAM.call(v347.charAt,v347,[i],JAM.policy.p9);v347||(v347=sequenceArray[j],
v347="."==JAM.call(v347.charAt,v347,[i],JAM.policy.p9));if(v347)firstG+=0.25,firstA+=0.25,firstT+=0.25,firstC+=0.25,secondG+=0.25,secondA+=0.25,secondT+=0.25,secondC+=0.25,thirdG+=0.25,thirdA+=0.25,thirdT+=0.25,thirdC+=0.25;else{try{var v347=codonTable,v1008=sequenceArray[j],v886=JAM.call(v1008.charAt,v1008,[i],JAM.policy.p9),v678=JAM.call(v886.toString,v886,[],JAM.policy.p9);aminoAcid=v347[JAM.call(v678.toLowerCase,v678,[],JAM.policy.p9)]}catch(e){markG=sequenceArray[j];alert("A codon table entry wasn't found for "+
JAM.call(markG.charAt,markG,[i],JAM.policy.p9));return}firstG+=aminoAcid.baseFreqPosOne[0];firstA+=aminoAcid.baseFreqPosOne[1];firstT+=aminoAcid.baseFreqPosOne[2];firstC+=aminoAcid.baseFreqPosOne[3];secondG+=aminoAcid.baseFreqPosTwo[0];secondA+=aminoAcid.baseFreqPosTwo[1];secondT+=aminoAcid.baseFreqPosTwo[2];secondC+=aminoAcid.baseFreqPosTwo[3];thirdG+=aminoAcid.baseFreqPosThree[0];thirdA+=aminoAcid.baseFreqPosThree[1];thirdT+=aminoAcid.baseFreqPosThree[2];thirdC+=aminoAcid.baseFreqPosThree[3]}j+=
1;v347=j<sequenceArray.length}firstG=JAM.call(Math.round,Math,[markLength*firstG/sequenceArray.length],JAM.policy.p9);firstA=JAM.call(Math.round,Math,[markLength*firstA/sequenceArray.length],JAM.policy.p9);firstT=JAM.call(Math.round,Math,[markLength*firstT/sequenceArray.length],JAM.policy.p9);firstC=JAM.call(Math.round,Math,[markLength*firstC/sequenceArray.length],JAM.policy.p9);secondG=JAM.call(Math.round,Math,[markLength*secondG/sequenceArray.length],JAM.policy.p9);secondA=JAM.call(Math.round,Math,
[markLength*secondA/sequenceArray.length],JAM.policy.p9);secondT=JAM.call(Math.round,Math,[markLength*secondT/sequenceArray.length],JAM.policy.p9);secondC=JAM.call(Math.round,Math,[markLength*secondC/sequenceArray.length],JAM.policy.p9);thirdG=JAM.call(Math.round,Math,[markLength*thirdG/sequenceArray.length],JAM.policy.p9);thirdA=JAM.call(Math.round,Math,[markLength*thirdA/sequenceArray.length],JAM.policy.p9);thirdT=JAM.call(Math.round,Math,[markLength*thirdT/sequenceArray.length],JAM.policy.p9);
thirdC=JAM.call(Math.round,Math,[markLength*thirdC/sequenceArray.length],JAM.policy.p9);j=outputWindow.document;JAM.call(j.write,j,["<b>"+(i+1)+"_"+columnSeq+"_first</b>\n"],JAM.policy.p9);j=outputWindow.document;v347="g"+JAM.call(markG.substring,markG,[0,firstG],JAM.policy.p9)+" ";firstG/=markLength;firstG=v347+JAM.call(firstG.toFixed,firstG,[2],JAM.policy.p9)+"\na"+JAM.call(markA.substring,markA,[0,firstA],JAM.policy.p9)+" ";firstA/=markLength;firstA=firstG+JAM.call(firstA.toFixed,firstA,[2],JAM.policy.p9)+
"\nT"+JAM.call(markT.substring,markT,[0,firstT],JAM.policy.p9)+" ";firstT/=markLength;firstT=firstA+JAM.call(firstT.toFixed,firstT,[2],JAM.policy.p9)+"\nC"+JAM.call(markC.substring,markC,[0,firstC],JAM.policy.p9)+" ";firstC/=markLength;JAM.call(j.write,j,[firstT+JAM.call(firstC.toFixed,firstC,[2],JAM.policy.p9)+"\n"],JAM.policy.p9);firstC=outputWindow.document;JAM.call(firstC.write,firstC,["<b>"+(i+1)+"_"+columnSeq+"_second</b>\n"],JAM.policy.p9);firstC=outputWindow.document;firstT="g"+JAM.call(markG.substring,
markG,[0,secondG],JAM.policy.p9)+" ";secondG/=markLength;secondG=firstT+JAM.call(secondG.toFixed,secondG,[2],JAM.policy.p9)+"\na"+JAM.call(markA.substring,markA,[0,secondA],JAM.policy.p9)+" ";secondA/=markLength;secondA=secondG+JAM.call(secondA.toFixed,secondA,[2],JAM.policy.p9)+"\nT"+JAM.call(markT.substring,markT,[0,secondT],JAM.policy.p9)+" ";secondT/=markLength;secondT=secondA+JAM.call(secondT.toFixed,secondT,[2],JAM.policy.p9)+"\nC"+JAM.call(markC.substring,markC,[0,secondC],JAM.policy.p9)+" ";
secondC/=markLength;JAM.call(firstC.write,firstC,[secondT+JAM.call(secondC.toFixed,secondC,[2],JAM.policy.p9)+"\n"],JAM.policy.p9);secondC=outputWindow.document;JAM.call(secondC.write,secondC,["<b>"+(i+1)+"_"+columnSeq+"_third</b>\n"],JAM.policy.p9);columnSeq=outputWindow.document;secondC="g"+JAM.call(markG.substring,markG,[0,thirdG],JAM.policy.p9)+" ";thirdG/=markLength;thirdG=secondC+JAM.call(thirdG.toFixed,thirdG,[2],JAM.policy.p9)+"\na"+JAM.call(markA.substring,markA,[0,thirdA],JAM.policy.p9)+
" ";thirdA/=markLength;thirdA=thirdG+JAM.call(thirdA.toFixed,thirdA,[2],JAM.policy.p9)+"\nT"+JAM.call(markT.substring,markT,[0,thirdT],JAM.policy.p9)+" ";thirdT/=markLength;thirdT=thirdA+JAM.call(thirdT.toFixed,thirdT,[2],JAM.policy.p9)+"\nC"+JAM.call(markC.substring,markC,[0,thirdC],JAM.policy.p9)+" ";thirdC/=markLength;JAM.call(columnSeq.write,columnSeq,[thirdT+JAM.call(thirdC.toFixed,thirdC,[2],JAM.policy.p9)+"\n"],JAM.policy.p9);thirdC=outputWindow.document;JAM.call(thirdC.write,thirdC,["\n"],
JAM.policy.p9);i+=1;thirdC=i<sequenceArray[0].length}}
function makeCodonTable(gcgTable){gcgTable=JAM.call(gcgTable.replace,gcgTable,[/[^\.]*\.\./,""],JAM.policy.p9);var tableArray=JAM.call(gcgTable.split,gcgTable,[/[\f\n\r]/],JAM.policy.p9),re=/(\w+)\s+(\w+)\s+(\S+)\s+(\S+)\s+(\S+)/g,matchArray;gcgTable=new CodonTable;var i=0;for(matchArray=i<tableArray.length;matchArray;){for(var v377=matchArray=JAM.call(re.exec,re,[tableArray[i]],JAM.policy.p9);v377;){try{var v377=gcgTable,v898=matchArray[1],v374=v377[JAM.call(v898.toLowerCase,v898,[],JAM.policy.p9)];
JAM.call(v374.addCodon,v374,[new Codon(matchArray[2],parseFloat(matchArray[3]),parseFloat(matchArray[4]),parseFloat(matchArray[5]))],JAM.policy.p9)}catch(e){return alert("There is a problem with a line of the codon table: "+matchArray[1]+" "+matchArray[2]+" "+matchArray[3]+" "+matchArray[4]+" "+matchArray[4]),!1}v377=matchArray=JAM.call(re.exec,re,[tableArray[i]],JAM.policy.p9)}i+=1;matchArray=i<tableArray.length}v898=gcgTable.a;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.c;
JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.d;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.e;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.f;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.g;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.h;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.i;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.k;JAM.call(v898.determineBaseFreq,
v898,[],JAM.policy.p9);v898=gcgTable.l;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.m;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.n;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.p;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.q;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.r;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.s;JAM.call(v898.determineBaseFreq,v898,
[],JAM.policy.p9);v898=gcgTable.t;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.v;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.w;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.y;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);v898=gcgTable.z;JAM.call(v898.determineBaseFreq,v898,[],JAM.policy.p9);return gcgTable}
function CodonTable(){var v1282=new AminoAcid;this.a=v1282;this.c=v1282=new AminoAcid;this.d=v1282=new AminoAcid;this.e=v1282=new AminoAcid;this.f=v1282=new AminoAcid;this.g=v1282=new AminoAcid;this.h=v1282=new AminoAcid;this.i=v1282=new AminoAcid;this.k=v1282=new AminoAcid;this.l=v1282=new AminoAcid;this.m=v1282=new AminoAcid;this.n=v1282=new AminoAcid;this.p=v1282=new AminoAcid;this.q=v1282=new AminoAcid;this.r=v1282=new AminoAcid;this.s=v1282=new AminoAcid;this.t=v1282=new AminoAcid;this.v=v1282=
new AminoAcid;this.w=v1282=new AminoAcid;this.y=v1282=new AminoAcid;this.z=v1282=new AminoAcid;this.ala=this.a;this.cys=this.c;this.asp=this.d;this.glu=this.e;this.phe=this.f;this.gly=this.g;this.his=this.h;this.ile=this.i;this.lys=this.k;this.leu=this.l;this.met=this.m;this.asn=this.n;this.pro=this.p;this.gln=this.q;this.arg=this.r;this.ser=this.s;this.thr=this.t;this.val=this.v;this.trp=this.w;this.tyr=this.y;this.end=this.z}
function addCodon(codon){var v400=this.codons;JAM.call(v400.push,v400,[codon],JAM.policy.p9)}
function determineBaseFreq(){JAM.call(this.fixFraction,this,[],JAM.policy.p9);for(var i=0,v425=i<this.codons.length;v425;)v425=this.codons[i].sequence,"g"==JAM.call(v425.charAt,v425,[0],JAM.policy.p9)?this.baseFreqPosOne[0]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"a"==JAM.call(v425.charAt,v425,[0],JAM.policy.p9)?this.baseFreqPosOne[1]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"t"==JAM.call(v425.charAt,v425,[0],JAM.policy.p9)?this.baseFreqPosOne[2]+=this.codons[i].fraction:
(v425=this.codons[i].sequence,"c"==JAM.call(v425.charAt,v425,[0],JAM.policy.p9)&&(this.baseFreqPosOne[3]+=this.codons[i].fraction)))),v425=this.codons[i].sequence,"g"==JAM.call(v425.charAt,v425,[1],JAM.policy.p9)?this.baseFreqPosTwo[0]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"a"==JAM.call(v425.charAt,v425,[1],JAM.policy.p9)?this.baseFreqPosTwo[1]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"t"==JAM.call(v425.charAt,v425,[1],JAM.policy.p9)?this.baseFreqPosTwo[2]+=this.codons[i].fraction:
(v425=this.codons[i].sequence,"c"==JAM.call(v425.charAt,v425,[1],JAM.policy.p9)&&(this.baseFreqPosTwo[3]+=this.codons[i].fraction)))),v425=this.codons[i].sequence,"g"==JAM.call(v425.charAt,v425,[2],JAM.policy.p9)?this.baseFreqPosThree[0]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"a"==JAM.call(v425.charAt,v425,[2],JAM.policy.p9)?this.baseFreqPosThree[1]+=this.codons[i].fraction:(v425=this.codons[i].sequence,"t"==JAM.call(v425.charAt,v425,[2],JAM.policy.p9)?this.baseFreqPosThree[2]+=this.codons[i].fraction:
(v425=this.codons[i].sequence,"c"==JAM.call(v425.charAt,v425,[2],JAM.policy.p9)&&(this.baseFreqPosThree[3]+=this.codons[i].fraction)))),i+=1,v425=i<this.codons.length;return!0}function fixFraction(){for(var perThouTotal=0,i=0,v427=i<this.codons.length;v427;)perThouTotal+=this.codons[i].perThou,i+=1,v427=i<this.codons.length;if(0==perThouTotal)return!1;i=0;for(v427=i<this.codons.length;v427;)this.codons[i].fraction=this.codons[i].perThou/perThouTotal,i+=1,v427=i<this.codons.length;return!0}
function AminoAcid(){var v1303=[];this.codons=v1303;this.baseFreqPosOne=v1303=[0,0,0,0];this.baseFreqPosTwo=v1303=[0,0,0,0];this.baseFreqPosThree=v1303=[0,0,0,0]}function Codon(sequence,number,perThou,fraction){this.sequence=sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);this.number=number;this.perThou=perThou;this.fraction=fraction}
function _getConsensusBase(baseFreq){var g,a,t,c;0<baseFreq[0]&&(g=!0);0<baseFreq[1]&&(a=!0);0<baseFreq[2]&&(t=!0);0<baseFreq[3]&&(c=!0);(baseFreq=!g)&&(baseFreq=!a)&&(baseFreq=!c)&&(baseFreq=!t);if(baseFreq)return"n";(baseFreq=g)&&(baseFreq=a)&&(baseFreq=c&&t);if(baseFreq)return"n";(baseFreq=a)&&(baseFreq=c&&t);if(baseFreq)return"h";(baseFreq=a)&&(baseFreq=g&&t);if(baseFreq)return"d";(baseFreq=c)&&(baseFreq=g&&t);return baseFreq?"b":a&&c?"m":g&&t?"k":a&&t?"w":g&&c?"s":c&&t?"y":a&&g?"r":t?"t":g?"g":
c?"c":a?"a":"?"}new AminoAcid;AminoAcid.prototype.addCodon=addCodon;AminoAcid.prototype.determineBaseFreq=determineBaseFreq;AminoAcid.prototype.fixFraction=fixFraction;JAM.set(document,"onload",v2);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p9),"onclick",v3);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p9),"onclick",v4);

JAM.stopProfile('load');
