
JAM.startProfile('load');
function v4(){function v3(url){JAM.call(initialize,null,[url],JAM.policy.p3)}function v2(features,opt_callback){var urlToLoad,v72=!features;v72||(v72=0==features.length);if(v72)JAM.call(warn,null,[["Cannot load empty features."]],JAM.policy.p3);else{var v72=features,set=JAM.call(toSet,null,[loadedFeatures],JAM.policy.p3),isSubset=!0,i=0,v73=isSubset;for(v73&&(v73=i<v72.length);v73;)isSubset&&(isSubset=set[v72[i]]),i+=1,(v73=isSubset)&&(v73=i<v72.length);if(v72=isSubset)JAM.call(warn,null,[["Cannot load loaded features [",
JAM.call(features.join,features,[","],JAM.policy.p2),"]."]],JAM.policy.p3);else if((v72="s"===type)||(v72="i"===type),v72)JSCompiler_inline_label_processUrlFromMap_25:v72=features,(urlToLoad=descriptors[JAM.call(toKey,null,[v72,loadedFeatures],JAM.policy.p3)])?urlToLoad=host+"/"+urlToLoad+".js":(JAM.call(warn,null,[["Cannot find features [",JAM.call(v72.join,v72,[","],JAM.policy.p2),"], except [",JAM.call(loadedFeatures.join,loadedFeatures,[","],JAM.policy.p2),"]."]],JAM.policy.p3),urlToLoad=void 0);
else"d"===type?(v72=host+"/"+JAM.call(toKey,null,[features,loadedFeatures],JAM.policy.p3),v72+=".js?container="+container+"&c=2",repository&&(v72+="&r="+repository),urlToLoad=v72):((v72="r"===type)||(v72="f"===type),v72?(v72=host+"/"+repository+"/",urlToLoad=loadedFeatures,set=JAM.call(normalize,null,[features],JAM.policy.p3),set=JAM.call(set.join,set,["__"],JAM.policy.p2),(i=urlToLoad)&&(i=0<urlToLoad.length),i&&(urlToLoad=JAM.call(normalize,null,[urlToLoad],JAM.policy.p3),set+="--"+JAM.call(urlToLoad.join,
urlToLoad,["__"],JAM.policy.p2)),urlToLoad=set,urlToLoad=v72+urlToLoad+".js"):JAM.call(warn,null,[["Cannot respond for features [",JAM.call(features.join,features,[","],JAM.policy.p2),"]."]],JAM.policy.p3))}v72=features;set=opt_callback;if(urlToLoad){(isSubset=(i=window.___jsl)&&set)&&(isSubset=1);if(isSubset){if(i.c)throw"Cannot continue until a pending callback completes.";i.c=set;i.o=1}JSCompiler_inline_label_canLoadUrl_58:if(set=urlToLoad,(i="s"===type)||(i="r"===type),i)set=JAM.call(set.match,
set,[VALID_SCS_URL_REGEX],JAM.policy.p3);else{if(isSubset=i=window.___jsl)(isSubset="dev"==i.m)||(isSubset="google"==i.m);(i=isSubset)&&(i=JAM.call(set.match,set,[VALID_GOOGLE_URL_REGEX],JAM.policy.p3));set=i}if(!set)throw"Cannot load url "+urlToLoad+".";JAM.call(shouldLoadSync,null,[],JAM.policy.p3)?JAM.call(document.write,document,['<script src="'+urlToLoad+'">\x3c/script>'],JAM.policy.p3):(set=JAM.call(document.createElement,document,["script"],JAM.policy.p3),JAM.call(set.setAttribute,set,["src",
urlToLoad],JAM.policy.p2),urlToLoad=JAM.call(document.getElementsByTagName,document,["head"],JAM.policy.p2)[0],JAM.call(urlToLoad.appendChild,urlToLoad,[set],JAM.policy.p3));loadedFeatures=JAM.call(normalize,null,[JAM.call(loadedFeatures.concat,loadedFeatures,[v72],JAM.policy.p3)],JAM.policy.p3)}else set&&JAM.call(set,null,[],JAM.policy.p3)}function toKey(reqFeatures,opt_loadFeatures){var v35=JAM.call(normalize,null,[reqFeatures],JAM.policy.p3),v35=JAM.call(v35.join,v35,[":"],JAM.policy.p2),v91=opt_loadFeatures;
v91&&(v91=0<opt_loadFeatures.length);v91&&(v91=JAM.call(normalize,null,[opt_loadFeatures],JAM.policy.p3),v35+="!"+JAM.call(v91.join,v91,[":"],JAM.policy.p2));return v35}function toSet(array){for(var result={},i=0,v38=i<array.length;v38;)JAM.set(result,array[i],!0),i+=1,v38=i<array.length;return result}function normalize(features){var result=[],s;for(s in JAM.call(toSet,null,[features],JAM.policy.p3))JAM.call(result.push,result,[s],JAM.policy.p3);return JAM.call(result.sort,result,[],JAM.policy.p3)}
function shouldLoadSync(){if(!0===window.___gapisync)return!0;for(var metas=JAM.call(document.getElementsByTagName,document,["meta"],JAM.policy.p2),i=0,v42=i<metas.length;v42;){var v42=metas[i],v97="generator"==JAM.call(v42.getAttribute,v42,["name"],JAM.policy.p2);v97||(v97="blogger"==JAM.call(v42.getAttribute,v42,["content"],JAM.policy.p2));if(v97)return!0;i+=1;v42=i<metas.length}return!1}function warn(values){console&&JAM.call(console.warn,console,[JAM.call(values.join,values,[""],JAM.policy.p2)],
JAM.policy.p3)}function initDescriptors(values){for(var i=0,v46=i<values.length;v46;){var v46=values[i],v46=JAM.call(v46.split,v46,["@"],JAM.policy.p2),JSCompiler_temp_const=descriptors,JSCompiler_inline_result;JSCompiler_inline_result=v46[0];var featureParts=JAM.call(JSCompiler_inline_result.split,JSCompiler_inline_result,["!"],JAM.policy.p2);JSCompiler_inline_result=featureParts[0];JSCompiler_inline_result=JAM.call(normalize,null,[JAM.call(JSCompiler_inline_result.split,JSCompiler_inline_result,
[":"],JAM.policy.p2)],JAM.policy.p3);var v45=featureParts[1];v45&&(featureParts=featureParts[1],v45=JAM.call(normalize,null,[JAM.call(featureParts.split,featureParts,[":"],JAM.policy.p2)],JAM.policy.p3));featureParts=v45;JSCompiler_inline_result=JAM.call(toKey,null,[JSCompiler_inline_result,featureParts],JAM.policy.p3);JAM.set(JSCompiler_temp_const,JSCompiler_inline_result,v46[1]);i+=1;v46=i<values.length}}function getLastHint(pattern){var v47=pattern=JAM.call(parentUrl.match,parentUrl,[pattern],
JAM.policy.p3);v47&&(v47=pattern[pattern.length-1]);return v47}function initialize(url){host=type=0;descriptors={};loadedFeatures=[];var v48=window.console;!v48&&(v48=window.opera)&&(v48=window.opera.postError);console=v48;parentUrl=url;(url=JAM.call(getLastHint,null,[QUERY_PATTERN],JAM.policy.p3))||(url=JAM.call(getLastHint,null,[FRAGMENT_PATTERN],JAM.policy.p3));url||((v48=url=window.___jsl)&&(v48=url.h),url=v48);if(url)if(url=JAM.call(url.split,url,[";"],JAM.policy.p2),type=url[0],"s"===type)host=
"https://ssl.gstatic.com/webclient/js",JAM.call(initDescriptors,null,[JAM.call(url.slice,url,[1],JAM.policy.p2)],JAM.policy.p3);else if("i"===type)host=url[1],JAM.call(initDescriptors,null,[JAM.call(url.slice,url,[2],JAM.policy.p2)],JAM.policy.p3);else if("d"===type)host=url[1],repository=url[2],(url=url[3])||(url="gcjs-3p"),container=url;else if("r"===type)host="https://ssl.gstatic.com/webclient/js",repository=url[1];else if(v48="f"===type)host=url[1],repository=url[2]}var QUERY_PATTERN=/\?[&|(\S*=\S*&)]*jsh=(\S*)#?/,
FRAGMENT_PATTERN=/#[&|(\S*=\S*&)]*jsh=(\S*)/,VALID_SCS_URL_REGEX=/^https:\/\/ssl.gstatic.com\/webclient\/js(\/[a-zA-Z0-9_\-]+)*\/[a-zA-Z0-9_\-\.:!]+\.js$/,VALID_GOOGLE_URL_REGEX=JAM.call(RegExp,null,["^(http:|https:)?(\\/\\/)?([a-zA-Z0-9_\\-]+\\.)*google\\.com(:[0-9]+)?(\\/[a-zA-Z0-9_\\-]+)*\\/[a-zA-Z0-9_\\-\\.:!]+\\.js(\\?[a-zA-Z0-9_\\-&=%]*)?$"],JAM.policy.p2),type,host,container,repository,descriptors,loadedFeatures,console,parentUrl;JAM.call(initialize,null,[document.location.href],JAM.policy.p3);
jsloader_load=v2;jsloader.reinitialize_=v3}function v1(){function f(n){function v0(){var v53=window.___gpq;JAM.call(v53.push,v53,[n,arguments],JAM.policy.p3)}return v0}return{go:JAM.call(f,null,["go"],JAM.policy.p2),render:JAM.call(f,null,["render"],JAM.policy.p2)}}
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone,f;f=window.___gpq;for(var v58=f=JAM.call(f.shift,f,[],JAM.policy.p3);v58;){if(v58=p[f])f=p[f],v58=window.___gpq,JAM.call(f.apply,f,[p,JAM.call(v58.shift,v58,[],JAM.policy.p3)],JAM.policy.p3);f=window.___gpq;v58=f=JAM.call(f.shift,f,[],JAM.policy.p3)}p=gadgets.config;"explicit"!==JAM.call(p.get,p,["gwidget"],JAM.policy.p2).parsetags&&(p=gapi.plusone,JAM.call(p.go,p,[],JAM.policy.p3))}
function gapi_load(features,opt_callback){JAM.call(jsloader_load,null,[JAM.call(features.split,features,[":"],JAM.policy.p2),opt_callback],JAM.policy.p3)}var v62=window.___jsl;v62||(v62={});window.___jsl=v62;var v63=window.___jsl,v118=window.___jsl.h;v118||(v118="s;plusone:googleapis.client@21550740_8d71de52/client;googleapis.proxy@21550740_8d71de52/proxy;plusone:googleapis.client:iframes-styles-bubble@21550740_8d71de52/bubble;iframes-styles-bubble!plusone:googleapis.client@21550740_8d71de52/bubble_only;plusone-unsupported@21550740_8d71de52/unsupported");
v63.h=v118;window.___gpq=[];var v64=window.gapi;v64||(v64={});window.gapi=v64;var v65=window.gapi,v120=window.gapi.plusone;v120||(v120=JAM.call(v1,null,[],JAM.policy.p3));v65.plusone=v120;var jsloader_load,goog,v66=window.___jsl;v66||(v66={});window.___jsl=v66;window.___jsl.u="https://apis.google.com/js/plusone.js";window.___jsl.f=["googleapis.client","plusone"];var v69=window.jsloader;v69||(v69={});var jsloader=v69,v70=window.gapi;v70||(v70={});var gapi=v70;JAM.call(v4,null,[],JAM.policy.p3);
JAM.call(gapi_load,null,["googleapis.client:plusone",window.__bsld],JAM.policy.p2)

JAM.stopProfile('load');
