
JAM.startProfile('load');
function v230(name){return JAM.call(AJS.A,AJS,[{href:"javascript:;",name:name}])}function v229(elm){var img=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"indicator.gif",style:"margin-right: 5px;"}]);JAM.call(AJS.setWidth,AJS,[img,16]);JAM.call(AJS.setHeight,AJS,[img,16]);this.indicator=img;img.style.textDecoration="none";try{JAM.call(AJS.insertBefore,AJS,[img,elm])}catch(e){}}function v228(elm){try{JAM.call(AJS.removeElement,AJS,[this.indicator])}catch(e){}}
function v227(name,css_class,c_fn){var btn_row=AJS.TR(),btn=AJS.TD();JAM.set(btn,"onmouseover",GoogieSpell.item_onmouseover);JAM.set(btn,"onmouseout",GoogieSpell.item_onmouseout);""!=css_class?(css_class=JAM.call(AJS.SPAN,AJS,[{"class":css_class}]),JAM.set(css_class,"innerHTML",name)):css_class=JAM.call(AJS.TN,AJS,[name]);JAM.call(btn.appendChild,btn,[css_class]);JAM.call(AJS.AEV,AJS,[btn,"click",c_fn]);JAM.call(btn_row.appendChild,btn_row,[btn]);return btn_row}
function v226(c_fn){return JAM.call(this.createButton,this,[this.lang_close,"googie_list_close",JAM.call(AJS.$b,AJS,[c_fn,this])])}function v225(e){e=JAM.call(AJS.getEventElm,AJS,[e]);var v889="googie_list_revert"!=e.className;v889&&(v889="googie_list_close"!=e.className);v889?e.className="googie_list_onout":e.parentNode.className="googie_list_onout"}
function v224(e){e=JAM.call(AJS.getEventElm,AJS,[e]);var v890="googie_list_revert"!=e.className;v890&&(v890="googie_list_close"!=e.className);v890?e.className="googie_list_onhover":e.parentNode.className="googie_list_onhover"}
function v223(fire){function fn(){this.spellCheck()}var v891=!JAM.call(AJS.isDefined,AJS,[fire]);v891||(v891=fire);v891&&JAM.call(this.setStateChanged,this,["spell_check"]);this.switch_lan_pic=fire=this.show_change_lang_pic?this.createChangeLangPic():AJS.SPAN();fire=this.createSpellDiv();this.custom_spellcheck_starter?JAM.set(fire,"onclick",this.custom_spellcheck_starter):(v891=JAM.call(AJS.$b,AJS,[fn,this]),JAM.call(AJS.AEV,AJS,[fire,"click",v891]));this.spell_span=fire;this.main_controller&&("left"==
this.change_lang_pic_placement?JAM.call(AJS.RCN,AJS,[this.spell_container,fire," ",this.switch_lan_pic]):JAM.call(AJS.RCN,AJS,[this.spell_container,this.switch_lan_pic," ",fire]))}
function v222(){function v221(e){this.resumeEditing()}JAM.call(this.setStateChanged,this,["resume_editing"]);if(this.main_controller){JAM.call(AJS.hideElement,AJS,[this.switch_lan_pic]);var dummy=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"blank.gif",style:"height: 16px; width: 1px;"}]),rsm=AJS.SPAN();JAM.set(rsm,"innerHTML",this.lang_rsm_edt);JAM.call(AJS.RCN,AJS,[this.spell_span,JAM.call(AJS.SPAN,AJS,[dummy,rsm])]);dummy=v221;dummy=JAM.call(AJS.$b,AJS,[dummy,this]);this.spell_span.addEventListener("click",
dummy,!1);this.spell_span.className="googie_resume_editing"}try{this.edit_layer.scrollTop=this.ta_scroll_top}catch(e$$0){}}
function v220(on_finish){function v219(){on_finish();this.checkSpellingState()}var no_spell_errors;no_spell_errors=on_finish?v219:this.checkSpellingState;JAM.call(this.setStateChanged,this,["no_error_found"]);if(this.main_controller){JAM.call(AJS.hideElement,AJS,[this.switch_lan_pic]);var dummy=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"blank.gif",style:"height: 16px; width: 1px;"}]),rsm=AJS.SPAN();JAM.set(rsm,"innerHTML",this.lang_no_error_found);JAM.call(AJS.RCN,AJS,[this.spell_span,JAM.call(AJS.SPAN,
AJS,[dummy,rsm])]);this.spell_span.className="googie_check_spelling_ok";this.spell_span.style.textDecoration="none";this.spell_span.style.cursor="default";JAM.call(setTimeout,null,[JAM.call(AJS.$b,AJS,[no_spell_errors,this]),1200])}}
function v218(){var chk_spell=JAM.call(AJS.SPAN,AJS,[{"class":"googie_check_spelling_link",id:"googie_check_spelling_link"}]);JAM.set(chk_spell,"innerHTML",this.lang_chck_spell);var spell_img=null;this.show_spell_img&&(spell_img=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"spellc.gif"}]));return JAM.call(AJS.SPAN,AJS,[spell_img," ",chk_spell])}
function v217(){function fn(e){e=JAM.call(AJS.getEventElm,AJS,[e]);"img"==JAM.call(AJS.nodeName,AJS,[e])&&(e=e.parentNode);"googie_lang_3d_click"==e.className?(e.className="googie_lang_3d_on",this.hideLangWindow()):(e.className="googie_lang_3d_click",JAM.call(this.showLangWindow,this,[switch_lan]))}var img=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"change_lang.gif",alt:"Change language"}]);img.googie_action_btn="1";var switch_lan=JAM.call(AJS.SPAN,AJS,[{"class":"googie_lang_3d_on",style:"padding-left: 6px;"},
img]);JAM.call(AJS.AEV,AJS,[switch_lan,"click",JAM.call(AJS.$b,AJS,[fn,this])]);return switch_lan}
function v216(elm,ofst_top,ofst_left){this.show_menu_observer&&JAM.call(this.show_menu_observer,this,[this]);JAM.call(AJS.isDefined,AJS,[ofst_top])||(ofst_top=20);JAM.call(AJS.isDefined,AJS,[ofst_left])||(ofst_left=100);this.createLangWindow();var v280=AJS.getBody();JAM.call(v280.appendChild,v280,[this.language_window]);elm=JAM.call(AJS.absolutePosition,AJS,[elm]);JAM.call(AJS.showElement,AJS,[this.language_window]);JAM.call(AJS.setTop,AJS,[this.language_window,elm.y+ofst_top]);JAM.call(AJS.setLeft,
AJS,[this.language_window,elm.x+ofst_left-this.language_window.offsetWidth]);this.highlightCurSel();this.language_window.style.visibility="visible"}
function v215(){null==GOOGIE_CUR_LANG&&(GOOGIE_CUR_LANG=GOOGIE_DEFAULT_LANG);for(var i=0,v293=i<this.lang_elms.length;v293;){v293=this.lang_elms;introspect(JAM.policy.p1)v293=v293[i];if(v293.googieId==GOOGIE_CUR_LANG){v293=this.lang_elms;introspect(JAM.policy.p1)v293=v293[i];v293.className="googie_list_selected";v293=this.lang_elms;introspect(JAM.policy.p1)this.lang_cur_elm=v293[i]}else{v293=this.lang_elms;introspect(JAM.policy.p1)v293=v293[i];v293.className="googie_list_onout"}i+=1;v293=i<this.lang_elms.length}}
function v214(){this.lang_cur_elm.className="googie_list_onout"}function v213(){try{this.language_window.style.visibility="hidden",this.switch_lan_pic.className="googie_lang_3d_on"}catch(e){}}function v212(){var v297=null!=this.language_window;v297&&(v297="visible"==this.language_window.style.visibility);return v297}function v211(lan_code){GOOGIE_CUR_LANG=lan_code;var now=new Date;now.setTime(now.getTime()+31536E6);setCookie(lan_code,now)}
function v210(){function v209(e){e=JAM.call(AJS.getEventElm,AJS,[e]);"googie_list_selected"!=e.className&&(e.className="googie_list_onout")}function v208(e){e=JAM.call(AJS.getEventElm,AJS,[e]);"googie_list_selected"!=e.className&&(e.className="googie_list_onhover")}function v207(e){e=JAM.call(AJS.getEventElm,AJS,[e]);this.deHighlightCurSel();JAM.call(this.setCurrentLanguage,this,[e.googieId]);null!=this.lang_state_observer&&this.lang_state_observer();this.highlightCurSel();this.hideLangWindow()}var v1373=
JAM.call(AJS.DIV,AJS,[{"class":"googie_window"}]);this.language_window=v1373;JAM.call(AJS.setWidth,AJS,[this.language_window,100]);this.language_window.googie_action_btn="1";v1373=JAM.call(AJS.TABLE,AJS,[{"class":"googie_list"}]);JAM.call(AJS.setWidth,AJS,[v1373,"100%"]);var list=AJS.TBODY(),v1374=[];this.lang_elms=v1374;i=0;for(v1374=i<this.langlist_codes.length;v1374;){var v1374=AJS.TR(),item=AJS.TD(),v307=this.langlist_codes;introspect(JAM.policy.p1)item.googieId=v307[i];this.lang_elms.push(item);
var v307=AJS.SPAN(),v309=this.lang_to_word,v921=this.langlist_codes;introspect(JAM.policy.p1)v921=v921[i];JAM.set(v307,"innerHTML",JAM.get(v309,v921,JAM.policy.p1));JAM.call(item.appendChild,item,[JAM.call(AJS.TN,AJS,[v307.innerHTML])]);v307=v207;JAM.call(AJS.AEV,AJS,[item,"click",JAM.call(AJS.$b,AJS,[v307,this])]);JAM.set(item,"onmouseover",v208);JAM.set(item,"onmouseout",v209);JAM.call(v1374.appendChild,v1374,[item]);JAM.call(list.appendChild,list,[v1374]);i+=1;v1374=i<this.langlist_codes.length}this.use_close_btn&&
JAM.call(list.appendChild,list,[JAM.call(this.createCloseButton,this,[this.hideLangWindow])]);this.highlightCurSel();JAM.call(v1373.appendChild,v1373,[list]);list=this.language_window;JAM.call(list.appendChild,list,[v1373])}
function v206(){function v205(elm){JAM.call(me.custom_item_evaulator,me,[me,elm])}var output=AJS.DIV();output.style.textAlign="left";var pointer=0,results=this.results;if(0<results.length){for(var i=0,v323=i<results.length;v323;){introspect(JAM.policy.p1)v323=results[i];v323=v323.attrs.o;introspect(JAM.policy.p1)var v928=results[i];var v928=v928.attrs.l,part_1_text=this.orginal_text.substring(pointer,v323),part_1_text=JAM.call(GoogieSpell.createPart,GoogieSpell,[part_1_text]);JAM.call(output.appendChild,
output,[part_1_text]);pointer+=v323-pointer;v323=JAM.call(this.createErrorLink,this,[this.orginal_text.substr(v323,v928),i]);this.error_links.push(v323);JAM.call(output.appendChild,output,[v323]);pointer+=v928;i+=1;v323=i<results.length}pointer=this.orginal_text.substr(pointer,this.orginal_text.length);pointer=JAM.call(GoogieSpell.createPart,GoogieSpell,[pointer]);JAM.call(output.appendChild,output,[pointer])}else JAM.set(output,"innerHTML",this.orginal_text);var me=this;this.custom_item_evaulator&&
JAM.call(AJS.map,AJS,[this.error_links,v205]);JAM.call(AJS.ACN,AJS,[this.edit_layer,output]);this.text_area_bottom=this.text_area.offsetTop+this.text_area.offsetHeight;JAM.call(AJS.hideElement,AJS,[this.text_area]);JAM.call(AJS.insertBefore,AJS,[this.edit_layer,this.text_area]);this.use_focus&&(this.focus_link_t=output=JAM.call(this.createFocusLink,this,["focus_t"]),this.focus_link_b=output=JAM.call(this.createFocusLink,this,["focus_b"]),JAM.call(AJS.insertBefore,AJS,[this.focus_link_t,this.edit_layer]),
JAM.call(AJS.insertAfter,AJS,[this.focus_link_b,this.edit_layer]));this.edit_layer.scrollTop=this.ta_scroll_top}
function v204(txt_part){if(" "==txt_part)return JAM.call(AJS.TN,AJS,[" "]);AJS.SPAN();navigator.userAgent.toLowerCase().indexOf("safari");var part=AJS.SPAN();txt_part=JAM.call(GoogieSpell.escapeSepcial,GoogieSpell,[txt_part]);txt_part=txt_part.replace(/\n/g,"<br>");txt_part=txt_part.replace(/    /g," &nbsp;");txt_part=txt_part.replace(/^ /g,"&nbsp;");txt_part=txt_part.replace(/ $/g,"&nbsp;");JAM.set(part,"innerHTML",txt_part);return part}
function v203(text,id){function d(e){JAM.call(me.showErrorWindow,me,[elm,id]);d=null;return!1}var elm=JAM.call(AJS.SPAN,AJS,[{"class":"googie_link"}]),me=this;JAM.call(AJS.AEV,AJS,[elm,"click",d]);elm.googie_action_btn="1";elm.g_id=id;elm.is_corrected=!1;JAM.call(AJS.AEV,AJS,[elm,"contextmenu",d]);JAM.set(elm,"innerHTML",text);return elm}
function v202(){JAM.call(this.setStateChanged,this,["spell_check"]);this.switch_lan_pic.style.display="inline";this.edit_layer&&(this.el_scroll_top=this.edit_layer.scrollTop);this.hideErrorWindow();this.main_controller&&(this.spell_span.className="googie_no_style");if(!this.ignore){try{this.edit_layer.parentNode.removeChild(this.edit_layer),this.use_focus&&(JAM.call(AJS.removeElement,AJS,[this.focus_link_t]),JAM.call(AJS.removeElement,AJS,[this.focus_link_b]))}catch(e){}JAM.call(AJS.showElement,AJS,
[this.text_area]);void 0!=this.el_scroll_top&&(this.text_area.scrollTop=this.el_scroll_top)}JAM.call(this.checkSpellingState,this,[!1])}
function v201(width,height){function v200(e){function v199(){me.text_area.focus();fn1=null}(e="googie_link"!=JAM.call(AJS.getEventElm,AJS,[e]).className)&&(e=!me.isErrorWindowShown());if(e){me.resumeEditing();var fn1=v199;JAM.call(setTimeout,null,[fn1,10])}return!1}var v1377=JAM.call(AJS.DIV,AJS,[{"class":"googie_edit_layer"}]);this.edit_layer=v1377;this.edit_layer.className=this.text_area.className;this.edit_layer.style.border="1px solid #999";this.edit_layer.style.backgroundColor="#f7f7f7";this.edit_layer.style.padding=
"3px";this.edit_layer.style.margin="0px";JAM.call(AJS.setWidth,AJS,[this.edit_layer,width-8]);(v1377="input"!=JAM.call(AJS.nodeName,AJS,[this.text_area]))||(v1377=""==JAM.call(this.getValue,this,[this.text_area]));v1377?(this.edit_layer.style.overflow="auto",JAM.call(AJS.setHeight,AJS,[this.edit_layer,height-6])):this.edit_layer.style.overflow="hidden";if(this.edit_layer_dbl_click){var me=this,v1377=v200;JAM.set(this.edit_layer,"ondblclick",v1377);v1377=null}}
function v198(elm,id){function v197(i){function v196(){return JAM.call(e_elm[1],e_elm,[elm,me])}if(i<me.extra_menu_items.length){var v375=me.extra_menu_items;introspect(JAM.policy.p1)var e_elm=v375[i];(v375=!e_elm[2])||(v375=JAM.call(e_elm[2],e_elm,[elm,me]));if(v375){var v375=AJS.TR(),e_col=JAM.call(AJS.TD,AJS,[e_elm[0]]);JAM.set(e_col,"onmouseover",GoogieSpell.item_onmouseover);JAM.set(e_col,"onmouseout",GoogieSpell.item_onmouseout);var fn=v196;JAM.call(AJS.AEV,AJS,[e_col,"click",fn]);JAM.call(AJS.ACN,
AJS,[v375,e_col]);JAM.call(AJS.ACN,AJS,[list,v375])}JAM.call(loop,null,[i+1])}}function v195(){""!=edit_input.value&&(JAM.call(AJS.isDefined,AJS,[elm.old_value])||JAM.call(this.saveOldValue,this,[elm,elm.innerHTML]),JAM.call(this.updateOrginalText,this,[offset,elm.innerHTML,edit_input.value,id]),elm.style.color="green",elm.is_corrected=!0,JAM.set(elm,"innerHTML",edit_input.value),this.hideErrorWindow());return!1}function v194(e){JAM.call(this.updateOrginalText,this,[offset,elm.innerHTML,old_value,
id]);elm.is_corrected=!0;elm.style.color="#b91414";JAM.set(elm,"innerHTML",old_value);this.hideErrorWindow()}function v193(e){e=JAM.call(AJS.getEventElm,AJS,[e]);JAM.call(this.correctError,this,[id,elm,e])}this.show_menu_observer&&JAM.call(this.show_menu_observer,this,[this]);var me=this,abs_pos=JAM.call(AJS.absolutePosition,AJS,[elm]);abs_pos.y-=this.edit_layer.scrollTop;this.error_window.style.visibility="visible";JAM.call(AJS.setTop,AJS,[this.error_window,abs_pos.y+20]);JAM.call(AJS.setLeft,AJS,
[this.error_window,abs_pos.x]);abs_pos=JAM.call(AJS.TABLE,AJS,[{"class":"googie_list"}]);abs_pos.googie_action_btn="1";var list=AJS.TBODY(),changed=!1;if(this.custom_menu_builder!=[])for(var k=0,v397=k<this.custom_menu_builder.length;v397;){v397=this.custom_menu_builder;introspect(JAM.policy.p1)v397=v397[k];var v1217=this.results;introspect(JAM.policy.p1)v1217=v1217[id];if(JAM.call(v397[0],v397,[v1217])){changed=JAM.call(v397[1],v397,[this,list,elm]);break}k+=1;v397=k<this.custom_menu_builder.length}if(!changed){changed=
this.results;introspect(JAM.policy.p1)changed=changed[id];changed=changed.suggestions;k=this.results;introspect(JAM.policy.p1)k=k[id];var offset=k.attrs.o;0==changed.length&&(k=AJS.TR(),v397=JAM.call(AJS.TD,AJS,[{style:"cursor: default;"}]),v1217=AJS.SPAN(),JAM.set(v1217,"innerHTML",this.lang_no_suggestions),JAM.call(AJS.ACN,AJS,[v397,JAM.call(AJS.TN,AJS,[v1217.innerHTML])]),v397.googie_action_btn="1",JAM.call(k.appendChild,k,[v397]),JAM.call(list.appendChild,list,[k]));i=0;for(k=i<changed.length;k;)k=
AJS.TR(),v397=AJS.TD(),v1217=AJS.SPAN(),JAM.set(v1217,"innerHTML",JAM.get(changed,i,JAM.policy.p1)),v1217=JAM.call(AJS.TN,AJS,[v1217.innerHTML]),JAM.call(v397.appendChild,v397,[v1217]),v1217=v193,JAM.call(AJS.AEV,AJS,[v397,"click",JAM.call(AJS.$b,AJS,[v1217,this])]),v1217=GoogieSpell.item_onmouseover,JAM.call(AJS.AEV,AJS,[v397,"mouseover",v1217]),v1217=GoogieSpell.item_onmouseout,JAM.call(AJS.AEV,AJS,[v397,"mouseout",v1217]),JAM.call(k.appendChild,k,[v397]),JAM.call(list.appendChild,list,[k]),i+=
1,k=i<changed.length;(changed=elm.is_changed)&&(changed=elm.innerHTML!=elm.old_value);if(changed){var old_value=elm.old_value,changed=AJS.TR(),k=AJS.TD(),v1217=GoogieSpell.item_onmouseover;JAM.call(AJS.AEV,AJS,[k,"mouseover",v1217]);v1217=GoogieSpell.item_onmouseout;JAM.call(AJS.AEV,AJS,[k,"mouseout",v1217]);v397=JAM.call(AJS.SPAN,AJS,[{"class":"googie_list_revert"}]);JAM.set(v397,"innerHTML",this.lang_revert+" "+old_value);JAM.call(k.appendChild,k,[v397]);v1217=v194;JAM.call(AJS.AEV,AJS,[k,"click",
JAM.call(AJS.$b,AJS,[v1217,this])]);JAM.call(changed.appendChild,changed,[k]);JAM.call(list.appendChild,list,[changed])}var changed=AJS.TR(),k=JAM.call(AJS.TD,AJS,[{style:"cursor: default"}]),edit_input=JAM.call(AJS.INPUT,AJS,[{style:"width: 120px; margin:0; padding:0",value:elm.innerHTML}]);edit_input.googie_action_btn="1";var v397=v195,v397=JAM.call(AJS.$b,AJS,[v397,this]),v1217=JAM.call(AJS.IMG,AJS,[{src:this.img_dir+"ok.gif",style:"width: 32px; height: 16px; margin-left: 2px; margin-right: 2px; cursor: pointer;"}]),
edit_form=JAM.call(AJS.FORM,AJS,[{style:"margin: 0; padding: 0; cursor: default;"},edit_input,v1217]);edit_form.googie_action_btn="1";k.googie_action_btn="1";JAM.call(AJS.AEV,AJS,[edit_form,"submit",v397]);JAM.call(AJS.AEV,AJS,[v1217,"click",v397]);JAM.call(k.appendChild,k,[edit_form]);JAM.call(changed.appendChild,changed,[k]);JAM.call(list.appendChild,list,[changed]);0<this.extra_menu_items.length&&JAM.call(AJS.ACN,AJS,[list,this.createListSeparator()]);var loop=v197;JAM.call(loop,null,[0]);loop=
null;this.use_close_btn&&JAM.call(AJS.ACN,AJS,[list,JAM.call(this.createCloseButton,this,[this.hideErrorWindow])])}JAM.call(abs_pos.appendChild,abs_pos,[list]);changed=this.error_window;JAM.call(changed.appendChild,changed,[abs_pos]);(abs_pos=AJS.isIe())&&(abs_pos=!this.error_window_iframe);abs_pos&&(abs_pos=JAM.call(AJS.IFRAME,AJS,[{style:"position: absolute; z-index: 0;"}]),JAM.call(AJS.ACN,AJS,[AJS.getBody(),abs_pos]),this.error_window_iframe=abs_pos);AJS.isIe()&&(abs_pos=this.error_window_iframe,
JAM.call(AJS.setTop,AJS,[abs_pos,this.error_window.offsetTop]),JAM.call(AJS.setLeft,AJS,[abs_pos,this.error_window.offsetLeft]),JAM.call(AJS.setWidth,AJS,[abs_pos,this.error_window.offsetWidth]),JAM.call(AJS.setHeight,AJS,[abs_pos,this.error_window.offsetHeight]),abs_pos.style.visibility="visible");abs_pos=JAM.call(this.createFocusLink,this,["link"]);changed=JAM.call(AJS.TD,AJS,[{style:"text-align: right; font-size: 1px; height: 1px; margin: 0; padding: 0;"},abs_pos]);changed=JAM.call(AJS.TR,AJS,
[changed]);JAM.call(list.appendChild,list,[changed]);abs_pos.focus()}
function v192(id,elm,l_elm,rm_pre_space){var old_value=elm.innerHTML;l_elm=l_elm.innerHTML;var v1226=this.results;introspect(JAM.policy.p1)v1226=v1226[id];v1226=v1226.attrs.o;if(rm_pre_space){var pre_length=elm.previousSibling.innerHTML;rm_pre_space=elm.previousSibling;pre_length=pre_length.slice(0,pre_length.length-1);JAM.set(rm_pre_space,"innerHTML",pre_length);old_value=" "+old_value;v1226-=1}this.hideErrorWindow();JAM.call(this.updateOrginalText,this,[v1226,old_value,l_elm,id]);JAM.set(elm,"innerHTML",
l_elm);elm.style.color="green";elm.is_corrected=!0;rm_pre_space=this.results;introspect(JAM.policy.p1)id=rm_pre_space[id];id.attrs.l=l_elm.length;JAM.call(AJS.isDefined,AJS,[elm.old_value])||JAM.call(this.saveOldValue,this,[elm,old_value]);this.errorFixed()}function v191(){var e_col=JAM.call(AJS.TD,AJS,[" "]);e_col.googie_action_btn="1";e_col.style.cursor="default";e_col.style.fontSize="3px";e_col.style.borderTop="1px solid #ccc";e_col.style.paddingTop="3px";return JAM.call(AJS.TR,AJS,[e_col])}
function v190(elm,old_value){elm.is_changed=!0;elm.old_value=old_value}
function v189(offset,old_value,new_value,id){var part_1=this.orginal_text.substring(0,offset);offset=this.orginal_text.substring(offset+old_value.length);this.orginal_text=part_1+new_value+offset;JAM.call(this.setValue,this,[this.text_area,this.orginal_text]);old_value=new_value.length-old_value.length;new_value=0;for(part_1=new_value<this.results.length;part_1;){(part_1=new_value!=id)&&(part_1=new_value>id);if(part_1){part_1=this.results;introspect(JAM.policy.p1)part_1=part_1[new_value];part_1=part_1.attrs;
part_1.o+=old_value}new_value+=1;part_1=new_value<this.results.length}}function v188(){try{this.error_window.style.visibility="hidden",this.error_window_iframe&&(this.error_window_iframe.style.visibility="hidden")}catch(e){}}function v187(){var v456=null!=this.error_window;v456&&(v456="visible"==this.error_window.style.visibility);return v456}function v186(){var v1379=AJS.DIV();this.error_window=v1379;this.error_window.className="googie_window";this.error_window.googie_action_btn="1"}
function v185(){this.cnt_errors+=1}function v184(){this.cnt_errors_fixed+=1;this.all_errors_fixed_observer&&this.cnt_errors_fixed==this.cnt_errors&&(this.hideErrorWindow(),this.all_errors_fixed_observer())}
function v183(r_text){JAM.startProfile('parse');var re_split_attr_c=/\w+="(\d+|true)"/g,re_split_text=/\t/g;r_text=r_text.match(/<c[^>]*>[^<]*<\/c>/g);var results=[];if(null==r_text)return results;for(var i=0,v476=i<r_text.length;v476;){v476=[];this.errorFound();var v1380=[];v476.attrs=v1380;introspect(JAM.policy.p1)v1380=r_text[i];for(var v1380=v1380.match(re_split_attr_c),j=0,v470=j<v1380.length;v470;){introspect(JAM.policy.p1)v470=v1380[j];var c_attr=v470.split(/=/),val=c_attr[1].replace(/"/g,"");"true"!=val?(v470=v476.attrs,
c_attr=c_attr[0],val=parseInt(val),JAM.set(v470,c_attr,val)):JAM.set(v476.attrs,c_attr[0],val);j+=1;v470=j<v1380.length}v1380=[];v476.suggestions=v1380;introspect(JAM.policy.p1)v1380=r_text[i];v1380=v1380.replace(/<[^>]*>/g,"");v1380=v1380.split(re_split_text);j=0;for(v470=j<v1380.length;v470;){introspect(JAM.policy.p1)v470=v1380[j];if(""!=v470){v470=v476.suggestions;introspect(JAM.policy.p1)val=v1380[j];v470.push(val)}j+=1;v470=j<v1380.length}results.push(v476);i+=1;v476=i<r_text.length}JAM.stopProfile('parse');return results}
function v182(ignore){JAM.startProfile('submit');function reqfailed(res_txt,req){me.custom_ajax_error?JAM.call(me.custom_ajax_error,me,[req]):alert("An error was encountered on the server. Please try again later.");me.main_controller&&(JAM.call(AJS.removeElement,AJS,[me.spell_span]),me.removeIndicator());me.checkSpellingState()}function reqdone(res_txt){var v480=me,v1383=JAM.call(me.parseResult,me,[res_txt]);v480.results=v1383;null!=res_txt.match(/<c.*>/)?(me.showErrorsInIframe(),me.resumeEditingState()):me.custom_no_spelling_error?
JAM.call(me.custom_no_spelling_error,me,[me]):me.flashNoSpellingErrorState();me.removeIndicator()}var me=this;this.cnt_errors=this.cnt_errors_fixed=0;JAM.call(this.setStateChanged,this,["checking_spell"]);this.main_controller&&JAM.call(this.appendIndicator,this,[this.spell_span]);this.error_links=[];this.ta_scroll_top=this.text_area.scrollTop;try{this.hideLangWindow()}catch(e){}this.ignore=ignore;var v1005=""==JAM.call(this.getValue,this,[this.text_area]);v1005||(v1005=ignore);v1005?(me.custom_no_spelling_error?
JAM.call(me.custom_no_spelling_error,me,[me]):me.flashNoSpellingErrorState(),me.removeIndicator()):(JAM.call(this.createEditLayer,this,[this.text_area.offsetWidth,this.text_area.offsetHeight]),this.createErrorWindow(),ignore=AJS.getBody(),JAM.call(ignore.appendChild,ignore,[this.error_window]),this.main_controller&&JAM.set(this.spell_span,"onclick",null),this.orginal_text=ignore=JAM.call(this.getValue,this,[this.text_area]),ignore=JAM.call(AJS.getRequest,AJS,[this.getGoogleUrl()]),JAM.call(ignore.addCallback,
ignore,[reqdone]),reqdone=null,JAM.call(ignore.addErrback,ignore,[reqfailed]),reqfailed=null,v1005=JAM.call(GoogieSpell.escapeSepcial,GoogieSpell,[this.orginal_text]),JAM.call(ignore.sendReq,ignore,[JAM.call(GoogieSpell.createXMLReq,GoogieSpell,[v1005])]));JAM.stopProfile('submit');}function v181(text){return'<?xml version="1.0" encoding="utf-8" ?><spellrequest textalreadyclipped="0" ignoredups="0" ignoredigits="1" ignoreallcaps="1"><text>'+text+"</text></spellrequest>"}
function v180(val){return val.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function v179(){return this.server_url+GOOGIE_CUR_LANG}function v178(bool){this.report_state_change=bool}function v177(current_state){this.state=current_state;var v1010=null!=this.spelling_state_observer;v1010&&(v1010=this.report_state_change);v1010&&JAM.call(this.spelling_state_observer,this,[current_state,this])}function v176(ta,value){ta.value=value}function v175(ta){return ta.value}
function v174(){try{return this.focus_link_b.focus(),this.focus_link_t.focus(),!0}catch(e){return!1}}function v173(eval,builder){this.custom_menu_builder.push([eval,builder])}function v172(name,call_back_fn,checker){this.extra_menu_items.push([name,call_back_fn,checker])}function v171(){this.use_close_btn=!1}function v170(bool){this.decoration=bool}function v169(width,height){this.force_width=width;this.force_height=height}
function v168(lang_dict){this.lang_to_word=lang_dict;this.langlist_codes=lang_dict=JAM.call(AJS.keys,AJS,[lang_dict])}function v167(elm){this.spell_container=elm=JAM.call(AJS.$,AJS,[elm])}
function v166(id){"string"==typeof id&&(id=JAM.call(AJS.$,AJS,[id]));this.text_area=id;var r_height;if(null!=this.text_area){if(id=!JAM.call(AJS.isDefined,AJS,[this.spell_container]))id=this.decoration;if(id){var table=AJS.TABLE(),tbody=AJS.TBODY(),tr=AJS.TR();id=JAM.call(AJS.isDefined,AJS,[this.force_width])?this.force_width:this.text_area.offsetWidth+"px";r_height=JAM.call(AJS.isDefined,AJS,[this.force_height])?this.force_height:"";var spell_container=AJS.TD();this.spell_container=spell_container;
JAM.call(tr.appendChild,tr,[spell_container]);JAM.call(tbody.appendChild,tbody,[tr]);JAM.call(table.appendChild,table,[tbody]);JAM.call(AJS.insertBefore,AJS,[table,this.text_area]);JAM.call(AJS.setHeight,AJS,[table,spell_container,r_height]);JAM.call(AJS.setWidth,AJS,[table,spell_container,id]);spell_container.style.textAlign="right"}this.checkSpellingState()}else this.report_ta_not_found&&alert("Text area not found")}
function v165(data){var req=this.req,http_method=this.http_method,http_url=this.http_url;"POST"==http_method?(req.open(http_method,http_url,!0),http_method=req,http_url=JAM.call(AJS.$b,AJS,[this._onreadystatechange,this]),JAM.set(http_method,"onreadystatechange",http_url),req.setRequestHeader("Content-type","application/x-www-form-urlencoded"),JAM.call(AJS.isObject,AJS,[data])?req.send(JAM.call(AJS.encodeArguments,AJS,[data])):JAM.call(AJS.isDefined,AJS,[data])?req.send(data):req.send("")):(req.open("GET",
http_url,!0),data=req,http_method=JAM.call(AJS.$b,AJS,[this._onreadystatechange,this]),JAM.set(data,"onreadystatechange",http_method),req.send(null))}function v164(){var req=this.req;if(4==req.readyState){var status="";try{status=req.status}catch(e){}var v1239=200==status;v1239||(v1239=304==status);(status=v1239)||(status=null==req.responseText);status?this.callback():this.errback()}}function v163(fn1,fn2){JAM.call(this.addCallback,this,[fn1]);JAM.call(this.addErrback,this,[fn2])}
function v162(){this.req.abort()}function v161(fn){this.callbacks.unshift(fn)}function v160(fn){this.errbacks.unshift(fn)}
function v159(){if(0==this.errbacks.length)if(AJS.ajaxErrorHandler)JAM.call(AJS.ajaxErrorHandler,AJS,[req.responseText,req]);else{var txt=this.req.responseText.substring(0,200),v1023=JAM.call(AJS.strip,AJS,[txt]);v1023&&(v1023=-1==txt.indexOf("<html"));v1023&&alert("Error encountered:\n"+txt)}if(AJS.generalErrorback&&(txt=JAM.call(AJS.generalErrorback,AJS,[this.req]),!txt))return;JAM.call(this.excCallbackSeq,this,[this.req,this.errbacks])}
function v158(){JAM.call(this.excCallbackSeq,this,[this.req,this.callbacks])}function v157(req,list){var data=req.responseText;if(AJS.generalCallback&&(data=JAM.call(AJS.generalCallback,AJS,[req,list]),!data))return;for(var v544=0<list.length;v544;){v544=list.pop();if(v544=JAM.call(v544,null,[data,req]))data=v544;else if(0==v544)break;v544=0<list.length}}function v156(req,method,url){this.callbacks=[];this.errbacks=[];this.req=req;this.http_method=method;this.http_url=url}
function v155(cur,prev){function v154(){this.parent=prev;return JAM.call(cur.apply,cur,[this,arguments])}return v154}function v153(members){JAM.call(AJS.update,AJS,[this.prototype,members])}
function v152(members){var parent=JAM.new(this,["no_init"]);for(k in members){introspect(JAM.policy.p1)var prev=parent[k];introspect(JAM.policy.p1)var cur=members[k];var v1244=prev;v1244&&(v1244=prev!=cur);v1244&&(v1244="function"==typeof cur);v1244&&(cur=JAM.call(this._parentize,this,[cur,prev]));JAM.set(parent,k,cur)}return JAM.new(AJS.Class,[parent])}
function v151(members){function fn(){if("no_init"!=arguments[0]){var v548=this.init;return JAM.call(v548.apply,v548,[this,arguments])}}fn.prototype=members;JAM.call(AJS.update,AJS,[fn,AJS.Class.prototype]);return fn}function v150(str,limit,delim){return str.length>limit?str.substring(0,limit)+(delim||"..."):str}function v149(str){return str.replace(/^\s+/,"").replace(/\s+$/g,"")}function v148(export_scope,fn){JAM.call(fn.apply,fn,[export_scope,[]])}
function v147(o){try{if(window._firebug){var v555=window._firebug;JAM.call(v555.log,v555,[o])}else window.console&&JAM.call(console.log,console,[o])}catch(e){}}function v146(scope){scope=scope||window;for(e in AJS)"addEventListener"!=e&&JAM.set(scope,e,JAM.get(AJS,e,JAM.policy.p1))}function v145(o){o=String(o);return-1!=o.indexOf(" Object")}function v144(obj){return"function"==typeof obj}function v143(obj){return"object"==typeof obj}function v142(obj){return"number"==typeof obj}
function v141(obj){return"string"==typeof obj}function v140(obj){try{return obj instanceof Array}catch(e){return!1}}function v139(o){var v564="undefined"!=o;v564&&(v564=null!=o);return v564}function v138(str){var v1246=JAM.call(AJS.isDefined,AJS,[str]);v1246&&(v1246=str.toString());(str=v1246)||(str="");str=decodeURIComponent(str);return str.replace(/\+/g," ")}
function v137(str){var v1248=JAM.call(AJS.isDefined,AJS,[str]);v1248&&(v1248=str.toString());(str=v1248)||(str="");return encodeURIComponent(str)}function v136(obj){var rval=[],prop;for(prop in obj){introspect(JAM.policy.p1)var v567=obj[prop];rval.push(v567)}return rval}function v135(obj){var rval=[],prop;for(prop in obj)rval.push(prop);return rval}
function v134(name,fn,interval){var v568=AJS._reccruing_tos;introspect(JAM.policy.p1)v568=v568[name];v568&&clearTimeout(v568);v568=AJS._reccruing_tos;fn=JAM.call(setTimeout,null,[fn,interval]);JAM.set(v568,name,fn)}function v133(fn,extra_args){function v132(){try{var args=JAM.call(AJS.$FA,AJS,[arguments]).concat(extra_args);return JAM.call(fn.apply,fn,[scope,args])}catch(e){}}extra_args=JAM.call(AJS.$A,AJS,[extra_args]);var v572=fn._cscope;v572||(v572=window);var scope=v572;return v132}
function v131(elm,type,fn){function r_fn(){JAM.call(AJS.removeEventListener,AJS,[elm,type,r_fn]);JAM.call(fn,null,[arguments])}return r_fn}function v130(e){AJS.isIe()?window.event.returnValue=!1:e.preventDefault()}function v129(self){for(var k in self){introspect(JAM.policy.p1)var func=self[k];if("function"==typeof func){var v575=self,v576=k,func=JAM.call(AJS.$b,AJS,[func,self]);JAM.set(v575,v576,func)}}}
function v128(fn,scope,extra_args){fn._cscope=scope;return JAM.call(AJS._getRealScope,AJS,[fn,extra_args])}function v127(elms,type,handler){function v126(elm){var v1034=elm.events;if(v1034){v1034=elm.events;introspect(JAM.policy.p1)v1034=v1034[type]}if(v1034){elm=elm.events;introspect(JAM.policy.p1)elm=elm[type];delete elm[handler.$f_guid]}}elms=JAM.call(AJS.$A,AJS,[elms]);map(elms,v126)}
function v125(event){function v124(handler){var v1036=me.events,v1037=event.type;introspect(JAM.policy.p1)v1036=v1036[v1037];delete v1036[handler.$f_guid]}var me=this,v583=event;v583||(v583=window.event);if(event=v583){(v583=!event.ctrl)&&(v583=-1!=event.type.indexOf("key"));v583&&JAM.call(AJS.setEventKey,AJS,[event]);var v583=this.events,v587=event.type;introspect(JAM.policy.p1)v583=v583[v587];var v587=[],res=!0,i;for(i in v583){introspect(JAM.policy.p1)var handler$$0=this.$$handleEvent=v583[i];
handler$$0!=AJS.handleEvent&&(res=JAM.call(handler$$0,null,[event]),handler$$0.listen_once&&v587.push(handler$$0))}0<v587.length&&JAM.call(AJS.map,AJS,[v587,v124]);return res}}
function v123(elms,types,handler,listen_once){function v122(elm){function v121(type){var v591=elm.events;introspect(JAM.policy.p1)v591=v591[type];var v1042=elm==window;v1042&&(v1042="load"==type);if(v1042)AJS.ready_list.push(handler);else{"lazy_load"==type&&(type="load");if(!v591){v591=JAM.set(elm.events,type,{});v1042="on"+type;introspect(JAM.policy.p1)v1042=elm[v1042];if(v1042){v1042="on"+type;introspect(JAM.policy.p1)v591[0]=elm[v1042]}}elm._wipe_guid||(elm._wipe_guid=AJS._wipe_guid,AJS._wipe_guid+=
1);JAM.set(v591,handler.$f_guid,handler);elm.addEventListener(type,AJS.handleEvent,!1)}}listen_once&&(handler.listen_once=!0);handler.$f_guid||(handler.$f_guid=AJS._f_guid,AJS._f_guid+=1);elm.events||(elm.events={});JAM.call(AJS.map,AJS,[types,v121]);elm=null}elms=JAM.call(AJS.$A,AJS,[elms]);types=JAM.call(AJS.$A,AJS,[types]);JAM.call(AJS.map,AJS,[elms,v122])}
function v120(fn$$0){function v119(fn){JAM.call(fn.call,fn,[window])}AJS.is_ready||(AJS.is_ready=!0,JAM.call(AJS.map,AJS,[AJS.ready_list,v119]),AJS.ready_list=[])}
function v118(){function v117(){if(!AJS.is_ready){try{var v607=document.documentElement;JAM.call(v607.doScroll,v607,["left"])}catch(error){JAM.call(setTimeout,null,[arguments.callee,0]);return}AJS.ready()}}function v116(){"complete"===document.readyState&&(JAM.call(document.detachEvent,document,["onreadystatechange",arguments.callee]),AJS.ready())}function v115(){JAM.call(document.removeEventListener,document,["DOMContentLoaded",arguments.callee,!1]);AJS.ready()}if(!AJS.ready_bound){AJS.ready_bound=
!0;if(document.addEventListener)document.addEventListener("DOMContentLoaded",v115,!1);else if(document.attachEvent){JAM.call(document.attachEvent,document,["onreadystatechange",v116]);var v1050=document.documentElement.doScroll;v1050&&(v1050=window==window.top);v1050&&v117()}JAM.call(AJS.AEV,AJS,[window,"load",AJS.ready])}}
function v114(elms,type,handler,listen_once){function v113(elm){elm.events&&JAM.set(elm.events,type,{})}elms=JAM.call(AJS.$A,AJS,[elms]);JAM.call(AJS.map,AJS,[elms,v113]);return JAM.call(AJS.AEV,AJS,[elms,type,handler,listen_once])}function v112(e){e||(e=window.event);var v620;v620=e.keyCode?e.keyCode:e.charCode;e.key=v620;e.ctrl=e.ctrlKey;e.alt=e.altKey;e.meta=e.metaKey;e.shift=e.shiftKey}
function v111(e){var v1255=e;v1255&&(v1255=!e.type);v1255&&(v1255=!e.keyCode);if(v1255)return e;var targ;e||(e=window.event);e.target?targ=e.target:e.srcElement&&(targ=e.srcElement);(e=targ)&&(e=3==targ.nodeType);e&&(targ=targ.parentNode);return targ}
function v110(elm1,elm2){function getSign(v){return 0<v?"+":0>v?"-":0}var pos_elm1=JAM.call(AJS.absolutePosition,AJS,[elm1]),pos_elm2=JAM.call(AJS.absolutePosition,AJS,[elm2]),top1=pos_elm1.y,pos_elm1=pos_elm1.x,right1=pos_elm1+elm1.offsetWidth,bottom1=top1+elm1.offsetHeight,top2=pos_elm2.y,pos_elm2=pos_elm2.x,right2=pos_elm2+elm2.offsetWidth,bottom2=top2+elm2.offsetHeight;(top1=getSign(top1-bottom2)!=getSign(bottom1-top2))&&(top1=getSign(pos_elm1-right2)!=getSign(right1-pos_elm2));return top1?!0:
!1}function v109(doc){doc=doc||document;var win_w,win_h;if(self.innerHeight)win_w=self.innerWidth,win_h=self.innerHeight;else{var v1055=doc.documentElement;v1055&&(v1055=doc.documentElement.clientHeight);v1055?(win_w=doc.documentElement.clientWidth,win_h=doc.documentElement.clientHeight):doc.body&&(win_w=doc.body.clientWidth,win_h=doc.body.clientHeight)}return{w:win_w,h:win_h}}
function v108(elm){if(!elm)return{x:0,y:0};if(elm.scrollLeft)return{x:elm.scrollLeft,y:elm.scrollTop};if(elm.clientX)return{x:elm.clientX,y:elm.clientY};var posObj={x:elm.offsetLeft,y:elm.offsetTop};if(elm.offsetParent)for(var next=elm.offsetParent;next;)posObj.x+=next.offsetLeft,posObj.y+=next.offsetTop,next=next.offsetParent;(next=AJS.isSafari())&&(next="absolute"==elm.style.position);next&&(posObj.x-=document.body.offsetLeft,posObj.y-=document.body.offsetTop);return posObj}
function v107(){var t,v1065=document.documentElement;v1065&&(v1065=document.documentElement.scrollTop);v1065?t=document.documentElement.scrollTop:document.body&&(t=document.body.scrollTop);return t}
function v106(e){var posx=0,posy=0;e||(e=window.event);var v1066=e.pageX;v1066||(v1066=e.pageY);v1066?(posx=e.pageX,posy=e.pageY):(v1066=e.clientX,v1066||(v1066=e.clientY),v1066&&(posx=e.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,posy=e.clientY+document.body.scrollTop+document.documentElement.scrollTop));return{x:posx,y:posy}}
function v105(date){function leadingZero(nr){10>nr&&(nr="0"+nr);return nr}var year=date.getUTCFullYear(),dd=date.getUTCDate(),mm=date.getUTCMonth()+1;return'"'+year+"-"+mm+"-"+dd+"T"+leadingZero(date.getUTCHours())+":"+leadingZero(date.getUTCMinutes())+":"+leadingZero(date.getUTCSeconds())+'"'}function v104(o){return('"'+o.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")}
function v103(data){var post_data=[];for(k in data){var v1077=k+"=";introspect(JAM.policy.p1)var v1274=data[k];post_data.push(v1077+JAM.call(AJS.urlencode,AJS,[v1274]))}return JAM.call(post_data.join,post_data,["&"])}
function v102(html){html=html.match(/<script.*?>((\n|\r|.)*?)<\/script>/g);if(null!=html)for(var i=0,v668=i<html.length;v668;){introspect(JAM.policy.p1)v668=html[i];v668=v668.replace(/<script.*?>/g,"");v668=v668.replace(/<\/script>/g,"");JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v668+" }"):JAM.call(eval,null,[v668]);i+=1;v668=i<html.length}}
function v101(txt){try{var v670="("+txt+")";return JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v670+" }"):JAM.call(eval,null,[v670])}catch(e){return JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+txt+" }"):JAM.call(eval,null,[txt])}}
function v100(url,type,debug){function eval_req(data,req){var text=req.responseText;if("Error"==text)JAM.call(d.errback,d,[req]);else return JAM.call(AJS.evalTxt,AJS,[text])}var d=JAM.call(AJS.getRequest,AJS,[url,type]);JAM.call(d.addCallback,d,[eval_req]);return d}
function v99(o){var objtype=typeof o;if("undefined"==objtype)return"null";var v1082="number"==objtype;v1082||(v1082="boolean"==objtype);if(v1082)return o+"";if(null===o)return"null";if("string"==objtype)return JAM.call(AJS._reprString,AJS,[o]);if(v1082="object"==objtype)v1082=o.getFullYear;if(v1082)return JAM.call(AJS._reprDate,AJS,[o]);var v1082=arguments.callee,v1084="function"!=objtype;v1084&&(v1084="number"==typeof o.length);if(v1084){for(var objtype=[],i=0,v1084=i<o.length;v1084;){introspect(JAM.policy.p1)v1084=
o[i];v1084=JAM.call(v1082,null,[v1084]);"string"!=typeof v1084&&(v1084="undefined");objtype.push(v1084);i+=1;v1084=i<o.length}return"["+JAM.call(objtype.join,objtype,[","])+"]"}if("function"==objtype)return null;objtype=[];for(i in o){var useKey;if("number"==typeof i)useKey='"'+i+'"';else if("string"==typeof i)useKey=JAM.call(AJS._reprString,AJS,[i]);else continue;introspect(JAM.policy.p1)v1084=o[i];v1084=JAM.call(v1082,null,[v1084]);"string"==typeof v1084&&objtype.push(useKey+":"+v1084)}return"{"+
JAM.call(objtype.join,objtype,[","])+"}"}function v98(url,method){var req=AJS.getXMLHttpRequest();null==url.match(/^https?:\/\//)&&""!=AJS.BASE_URL&&(AJS.BASE_URL.lastIndexOf("/")!=AJS.BASE_URL.length-1&&(AJS.BASE_URL+="/"),url=AJS.BASE_URL+url);method||(method="POST");return JAM.new(AJSDeferred,[req,method,url])}
function v97(){function v96(){throw"Browser does not support XMLHttpRequest";}function v95(){return new ActiveXObject("Msxml2.XMLHTTP.4.0")}function v94(){return new ActiveXObject("Microsoft.XMLHTTP")}function v93(){return new ActiveXObject("Msxml2.XMLHTTP")}function v92(){return new XMLHttpRequest}for(var try_these=[v92,v93,v94,v95,v96],i=0,v695=i<try_these.length;v695;){introspect(JAM.policy.p1)v695=try_these[i];try{return v695()}catch(e){JAM.call(AJS.log,AJS,[e])}i+=1;v695=i<try_these.length}}
function v91(tmpl,ns,scope){function fn(w,g){g=g.split("|");var v696=g[0];introspect(JAM.policy.p1)v696=ns[v696];for(var i=1,v698=i<g.length;v698;){introspect(JAM.policy.p1)v698=g[i];v696=JAM.call(JAM.get(scope,v698,JAM.policy.p1),scope,[v696]);i+=1;v698=i<g.length}if(""==v696)return"";(i=0==v696)||(i=-1==v696);i&&(v696+="");return v696||w}scope=scope||window;return tmpl.replace(/%\(([A-Za-z0-9_|.]*)\)/g,fn)}
function v90(){function v89(args){function v88(src){var pic=new Image;pic.src=src}JAM.call(AJS.map,AJS,[args,v88])}JAM.call(AJS.AEV,AJS,[window,"load",JAM.call(AJS.$p,AJS,[v89,arguments])])}function v87(html,first_child){var d=AJS.DIV();JAM.set(d,"innerHTML",html);return first_child?d.childNodes[0]:d}function v86(elm,p){1==p?(elm.style.opacity=1,elm.style.filter=""):(elm.style.opacity=p,elm.style.filter="alpha(opacity="+100*p+")")}
function v85(){function v84(elm){var v708=elm;elm=elm.className.replace(new RegExp("(^|\\s)"+cls,"g"),"");v708.className=elm}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),cls=args.pop();JAM.call(AJS.map,AJS,[args,v84])}function v83(elm,cls){var v1107=!elm;v1107||(v1107=!elm.className);if(v1107)return!1;var v1107=elm.className,v710=0<v1107.length;v710&&((v710=v1107==cls)||(v710=(new RegExp("(^|\\s)"+cls+"(\\s|$)")).test(v1107)));return v710}
function v82(){function v81(elm){if(!(new RegExp("(^|\\s)"+cls+"(\\s|$)")).test(elm.className)){var v1111=elm.className,v1342;v1342=elm.className?" ":"";elm.className=v1111+(v1342+cls)}}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),cls=args.pop();JAM.call(AJS.map,AJS,[args,v81])}function v80(){function v79(elm){elm.className=c}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),c=args.pop();JAM.call(AJS.map,AJS,[args,v79])}
function v78(){return JAM.call(AJS.__cssDim,AJS,[arguments,"top"])}function v77(){return JAM.call(AJS.__cssDim,AJS,[arguments,"right"])}function v76(){return JAM.call(AJS.__cssDim,AJS,[arguments,"left"])}function v75(){return JAM.call(AJS.__cssDim,AJS,[arguments,"height"])}function v74(){return JAM.call(AJS.__cssDim,AJS,[arguments,"width"])}
function v73(args,property){args=JAM.call(AJS.$FA,AJS,[args]);args.splice(args.length-1,0,property);var v713=AJS.setStyle;JAM.call(v713.apply,v713,[null,args])}
function v72(){function v71(elm){if(JAM.call(AJS.isIn,AJS,[property,num_styles])){var v1114=JAM.call(AJS.isString,AJS,[value]);v1114&&(v1114=value);v1114||(v1114=value+"px");value=v1114}JAM.set(elm.style,property,value)}function v70(elm){function v69(prop){introspect(JAM.policy.p1)var css_dim=value[prop];if(JAM.call(AJS.isIn,AJS,[prop,num_styles])){var v1116=JAM.call(AJS.isString,AJS,[css_dim]);v1116&&(v1116=css_dim);v1116||(v1116=css_dim+"px");css_dim=v1116}JAM.set(elm.style,prop,css_dim)}JAM.call(AJS.map,
AJS,[JAM.call(AJS.keys,AJS,[value]),v69])}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),value=args.pop(),num_styles=["top","left","right","width","height"];if(JAM.call(AJS.isObject,AJS,[value]))JAM.call(AJS.map,AJS,[args,v70]);else{var property=args.pop();JAM.call(AJS.map,AJS,[args,v71])}}function v68(elm){return!JAM.call(AJS.isElementHidden,AJS,[elm])}function v67(elm){var v723="none"==elm.style.display;v723||(v723="hidden"==elm.style.visibility);return v723}
function v66(elm){JAM.call(AJS.setStyle,AJS,[JAM.call(AJS.flattenElmArguments,AJS,[arguments]),"display","none"])}function v65(){JAM.call(AJS.setStyle,AJS,[JAM.call(AJS.flattenElmArguments,AJS,[arguments]),"display",""])}function v64(){var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),v1121=args.pop();v1121&&(v1121="visible");v1121||(v1121="hidden");JAM.call(AJS.setStyle,AJS,[args,"visibility",v1121])}
function v63(){function v62(elm){elm&&JAM.set(elm,"innerHTML",html)}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),html=args.pop();JAM.call(AJS.map,AJS,[args,v62]);return args[0]}
function v61(){function v60(text){return document.createTextNode(text)}function extends_ajs(elm){function v59(){var v727=AJS.createDOM;return JAM.call(v727.apply,v727,[null,[elm,arguments]])}JAM.set(AJS,elm.toUpperCase(),v59)}var elms="ul li td tr th tbody table input span b a div img button h1 h2 h3 h4 h5 h6 br textarea form p select option optgroup iframe script center dl dt dd small pre i label thead".split(" ");JAM.call(AJS.map,AJS,[elms,extends_ajs]);AJS.TN=v60}
function v58(name,attrs){var i=0,attr,elm=document.createElement(name),first_attr=attrs[0];introspect(JAM.policy.p1)attr=attrs[i];if(JAM.call(AJS.isDict,AJS,[attr])){for(k in first_attr){introspect(JAM.policy.p1)attr=first_attr[k];var v1124="style"==k;v1124||(v1124="s"==k);v1124?elm.style.cssText=attr:((v1124="c"==k)||(v1124="class"==k),v1124||(v1124="className"==k),v1124?elm.className=attr:JAM.call(elm.setAttribute,elm,[k,attr]))}i+=1}null==first_attr&&(i=1);for(attr=i<attrs.length;attr;){introspect(JAM.policy.p1)attr=
attrs[i];attr&&(first_attr=typeof attr,(v1124="string"==first_attr)||(v1124="number"==first_attr),v1124&&(attr=JAM.call(AJS.TN,AJS,[attr])),JAM.call(elm.appendChild,elm,[attr]));i+=1;attr=i<attrs.length}return elm}function v57(){function v56(elm){$(elm)&&JAM.call(AJS.swapDOM,AJS,[elm,null])}var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]);try{JAM.call(AJS.map,AJS,[args,v56])}catch(e){}}
function v55(dest,src){dest=JAM.call(AJS.getElement,AJS,[dest]);var parent=dest.parentNode;src?(src=JAM.call(AJS.getElement,AJS,[src]),JAM.call(parent.replaceChild,parent,[src,dest])):parent.removeChild(dest);return src}function v54(elm,reference_elm){var v738=reference_elm.parentNode;JAM.call(v738.insertBefore,v738,[elm,reference_elm]);return elm}function v53(elm,reference_elm){var v739=reference_elm.parentNode;JAM.call(v739.insertBefore,v739,[elm,reference_elm.nextSibling]);return elm}
function v52(elm){for(var child,v741=child=elm.firstChild;v741;)JAM.call(AJS.swapDOM,AJS,[child,null]),v741=child=elm.firstChild;if(2>arguments.length)return elm;child=AJS.appendChildNodes;return JAM.call(child.apply,child,[null,arguments])}
function v51(elm){var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]).slice(1);if(1<=args.length){var first_child=elm.firstChild;if(first_child)for(;;){var t_elm=args.shift();if(t_elm)JAM.call(AJS.insertBefore,AJS,[t_elm,first_child]);else break}else args=AJS.ACN,JAM.call(args.apply,args,[null,arguments])}return elm}
function v50(elm){function v49(n){JAM.call(AJS.isString,AJS,[n])&&(n=JAM.call(AJS.TN,AJS,[n]));JAM.call(AJS.isDefined,AJS,[n])&&JAM.call(elm.appendChild,elm,[n])}2<=arguments.length&&JAM.call(AJS.map,AJS,[arguments,v49,1]);return elm}function v48(elm){"string"==typeof elm&&(elm=JAM.call(AJS.HTML2DOM,AJS,[elm]));JAM.call(JAM.get(document,"write",JAM.policy.p1),document,['<span id="dummy_holder"></span>']);JAM.call(AJS.swapDOM,AJS,[JAM.call(AJS.$,AJS,["dummy_holder"]),elm])}
function v47(select){select=JAM.call(AJS.$,AJS,[select]);var v1133=select.options;select=select.selectedIndex;introspect(JAM.policy.p1)v1133=v1133[select];return v1133.value}
function v46(form,name){function v45(elm){var v1135=elm.name;v1135&&(v1135=elm.name==name);v1135&&(r=elm)}function v44(elm){var v1136=elm.name;v1136&&(v1136=elm.name==name);v1136&&(r=elm)}form=JAM.call(AJS.$,AJS,[form]);var r=null;JAM.call(AJS.map,AJS,[form.elements,v44]);if(r)return r;JAM.call(AJS.map,AJS,[JAM.call(AJS.$bytc,AJS,["select",null,form]),v45]);return r}function v43(){return JAM.call(AJS.$bytc,AJS,["body"])[0]}
function v42(elm,tag_name,class_name){function v41(m){return m.nextSibling}return JAM.call(AJS._nodeWalk,AJS,[elm,tag_name,class_name,v41])}function v40(elm,tag_name,class_name){function v39(m){return m.previousSibling}return JAM.call(AJS._nodeWalk,AJS,[elm,tag_name,class_name,v39])}function v38(elm,parent_to_consider,max_look_up){return elm==parent_to_consider?!0:0==max_look_up?!1:JAM.call(AJS.hasParent,AJS,[elm.parentNode,parent_to_consider,max_look_up-1])}
function v37(elm,tag_name,class_name){elm=JAM.call(AJS.$bytc,AJS,[tag_name,class_name,elm]);return 0<elm.length?elm[0]:null}function v36(elm,tag_name,class_name){function v35(m){if(m)return m.parentNode}return JAM.call(AJS._nodeWalk,AJS,[elm,tag_name,class_name,v35])}
function v34(elm,tag_name,class_name,fn_next_elm){function v33(p){return JAM.call(AJS.hasClass,AJS,[p,class_name])}function v32(p){return JAM.call(AJS.nodeName,AJS,[p])==tag_name}function v31(p){var v764=JAM.call(AJS.nodeName,AJS,[p])==tag_name;v764&&(v764=JAM.call(AJS.hasClass,AJS,[p,class_name]));return v764}var p=JAM.call(fn_next_elm,null,[elm]),checkFn;checkFn=tag_name&&class_name?v31:tag_name?v32:v33;if(JAM.call(checkFn,null,[elm]))return elm;for(;p;){if(JAM.call(checkFn,null,[p]))return p;p=
JAM.call(fn_next_elm,null,[p])}return null}function v30(elm){return elm.nodeName.toLowerCase()}
function v29(tag_name,class_name,parent,first_match){var class_elements=[];JAM.call(AJS.isDefined,AJS,[parent])||(parent=document);JAM.call(AJS.isDefined,AJS,[tag_name])||(tag_name="*");var v1141=class_name;v1141&&(v1141=document.getElementsByClassName);if(v1141)if(v1141=parent.getElementsByClassName(class_name),"*"==tag_name)class_elements=JAM.call(AJS.forceArray,AJS,[v1141]);else{var els_len=v1141.length;parent=0;for(class_name=parent<els_len;class_name;){introspect(JAM.policy.p1)class_name=v1141[parent];
if(class_name.nodeName.toLowerCase()==tag_name){introspect(JAM.policy.p1)class_name=v1141[parent];class_elements.push(class_name)}parent+=1;class_name=parent<els_len}}else if(v1141=parent.getElementsByTagName(tag_name),class_name){els_len=v1141.length;tag_name=new RegExp("(^|\\s)"+class_name+"(\\s|$)");parent=0;for(var v778=parent<els_len;v778;){introspect(JAM.policy.p1)v778=v1141[parent];(v778=tag_name.test(v778.className))||(v778=!class_name);if(v778){introspect(JAM.policy.p1)v778=v1141[parent];
class_elements.push(v778)}parent+=1;v778=parent<els_len}}else class_elements=JAM.call(AJS.forceArray,AJS,[v1141]);return first_match?class_elements[0]:class_elements}function v28(){for(var args=JAM.call(AJS.flattenElmArguments,AJS,[arguments]),elements=[],i=0,v782=i<args.length;v782;){introspect(JAM.policy.p1)v782=args[i];v782=JAM.call(AJS.getElement,AJS,[v782]);elements.push(v782);i+=1;v782=i<args.length}return elements}
function v27(id){var v1147=JAM.call(AJS.isString,AJS,[id]);v1147||(v1147=JAM.call(AJS.isNumber,AJS,[id]));return v1147?document.getElementById(id):id}function v26(fn){function v25(){args=args.concat(JAM.call(AJS.$FA,AJS,[arguments]));return JAM.call(fn.apply,fn,[window,args])}var args=JAM.call(AJS.$FA,AJS,[arguments]);args.shift();return v25}
function v24(list,fn,start_index,end_index){function v23(elm){JAM.call(fn,null,[elm])&&r.push(elm)}var r=[];JAM.call(AJS.map,AJS,[list,v23,start_index,end_index]);return r}function v22(list,fn){for(var i=list.length-1,l=0,v789=i>=l;v789;){introspect(JAM.policy.p1)v789=list[i];v789=JAM.call(fn.apply,fn,[null,[v789,i]]);if(void 0!=v789)return v789;i-=1;v789=i>=l}}
function v21(list,fn,start_index,end_index){var i=0,l=list.length;start_index&&(i=start_index);end_index&&(l=end_index);for(start_index=i<l;start_index;){introspect(JAM.policy.p1)start_index=list[i];start_index=JAM.call(fn,null,[start_index,i]);if(void 0!=start_index)return start_index;i+=1;start_index=i<l}}function v20(args){args=JAM.call(AJS.forceArray,AJS,[args]);return JAM.call(AJS.flattenList,AJS,[args])}
function v19(list){function _flatten(r,l){function v18(o){null!=o&&(JAM.call(AJS.isArray,AJS,[o])?_flatten(r,o):r.push(o))}JAM.call(AJS.map,AJS,[l,v18])}for(var has_list=!1,new_list=[],i=0,v797=i<list.length;v797;){introspect(JAM.policy.p1)v797=list[i];if(JAM.call(AJS.isArray,AJS,[v797])){has_list=!0;break}null!=v797&&new_list.push(v797);i+=1;v797=i<list.length}if(!has_list)return new_list;has_list=[];_flatten(has_list,list);return has_list}
function v17(l1,l2){for(var i in l2)JAM.set(l1,i,JAM.get(l2,i,JAM.policy.p1));return l1}function v16(list){var v799=list;list=Math.floor(Math.random()*list.length);introspect(JAM.policy.p1)return v799[list]}function v15(list){if(0<list.length){var v801=list.length-1;introspect(JAM.policy.p1)return list[v801]}else return null}function v14(list){return 0<list.length?list[0]:null}
function v13(elm,list,eval_fn){for(var i=0,v805=i<list.length;v805;){if(v805=eval_fn){introspect(JAM.policy.p1)v805=list[i];v805=JAM.call(eval_fn,null,[v805])}if(!v805){introspect(JAM.policy.p1)v805=list[i];v805=elm==v805}if(v805)return i;i+=1;v805=i<list.length}return-1}function v12(elm,list){var i=JAM.call(AJS.getIndex,AJS,[elm,list]);return-1!=i?!0:!1}
function v11(delim,list){function v10(elm){r+=delim+elm}try{return JAM.call(list.join,list,[delim])}catch(e){var v807=list[0];v807||(v807="");var r=v807;JAM.call(AJS.map,AJS,[list,v10,1]);return r+""}}function v9(args){for(var r=[],i=0,v809=i<args.length;v809;){introspect(JAM.policy.p1)v809=args[i];r.push(v809);i+=1;v809=i<args.length}return r}function v8(v){var v1162=JAM.call(AJS.isArray,AJS,[v]);v1162&&(v1162=!JAM.call(AJS.isString,AJS,[v]));return v1162?v:v?[v]:[]}
function v7(){return-1!=AJS._agent.indexOf("camino")}function v6(){return-1!=AJS._agent.indexOf("macintosh")}function v5(){var v814=-1!=AJS._agent.indexOf("gecko");v814&&(v814=20030210<=AJS._agent_version);return v814}function v4(){return-1!=AJS._agent.indexOf("opera")}function v3(all){if(all)return AJS._agent.indexOf("khtml");(all=-1!=AJS._agent.indexOf("khtml"))&&(all=null==AJS._agent.match(/3\.\d\.\d safari/));return all}function v2(){return-1!=AJS._agent.indexOf("msie 8")}
function v1(){var v819=-1!=AJS._agent.indexOf("msie");v819&&(v819=-1==AJS._agent.indexOf("opera"));return v819}function v0(var_name){for(var query=window.location.search.substring(1),query=query.split("&"),i=0,v823=i<query.length;v823;){introspect(JAM.policy.p1)v823=query[i];v823=v823.split("=");if(v823[0]==var_name)return v823[1];i+=1;v823=i<query.length}return null}
function GoogieSpell(img_dir,server_url){function fn(e){e=JAM.call(AJS.getEventElm,AJS,[e]);var v1177="1"!=e.googie_action_btn;v1177&&(v1177=this.isLangWindowShown());v1177&&this.hideLangWindow();(e="1"!=e.googie_action_btn)&&(e=this.isErrorWindowShown());e&&this.hideErrorWindow()}var cookie_value;cookie_value=getCookie();GOOGIE_CUR_LANG=null!=cookie_value?cookie_value:GOOGIE_DEFAULT_LANG;this.img_dir=img_dir;this.server_url=server_url;this.lang_to_word=this.org_lang_to_word={da:"Dansk",de:"Deutsch",
en:"English",es:"Espa&#241;ol",fr:"Fran&#231;ais",it:"Italiano",nl:"Nederlands",pl:"Polski",pt:"Portugu&#234;s",fi:"Suomi",sv:"Svenska"};this.langlist_codes=cookie_value=JAM.call(AJS.keys,AJS,[this.lang_to_word]);this.show_change_lang_pic=!0;this.change_lang_pic_placement="left";this.report_state_change=!0;this.el_scroll_top=this.ta_scroll_top=0;this.lang_chck_spell="Check spelling";this.lang_revert="Revert to";this.lang_close="Close";this.lang_rsm_edt="Resume editing";this.lang_no_error_found="No spelling errors found";
this.lang_no_suggestions="No suggestions";this.report_ta_not_found=this.edit_layer_dbl_click=this.use_close_btn=this.decoration=this.show_spell_img=!0;this.custom_no_spelling_error=this.custom_ajax_error=null;this.custom_menu_builder=[];this.custom_item_evaulator=null;this.extra_menu_items=[];this.custom_spellcheck_starter=null;this.main_controller=!0;this.all_errors_fixed_observer=this.show_menu_observer=this.spelling_state_observer=this.lang_state_observer=null;this.use_focus=!1;this.focus_link_b=
this.focus_link_t=null;this.cnt_errors_fixed=this.cnt_errors=0;JAM.call(AJS.AEV,AJS,[document,"click",JAM.call(AJS.$b,AJS,[fn,this])])}function setCookie(value,expires){var path,domain,secure,name="language",name=name+"="+escape(value),v1359;v1359=expires?"; expires="+expires.toGMTString():"";name+=v1359;path=path?"; path="+path:"";path=name+path;domain=domain?"; domain="+domain:"";domain=path+domain;secure=secure?"; secure":"";secure=domain+secure;document.cookie=secure}
function getCookie(){var name="language",dc=document.cookie,name=name+"=",begin=dc.indexOf("; "+name);if(-1==begin){if(begin=dc.indexOf(name),0!=begin)return null}else begin+=2;var end=document.cookie.indexOf(";",begin);-1==end&&(end=dc.length);return unescape(dc.substring(begin+name.length,end))}
if(!window.AJS){var AJS={BASE_URL:"",ajaxErrorHandler:null,getQueryArgument:v0,_agent:navigator.userAgent.toLowerCase(),_agent_version:navigator.productSub,isIe:v1,isIe8:v2,isSafari:v3,isOpera:v4,isMozilla:v5,isMac:v6,isCamino:v7,createArray:v8,forceArray:v9,join:v11,isIn:v12,getIndex:v13,getFirst:v14,getLast:v15,getRandom:v16,update:v17,flattenList:v19,flattenElmArguments:v20,map:v21,rmap:v22,filter:v24,partial:v26,getElement:v27,getElements:v28,getElementsByTagAndClassName:v29,nodeName:v30,_nodeWalk:v34,
getParentBytc:v36,getChildBytc:v37,hasParent:v38,getPreviousSiblingBytc:v40,getNextSiblingBytc:v42,getBody:v43,getFormElement:v46,getSelectValue:v47,documentInsert:v48,appendChildNodes:v50,appendToTop:v51,replaceChildNodes:v52,insertAfter:v53,insertBefore:v54,swapDOM:v55,removeElement:v57,createDOM:v58,_createDomShortcuts:v61,setHTML:v63,setVisibility:v64,showElement:v65,hideElement:v66,isElementHidden:v67,isElementShown:v68,setStyle:v72,__cssDim:v73,setWidth:v74,setHeight:v75,setLeft:v76,setRight:v77,
setTop:v78,setClass:v80,addClass:v82,hasClass:v83,removeClass:v85,setOpacity:v86,HTML2DOM:v87,preloadImages:v90,RND:v91,getXMLHttpRequest:v97,getRequest:v98,serializeJSON:v99,loadJSON:v100,evalTxt:v101,evalScriptTags:v102,encodeArguments:v103,_reprString:v104,_reprDate:v105,getMousePos:v106,getScrollTop:v107,absolutePosition:v108,getWindowSize:v109,isOverlapping:v110,getEventElm:v111,setEventKey:v112,onEvent:v114,ready_bound:!1,is_ready:!1,bindReady:v118,ready_list:[],ready:v120,_f_guid:0,_wipe_guid:0,
myaddEventListener:v123,handleEvent:v125,removeEventListener:v127,bind:v128,bindMethods:v129,preventDefault:v130,_listenOnce:v131,_getRealScope:v133,_reccruing_tos:{},setSingleTimeout:v134,keys:v135,values:v136,urlencode:v137,urldecode:v138,isDefined:v139,isArray:v140,isString:v141,isNumber:v142,isObject:v143,isFunction:v144,isDict:v145,exportToGlobalScope:v146,log:v147,withScope:v148,strip:v149,trim_if_needed:v150};AJS.Class=v151;AJS.Class.prototype={extend:v152,implement:v153,_parentize:v155};AJS.$=
AJS.getElement;AJS.$$=AJS.getElements;AJS.$f=AJS.getFormElement;AJS.$b=AJS.bind;AJS.$p=AJS.partial;AJS.$FA=AJS.forceArray;AJS.$A=AJS.createArray;AJS.DI=AJS.documentInsert;AJS.ACN=AJS.appendChildNodes;AJS.RCN=AJS.replaceChildNodes;AJS.AEV=AJS.myaddEventListener;AJS.REV=AJS.removeEventListener;AJS.$bytc=AJS.getElementsByTagAndClassName;AJS.$AP=AJS.absolutePosition;AJS.loadJSONDoc=AJS.loadJSON;AJS.queryArguments=AJS.encodeArguments;AJS.$gp=AJS.getParentBytc;AJS.$gc=AJS.getChildBytc;AJS.$sv=AJS.setVisibility;
AJS.generalErrorback=null;AJS.generalCallback=null;AJSDeferred=v156;AJSDeferred.prototype={excCallbackSeq:v157,callback:v158,errback:v159,addErrback:v160,addCallback:v161,abort:v162,addCallbacks:v163,_onreadystatechange:v164,sendReq:v165};AJS._createDomShortcuts()}script_loaded=!0;AJS.exportToGlobalScope();AJS.bindReady();var GOOGIE_CUR_LANG=null,GOOGIE_DEFAULT_LANG="en";GoogieSpell.prototype.decorateTextarea=v166;GoogieSpell.prototype.setSpellContainer=v167;GoogieSpell.prototype.setLanguages=v168;
GoogieSpell.prototype.setForceWidthHeight=v169;GoogieSpell.prototype.setDecoration=v170;GoogieSpell.prototype.dontUseCloseButtons=v171;GoogieSpell.prototype.appendNewMenuItem=v172;GoogieSpell.prototype.appendCustomMenuBuilder=v173;GoogieSpell.prototype.setFocus=v174;GoogieSpell.prototype.getValue=v175;GoogieSpell.prototype.setValue=v176;GoogieSpell.prototype.setStateChanged=v177;GoogieSpell.prototype.setReportStateChange=v178;GoogieSpell.prototype.getGoogleUrl=v179;GoogieSpell.escapeSepcial=v180;
GoogieSpell.createXMLReq=v181;GoogieSpell.prototype.spellCheck=v182;GoogieSpell.prototype.parseResult=v183;GoogieSpell.prototype.errorFixed=v184;GoogieSpell.prototype.errorFound=v185;GoogieSpell.prototype.createErrorWindow=v186;GoogieSpell.prototype.isErrorWindowShown=v187;GoogieSpell.prototype.hideErrorWindow=v188;GoogieSpell.prototype.updateOrginalText=v189;GoogieSpell.prototype.saveOldValue=v190;GoogieSpell.prototype.createListSeparator=v191;GoogieSpell.prototype.correctError=v192;
GoogieSpell.prototype.showErrorWindow=v198;GoogieSpell.prototype.createEditLayer=v201;GoogieSpell.prototype.resumeEditing=v202;GoogieSpell.prototype.createErrorLink=v203;GoogieSpell.createPart=v204;GoogieSpell.prototype.showErrorsInIframe=v206;GoogieSpell.prototype.createLangWindow=v210;GoogieSpell.prototype.setCurrentLanguage=v211;GoogieSpell.prototype.isLangWindowShown=v212;GoogieSpell.prototype.hideLangWindow=v213;GoogieSpell.prototype.deHighlightCurSel=v214;
GoogieSpell.prototype.highlightCurSel=v215;GoogieSpell.prototype.showLangWindow=v216;GoogieSpell.prototype.createChangeLangPic=v217;GoogieSpell.prototype.createSpellDiv=v218;GoogieSpell.prototype.flashNoSpellingErrorState=v220;GoogieSpell.prototype.resumeEditingState=v222;GoogieSpell.prototype.checkSpellingState=v223;GoogieSpell.item_onmouseover=v224;GoogieSpell.item_onmouseout=v225;GoogieSpell.prototype.createCloseButton=v226;GoogieSpell.prototype.createButton=v227;
GoogieSpell.prototype.removeIndicator=v228;GoogieSpell.prototype.appendIndicator=v229;GoogieSpell.prototype.createFocusLink=v230;var x=document.cookie,googie1=new GoogieSpell("./","./spell-check/spell-check.php?lang=");JAM.call(googie1.decorateTextarea,googie1,["ta1"])

JAM.stopProfile('load');
