
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" "}function v3(){try{JAM.startProfile('compute');colorAlignCons();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){var v7=document.main_form.main_submit;JAM.call(v7.focus,v7,[],JAM.policy.p9)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p9)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v11=i<arrayOfTitles.length;v11;){v11=arrayOfTitles[i];v11=-1==JAM.call(v11.search,v11,[/\S/],JAM.policy.p9);v11||(v11=arrayOfSequences[i],(v11=-1==JAM.call(v11.search,v11,[/\S/],JAM.policy.p9))||(v11=arrayOfSequences[i].length!=lengthOfAlign));if(v11)return alert("There is a problem with the alignment format."),
!1;i+=1;v11=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v350=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p9);v350||(v350=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p9),v350||(v350=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p9),v350||(v350=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p9))||(v350=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p9))));return v350?(alert("The codon table has been entered incorrectly."),!1):
!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p9)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v16=z<arrayOfPatterns.length;v16;){v16=arrayOfPatterns[z];if(-1==JAM.call(v16.search,v16,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v16=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v16=0,v25=v16<arrayOfPatterns.length;v25;){var v25=z,v20=v16,v714=arrayOfPatterns[v16],v714=JAM.call(v714.match,v714,[/\/.+\//],JAM.policy.p9)+"gi",v714=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v714+" }"):JAM.call(eval,null,[v714]);v25[v20]=v714;v25=codon;v20=v16;v714=arrayOfPatterns[v16];v714=JAM.call(v714.match,v714,[/=[a-zA-Z\*]/],JAM.policy.p9);v714=JAM.call(v714.toString,
v714,[],JAM.policy.p9);v25[v20]=v714;v25=codon;v20=v16;v714=codon[v16];v714=JAM.call(v714.replace,v714,[/=/g,""],JAM.policy.p9);v25[v20]=v714;v16+=1;v25=v16<arrayOfPatterns.length}arrayOfPatterns=0;for(v16=arrayOfPatterns<=testSequence.length-3;v16;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p9);v16=0;for(v25=v16<z.length;v25;){if(-1!=JAM.call(codon.search,codon,[z[v16]],JAM.policy.p9)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v16+=1;v25=v16<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v16=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v34=z<arrayOfPatterns.length;v34;){v34=arrayOfPatterns[z];if(-1!=JAM.call(v34.search,v34,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p9))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v34=z<arrayOfPatterns.length}z=0;for(v34=z<arrayOfPatterns.length;v34;){for(var v34=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v37=j<arrayOfPatterns.length;v37;){v37=arrayOfPatterns[j];if(-1!=JAM.call(v37.search,v37,[v34],JAM.policy.p9))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v37=j<arrayOfPatterns.length}z+=1;v34=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v41=z<arrayOfPatterns.length;v41;){v41=arrayOfPatterns[z];if(-1==JAM.call(v41.search,v41,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p9)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v41=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v715=getSequenceFromFasta(text);return JAM.call(v715.replace,v715,[/[^A-Za-z]/g,""],JAM.policy.p9).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/2/g,"R"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/M/g,"2"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/B/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p9);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p9);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p9);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p9)}
function closeForm(){var v46=outputWindow.document;JAM.call(v46.write,v46,["</form>"],JAM.policy.p9);return!0}function closePre(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</div>"],JAM.policy.p9);v47=outputWindow.document;JAM.call(v47.write,v47,["</pre>\n"],JAM.policy.p9)}function closeTextArea(){var v49=outputWindow.document;JAM.call(v49.write,v49,["</textarea>"],JAM.policy.p9);return!0}
function closeWindow(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</body>\n</html>\n"],JAM.policy.p9);outputWindow.status="Done.";v50=outputWindow.document;JAM.call(v50.close,v50,[],JAM.policy.p9)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p9);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p9);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p9)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v54=i<alignArray.length;v54;){v54=alignArray[i];if(-1==JAM.call(v54.search,v54,[/[^\s]+\s/],JAM.policy.p9))return alert("There is a problem with the alignment format."),!1;i+=1;v54=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p9)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p9);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p9);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p9)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9))for(var v56=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);v56;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p9),v56=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p9);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v74=j<arrayOfPatterns.length;v74;){var v74=geneticCodeMatchExp,v73=j,v716=arrayOfPatterns[j],v716=JAM.call(v716.match,v716,[/\/.+\//],JAM.policy.p9)+"gi",v716=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v716+" }"):JAM.call(eval,null,[v716]);v74[v73]=v716;j+=1;v74=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v80=j<arrayOfPatterns.length;v80;){var v80=geneticCodeMatchResult,v77=j,v613=arrayOfPatterns[j],v613=JAM.call(v613.match,v613,[/=[a-zA-Z\*]/],JAM.policy.p9),v613=JAM.call(v613.toString,v613,[],JAM.policy.p9);v80[v77]=v613;v80=geneticCodeMatchResult;v77=j;v613=geneticCodeMatchResult[j];v613=JAM.call(v613.replace,v613,[/=/g,""],JAM.policy.p9);v80[v77]=v613;j+=1;v80=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p9)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p9)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p9)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p9)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p9),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p10)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p9)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p9),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p9),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p9));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p9);v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p9),v438||(v438=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p9))||(v438=
-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p9))))))))));return v438?!1:!0}function openForm(){var v106=outputWindow.document;JAM.call(v106.write,v106,['<form action="">\n'],JAM.policy.p9);return!0}function openPre(){var v107=outputWindow.document;JAM.call(v107.write,v107,["<pre>"],JAM.policy.p9);v107=outputWindow.document;JAM.call(v107.write,v107,['<div class="pre">'],JAM.policy.p9)}
function openTextArea(){var v109=outputWindow.document;JAM.call(v109.write,v109,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p9);return!0}function openWindow(title){_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v110=outputWindow.document;JAM.call(v110.write,v110,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p9)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title,!0)}
function _openWindowAlign(title,isBackground){outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p10);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9);var v118=outputWindow.document;JAM.call(v118.write,v118,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p9);isBackground?(v118=outputWindow.document,JAM.call(v118.write,v118,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p9)):(v118=outputWindow.document,JAM.call(v118.write,v118,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p9));v118=outputWindow.document;JAM.call(v118.write,v118,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p9);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p9)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p9)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p9)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p9)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p9)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p9)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p9)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p9)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p9)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p9),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p9),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p10));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p9);for(var j=theNumber.length,v127=j<lengthOfColumn;v127;)tempString+=" ",j+=1,v127=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p9);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p9))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p9);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p9)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p9)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v453=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v453||(v453=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v453||(v453=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v453=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v453?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p9))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p9)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p9)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v458=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v458||(v458=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v458||(v458=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v458=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v458?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v459=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p9);v459||(v459=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p9),v459||(v459=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p9))||(v459=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p9)));return v459?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v461=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p9);v461||(v461=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p9),v461||(v461=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p9))||(v461=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p9)));return v461?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p9)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v155=startBase<stopBase;v155;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v155=1,v152=v155<=basePerLine/groupSize;v152;){for(v152=k<groupSize;v152;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v152=k<groupSize;startBase+=groupSize;k=0;lineOfText+=
sepChar;v155+=1;v152=v155<=basePerLine/groupSize}v155=outputWindow.document;JAM.call(v155.write,v155,[lineOfText+"\n"],JAM.policy.p9);lineOfText="";v155=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v466=0>adjustment;v466&&(v466=0<=adjusted);v466&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v165=j<=basePerLine/groupSize;v165;){for(v165=k<groupSize;v165&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v165=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v165=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p9),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p9),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p9)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v198=j<=basePerLine/groupSize;v198;){for(v198=k<groupSize;v198&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p9),k+=1,v198=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v198=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p9)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p9)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p9),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p9));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v483=sequence.length<=firstIndexToMutate;v483||(v483=0>lastIndexToMutate)||(v483=lastIndexToMutate<=firstIndexToMutate);v483&&(numMut=0);v483=0;for(randNum=v483<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*randNum],JAM.policy.p9);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p9);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p9)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p9)}v483+=1;randNum=v483<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p9);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*components.length],JAM.policy.p9),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p9),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p9);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p9)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p9),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p9);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p9)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p9);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p9);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p9));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v502=matchPosition>=lowerLimit;v502&&(v502=matchPosition<upperLimit);v502&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p9)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p9)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p9));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p9);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p9);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p9)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p9);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v253=outputWindow.document;JAM.call(v253.write,v253,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p9);v253=outputWindow.document;JAM.call(v253.write,v253,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p9);for(var v253=0,v264=v253<arrayOfItems.length;v264;){var v264=0,v511=arrayOfItems[v253],v511=
JAM.call(v511.match,v511,[/\/[^\/]+\//],JAM.policy.p9)+"gi",v511=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v511+" }"):JAM.call(eval,null,[v511]);-1!=JAM.call(sequence.search,sequence,[v511],JAM.policy.p9)&&(v264=JAM.call(sequence.match,sequence,[v511],JAM.policy.p9).length);var v511=0,v657=originalLength+1,v800=arrayOfItems[v253];0<v657-parseFloat(JAM.call(v800.match,v800,[/\d+/],JAM.policy.p9))&&(v511=100*v264,v657=originalLength+1,v800=arrayOfItems[v253],v511/=v657-parseFloat(JAM.call(v800.match,
v800,[/\d+/],JAM.policy.p9)));v657=outputWindow.document;v800=arrayOfItems[v253];v800=JAM.call(v800.match,v800,[/\([^\(]+\)\b/],JAM.policy.p9);v800=JAM.call(v800.toString,v800,[],JAM.policy.p9);JAM.call(v657.write,v657,["<tr><td>"+JAM.call(v800.replace,v800,[/\(|\)/g,""],JAM.policy.p9)+"</td><td>"+v264+"</td><td>"+JAM.call(v511.toFixed,v511,[2],JAM.policy.p9)+"</td></tr>\n"],JAM.policy.p9);v253+=1;v264=v253<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,originalLength,
["</tbody></table>\n"],JAM.policy.p9);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p9)*tempChar],JAM.policy.p9),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p9),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p9),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p9),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p9),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p9);return!0}
function colorAlignCons(){var theDocument=document,maxInput=2E4;if(!1!=testScript()){var theAlignment="",theAlignment=[],theAlignment="",theAlignment=[],titleArray=[],sequenceArray=[],longestTitle;(theAlignment=!1==checkFormElement(theDocument.forms[0].elements[0]))||(theAlignment=!1==checkTextLength(theDocument.forms[0].elements[0].value,maxInput));if(!theAlignment&&(theAlignment="X"+theDocument.forms[0].elements[0].value,theAlignment=JAM.call(theAlignment.split,theAlignment,[/[>%#]/],JAM.policy.p9),
!1!=earlyCheckAlign(theAlignment))){for(var maxInput=1,v293=maxInput<theAlignment.length;v293;){var v293=titleArray,v280=maxInput-1,v527=theAlignment[maxInput],v527=JAM.call(v527.match,v527,[/[^\f\n\r]+[\f\n\r]/],JAM.policy.p9);v293[v280]=v527;v293=titleArray;v280=maxInput-1;v527=titleArray[maxInput-1];v527=filterFastaTitle(JAM.call(v527.toString,v527,[],JAM.policy.p9));v527=JAM.call(v527.replace,v527,[/[\f\n\r]/g,""],JAM.policy.p9);v293[v280]=v527;v293=titleArray;v280=maxInput-1;v527=titleArray[maxInput-
1];v527=JAM.call(v527.substring,v527,[0,20],JAM.policy.p9);v293[v280]=v527;1==maxInput?longestTitle=titleArray[maxInput-1].length:titleArray[maxInput-1].length>longestTitle&&(longestTitle=titleArray[maxInput-1].length);v293=sequenceArray;v280=maxInput-1;v527=theAlignment[maxInput];v527=JAM.call(v527.replace,v527,[/[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p9);v293[v280]=v527;v293=sequenceArray;v280=maxInput-1;v527=filterAlignSeq(sequenceArray[maxInput-1]);v293[v280]=v527;maxInput+=1;v293=maxInput<theAlignment.length}theAlignment=
"                    ";maxInput=0;for(v293=maxInput<titleArray.length;v293;)titleArray[maxInput].length<longestTitle&&(titleArray[maxInput]+=JAM.call(theAlignment.substring,theAlignment,[0,longestTitle-titleArray[maxInput].length],JAM.policy.p9)),maxInput+=1,v293=maxInput<titleArray.length;!1!=checkAlign(titleArray,sequenceArray)&&(maxInput=theDocument.forms[0].elements[7].value,maxInput=JAM.call(maxInput.replace,maxInput,[/\s/g,""],JAM.policy.p9),theAlignment=JAM.call(maxInput.toUpperCase,maxInput,
[],JAM.policy.p9),theAlignment=JAM.call(theAlignment.split,theAlignment,[/,/],JAM.policy.p9),!1!=checkGroupInput(theAlignment)&&(maxInput="background"==theDocument.forms[0].elements[6].options[theDocument.forms[0].elements[6].selectedIndex].value?!0:!1,_openWindowAlign("Color Align Conservation",maxInput),openPre(),colorAlign(titleArray,sequenceArray,theDocument.forms[0].elements[4].options[theDocument.forms[0].elements[4].selectedIndex].value,theDocument.forms[0].elements[5].options[theDocument.forms[0].elements[5].selectedIndex].value,
theAlignment,theDocument.forms[0].elements[8].value,longestTitle),closePre(),closeWindow()))}}}
function colorAlign(arrayOfTitles,arrayOfSequences,basePerLine,consensus,arrayOfGroups,definedStarts,longestTitle){longestTitle=Array(arrayOfSequences.length);-1==JAM.call(definedStarts.search,definedStarts,[/\S/],JAM.policy.p9)&&(definedStarts="0,0");var definedStartsArray=JAM.call(definedStarts.split,definedStarts,[/,/],JAM.policy.p9);definedStarts=0;for(var v311=definedStarts<longestTitle.length;v311;){if(definedStarts>=definedStartsArray.length)longestTitle[definedStarts]=0;else if(v311=definedStartsArray[definedStarts],
-1!=JAM.call(v311.search,v311,[/\d/],JAM.policy.p9)){var v311=longestTitle,v308=definedStarts,v680=definedStartsArray[definedStarts],v680=parseInt(JAM.call(v680.replace,v680,[/[^\d\-]/g,""],JAM.policy.p9));v311[v308]=v680}else alert("An incorrect starting position was encountered. It was set to 0."),JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p9),longestTitle[definedStarts]=0;definedStarts+=1;v311=definedStarts<longestTitle.length}definedStartsArray=0;consensus=parseInt(consensus)/100;
basePerLine=parseInt(basePerLine);v308=0;v311=Array(basePerLine);definedStarts=0;for(v680=definedStarts<v311.length;v680;){var v680=v311,v314=definedStarts,v928=Array(arrayOfSequences.length);v680[v314]=v928;definedStarts+=1;v680=definedStarts<v311.length}definedStarts=0;for(var re,result,v314="",v680=definedStartsArray<arrayOfSequences[0].length;v680;){v680=0;for(v928=v680<arrayOfSequences.length;v928;){v314=v314+arrayOfTitles[v680]+" ";for((v928=definedStarts<definedStartsArray+basePerLine)&&(v928=
definedStarts<arrayOfSequences[0].length);v928;){if(0==v680)for(v928=0,re=v928<arrayOfSequences.length;re;){re=v311[v308];result=v928;var v562=arrayOfSequences[v928],v562=JAM.call(v562.charAt,v562,[definedStarts],JAM.policy.p9);re[result]=v562;v928+=1;re=v928<arrayOfSequences.length}v928=arrayOfSequences[v680];v928="."==JAM.call(v928.charAt,v928,[definedStarts],JAM.policy.p9);v928||(v928=arrayOfSequences[v680],v928="-"==JAM.call(v928.charAt,v928,[definedStarts],JAM.policy.p9));if(v928)v314+='<span class="diff">';
else if(v928=v311[v308],v928=JAM.call(v928.join,v928,[","],JAM.policy.p9),re=arrayOfSequences[v680],re=RegExp(JAM.call(re.charAt,re,[definedStarts],JAM.policy.p9),"gi"),JAM.call(v928.match,v928,[re],JAM.policy.p9).length/arrayOfSequences.length>=consensus)v314+='<span class="ident">';else{result=1;for(var v562=0,v330=v562<arrayOfGroups.length;v330;){v330=arrayOfGroups[v562];if(-1!=JAM.call(v330.search,v330,[re],JAM.policy.p9)){re=RegExp("["+arrayOfGroups[v562]+"]","gi");result=JAM.call(v928.match,
v928,[re],JAM.policy.p9).length;break}v562+=1;v330=v562<arrayOfGroups.length}v314=result/arrayOfSequences.length>=consensus?v314+'<span class="sim">':v314+'<span class="diff">'}v928=arrayOfSequences[v680];v314=v314+JAM.call(v928.charAt,v928,[definedStarts],JAM.policy.p9)+"</span>";definedStarts+=1;v308+=1;(v928=definedStarts<definedStartsArray+basePerLine)&&(v928=definedStarts<arrayOfSequences[0].length)}v308=longestTitle;v928=v680;re=longestTitle[v680];result=arrayOfSequences[v680];definedStarts=
JAM.call(result.substring,result,[definedStartsArray,definedStarts],JAM.policy.p9);v308[v928]=re+JAM.call(definedStarts.replace,definedStarts,[/\.|\-/g,""],JAM.policy.p9).length;v314=v314+" "+longestTitle[v680]+"\n";definedStarts=outputWindow.document;JAM.call(definedStarts.write,definedStarts,[v314],JAM.policy.p9);v314="";definedStarts=definedStartsArray;v308=0;v680+=1;v928=v680<arrayOfSequences.length}definedStarts=definedStartsArray+=basePerLine;v680=outputWindow.document;JAM.call(v680.write,v680,
["\n"],JAM.policy.p9);v680=definedStartsArray<arrayOfSequences[0].length}}JAM.set(document,"onload",v2);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p9),"onclick",v3);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p9),"onclick",v4);

JAM.stopProfile('load');
