
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" ";document.forms[0].elements[4].value=" "}function v3(){try{JAM.startProfile('compute');fuzzySearchDna();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){document.main_form.main_submit.focus()}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=sequence.replace(/(.{60})/g,v0)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v12=i<arrayOfTitles.length;v12;){introspect(JAM.policy.p5)v12=arrayOfTitles[i];v12=-1==JAM.call(v12.search,v12,[/\S/]);if(!v12){introspect(JAM.policy.p5)v12=arrayOfSequences[i];v12=-1==JAM.call(v12.search,v12,[/\S/]);if(!v12){introspect(JAM.policy.p5)v12=arrayOfSequences[i];v12=v12.length!=
lengthOfAlign}}if(v12)return alert("There is a problem with the alignment format."),!1;i+=1;v12=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v423=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/]);v423||(v423=-1==JAM.call(codonTable.search,codonTable,[/Codon/]),v423||(v423=-1==JAM.call(codonTable.search,codonTable,[/Number/]),v423||(v423=-1==JAM.call(codonTable.search,codonTable,[/\/1000/]))||(v423=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./]))));return v423?(alert("The codon table has been entered incorrectly."),!1):!0}
function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/])?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v17=z<arrayOfPatterns.length;v17;){introspect(JAM.policy.p5)v17=arrayOfPatterns[z];if(-1==JAM.call(v17.search,v17,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;introspect(JAM.policy.p5)v17=arrayOfPatterns[z];if(!1==moreExpressionCheck(v17))return alert("Genetic code error: one or more patterns have been entered incorrectly."),!1;z+=1;v17=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v17=0,v26=v17<arrayOfPatterns.length;v26;){var v26=z,v21=v17;introspect(JAM.policy.p5)var v945=arrayOfPatterns[v17];v945=JAM.call(v945.match,v945,[/\/.+\//])+"gi";v945=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+
v945+" }"):JAM.call(eval,null,[v945]);v26[v21]=v945;v26=codon;v21=v17;introspect(JAM.policy.p5)v945=arrayOfPatterns[v17];v945=JAM.call(v945.match,v945,[/=[a-zA-Z\*]/]).toString();v26[v21]=v945;v26=codon;v21=v17;introspect(JAM.policy.p5)v945=codon[v17];v945=v945.replace(/=/g,"");v26[v21]=v945;v17+=1;v26=v17<arrayOfPatterns.length}arrayOfPatterns=0;for(v17=arrayOfPatterns<=testSequence.length-3;v17;){codon=testSequence.substring(arrayOfPatterns,arrayOfPatterns+3);v17=0;for(v26=v17<z.length;v26;){introspect(JAM.policy.p5)v26=
z[v17];if(-1!=JAM.call(codon.search,codon,[v26])){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+codon+"."),!1;oneMatch=!0}v17+=1;v26=v17<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v17=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v35=z<arrayOfPatterns.length;v35;){introspect(JAM.policy.p5)v35=arrayOfPatterns[z];if(-1!=JAM.call(v35.search,v35,[/[^acdefghiklmnpqrstvwyz]/i]))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v35=z<arrayOfPatterns.length}z=0;for(v35=z<arrayOfPatterns.length;v35;){introspect(JAM.policy.p5)v35=arrayOfPatterns[z];for(var v35=RegExp("["+v35+"]","gi"),j=z+1,v38=j<arrayOfPatterns.length;v38;){introspect(JAM.policy.p5)v38=arrayOfPatterns[j];
if(-1!=JAM.call(v38.search,v38,[v35]))return alert("The same amino acid is in more than one similarity group."),!1;j+=1;v38=j<arrayOfPatterns.length}z+=1;v35=z<arrayOfPatterns.length}return!0}
function checkRestPatterns(arrayOfPatterns){for(var z=0,v42=z<arrayOfPatterns.length;v42;){introspect(JAM.policy.p5)v42=arrayOfPatterns[z];if(-1==JAM.call(v42.search,v42,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i]))return alert("One or more patterns have been entered incorrectly."),!1;introspect(JAM.policy.p5)v42=arrayOfPatterns[z];if(!1==moreExpressionCheck(v42))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v42=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){return getSequenceFromFasta(text).replace(/[^A-Za-z]/g,"").length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=dnaSequence.replace(/g/g,"1");dnaSequence=dnaSequence.replace(/c/g,"2");dnaSequence=dnaSequence.replace(/1/g,"c");dnaSequence=dnaSequence.replace(/2/g,"g");dnaSequence=dnaSequence.replace(/G/g,"1");dnaSequence=dnaSequence.replace(/C/g,"2");dnaSequence=dnaSequence.replace(/1/g,"C");dnaSequence=dnaSequence.replace(/2/g,"G");dnaSequence=dnaSequence.replace(/a/g,"1");dnaSequence=dnaSequence.replace(/t/g,"2");dnaSequence=dnaSequence.replace(/1/g,"t");dnaSequence=
dnaSequence.replace(/2/g,"a");dnaSequence=dnaSequence.replace(/A/g,"1");dnaSequence=dnaSequence.replace(/T/g,"2");dnaSequence=dnaSequence.replace(/1/g,"T");dnaSequence=dnaSequence.replace(/2/g,"A");dnaSequence=dnaSequence.replace(/u/g,"a");dnaSequence=dnaSequence.replace(/U/g,"A");dnaSequence=dnaSequence.replace(/r/g,"1");dnaSequence=dnaSequence.replace(/y/g,"2");dnaSequence=dnaSequence.replace(/1/g,"y");dnaSequence=dnaSequence.replace(/2/g,"r");dnaSequence=dnaSequence.replace(/R/g,"1");dnaSequence=
dnaSequence.replace(/Y/g,"2");dnaSequence=dnaSequence.replace(/1/g,"Y");dnaSequence=dnaSequence.replace(/2/g,"R");dnaSequence=dnaSequence.replace(/k/g,"1");dnaSequence=dnaSequence.replace(/m/g,"2");dnaSequence=dnaSequence.replace(/1/g,"m");dnaSequence=dnaSequence.replace(/2/g,"k");dnaSequence=dnaSequence.replace(/K/g,"1");dnaSequence=dnaSequence.replace(/M/g,"2");dnaSequence=dnaSequence.replace(/1/g,"M");dnaSequence=dnaSequence.replace(/2/g,"K");dnaSequence=dnaSequence.replace(/b/g,"1");dnaSequence=
dnaSequence.replace(/v/g,"2");dnaSequence=dnaSequence.replace(/1/g,"v");dnaSequence=dnaSequence.replace(/2/g,"b");dnaSequence=dnaSequence.replace(/B/g,"1");dnaSequence=dnaSequence.replace(/V/g,"2");dnaSequence=dnaSequence.replace(/1/g,"V");dnaSequence=dnaSequence.replace(/2/g,"B");dnaSequence=dnaSequence.replace(/d/g,"1");dnaSequence=dnaSequence.replace(/h/g,"2");dnaSequence=dnaSequence.replace(/1/g,"h");dnaSequence=dnaSequence.replace(/2/g,"d");dnaSequence=dnaSequence.replace(/D/g,"1");dnaSequence=
dnaSequence.replace(/H/g,"2");dnaSequence=dnaSequence.replace(/1/g,"H");return dnaSequence=dnaSequence.replace(/2/g,"D")}function closeForm(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</form>"]);return!0}function closePre(){var v48=outputWindow.document;JAM.call(v48.write,v48,["</div>"]);v48=outputWindow.document;JAM.call(v48.write,v48,["</pre>\n"])}function closeTextArea(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</textarea>"]);return!0}
function closeWindow(){var v51=outputWindow.document;JAM.call(v51.write,v51,["</body>\n</html>\n"]);outputWindow.status="Done.";outputWindow.document.close()}
function convertDegenerates(sequence){sequence=sequence.toLowerCase();sequence=sequence.replace(/t/g,"[TU]");sequence=sequence.replace(/r/g,"[AGR]");sequence=sequence.replace(/y/g,"[CTUY]");sequence=sequence.replace(/s/g,"[GCS]");sequence=sequence.replace(/w/g,"[ATUW]");sequence=sequence.replace(/k/g,"[GTUK]");sequence=sequence.replace(/m/g,"[ACM]");sequence=sequence.replace(/b/g,"[CGTUBSKY]");sequence=sequence.replace(/d/g,"[AGTUDRKW]");sequence=sequence.replace(/h/g,"[ACTUHMYW]");sequence=sequence.replace(/v/g,
"[ACGVSMR]");return sequence=sequence.replace(/n/g,"[ACGTURYSWKMBDHVN]")}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v55=i<alignArray.length;v55;){introspect(JAM.policy.p5)v55=alignArray[i];if(-1==JAM.call(v55.search,v55,[/[^\s]+\s/]))return alert("There is a problem with the alignment format."),!1;i+=1;v55=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=alignSeq.replace(/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,"")}function filterFastaTitle(sequenceTitle){sequenceTitle=sequenceTitle.replace(/\s{2,}/g," ");sequenceTitle=sequenceTitle.replace(/^\s*/g,"");sequenceTitle=sequenceTitle.replace(/[\f\n\r\t]+$/g,"\n");return sequenceTitle.replace(/[\<\>]\n/gi,"")}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/]))for(var v57=matchArray=re.exec(sequenceData);v57;)arrayOfFasta.push(matchArray[0]),v57=matchArray=re.exec(sequenceData);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+sequence.substring(0,10)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+sequenceOne.substring(0,10)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,
fastaSequenceTitleTwo,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+sequenceTwo.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v75=j<arrayOfPatterns.length;v75;){var v75=geneticCodeMatchExp,v74=j;introspect(JAM.policy.p5)var v947=arrayOfPatterns[j];v947=JAM.call(v947.match,v947,[/\/.+\//])+"gi";v947=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v947+" }"):JAM.call(eval,null,[v947]);v75[v74]=v947;j+=1;v75=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v81=j<arrayOfPatterns.length;v81;){var v81=geneticCodeMatchResult,v78=j;introspect(JAM.policy.p5)var v756=arrayOfPatterns[j];v756=JAM.call(v756.match,v756,[/=[a-zA-Z\*]/]).toString();v81[v78]=v756;v81=geneticCodeMatchResult;v78=j;introspect(JAM.policy.p5)v756=geneticCodeMatchResult[j];v756=v756.replace(/=/g,"");v81[v78]=v756;j+=1;v81=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+sequence.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/])&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+sequence.substring(0,10)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+sequenceOne.substring(0,10)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,
fastaSequenceTitleTwo,[/[^\s]/])&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+sequenceTwo.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=Math.floor(Math.random()*components.length),tempNum=components[tempNum],sequenceArray.push(tempNum),j+=1,tempNum=j<lengthOut;return sequenceArray.join("")}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/])&&(sequenceRecord=sequenceRecord.replace(/\>[^\f\n\r]+[\f\n\r]/,""));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/])&&(fastaTitle=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""]).toString(),fastaTitle=fastaTitle.replace(/\>|[\f\n\r]/g,""),fastaTitle=fastaTitle.replace(/\s{2,}/g," "),fastaTitle=fastaTitle.replace(/[\<\>]/gi,""));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/]);v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\//]),v511||(v511=-1!=JAM.call(expressionToCheck.search,
expressionToCheck,[/\|\|/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/]),v511||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</]))||(v511=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/]))))))))));return v511?!1:!0}
function openForm(){var v107=outputWindow.document;JAM.call(v107.write,v107,['<form action="">\n']);return!0}function openPre(){var v108=outputWindow.document;JAM.call(v108.write,v108,["<pre>"]);v108=outputWindow.document;JAM.call(v108.write,v108,['<div class="pre">'])}function openTextArea(){var v110=outputWindow.document;JAM.call(v110.write,v110,['<br /><textarea rows="6" cols="61">\n']);return!0}function openWindow(){var title="Fuzzy Search DNA";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(JAM.get(window,"open",JAM.policy.p1),window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"]);outputWindow.focus();var v111=outputWindow.document;JAM.call(v111.write,v111,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n']);
isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'])):
(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n']));
isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"]);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(JAM.get(window,"open",JAM.policy.p1),window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"]);outputWindow.focus();var v119=outputWindow.document;JAM.call(v119.write,v119,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n']);
isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'])):
(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n']));
isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"]);outputWindow.status="Please Wait."}function removeFormatting(sequence){return sequence.replace(/[\d\s]/g,"")}function removeNonDna(sequence){return sequence.replace(/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,"")}function removeNonDnaStrict(sequence){return sequence.replace(/[^gatucGATUC]/g,"")}
function removeNonProtein(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,"")}function removeNonProteinStrict(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,"")}function removeNonProteinAllowDegen(sequence){return sequence.replace(/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,"")}function removeNonProteinAllowX(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,"")}
function removeWhiteSpace(text){return text.replace(/\s/g,"")}function removeNonLetters(sequence){return sequence.replace(/[^A-Z]/gi,"")}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./])&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g]),tempDnaArray=tempDnaArray.reverse(),dnaSequence=tempDnaArray.join(""));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=theNumber.toString();for(var j=theNumber.length,v128=j<lengthOfColumn;v128;)tempString+=" ",j+=1,v128=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";testArray.push(testString);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray]))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):
JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=testString.replace(/(\d)/g,v1);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),!1;testString=2489.8237;return 2489.824!=testString.toFixed(3)?(alert("Number toFixed() method not supported. See browser compatibility page."),
!1):2489.8!=testString.toPrecision(5)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/]))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v526=-1==JAM.call(emblFile.search,emblFile,[/ID/]);v526||(v526=-1==JAM.call(emblFile.search,emblFile,[/AC/]),v526||(v526=-1==JAM.call(emblFile.search,emblFile,[/DE/]))||(v526=-1==JAM.call(emblFile.search,emblFile,[/SQ/])));return v526?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/]))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i])&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i])&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v531=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/]);v531||(v531=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/]),v531||(v531=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/]))||(v531=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/])));return v531?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v532=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/]);v532||(v532=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/]),v532||(v532=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/]))||(v532=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/])));return v532?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/])?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v534=-1==JAM.call(emblFile.search,emblFile,[/ID/]);v534||(v534=-1==JAM.call(emblFile.search,emblFile,[/AC/]),v534||(v534=-1==JAM.call(emblFile.search,emblFile,[/DE/]))||(v534=-1==JAM.call(emblFile.search,emblFile,[/SQ/])));return v534?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m])?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v156=startBase<stopBase;v156;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v156=1,v153=v156<=basePerLine/groupSize;v153;){for(v153=k<groupSize;v153;)lineOfText+=text.charAt(k+startBase),k+=1,v153=k<groupSize;startBase+=groupSize;k=0;lineOfText+=sepChar;v156+=1;v153=v156<=basePerLine/
groupSize}v156=outputWindow.document;JAM.call(v156.write,v156,[lineOfText+"\n"]);lineOfText="";v156=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v539=0>adjustment;v539&&(v539=0<=adjusted);v539&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v166=j<=basePerLine/groupSize;v166;){for(v166=k<groupSize;v166&&!(startBase+k>=stopBase);)lineOfText+=text.charAt(k+startBase),k+=1,v166=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v166=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,
aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"]),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"]))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"]),
"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"]))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"]),lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[lineOfText+"\n"]),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+
"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"])));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v199=j<=basePerLine/groupSize;v199;){for(v199=k<groupSize;v199&&!(startBase+k>=stopBase);)lineOfText+=text.charAt(k+startBase),k+=1,v199=k<groupSize;lineOfText+=sepChar;startBase+=
k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v199=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"])):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"])):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"]),
aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"]));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v556=sequence.length<=firstIndexToMutate;v556||(v556=0>lastIndexToMutate)||(v556=lastIndexToMutate<=firstIndexToMutate);v556&&(numMut=0);v556=0;for(randNum=v556<numMut;randNum;){randNum=sequence.length;randNum=Math.floor(Math.random()*
randNum);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=sequence.charAt(randNum);for(needNewChar=!0;needNewChar;){componentsIndex=Math.round(Math.random()*components.length);componentsIndex==components.length&&(componentsIndex=0);introspect(JAM.policy.p5)var v562=components[componentsIndex];v562!=currentChar&&(needNewChar=!1)}currentChar=sequence.substring(0,randNum);introspect(JAM.policy.p5)needNewChar=components[componentsIndex];
sequence=currentChar+needNewChar+sequence.substring(randNum+1,sequence.length)}v556+=1;randNum=v556<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)]);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=Math.floor(Math.random()*components.length),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"]),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"]);return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=sequence.substring(0,lookAhead).length,sequence=sequence.substring(sequence.length-lookAhead,sequence.length)+sequence+sequence.substring(0,lookAhead),lowerLimit=0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,
dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n']);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n']);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";introspect(JAM.policy.p5)matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//])+"gi";matchExp=JAM.isEval(eval)?
eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);introspect(JAM.policy.p5)cutDistance=arrayOfItems[dnaConformation];cutDistance=parseFloat(JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/]).toString().replace(/\)\D*/,""));for(matchPosition=matchExp.exec(sequence);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v575=matchPosition>=lowerLimit;v575&&(v575=matchPosition<upperLimit);v575&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-
shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=matchExp.exec(sequence)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/])&&(lookAhead=lookAhead.replace(/none,\s*/,""));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';introspect(JAM.policy.p5)matchPosition=arrayOfItems[dnaConformation];JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/]).toString().replace(/\(|\)/g,"")+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"]);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"]);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v254=outputWindow.document;JAM.call(v254.write,v254,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n']);v254=outputWindow.document;JAM.call(v254.write,v254,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n']);for(var v254=0,v265=v254<arrayOfItems.length;v265;){v265=0;introspect(JAM.policy.p5)var v584=arrayOfItems[v254];v584=
JAM.call(v584.match,v584,[/\/[^\/]+\//])+"gi";v584=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v584+" }"):JAM.call(eval,null,[v584]);-1!=JAM.call(sequence.search,sequence,[v584])&&(v265=JAM.call(sequence.match,sequence,[v584]).length);var v584=0,v800=originalLength+1;introspect(JAM.policy.p5)var v1069=arrayOfItems[v254];if(0<v800-parseFloat(JAM.call(v1069.match,v1069,[/\d+/]))){v584=100*v265;v800=originalLength+1;introspect(JAM.policy.p5)v1069=arrayOfItems[v254];v584/=v800-parseFloat(JAM.call(v1069.match,
v1069,[/\d+/]))}v800=outputWindow.document;introspect(JAM.policy.p5)v1069=arrayOfItems[v254];JAM.call(v800.write,v800,["<tr><td>"+JAM.call(v1069.match,v1069,[/\([^\(]+\)\b/]).toString().replace(/\(|\)/g,"")+"</td><td>"+v265+"</td><td>"+v584.toFixed(2)+"</td></tr>\n"]);v254+=1;v265=v254<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,originalLength,["</tbody></table>\n"]);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=Math.floor(Math.random()*tempChar),tempChar=sequence.charAt(tempString2),tempSeq+=tempChar,tempChar=sequence.substring(0,tempString2),tempString2=sequence.substring(tempString2+1,sequence.length),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,
[tempSeq+"\n"]),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"]);return!0}
function fuzzySearchDna(){var theDocument=document,targetSequence="",targetTitle="",querySequence="",queryTitle="",maxTarget=2E3,maxQuery=30;if(!1!=testScript()){var v596=!1==checkFormElement(theDocument.forms[0].elements[0]);v596||(maxTarget=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxTarget),maxTarget||(maxTarget=!1==checkFormElement(theDocument.forms[0].elements[1]))||(maxTarget=!1==checkSequenceLength(theDocument.forms[0].elements[1].value,maxQuery)),v596=maxTarget);if(!v596){maxQuery=
theDocument.forms[0].elements[5].options;maxTarget=theDocument.forms[0].elements[5].selectedIndex;introspect(JAM.policy.p5)maxQuery=maxQuery[maxTarget];maxQuery=parseInt(maxQuery.value);maxTarget=theDocument.forms[0].elements[6].options;v596=theDocument.forms[0].elements[6].selectedIndex;introspect(JAM.policy.p5)maxTarget=maxTarget[v596];maxTarget=parseInt(maxTarget.value);v596=theDocument.forms[0].elements[7].options;targetSequence=theDocument.forms[0].elements[7].selectedIndex;introspect(JAM.policy.p5)v596=
v596[targetSequence];v596=parseInt(v596.value);targetSequence=theDocument.forms[0].elements[8].options;targetTitle=theDocument.forms[0].elements[8].selectedIndex;introspect(JAM.policy.p5)targetSequence=targetSequence[targetTitle];var HITS=parseInt(targetSequence.value);openWindow();openPre();targetSequence=getSequenceFromFasta(theDocument.forms[0].elements[0].value);targetSequence=removeNonDna(targetSequence);targetTitle=getTitleFromFasta(theDocument.forms[0].elements[0].value);querySequence=getSequenceFromFasta(theDocument.forms[0].elements[1].value);
querySequence=removeNonDna(querySequence);queryTitle="query";theDocument=outputWindow.document;JAM.call(theDocument.write,theDocument,[getFuzzySearchTitle(targetTitle,targetSequence,queryTitle,querySequence)]);-1!=JAM.call(targetSequence.search,targetSequence,[/./])&&(targetSequence=JAM.call(targetSequence.match,targetSequence,[/./g]));-1!=JAM.call(querySequence.search,querySequence,[/./])&&(querySequence=JAM.call(querySequence.match,querySequence,[/./g]));0==targetSequence.length?alert("The sequence contains no DNA bases."):
0==querySequence.length?alert("The query sequence contains no DNA bases."):(_fuzzySearchDna(queryTitle,querySequence,targetTitle,targetSequence,maxQuery,maxTarget,v596,HITS),closePre(),closeWindow())}}}
function _fuzzySearchDna(queryTitle,querySequence,targetTitle,targetSequence,matchScore,mismatchScore,gapPenalty,hits){var matrix=new Identity;JAM.call(matrix.setMatch,matrix,[matchScore]);JAM.call(matrix.setMismatch,matrix,[mismatchScore]);matchScore=new ScoreSet;JAM.call(matchScore.setScoreSetParam,matchScore,[matrix,gapPenalty,hits]);hits=new FuzzySearch;JAM.call(hits.initializeMatrix,hits,[querySequence,targetSequence,matchScore]);hits.search();hits=hits.getHits();if(0<hits.length)for(querySequence=
0,targetSequence=querySequence<hits.length;targetSequence;){targetSequence=outputWindow.document;gapPenalty=">"+queryTitle+" from ";introspect(JAM.policy.p5)matrix=hits[querySequence];gapPenalty=gapPenalty+matrix.startM+" to ";introspect(JAM.policy.p5)matrix=hits[querySequence];JAM.call(targetSequence.write,targetSequence,[gapPenalty+matrix.endM+"\n"]);targetSequence=outputWindow.document;introspect(JAM.policy.p5)gapPenalty=hits[querySequence];JAM.call(targetSequence.write,targetSequence,[gapPenalty.sequenceM+
"\n"]);targetSequence=outputWindow.document;gapPenalty=">"+targetTitle+" from ";introspect(JAM.policy.p5)matrix=hits[querySequence];gapPenalty=gapPenalty+matrix.startN+" to ";introspect(JAM.policy.p5)matrix=hits[querySequence];JAM.call(targetSequence.write,targetSequence,[gapPenalty+matrix.endN+"\n"]);targetSequence=outputWindow.document;introspect(JAM.policy.p5)gapPenalty=hits[querySequence];JAM.call(targetSequence.write,targetSequence,[gapPenalty.sequenceN+"\n"]);targetSequence=outputWindow.document;
introspect(JAM.policy.p5)gapPenalty=hits[querySequence];JAM.call(targetSequence.write,targetSequence,["Score: "+gapPenalty.score+"\n\n"]);querySequence+=1;targetSequence=querySequence<hits.length}else queryTitle=outputWindow.document,JAM.call(queryTitle.write,queryTitle,["No hits were obtained.\n\n"])}function getScore(r1,r2){var v304=this.scoringMatrix;return JAM.call(v304.scoringMatrix_getScore,v304,[r1,r2])}
function setScoreSetParam(scoringMatrix,gapPenalty,hits){this.scoringMatrix=scoringMatrix;this.gap=gapPenalty;this.hits=hits}function ScoreSet(){}function scoringMatrix_getScore(r1,r2){r1=r1.toLowerCase();r2=r2.toLowerCase();return r1==r2?this.match:this.mismatch}function ScoringMatrix(){}function setMismatch(mismatchScore){this.mismatch=mismatchScore}function setMatch(matchScore){this.match=matchScore}function Identity(){}function Node(){this.alreadyMatched=!1}
function initializeMatrix(sequenceOne,sequenceTwo,scoreSet){this.scoreSet=scoreSet;this.M=sequenceOne;this.N=sequenceTwo;this.score=0;this.nodes=sequenceOne=Array(this.M.length+1);sequenceOne=0;for(sequenceTwo=sequenceOne<this.nodes.length;sequenceTwo;){sequenceTwo=this.nodes;scoreSet=sequenceOne;var v1226=Array(this.N.length+1);sequenceTwo[scoreSet]=v1226;sequenceTwo=0;scoreSet=this.nodes;introspect(JAM.policy.p5)scoreSet=scoreSet[sequenceOne];for(scoreSet=sequenceTwo<scoreSet.length;scoreSet;){scoreSet=
this.nodes;introspect(JAM.policy.p5)scoreSet=scoreSet[sequenceOne];var v1226=sequenceTwo,v1227=new Node;scoreSet[v1226]=v1227;sequenceTwo+=1;scoreSet=this.nodes;introspect(JAM.policy.p5)scoreSet=scoreSet[sequenceOne];scoreSet=sequenceTwo<scoreSet.length}sequenceOne+=1;sequenceTwo=sequenceOne<this.nodes.length}this.nodes[0][0].value=0;sequenceOne=1;for(sequenceTwo=sequenceOne<this.nodes.length;sequenceTwo;){sequenceTwo=this.nodes;introspect(JAM.policy.p5)sequenceTwo=sequenceTwo[sequenceOne];sequenceTwo=
sequenceTwo[0];scoreSet=this.nodes;v1226=sequenceOne-1;introspect(JAM.policy.p5)scoreSet=scoreSet[v1226];sequenceTwo.value=scoreSet[0].value;sequenceTwo=this.nodes;introspect(JAM.policy.p5)sequenceTwo=sequenceTwo[sequenceOne];sequenceTwo[0].tracebackI=sequenceOne-1;sequenceTwo=this.nodes;introspect(JAM.policy.p5)sequenceTwo=sequenceTwo[sequenceOne];sequenceTwo[0].tracebackJ=0;sequenceOne+=1;sequenceTwo=sequenceOne<this.nodes.length}sequenceTwo=1;for(sequenceOne=sequenceTwo<this.nodes[0].length;sequenceOne;){sequenceOne=
this.nodes[0];introspect(JAM.policy.p5)sequenceOne=sequenceOne[sequenceTwo];scoreSet=this.nodes[0];v1226=sequenceTwo-1;introspect(JAM.policy.p5)scoreSet=scoreSet[v1226];sequenceOne.value=scoreSet.value;sequenceOne=this.nodes[0];introspect(JAM.policy.p5)sequenceOne=sequenceOne[sequenceTwo];sequenceOne.tracebackI=0;sequenceOne=this.nodes[0];introspect(JAM.policy.p5)sequenceOne=sequenceOne[sequenceTwo];sequenceOne.tracebackJ=sequenceTwo-1;sequenceTwo+=1;sequenceOne=sequenceTwo<this.nodes[0].length}}
function dumpMatrix(){var v322=outputWindow.document;JAM.call(v322.write,v322,["Dynamic programming matrix i="+this.nodes.length+" and j="+this.nodes[0].length]);v322=outputWindow.document;JAM.call(v322.write,v322,["\n"]);for(var v322=0,v335=v322<this.nodes.length;v335;){var v335=0,v1012=this.nodes;introspect(JAM.policy.p5)v1012=v1012[v322];for(v1012=v335<v1012.length;v1012;){v1012=this.nodes;introspect(JAM.policy.p5)v1012=v1012[v322];introspect(JAM.policy.p5)v1012=v1012[v335];var v1012=v1012.tracebackI,
v851=this.nodes;introspect(JAM.policy.p5)v851=v851[v322];introspect(JAM.policy.p5)v851=v851[v335];v851=v851.tracebackJ;void 0==v1012&&(v1012="u");void 0==v851&&(v851="u");v1012="("+v322+","+v335+")["+v1012+","+v851+"]=";v851=this.nodes;introspect(JAM.policy.p5)v851=v851[v322];introspect(JAM.policy.p5)v851=v851[v335];v1012+=v851.value;v851=outputWindow.document;JAM.call(v851.write,v851,[rightNum(v1012,"",20," ")]);v335+=1;v1012=this.nodes;introspect(JAM.policy.p5)v1012=v1012[v322];v1012=v335<v1012.length}v335=
outputWindow.document;JAM.call(v335.write,v335,["\n"]);v322+=1;v335=v322<this.nodes.length}v322=outputWindow.document;JAM.call(v322.write,v322,["\n"])}
function updateMatrix(){for(var i=1,v377=i<this.nodes.length;v377;){for(var j=1,v376=j<this.nodes[0].length;v376;){var a,b,c,v1017=this.nodes;introspect(JAM.policy.p5)var v858=v1017[i];introspect(JAM.policy.p5)var v648=v858[j];if(v648.alreadyMatched)c=b=a=0;else{var v649=i==this.nodes.length-1;v649&&(v649=j==this.nodes[0].length-1);if(v649){var v861=this.nodes,v862=i-1;introspect(JAM.policy.p5)var v650=v861[v862];introspect(JAM.policy.p5)var v337=v650[j];a=v337.value;var v863=this.nodes;introspect(JAM.policy.p5)var v651=
v863[i];var v652=j-1;introspect(JAM.policy.p5)var v338=v651[v652];b=v338.value;var v1020=this.nodes,v1021=i-1;introspect(JAM.policy.p5)var v864=v1020[v1021];var v865=j-1;introspect(JAM.policy.p5)var v653=v864[v865];var v339=v653.value,v654=this.scoreSet,v866=this.M,v867=i-1;introspect(JAM.policy.p5)var v655=v866[v867];var v868=this.N,v869=j-1;introspect(JAM.policy.p5)var v656=v868[v869];c=v339+JAM.call(v654.getScore,v654,[v655,v656])}else if(i==this.nodes.length-1){var v1023=this.nodes,v1024=i-1;
introspect(JAM.policy.p5)var v871=v1023[v1024];introspect(JAM.policy.p5)var v658=v871[j];a=v658.value-this.scoreSet.gap;var v872=this.nodes;introspect(JAM.policy.p5)var v660=v872[i];var v661=j-1;introspect(JAM.policy.p5)var v343=v660[v661];b=v343.value;var v1025=this.nodes,v1026=i-1;introspect(JAM.policy.p5)var v873=v1025[v1026];var v874=j-1;introspect(JAM.policy.p5)var v662=v873[v874];var v344=v662.value,v663=this.scoreSet,v875=this.M,v876=i-1;introspect(JAM.policy.p5)var v664=v875[v876];var v877=
this.N,v878=j-1;introspect(JAM.policy.p5)var v665=v877[v878];c=v344+JAM.call(v663.getScore,v663,[v664,v665])}else if(j==this.nodes[0].length-1){var v880=this.nodes,v881=i-1;introspect(JAM.policy.p5)var v667=v880[v881];introspect(JAM.policy.p5)var v346=v667[j];a=v346.value;var v1028=this.nodes;introspect(JAM.policy.p5)var v882=v1028[i];var v883=j-1;introspect(JAM.policy.p5)var v668=v882[v883];b=v668.value-this.scoreSet.gap;var v1029=this.nodes,v1030=i-1;introspect(JAM.policy.p5)var v884=v1029[v1030];
var v885=j-1;introspect(JAM.policy.p5)var v670=v884[v885];var v349=v670.value,v671=this.scoreSet,v886=this.M,v887=i-1;introspect(JAM.policy.p5)var v672=v886[v887];var v888=this.N,v889=j-1;introspect(JAM.policy.p5)var v673=v888[v889];c=v349+JAM.call(v671.getScore,v671,[v672,v673])}else{var v1031=this.nodes,v1032=i-1;introspect(JAM.policy.p5)var v890=v1031[v1032];introspect(JAM.policy.p5)var v674=v890[j];a=v674.value-this.scoreSet.gap;var v1033=this.nodes;introspect(JAM.policy.p5)var v891=v1033[i];
var v892=j-1;introspect(JAM.policy.p5)var v676=v891[v892];b=v676.value-this.scoreSet.gap;var v1034=this.nodes,v1035=i-1;introspect(JAM.policy.p5)var v893=v1034[v1035];var v894=j-1;introspect(JAM.policy.p5)var v678=v893[v894];var v355=v678.value,v679=this.scoreSet,v895=this.M,v896=i-1;introspect(JAM.policy.p5)var v680=v895[v896];var v897=this.N,v898=j-1;introspect(JAM.policy.p5)var v681=v897[v898];c=v355+JAM.call(v679.getScore,v679,[v680,v681])}}var v682=a>b;v682&&(v682=a>c);if(v682){var v899=this.nodes;
introspect(JAM.policy.p5)var v683=v899[i];introspect(JAM.policy.p5)var v361=v683[j];v361.value=a;var v900=this.nodes;introspect(JAM.policy.p5)var v684=v900[i];introspect(JAM.policy.p5)var v362=v684[j];v362.tracebackI=i-1;var v901=this.nodes;introspect(JAM.policy.p5)var v685=v901[i];introspect(JAM.policy.p5)var v363=v685[j];v363.tracebackJ=j}else{var v686=b>c;v686&&(v686=b>a);if(v686){var v902=this.nodes;introspect(JAM.policy.p5)var v687=v902[i];introspect(JAM.policy.p5)var v364=v687[j];v364.value=
b;var v903=this.nodes;introspect(JAM.policy.p5)var v688=v903[i];introspect(JAM.policy.p5)var v365=v688[j];v365.tracebackI=i;var v904=this.nodes;introspect(JAM.policy.p5)var v689=v904[i];introspect(JAM.policy.p5)var v366=v689[j];v366.tracebackJ=j-1}else{var v905=this.nodes;introspect(JAM.policy.p5)var v690=v905[i];introspect(JAM.policy.p5)var v367=v690[j];v367.value=c;var v906=this.nodes;introspect(JAM.policy.p5)var v691=v906[i];introspect(JAM.policy.p5)var v368=v691[j];v368.tracebackI=i-1;var v907=
this.nodes;introspect(JAM.policy.p5)var v692=v907[i];introspect(JAM.policy.p5)var v369=v692[j];v369.tracebackJ=j-1}}var v1096=this.nodes;introspect(JAM.policy.p5)var v1036=v1096[i];introspect(JAM.policy.p5)var v908=v1036[j];if(0>v908.value){var v909=this.nodes;introspect(JAM.policy.p5)var v694=v909[i];introspect(JAM.policy.p5)var v372=v694[j];v372.value=0;var v910=this.nodes;introspect(JAM.policy.p5)var v695=v910[i];introspect(JAM.policy.p5)var v373=v695[j];v373.tracebackI=void 0;var v911=this.nodes;
introspect(JAM.policy.p5)var v696=v911[i];introspect(JAM.policy.p5)var v374=v696[j];v374.tracebackJ=void 0}j+=1;v376=j<this.nodes[0].length}i+=1;v377=i<this.nodes.length}var v914=this.nodes,v915=this.nodes.length-1;introspect(JAM.policy.p5)var v699=v914[v915];var v700=this.nodes[0].length-1;introspect(JAM.policy.p5)var v378=v699[v700];this.score=v378.value}
function search(){var v1228=[];this.hits=v1228;for(var v1228=0,v402=v1228<this.scoreSet.hits;v402;){this.updateMatrix();for(var maxNodeValue=0,maxNodeI=void 0,maxNodeJ=void 0,v402=1,v382=v402<this.nodes.length;v382;){for(var v382=1,v381=v382<this.nodes[0].length;v381;){v381=this.nodes;introspect(JAM.policy.p5)v381=v381[v402];introspect(JAM.policy.p5)v381=v381[v382];if(v381.value>maxNodeValue){maxNodeJ=this.nodes;introspect(JAM.policy.p5)maxNodeJ=maxNodeJ[v402];introspect(JAM.policy.p5)maxNodeJ=maxNodeJ[v382];
maxNodeValue=maxNodeJ.value;maxNodeI=v402;maxNodeJ=v382}v382+=1;v381=v382<this.nodes[0].length}v402+=1;v382=v402<this.nodes.length}if(0==maxNodeValue)break;v382=maxNodeI;v402=maxNodeJ;maxNodeValue=this.nodes;introspect(JAM.policy.p5)maxNodeI=maxNodeValue[maxNodeI];introspect(JAM.policy.p5)var currentNode=maxNodeI[maxNodeJ];var maxNodeJ=[],maxNodeI=[],maxNodeValue=currentNode.value,endN=v381=void 0,v709=void 0!=currentNode.tracebackI;for(v709&&(v709=void 0!=currentNode.tracebackJ);v709;){(v709=0==
v382)||(v709=0==v402);if(v709)break;(v709=currentNode.tracebackI==v382-1)&&(v709=currentNode.tracebackJ==v402-1);if(v709){void 0==v381&&(v381=v382,endN=v402);var v709=this.M,v713=v382-1;introspect(JAM.policy.p5)v709=v709[v713];maxNodeJ.push(v709);v709=this.N;v713=v402-1;introspect(JAM.policy.p5)v709=v709[v713];maxNodeI.push(v709)}else if(currentNode.tracebackJ==v402-1){if(void 0!=v381){maxNodeJ.push("-");v709=this.N;v713=v402-1;introspect(JAM.policy.p5)v709=v709[v713];maxNodeI.push(v709)}}else if(void 0!=
v381){v709=this.M;v713=v382-1;introspect(JAM.policy.p5)v709=v709[v713];maxNodeJ.push(v709);maxNodeI.push("-")}v709=this.nodes;introspect(JAM.policy.p5)v709=v709[v382];introspect(JAM.policy.p5)v709=v709[v402];v709.value=0;v709=this.nodes;introspect(JAM.policy.p5)v382=v709[v382];introspect(JAM.policy.p5)v402=v382[v402];v402.alreadyMatched=!0;v382=currentNode.tracebackI;v402=currentNode.tracebackJ;v709=this.nodes;v713=currentNode.tracebackI;introspect(JAM.policy.p5)v709=v709[v713];currentNode=currentNode.tracebackJ;
introspect(JAM.policy.p5)currentNode=v709[currentNode];(v709=void 0!=currentNode.tracebackI)&&(v709=void 0!=currentNode.tracebackJ)}maxNodeJ=maxNodeJ.reverse();maxNodeI=maxNodeI.reverse();this.hits.push(new Hit(maxNodeJ.join(""),maxNodeI.join(""),maxNodeValue,v382+1,v381,v402+1,endN));v1228+=1;v402=v1228<this.scoreSet.hits}}function getHits(){return this.hits}function FuzzySearch(){}
function Hit(sequenceM,sequenceN,score,startM,endM,startN,endN){this.sequenceM=sequenceM;this.sequenceN=sequenceN;this.score=score;this.startM=startM;this.endM=endM;this.startN=startN;this.endN=endN}new ScoreSet;ScoreSet.prototype.getScore=getScore;ScoreSet.prototype.setScoreSetParam=setScoreSetParam;new ScoringMatrix;ScoringMatrix.prototype.scoringMatrix_getScore=scoringMatrix_getScore;var v406=Identity,v1229=new ScoringMatrix;v406.prototype=v1229;Identity.prototype.setMismatch=setMismatch;
Identity.prototype.setMatch=setMatch;new FuzzySearch;FuzzySearch.prototype.initializeMatrix=initializeMatrix;FuzzySearch.prototype.updateMatrix=updateMatrix;FuzzySearch.prototype.search=search;FuzzySearch.prototype.getHits=getHits;FuzzySearch.prototype.dumpMatrix=dumpMatrix;JAM.set(document,"onload",v2);JAM.set(document.getElementById("submitbtn"),"onclick",v3);JAM.set(document.getElementById("clearbtn"),"onclick",v4);

JAM.stopProfile('load');
