
JAM.startProfile('load');
function SNote(){var serverPath="./SNote/",divParent=document.getElementById("div1");function init(divParent,serverPath){m_divInternal=divParent;var serverPath$$0=serverPath;m_divInternal.style.border="2px solid";m_divInternal.style.backgroundColor="#FFFFCC";m_preNote=document.createElement("pre");m_preNote.id="note";m_preNote.className="write-only non-editable";JAM.call(m_divInternal.appendChild,m_divInternal,[m_preNote]);m_divButtons=document.createElement("div");m_divButtons.style.textAlign="left";
JAM.call(m_divInternal.appendChild,m_divInternal,[m_divButtons]);m_imageEdit=createNoteButton(serverPath$$0+"SNoteEdit.png",handleEditButtonClick);m_imageView=createNoteButton(serverPath$$0+"SNoteRead.png",handleUnlockButtonClick);m_imageDelete=createNoteButton(serverPath$$0+"SNoteDelete.png",handleDeleteButtonClick);m_divEdit=createPopupDialog("edit_dialog",m_divInternal);m_divEdit.style.width=400;m_inputNewPassword=createPasswordPanel(m_divEdit,"Enter password:","edit_password");m_inputNewPasswordRetype=
createPasswordPanel(m_divEdit,"Retype password:","edit_password_retype");m_inputNote=document.createElement("textarea");m_inputNote.style.width=350;m_inputNote.style.height=200;m_inputNote.className="destructive-read read-only";m_inputNote.id="edit_note_input";JAM.call(m_divEdit.appendChild,m_divEdit,[m_inputNote]);divButtons=createDialogButtonPanel(handleEditDialogOk,handleEditDialogCancel,m_divEdit);m_divEdit.style.display="none";m_divUnlock=createPopupDialog("unlock_dialog",m_divInternal);m_inputPassword=
createPasswordPanel(m_divUnlock,"Enter password:","unlock_password");createDialogButtonPanel(handleUnlockDialogOk,handleUnlockDialogCancel,m_divUnlock);m_divUnlock.style.display="none";serverPath$$0=m_divDeleteDialog=createPopupDialog("delete_dialog",m_divInternal);label=document.createElement("label");JAM.set(label,"textContent","Are you sure you want to delete?",JAM.policy.p8);JAM.call(serverPath$$0.appendChild,serverPath$$0,[label]);createDialogButtonPanel(handleDeleteDialogOk,handleDeleteDialogCancel,
m_divDeleteDialog);m_divDeleteDialog.style.display="none";fetch(m_strId,handleSuccessfulFetch,handleFailedFetch)}function createNoteButton(strIconFile,funcHandleClick){var parent=m_divButtons;image=document.createElement("input");image.type="image";image.style.width=23;image.style.height=22;image.src=strIconFile;JAM.call(parent.appendChild,parent,[image]);JAM.set(image,"onclick",funcHandleClick);return image}function createPasswordPanel(parent,strPrompt,strPasswordInputId){divPassword=document.createElement("div");
JAM.call(parent.appendChild,parent,[divPassword]);labelPassword=document.createElement("label");JAM.set(labelPassword,"textContent",strPrompt,JAM.policy.p8);JAM.call(divPassword.appendChild,divPassword,[labelPassword]);inputPassword=document.createElement("input");inputPassword.type="password";inputPassword.className="destructive-read read-only";inputPassword.id=strPasswordInputId;JAM.call(divPassword.appendChild,divPassword,[inputPassword]);return inputPassword}function createPopupDialog(strDialogId,
parent){divDialog=document.createElement("div");divDialog.id=strDialogId;divDialog.className="popup";JAM.call(parent.appendChild,parent,[divDialog]);return divDialog}function createDialogButtonPanel(funcHandleOk,funcHandleCancel,parent){divButtons=document.createElement("div");buttonOk=document.createElement("button");buttonOk.type="input";JAM.set(buttonOk,"textContent","ok",JAM.policy.p8);JAM.set(buttonOk,"onclick",funcHandleOk);JAM.call(divButtons.appendChild,divButtons,[buttonOk]);buttonCancel=
document.createElement("button");buttonCancel.type="input";JAM.set(buttonCancel,"textContent","cancel",JAM.policy.p8);JAM.set(buttonCancel,"onclick",funcHandleCancel);JAM.call(divButtons.appendChild,divButtons,[buttonCancel]);JAM.call(parent.appendChild,parent,[divButtons]);return divButtons}function closeUnlockDialog(){var div=document.getElementById("unlock_dialog");div.style.display="none";m_inputPassword.value=""}function closeDeleteDialog(){var div=document.getElementById("delete_dialog");div.style.display=
"none"}function closeEditDialog(){var div=document.getElementById("edit_dialog");div.style.display="none";m_inputNote.value="";m_inputNewPassword.value="";m_inputNewPasswordRetype.value=""}function destructiveRead(elem){val=elem.value;elem.value="";return val}function handleDeleteButtonClick(){var div=document.getElementById("delete_dialog");div.style.display="block"}function handleDeleteDialogCancel(){closeDeleteDialog()}function handleDeleteDialogOk(){function v1(){alert("Failed to delete note.")}
function v0(strId){JAM.set(m_preNote,"textContent","",JAM.policy.p8);fetch(m_strId,handleSuccessfulFetch,handleFailedFetch)}deleteSNote(v0,v1);closeDeleteDialog()}function handleUnlockButtonClick(){var div=document.getElementById("unlock_dialog");div.style.display="block"}function handleUnlockDialogOk(){JAM.set(m_preNote,"textContent",message,JAM.policy.p8);closeUnlockDialog();m_imageEdit.style.display="none";m_imageView.style.display="none";m_imageDelete.style.display="inline"}function handleUnlockDialogCancel(){closeUnlockDialog()}
function handleEditButtonClick(){var div=document.getElementById("edit_dialog");div.style.display="block"}function handleEditDialogOk(){function v2(strId){""!=strId?closeEditDialog():alert("Error: note could not be saved.")}strNewPass=destructiveRead(m_inputNewPassword);strNewPassRetype=destructiveRead(m_inputNewPasswordRetype);0==strNewPass.length?alert("Must have non-empty password"):strNewPass!=strNewPassRetype?alert("Passwords do not match"):(save(destructiveRead(m_inputNote),v2),fetch(m_strId,
handleSuccessfulFetch,handleFailedFetch))}function handleEditDialogCancel(){closeEditDialog()}function handleSuccessfulFetch(strCipherText){m_imageEdit.style.display="none";m_imageDelete.style.display="none";m_imageView.style.display="inline";closeEditDialog()}function handleFailedFetch(){m_imageView.style.display="none";m_imageDelete.style.display="none";m_imageEdit.style.display="inline"}function fetch(strId,callbackSuccess,callbackFail){""==message?callbackFail():JAM.call(callbackSuccess,null,
[message])}function save(strEncNote,callbackDone){var pwd=strNewPass;password=pwd;message=strEncNote;JAM.call(callbackDone,null,["Saved"])}function deleteSNote(callbackSuccess,callbackFail){message="";JAM.call(callbackSuccess,null,["Deleted"])}var m_strId=divParent.id,m_divInternal=null,m_preNote=null,m_imageEdit=null,m_imageView=null,m_divEdit=null,m_inputNewPassword=null,m_inputNewPasswordRetype=null,m_inputNote=null,m_inputPassword=null;init(divParent,serverPath)}
function SNoteSwindler(){var divParent=document.getElementById("div2"),strNoteId="div1";function createButton(strLabel,strFunc){var parent=m_divInternal;button=document.createElement("button");button.type="input";JAM.set(button,"textContent",strLabel,JAM.policy.p8);JAM.set(button,"onclick",strFunc);JAM.call(parent.appendChild,parent,[button])}function forgeNote(){preNote=document.getElementById("note");JAM.set(preNote,"textContent","Forged note",JAM.policy.p8)}function forgeNoteInnerHTML(){preNote=
document.getElementById("note");JAM.set(preNote,"innerHTML","Forged note",JAM.policy.p2)}function readNote(){preNote=document.getElementById("note");introspect(JAM.policy.p6)var v37=preNote.textContent;alert(v37)}function readNoteInnerHTML(){preNote=document.getElementById("note");introspect(JAM.policy.p4)var v38=preNote.innerHTML;alert(v38)}m_divInternal=m_divParent=null;m_strNoteId=strNoteId;m_divParent=divParent;m_divInternal=document.createElement("div");m_divInternal.style.border="2px solid";
m_divInternal.style.backgroundColor="#CCCCCC";JAM.call(m_divParent.appendChild,m_divParent,[m_divInternal]);createButton("Forge Note",forgeNote);createButton("Forge Note Inner HTML",forgeNoteInnerHTML);createButton("Read Note",readNote);createButton("Read Note Inner HTML",readNoteInnerHTML)}var message="Here's a secret stored message",password="test";new SNote;new SNoteSwindler

JAM.stopProfile('load');
