
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" "}function v3(){try{JAM.startProfile('compute');genbankTrans();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){var v7=document.main_form.main_submit;JAM.call(v7.focus,v7,[],JAM.policy.p13)}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=JAM.call(sequence.replace,sequence,[/(.{60})/g,v0],JAM.policy.p13)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v11=i<arrayOfTitles.length;v11;){v11=arrayOfTitles[i];v11=-1==JAM.call(v11.search,v11,[/\S/],JAM.policy.p13);v11||(v11=arrayOfSequences[i],(v11=-1==JAM.call(v11.search,v11,[/\S/],JAM.policy.p13))||(v11=arrayOfSequences[i].length!=lengthOfAlign));if(v11)return alert("There is a problem with the alignment format."),
!1;i+=1;v11=i<arrayOfTitles.length}return!0}
function checkCodonTable(codonTable){var v309=-1==JAM.call(codonTable.search,codonTable,[/AmAcid/],JAM.policy.p13);v309||(v309=-1==JAM.call(codonTable.search,codonTable,[/Codon/],JAM.policy.p13),v309||(v309=-1==JAM.call(codonTable.search,codonTable,[/Number/],JAM.policy.p13),v309||(v309=-1==JAM.call(codonTable.search,codonTable,[/\/1000/],JAM.policy.p13))||(v309=-1==JAM.call(codonTable.search,codonTable,[/Fraction\s*\.\./],JAM.policy.p13))));return v309?(alert("The codon table has been entered incorrectly."),
!1):!0}function checkFormElement(formElement){formElement=formElement.value;return-1==JAM.call(formElement.search,formElement,[/\S/],JAM.policy.p13)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v16=z<arrayOfPatterns.length;v16;){v16=arrayOfPatterns[z];if(-1==JAM.call(v16.search,v16,[/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/],JAM.policy.p13)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("Genetic code error: one or more patterns have been entered incorrectly."),
!1;z+=1;v16=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v16=0,v25=v16<arrayOfPatterns.length;v25;){var v25=z,v20=v16,v583=arrayOfPatterns[v16],v583=JAM.call(v583.match,v583,[/\/.+\//],JAM.policy.p13)+"gi",v583=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v583+" }"):JAM.call(eval,null,[v583]);v25[v20]=v583;v25=codon;v20=v16;v583=arrayOfPatterns[v16];v583=JAM.call(v583.match,v583,[/=[a-zA-Z\*]/],JAM.policy.p13);v583=JAM.call(v583.toString,
v583,[],JAM.policy.p13);v25[v20]=v583;v25=codon;v20=v16;v583=codon[v16];v583=JAM.call(v583.replace,v583,[/=/g,""],JAM.policy.p13);v25[v20]=v583;v16+=1;v25=v16<arrayOfPatterns.length}arrayOfPatterns=0;for(v16=arrayOfPatterns<=testSequence.length-3;v16;){codon=JAM.call(testSequence.substring,testSequence,[arrayOfPatterns,arrayOfPatterns+3],JAM.policy.p13);v16=0;for(v25=v16<z.length;v25;){if(-1!=JAM.call(codon.search,codon,[z[v16]],JAM.policy.p23)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+
codon+"."),!1;oneMatch=!0}v16+=1;v25=v16<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v16=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v34=z<arrayOfPatterns.length;v34;){v34=arrayOfPatterns[z];if(-1!=JAM.call(v34.search,v34,[/[^acdefghiklmnpqrstvwyz]/i],JAM.policy.p13))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v34=z<arrayOfPatterns.length}z=0;for(v34=z<arrayOfPatterns.length;v34;){for(var v34=RegExp("["+arrayOfPatterns[z]+"]","gi"),j=z+1,v37=j<arrayOfPatterns.length;v37;){v37=arrayOfPatterns[j];if(-1!=JAM.call(v37.search,v37,[v34],JAM.policy.p23))return alert("The same amino acid is in more than one similarity group."),
!1;j+=1;v37=j<arrayOfPatterns.length}z+=1;v34=z<arrayOfPatterns.length}return!0}function checkRestPatterns(arrayOfPatterns){for(var z=0,v41=z<arrayOfPatterns.length;v41;){v41=arrayOfPatterns[z];if(-1==JAM.call(v41.search,v41,[/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i],JAM.policy.p13)||!1==moreExpressionCheck(arrayOfPatterns[z]))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v41=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){var v584=getSequenceFromFasta(text);return JAM.call(v584.replace,v584,[/[^A-Za-z]/g,""],JAM.policy.p13).length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/g/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/c/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"c"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"g"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/G/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/C/g,"2"],JAM.policy.p13);
dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"C"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"G"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/a/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/t/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"t"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"a"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/A/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/T/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"T"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"A"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/u/g,"a"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/U/g,"A"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/r/g,"1"],
JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/y/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"y"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"r"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/R/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/Y/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"Y"],JAM.policy.p13);dnaSequence=
JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"R"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/k/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/m/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"m"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"k"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/K/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,
dnaSequence,[/M/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"M"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"K"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/b/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/v/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"v"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"b"],
JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/B/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/V/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"V"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"B"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/d/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/h/g,"2"],JAM.policy.p13);dnaSequence=
JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"h"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"d"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/D/g,"1"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/H/g,"2"],JAM.policy.p13);dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/1/g,"H"],JAM.policy.p13);return dnaSequence=JAM.call(dnaSequence.replace,dnaSequence,[/2/g,"D"],JAM.policy.p13)}
function closeForm(){var v46=outputWindow.document;JAM.call(v46.write,v46,["</form>"],JAM.policy.p14);return!0}function closePre(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</div>"],JAM.policy.p14);v47=outputWindow.document;JAM.call(v47.write,v47,["</pre>\n"],JAM.policy.p14)}function closeTextArea(){var v49=outputWindow.document;JAM.call(v49.write,v49,["</textarea>"],JAM.policy.p14);return!0}
function closeWindow(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</body>\n</html>\n"],JAM.policy.p14);outputWindow.status="Done.";v50=outputWindow.document;JAM.call(v50.close,v50,[],JAM.policy.p13)}
function convertDegenerates(sequence){sequence=JAM.call(sequence.toLowerCase,sequence,[],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/t/g,"[TU]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/r/g,"[AGR]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/y/g,"[CTUY]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/s/g,"[GCS]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/w/g,"[ATUW]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,
sequence,[/k/g,"[GTUK]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/m/g,"[ACM]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/b/g,"[CGTUBSKY]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/d/g,"[AGTUDRKW]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/h/g,"[ACTUHMYW]"],JAM.policy.p13);sequence=JAM.call(sequence.replace,sequence,[/v/g,"[ACGVSMR]"],JAM.policy.p13);return sequence=JAM.call(sequence.replace,sequence,[/n/g,"[ACGTURYSWKMBDHVN]"],
JAM.policy.p13)}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v54=i<alignArray.length;v54;){v54=alignArray[i];if(-1==JAM.call(v54.search,v54,[/[^\s]+\s/],JAM.policy.p13))return alert("There is a problem with the alignment format."),!1;i+=1;v54=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=JAM.call(alignSeq.replace,alignSeq,[/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,""],JAM.policy.p13)}
function filterFastaTitle(sequenceTitle){sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/\s{2,}/g," "],JAM.policy.p13);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/^\s*/g,""],JAM.policy.p13);sequenceTitle=JAM.call(sequenceTitle.replace,sequenceTitle,[/[\f\n\r\t]+$/g,"\n"],JAM.policy.p13);return JAM.call(sequenceTitle.replace,sequenceTitle,[/[\<\>]\n/gi,""],JAM.policy.p13)}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=JAM.call(sequenceData.search,sequenceData,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p13))for(var v56=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p23);v56;)JAM.call(arrayOfFasta.push,arrayOfFasta,[matchArray[0]],JAM.policy.p23),v56=matchArray=JAM.call(re.exec,re,[sequenceData],JAM.policy.p23);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p13)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p13)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p13)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v74=j<arrayOfPatterns.length;v74;){var v74=geneticCodeMatchExp,v73=j,v585=arrayOfPatterns[j],v585=JAM.call(v585.match,v585,[/\/.+\//],JAM.policy.p13)+"gi",v585=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v585+" }"):JAM.call(eval,null,[v585]);v74[v73]=v585;j+=1;v74=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v80=j<arrayOfPatterns.length;v80;){var v80=geneticCodeMatchResult,v77=j,v518=arrayOfPatterns[j],v518=JAM.call(v518.match,v518,[/=[a-zA-Z\*]/],JAM.policy.p13),v518=JAM.call(v518.toString,v518,[],JAM.policy.p13);v80[v77]=v518;v80=geneticCodeMatchResult;v77=j;v518=geneticCodeMatchResult[j];v518=JAM.call(v518.replace,v518,[/=/g,""],JAM.policy.p13);v80[v77]=v518;j+=1;v80=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p13)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitle.search,fastaSequenceTitle,[/[^\s]/],JAM.policy.p13)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+JAM.call(sequence.substring,sequence,[0,10],JAM.policy.p13)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=JAM.call(fastaSequenceTitleOne.search,fastaSequenceTitleOne,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceOne.substring,sequenceOne,[0,10],JAM.policy.p13)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+
" residue sequence ";-1!=JAM.call(fastaSequenceTitleTwo.search,fastaSequenceTitleTwo,[/[^\s]/],JAM.policy.p13)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+JAM.call(sequenceTwo.substring,sequenceTwo,[0,10],JAM.policy.p13)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p13)*components.length],JAM.policy.p13),tempNum=components[tempNum],JAM.call(sequenceArray.push,sequenceArray,[tempNum],JAM.policy.p23),j+=1,tempNum=j<lengthOut;return JAM.call(sequenceArray.join,sequenceArray,[""],JAM.policy.p14)}
function getSequenceFromFasta(sequenceRecord){-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p13)&&(sequenceRecord=JAM.call(sequenceRecord.replace,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p13));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=JAM.call(sequenceRecord.search,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/],JAM.policy.p13)&&(sequenceRecord=JAM.call(sequenceRecord.match,sequenceRecord,[/\>[^\f\n\r]+[\f\n\r]/,""],JAM.policy.p13),fastaTitle=JAM.call(sequenceRecord.toString,sequenceRecord,[],JAM.policy.p13),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\>|[\f\n\r]/g,""],JAM.policy.p13),fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/\s{2,}/g," "],JAM.policy.p13),
fastaTitle=JAM.call(fastaTitle.replace,fastaTitle,[/[\<\>]/gi,""],JAM.policy.p13));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[[A-Za-z\|]*\[/],JAM.policy.p13);v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\][A-Za-z\|]*\]/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[\]/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/[A-Za-z\|]*\]/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,
[/\[[A-Za-z\|]*\//],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\|/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\/\|/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\|\//],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\[.\]/],JAM.policy.p13),v397||(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\</],JAM.policy.p13))||
(v397=-1!=JAM.call(expressionToCheck.search,expressionToCheck,[/\>/],JAM.policy.p13))))))))));return v397?!1:!0}function openForm(){var v106=outputWindow.document;JAM.call(v106.write,v106,['<form action="">\n'],JAM.policy.p14);return!0}function openPre(){var v107=outputWindow.document;JAM.call(v107.write,v107,["<pre>"],JAM.policy.p14);v107=outputWindow.document;JAM.call(v107.write,v107,['<div class="pre">'],JAM.policy.p14)}
function openTextArea(){var v109=outputWindow.document;JAM.call(v109.write,v109,['<br /><textarea rows="6" cols="61">\n'],JAM.policy.p14);return!0}function openWindow(){var title="GenBank Trans Extractor";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p14);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p13);var v110=outputWindow.document;JAM.call(v110.write,v110,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p23);isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'],
JAM.policy.p23)):(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p23));isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p23);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(window.open,window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"],JAM.policy.p14);JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p13);var v118=outputWindow.document;JAM.call(v118.write,v118,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n'],
JAM.policy.p23);isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'],
JAM.policy.p23)):(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n'],
JAM.policy.p23));isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"],JAM.policy.p23);outputWindow.status="Please Wait."}function removeFormatting(sequence){return JAM.call(sequence.replace,sequence,[/[\d\s]/g,""],JAM.policy.p13)}function removeNonDna(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,""],JAM.policy.p13)}
function removeNonDnaStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^gatucGATUC]/g,""],JAM.policy.p13)}function removeNonProtein(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p13)}function removeNonProteinStrict(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,""],JAM.policy.p13)}
function removeNonProteinAllowDegen(sequence){return JAM.call(sequence.replace,sequence,[/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,""],JAM.policy.p13)}function removeNonProteinAllowX(sequence){return JAM.call(sequence.replace,sequence,[/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,""],JAM.policy.p13)}function removeWhiteSpace(text){return JAM.call(text.replace,text,[/\s/g,""],JAM.policy.p13)}
function removeNonLetters(sequence){return JAM.call(sequence.replace,sequence,[/[^A-Z]/gi,""],JAM.policy.p13)}function reverse(dnaSequence){var tempDnaArray=[];-1!=JAM.call(dnaSequence.search,dnaSequence,[/./],JAM.policy.p13)&&(tempDnaArray=JAM.call(dnaSequence.match,dnaSequence,[/./g],JAM.policy.p13),tempDnaArray=JAM.call(tempDnaArray.reverse,tempDnaArray,[],JAM.policy.p13),dnaSequence=JAM.call(tempDnaArray.join,tempDnaArray,[""],JAM.policy.p14));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=JAM.call(theNumber.toString,theNumber,[],JAM.policy.p13);for(var j=theNumber.length,v127=j<lengthOfColumn;v127;)tempString+=" ",j+=1,v127=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";JAM.call(testArray.push,testArray,[testString],JAM.policy.p23);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==JAM.call(testString.search,testString,[testArray],JAM.policy.p23))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=
!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=JAM.call(testString.replace,testString,[/(\d)/g,v1],JAM.policy.p13);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),
!1;testString=2489.8237;return 2489.824!=JAM.call(testString.toFixed,testString,[3],JAM.policy.p13)?(alert("Number toFixed() method not supported. See browser compatibility page."),!1):2489.8!=JAM.call(testString.toPrecision,testString,[5],JAM.policy.p13)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p13))return alert("Please enter a number"),!1}
function verifyEmbl(emblFile){var v412=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p13);v412||(v412=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p13),v412||(v412=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p13))||(v412=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p13)));return v412?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==JAM.call(theNumber.search,theNumber,[/\d/],JAM.policy.p13))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=JAM.call(dnaSequence.search,dnaSequence,[/[^gatucryswkmbdhvnx\s]/i],JAM.policy.p13)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=JAM.call(proteinSequence.search,proteinSequence,[/[^acdefghiklmnpqrstvwyz\*\s]/i],JAM.policy.p13)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}
function verifyGenBank(genBankFile){var v417=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p13);v417||(v417=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p13),v417||(v417=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p13))||(v417=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p13)));return v417?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v418=-1==JAM.call(genBankFile.search,genBankFile,[/LOCUS/],JAM.policy.p13);v418||(v418=-1==JAM.call(genBankFile.search,genBankFile,[/DEFINITION/],JAM.policy.p13),v418||(v418=-1==JAM.call(genBankFile.search,genBankFile,[/ACCESSION/],JAM.policy.p13))||(v418=-1==JAM.call(genBankFile.search,genBankFile,[/ORIGIN/],JAM.policy.p13)));return v418?(alert("Please enter the contents of a GenBank file."),!1):-1==JAM.call(genBankFile.search,genBankFile,[/FEATURES {13}/],
JAM.policy.p13)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v420=-1==JAM.call(emblFile.search,emblFile,[/ID/],JAM.policy.p13);v420||(v420=-1==JAM.call(emblFile.search,emblFile,[/AC/],JAM.policy.p13),v420||(v420=-1==JAM.call(emblFile.search,emblFile,[/DE/],JAM.policy.p13))||(v420=-1==JAM.call(emblFile.search,emblFile,[/SQ/],JAM.policy.p13)));return v420?(alert("Please enter the contents of an EMBL file."),!1):-1==JAM.call(emblFile.search,emblFile,[/^FT/m],JAM.policy.p13)?(alert("The file has no defined features."),!1):
!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v155=startBase<stopBase;v155;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v155=1,v152=v155<=basePerLine/groupSize;v152;){for(v152=k<groupSize;v152;)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p23),k+=1,v152=k<groupSize;startBase+=groupSize;k=0;lineOfText+=sepChar;
v155+=1;v152=v155<=basePerLine/groupSize}v155=outputWindow.document;JAM.call(v155.write,v155,[lineOfText+"\n"],JAM.policy.p23);lineOfText="";v155=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v425=0>adjustment;v425&&(v425=0<=adjusted);v425&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v165=j<=basePerLine/groupSize;v165;){for(v165=k<groupSize;v165&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p23),k+=1,v165=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v165=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,
JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"],JAM.policy.p23),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"],JAM.policy.p23),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p14))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,
[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p23),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"],JAM.policy.p23),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p14))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p23),lineNum=outputWindow.document,JAM.call(lineNum.write,
lineNum,[lineOfText+"\n"],JAM.policy.p23),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+"\n"],JAM.policy.p23),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"],JAM.policy.p14)));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v198=j<=basePerLine/groupSize;v198;){for(v198=k<groupSize;v198&&!(startBase+k>=stopBase);)lineOfText+=JAM.call(text.charAt,text,[k+startBase],JAM.policy.p23),k+=1,v198=k<groupSize;
lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v198=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"],JAM.policy.p23)):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"],JAM.policy.p23)):"above"==numberPosition&&(lineNum=outputWindow.document,
JAM.call(lineNum.write,lineNum,[aboveNum+"\n"],JAM.policy.p23),aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"],JAM.policy.p23));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v442=sequence.length<=firstIndexToMutate;v442||(v442=0>lastIndexToMutate)||(v442=lastIndexToMutate<=firstIndexToMutate);v442&&(numMut=0);v442=0;for(randNum=v442<numMut;randNum;){randNum=sequence.length;randNum=JAM.call(Math.floor,
Math,[JAM.call(Math.random,Math,[],JAM.policy.p13)*randNum],JAM.policy.p13);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=JAM.call(sequence.charAt,sequence,[randNum],JAM.policy.p13);for(needNewChar=!0;needNewChar;)componentsIndex=JAM.call(Math.round,Math,[JAM.call(Math.random,Math,[],JAM.policy.p13)*components.length],JAM.policy.p13),componentsIndex==components.length&&(componentsIndex=0),components[componentsIndex]!=currentChar&&
(needNewChar=!1);sequence=JAM.call(sequence.substring,sequence,[0,randNum],JAM.policy.p13)+components[componentsIndex]+JAM.call(sequence.substring,sequence,[randNum+1,sequence.length],JAM.policy.p24)}v442+=1;randNum=v442<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)],JAM.policy.p23);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p13)*components.length],JAM.policy.p13),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"],JAM.policy.p23),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"],JAM.policy.p23);
return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p13).length,sequence=JAM.call(sequence.substring,sequence,[sequence.length-lookAhead,sequence.length],JAM.policy.p24)+sequence+JAM.call(sequence.substring,sequence,[0,lookAhead],JAM.policy.p13),lowerLimit=
0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p14);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n'],JAM.policy.p23);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";
matchExp=arrayOfItems[dnaConformation];matchExp=JAM.call(matchExp.match,matchExp,[/\/.+\//],JAM.policy.p13)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+matchExp+" }"):JAM.call(eval,null,[matchExp]);cutDistance=arrayOfItems[dnaConformation];cutDistance=JAM.call(cutDistance.match,cutDistance,[/\)\D*\d+/],JAM.policy.p13);cutDistance=JAM.call(cutDistance.toString,cutDistance,[],JAM.policy.p13);cutDistance=parseFloat(JAM.call(cutDistance.replace,cutDistance,[/\)\D*/,""],JAM.policy.p13));
for(matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p23);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v461=matchPosition>=lowerLimit;v461&&(v461=matchPosition<upperLimit);v461&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+1;matchPosition=JAM.call(matchExp.exec,matchExp,[sequence],JAM.policy.p23)}-1!=JAM.call(lookAhead.search,lookAhead,[/\d/],JAM.policy.p13)&&(lookAhead=
JAM.call(lookAhead.replace,lookAhead,[/none,\s*/,""],JAM.policy.p13));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';matchPosition=arrayOfItems[dnaConformation];matchPosition=JAM.call(matchPosition.match,matchPosition,[/\([^\(]+\)/],JAM.policy.p13);matchPosition=JAM.call(matchPosition.toString,matchPosition,[],JAM.policy.p13);JAM.call(matchExp.write,
matchExp,[cutDistance+JAM.call(matchPosition.replace,matchPosition,[/\(|\)/g,""],JAM.policy.p13)+'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"],JAM.policy.p23);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"],JAM.policy.p14);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v253=outputWindow.document;JAM.call(v253.write,v253,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n'],JAM.policy.p14);v253=outputWindow.document;JAM.call(v253.write,v253,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n'],JAM.policy.p23);for(var v253=0,v264=v253<arrayOfItems.length;v264;){var v264=0,v470=arrayOfItems[v253],
v470=JAM.call(v470.match,v470,[/\/[^\/]+\//],JAM.policy.p13)+"gi",v470=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v470+" }"):JAM.call(eval,null,[v470]);-1!=JAM.call(sequence.search,sequence,[v470],JAM.policy.p23)&&(v264=JAM.call(sequence.match,sequence,[v470],JAM.policy.p23).length);var v470=0,v562=originalLength+1,v652=arrayOfItems[v253];0<v562-parseFloat(JAM.call(v652.match,v652,[/\d+/],JAM.policy.p13))&&(v470=100*v264,v562=originalLength+1,v652=arrayOfItems[v253],v470/=v562-parseFloat(JAM.call(v652.match,
v652,[/\d+/],JAM.policy.p13)));v562=outputWindow.document;v652=arrayOfItems[v253];v652=JAM.call(v652.match,v652,[/\([^\(]+\)\b/],JAM.policy.p13);v652=JAM.call(v652.toString,v652,[],JAM.policy.p13);JAM.call(v562.write,v562,["<tr><td>"+JAM.call(v652.replace,v652,[/\(|\)/g,""],JAM.policy.p13)+"</td><td>"+v264+"</td><td>"+JAM.call(v470.toFixed,v470,[2],JAM.policy.p13)+"</td></tr>\n"],JAM.policy.p23);v253+=1;v264=v253<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,
originalLength,["</tbody></table>\n"],JAM.policy.p14);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=JAM.call(Math.floor,Math,[JAM.call(Math.random,Math,[],JAM.policy.p13)*tempChar],JAM.policy.p13),tempChar=JAM.call(sequence.charAt,sequence,[tempString2],JAM.policy.p13),tempSeq+=tempChar,tempChar=JAM.call(sequence.substring,sequence,[0,tempString2],JAM.policy.p13),tempString2=JAM.call(sequence.substring,sequence,
[tempString2+1,sequence.length],JAM.policy.p13),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,[tempSeq+"\n"],JAM.policy.p23),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"],JAM.policy.p23);return!0}
function genbankTrans(){var theDocument=document,maxInput=2E5;if(!1!=testScript()){var v482=!1==checkFormElement(theDocument.forms[0].elements[0]);v482||(v482=!1==verifyGenBankFeat(theDocument.forms[0].elements[0].value))||(v482=!1==checkTextLength(theDocument.forms[0].elements[0].value,maxInput));v482||(openWindow(),openPre(),genBankTransExtract(theDocument.forms[0].elements[0].value),closePre(),closeWindow())}}
function genBankTransExtract(genBankFile){genBankFile="_"+genBankFile+"_";genBankFile=JAM.call(genBankFile.split,genBankFile,[/LOCUS\s\s\s[^\f\n\r]*/m],JAM.policy.p13);for(var i=1,v286=i<genBankFile.length;v286;){var v286=genBankFile[i],v286=JAM.call(v286.split,v286,[/DEFINITION|ACCESSION|FEATURES|ORIGIN[^\f\n\r]*/],JAM.policy.p13),v571=v286[1],v571=filterFastaTitle(JAM.call(v571.replace,v571,[/[\f\n\r\t]+$/g,""],JAM.policy.p13))+"\n",v281=v286[4],v281=JAM.call(v281.split,v281,[/\/{2}/],JAM.policy.p13),
v282=outputWindow.document;JAM.call(v282.write,v282,[v571+"\n"],JAM.policy.p23);1==v281.length&&(alert("The entire GenBank file may not have been processed."),JAM.call(outputWindow.focus,outputWindow,[],JAM.policy.p13));v286=v286[3];v286=JAM.call(v286.split,v286,[/[\f\n\r] {5,12}\b/],JAM.policy.p13);showFeatureTrans(v286);i+=1;v286=i<genBankFile.length}}
function showFeatureTrans(arrayOfFeatures){for(var featureTitle="",theTitle="",featureTitle=theTitle="",featureTitle=!1,i=1,theTitle=i<arrayOfFeatures.length;theTitle;){theTitle=arrayOfFeatures[i];if(-1!=JAM.call(theTitle.search,theTitle,[/\/translation/],JAM.policy.p13)){var featureTitle=arrayOfFeatures,theTitle=i,v490=arrayOfFeatures[i],v490=JAM.call(v490.replace,v490,[/[\[\]\*]/g,""],JAM.policy.p13);featureTitle[theTitle]=v490;featureTitle=arrayOfFeatures[i];featureTitle=JAM.call(featureTitle.match,
featureTitle,[/[^ \f\n\r\t\v]+ /],JAM.policy.p13);featureTitle=JAM.call(featureTitle.toString,featureTitle,[],JAM.policy.p13);theTitle=RegExp(featureTitle);v490=arrayOfFeatures[i];JAM.call(v490.replace,v490,[theTitle,""],JAM.policy.p23);theTitle=arrayOfFeatures[i];theTitle=JAM.call(theTitle.match,theTitle,[/\/[^\f\n\r]+/],JAM.policy.p13);theTitle=JAM.call(theTitle.toString,theTitle,[],JAM.policy.p13);v490=outputWindow.document;JAM.call(v490.write,v490,["&gt;"+filterFastaTitle(featureTitle)+filterFastaTitle(theTitle)+
"\n"],JAM.policy.p23);featureTitle=arrayOfFeatures[i];featureTitle=JAM.call(featureTitle.match,featureTitle,[/\/translation="[^"]+"/],JAM.policy.p13);featureTitle=JAM.call(featureTitle.toString,featureTitle,[],JAM.policy.p13);featureTitle=JAM.call(featureTitle.replace,featureTitle,[/\/translation/,""],JAM.policy.p13);featureTitle=removeNonProtein(featureTitle);featureTitle=addReturns(featureTitle);theTitle=outputWindow.document;JAM.call(theTitle.write,theTitle,[featureTitle],JAM.policy.p23);featureTitle=
!0;theTitle=outputWindow.document;JAM.call(theTitle.write,theTitle,["\n\n"],JAM.policy.p14)}i+=1;theTitle=i<arrayOfFeatures.length}!1==featureTitle&&(arrayOfFeatures=outputWindow.document,JAM.call(arrayOfFeatures.write,arrayOfFeatures,["No translations were found.\n"],JAM.policy.p14))}JAM.set(document,"onload",v2);JAM.set(JAM.call(document.getElementById,document,["submitbtn"],JAM.policy.p14),"onclick",v3);JAM.set(JAM.call(document.getElementById,document,["clearbtn"],JAM.policy.p14),"onclick",v4);

JAM.stopProfile('load');
