
JAM.startProfile('load');
function v4(){document.forms[0].elements[0].value=" ";document.forms[0].elements[4].value=" "}function v3(){try{JAM.startProfile('compute');dnaMw();JAM.stopProfile('compute');}catch(e){alert("The following error was encountered: "+e)}}function v2(){document.main_form.main_submit.focus()}function addReturns(sequence){function v0(str,p1,offset,s){return p1+"\n"}return sequence=sequence.replace(/(.{60})/g,v0)}
function checkAlign(arrayOfTitles,arrayOfSequences){var lengthOfAlign=arrayOfSequences[0].length;if(2>arrayOfSequences.length)return alert("Please enter an alignment consisting of at least two sequences."),!1;for(var i=0,v12=i<arrayOfTitles.length;v12;){introspect(JAM.policy.p5)v12=arrayOfTitles[i];v12=-1==v12.search(/\S/);if(!v12){introspect(JAM.policy.p5)v12=arrayOfSequences[i];v12=-1==v12.search(/\S/);if(!v12){introspect(JAM.policy.p5)v12=arrayOfSequences[i];v12=v12.length!=lengthOfAlign}}if(v12)return alert("There is a problem with the alignment format."),
!1;i+=1;v12=i<arrayOfTitles.length}return!0}function checkCodonTable(codonTable){var v329=-1==codonTable.search(/AmAcid/);v329||(v329=-1==codonTable.search(/Codon/),v329||(v329=-1==codonTable.search(/Number/),v329||(v329=-1==codonTable.search(/\/1000/))||(v329=-1==codonTable.search(/Fraction\s*\.\./))));return v329?(alert("The codon table has been entered incorrectly."),!1):!0}
function checkFormElement(formElement){return-1==formElement.value.search(/\S/)?(alert("Please enter some text."),!1):!0}
function checkGeneticCode(arrayOfPatterns){for(var z=0,codon="",oneMatch=!1,testSequence="gggggaggtggcgaggaagatgacgtggtagttgtcgcggcagctgccaggagaagtagcaagaaaaataacatgataattatcacgacaactacctggtgatgttgctagtaatattacttgttatttttctcgtcatcttcccggcgacgtcgccagcaacatcacctgctacttctcccgccacctccc",v17=z<arrayOfPatterns.length;v17;){introspect(JAM.policy.p5)v17=arrayOfPatterns[z];if(-1==v17.search(/^\s*\/[a-zA-Z\|\[\]]+\/=[a-zA-Z\*]/))return alert("Genetic code error: one or more patterns have been entered incorrectly."),!1;
introspect(JAM.policy.p5)v17=arrayOfPatterns[z];if(!1==moreExpressionCheck(v17))return alert("Genetic code error: one or more patterns have been entered incorrectly."),!1;z+=1;v17=z<arrayOfPatterns.length}for(var codon=Array(arrayOfPatterns.length),z=Array(arrayOfPatterns.length),v17=0,v26=v17<arrayOfPatterns.length;v26;){var v26=z,v21=v17;introspect(JAM.policy.p5)var v617=arrayOfPatterns[v17];v617=v617.match(/\/.+\//)+"gi";v617=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v617+" }"):JAM.call(eval,
null,[v617]);v26[v21]=v617;v26=codon;v21=v17;introspect(JAM.policy.p5)v617=arrayOfPatterns[v17];v617=v617.match(/=[a-zA-Z\*]/).toString();v26[v21]=v617;v26=codon;v21=v17;introspect(JAM.policy.p5)v617=codon[v17];v617=v617.replace(/=/g,"");v26[v21]=v617;v17+=1;v26=v17<arrayOfPatterns.length}arrayOfPatterns=0;for(v17=arrayOfPatterns<=testSequence.length-3;v17;){codon=testSequence.substring(arrayOfPatterns,arrayOfPatterns+3);v17=0;for(v26=v17<z.length;v26;){introspect(JAM.policy.p5)v26=z[v17];if(-1!=
codon.search(v26)){if(!0==oneMatch)return alert("Genetic code error: more than one amino acid is coded by the codon: "+codon+"."),!1;oneMatch=!0}v17+=1;v26=v17<z.length}if(!1==oneMatch)return alert("The genetic code expressions are missing a codon."),!1;oneMatch=!1;arrayOfPatterns+=3;v17=arrayOfPatterns<=testSequence.length-3}return!0}
function checkGroupInput(arrayOfPatterns){for(var z=0,v35=z<arrayOfPatterns.length;v35;){introspect(JAM.policy.p5)v35=arrayOfPatterns[z];if(-1!=v35.search(/[^acdefghiklmnpqrstvwyz]/i))return alert("One or more groups have been entered incorrectly."),!1;z+=1;v35=z<arrayOfPatterns.length}z=0;for(v35=z<arrayOfPatterns.length;v35;){introspect(JAM.policy.p5)v35=arrayOfPatterns[z];for(var v35=RegExp("["+v35+"]","gi"),j=z+1,v38=j<arrayOfPatterns.length;v38;){introspect(JAM.policy.p5)v38=arrayOfPatterns[j];
if(-1!=v38.search(v35))return alert("The same amino acid is in more than one similarity group."),!1;j+=1;v38=j<arrayOfPatterns.length}z+=1;v35=z<arrayOfPatterns.length}return!0}
function checkRestPatterns(arrayOfPatterns){for(var z=0,v42=z<arrayOfPatterns.length;v42;){introspect(JAM.policy.p5)v42=arrayOfPatterns[z];if(-1==v42.search(/^\s*\/[acgturyswkmbdhvn\[\]]+\/\s+\([^\/]+\)\d+/i))return alert("One or more patterns have been entered incorrectly."),!1;introspect(JAM.policy.p5)v42=arrayOfPatterns[z];if(!1==moreExpressionCheck(v42))return alert("One or more patterns have been entered incorrectly."),!1;z+=1;v42=z<arrayOfPatterns.length}return!0}
function checkSequenceLength(text,maxInput){return getSequenceFromFasta(text).replace(/[^A-Za-z]/g,"").length>maxInput?(alert("Please enter a sequence consisting of less than or equal to "+maxInput+" characters."),!1):!0}function checkTextLength(text,maxInput){return text.length>maxInput?(alert("Please enter text consisting of less than or equal to "+maxInput+" characters."),!1):!0}
function complement(dnaSequence){dnaSequence=dnaSequence.replace(/g/g,"1");dnaSequence=dnaSequence.replace(/c/g,"2");dnaSequence=dnaSequence.replace(/1/g,"c");dnaSequence=dnaSequence.replace(/2/g,"g");dnaSequence=dnaSequence.replace(/G/g,"1");dnaSequence=dnaSequence.replace(/C/g,"2");dnaSequence=dnaSequence.replace(/1/g,"C");dnaSequence=dnaSequence.replace(/2/g,"G");dnaSequence=dnaSequence.replace(/a/g,"1");dnaSequence=dnaSequence.replace(/t/g,"2");dnaSequence=dnaSequence.replace(/1/g,"t");dnaSequence=
dnaSequence.replace(/2/g,"a");dnaSequence=dnaSequence.replace(/A/g,"1");dnaSequence=dnaSequence.replace(/T/g,"2");dnaSequence=dnaSequence.replace(/1/g,"T");dnaSequence=dnaSequence.replace(/2/g,"A");dnaSequence=dnaSequence.replace(/u/g,"a");dnaSequence=dnaSequence.replace(/U/g,"A");dnaSequence=dnaSequence.replace(/r/g,"1");dnaSequence=dnaSequence.replace(/y/g,"2");dnaSequence=dnaSequence.replace(/1/g,"y");dnaSequence=dnaSequence.replace(/2/g,"r");dnaSequence=dnaSequence.replace(/R/g,"1");dnaSequence=
dnaSequence.replace(/Y/g,"2");dnaSequence=dnaSequence.replace(/1/g,"Y");dnaSequence=dnaSequence.replace(/2/g,"R");dnaSequence=dnaSequence.replace(/k/g,"1");dnaSequence=dnaSequence.replace(/m/g,"2");dnaSequence=dnaSequence.replace(/1/g,"m");dnaSequence=dnaSequence.replace(/2/g,"k");dnaSequence=dnaSequence.replace(/K/g,"1");dnaSequence=dnaSequence.replace(/M/g,"2");dnaSequence=dnaSequence.replace(/1/g,"M");dnaSequence=dnaSequence.replace(/2/g,"K");dnaSequence=dnaSequence.replace(/b/g,"1");dnaSequence=
dnaSequence.replace(/v/g,"2");dnaSequence=dnaSequence.replace(/1/g,"v");dnaSequence=dnaSequence.replace(/2/g,"b");dnaSequence=dnaSequence.replace(/B/g,"1");dnaSequence=dnaSequence.replace(/V/g,"2");dnaSequence=dnaSequence.replace(/1/g,"V");dnaSequence=dnaSequence.replace(/2/g,"B");dnaSequence=dnaSequence.replace(/d/g,"1");dnaSequence=dnaSequence.replace(/h/g,"2");dnaSequence=dnaSequence.replace(/1/g,"h");dnaSequence=dnaSequence.replace(/2/g,"d");dnaSequence=dnaSequence.replace(/D/g,"1");dnaSequence=
dnaSequence.replace(/H/g,"2");dnaSequence=dnaSequence.replace(/1/g,"H");return dnaSequence=dnaSequence.replace(/2/g,"D")}function closeForm(){var v47=outputWindow.document;JAM.call(v47.write,v47,["</form>"]);return!0}function closePre(){var v48=outputWindow.document;JAM.call(v48.write,v48,["</div>"]);v48=outputWindow.document;JAM.call(v48.write,v48,["</pre>\n"])}function closeTextArea(){var v50=outputWindow.document;JAM.call(v50.write,v50,["</textarea>"]);return!0}
function closeWindow(){var v51=outputWindow.document;JAM.call(v51.write,v51,["</body>\n</html>\n"]);outputWindow.status="Done.";outputWindow.document.close()}
function convertDegenerates(sequence){sequence=sequence.toLowerCase();sequence=sequence.replace(/t/g,"[TU]");sequence=sequence.replace(/r/g,"[AGR]");sequence=sequence.replace(/y/g,"[CTUY]");sequence=sequence.replace(/s/g,"[GCS]");sequence=sequence.replace(/w/g,"[ATUW]");sequence=sequence.replace(/k/g,"[GTUK]");sequence=sequence.replace(/m/g,"[ACM]");sequence=sequence.replace(/b/g,"[CGTUBSKY]");sequence=sequence.replace(/d/g,"[AGTUDRKW]");sequence=sequence.replace(/h/g,"[ACTUHMYW]");sequence=sequence.replace(/v/g,
"[ACGVSMR]");return sequence=sequence.replace(/n/g,"[ACGTURYSWKMBDHVN]")}function earlyCheckAlign(alignArray){if(3>alignArray.length)return alert("There is a problem with the alignment format."),!1;for(var i=1,v55=i<alignArray.length;v55;){introspect(JAM.policy.p5)v55=alignArray[i];if(-1==v55.search(/[^\s]+\s/))return alert("There is a problem with the alignment format."),!1;i+=1;v55=i<alignArray.length}return!0}
function filterAlignSeq(alignSeq){return alignSeq=alignSeq.replace(/[^abcdefghiklmnpqrstvwxyz\.\-]/gi,"")}function filterFastaTitle(sequenceTitle){sequenceTitle=sequenceTitle.replace(/\s{2,}/g," ");sequenceTitle=sequenceTitle.replace(/^\s*/g,"");sequenceTitle=sequenceTitle.replace(/[\f\n\r\t]+$/g,"\n");return sequenceTitle.replace(/[\<\>]\n/gi,"")}
function getArrayOfFasta(sequenceData){var arrayOfFasta=[],matchArray,re=/\>[^\>]+/g;if(-1!=sequenceData.search(/\>[^\f\n\r]+[\f\n\r]/))for(var v57=matchArray=re.exec(sequenceData);v57;)arrayOfFasta.push(matchArray[0]),v57=matchArray=re.exec(sequenceData);else arrayOfFasta[0]=sequenceData;return arrayOfFasta}
function getFastaTitleFromTitleAndSequence(fastaSequenceTitle,sequence){var stringToReturn="&gt;results for "+sequence.length+" residue sequence ";-1!=fastaSequenceTitle.search(/[^\s]/)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+sequence.substring(0,10)+'"';return stringToReturn+"\n"}
function getFuzzySearchTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Search results for "+sequenceOne.length+" residue sequence ";-1!=fastaSequenceTitleOne.search(/[^\s]/)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+sequenceOne.substring(0,10)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+" residue sequence ";-1!=fastaSequenceTitleTwo.search(/[^\s]/)&&(stringToReturn=stringToReturn+
'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+sequenceTwo.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getGeneticCodeMatchExp(arrayOfPatterns){for(var geneticCodeMatchExp=Array(arrayOfPatterns.length),j=0,v75=j<arrayOfPatterns.length;v75;){var v75=geneticCodeMatchExp,v74=j;introspect(JAM.policy.p5)var v619=arrayOfPatterns[j];v619=v619.match(/\/.+\//)+"gi";v619=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v619+" }"):JAM.call(eval,null,[v619]);v75[v74]=v619;j+=1;v75=j<arrayOfPatterns.length}return geneticCodeMatchExp}
function getGeneticCodeMatchResult(arrayOfPatterns){for(var geneticCodeMatchResult=Array(arrayOfPatterns.length),j=0,v81=j<arrayOfPatterns.length;v81;){var v81=geneticCodeMatchResult,v78=j;introspect(JAM.policy.p5)var v543=arrayOfPatterns[j];v543=v543.match(/=[a-zA-Z\*]/).toString();v81[v78]=v543;v81=geneticCodeMatchResult;v78=j;introspect(JAM.policy.p5)v543=geneticCodeMatchResult[j];v543=v543.replace(/=/g,"");v81[v78]=v543;j+=1;v81=j<arrayOfPatterns.length}return geneticCodeMatchResult}
function getInfoFromTitleAndSequence(sequence){var fastaSequenceTitle=title,stringToReturn="Results for "+sequence.length+" residue sequence ";-1!=fastaSequenceTitle.search(/[^\s]/)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitle+'"');stringToReturn=stringToReturn+' starting "'+sequence.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}
function getInfoFromTitleAndSequenceAndTopology(fastaSequenceTitle,sequence,topology){topology="Results for "+topology+" "+sequence.length+" residue sequence ";-1!=fastaSequenceTitle.search(/[^\s]/)&&(topology=topology+'"'+fastaSequenceTitle+'"');topology=topology+' starting "'+sequence.substring(0,10)+'"';return'<div class="info">'+topology+"</div>\n"}
function getPairwiseAlignTitle(fastaSequenceTitleOne,sequenceOne,fastaSequenceTitleTwo,sequenceTwo){var stringToReturn="Alignment results for "+sequenceOne.length+" residue sequence ";-1!=fastaSequenceTitleOne.search(/[^\s]/)&&(stringToReturn=stringToReturn+'"'+fastaSequenceTitleOne+'"');stringToReturn=stringToReturn+' starting "'+sequenceOne.substring(0,10)+'"\n';stringToReturn=stringToReturn+"and "+sequenceTwo.length+" residue sequence ";-1!=fastaSequenceTitleTwo.search(/[^\s]/)&&(stringToReturn=
stringToReturn+'"'+fastaSequenceTitleTwo+'"');stringToReturn=stringToReturn+' starting "'+sequenceTwo.substring(0,10)+'"';return'<div class="info">'+stringToReturn+"</div>\n"}function getRandomSequence(components,lengthOut){for(var sequenceArray=[],tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=Math.floor(Math.random()*components.length),tempNum=components[tempNum],sequenceArray.push(tempNum),j+=1,tempNum=j<lengthOut;return sequenceArray.join("")}
function getSequenceFromFasta(sequenceRecord){-1!=sequenceRecord.search(/\>[^\f\n\r]+[\f\n\r]/)&&(sequenceRecord=sequenceRecord.replace(/\>[^\f\n\r]+[\f\n\r]/,""));return sequenceRecord}
function getTitleFromFasta(sequenceRecord){var fastaTitle="Untitled";-1!=sequenceRecord.search(/\>[^\f\n\r]+[\f\n\r]/)&&(fastaTitle=sequenceRecord.match(/\>[^\f\n\r]+[\f\n\r]/,"").toString(),fastaTitle=fastaTitle.replace(/\>|[\f\n\r]/g,""),fastaTitle=fastaTitle.replace(/\s{2,}/g," "),fastaTitle=fastaTitle.replace(/[\<\>]/gi,""));return fastaTitle}
function moreExpressionCheck(expressionToCheck){var v417=-1!=expressionToCheck.search(/\[[A-Za-z\|]*\[/);v417||(v417=-1!=expressionToCheck.search(/\][A-Za-z\|]*\]/),v417||(v417=-1!=expressionToCheck.search(/\[\]/),v417||(v417=-1!=expressionToCheck.search(/\/[A-Za-z\|]*\]/),v417||(v417=-1!=expressionToCheck.search(/\[[A-Za-z\|]*\//),v417||(v417=-1!=expressionToCheck.search(/\|\|/),v417||(v417=-1!=expressionToCheck.search(/\/\|/),v417||(v417=-1!=expressionToCheck.search(/\|\//),v417||(v417=-1!=expressionToCheck.search(/\[.\]/),
v417||(v417=-1!=expressionToCheck.search(/\</))||(v417=-1!=expressionToCheck.search(/\>/))))))))));return v417?!1:!0}function openForm(){var v107=outputWindow.document;JAM.call(v107.write,v107,['<form action="">\n']);return!0}function openPre(){var v108=outputWindow.document;JAM.call(v108.write,v108,["<pre>"]);v108=outputWindow.document;JAM.call(v108.write,v108,['<div class="pre">'])}
function openTextArea(){var v110=outputWindow.document;JAM.call(v110.write,v110,['<br /><textarea rows="6" cols="61">\n']);return!0}function openWindow(){var title="DNA Molecular Weight";_openWindow(title)}
function _openWindow(title){var isColor=!0;outputWindow=JAM.call(JAM.get(window,"open",JAM.policy.p1),window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"]);outputWindow.focus();var v111=outputWindow.document;JAM.call(v111.write,v111,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n']);
isColor?(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; background-color: #66FF00}\nspan.two, td.two {color: #000000; background-color: #FFFF66}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FF66FF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FF9933}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #990066; background-color: #FFFFFF}\ntd.many {color: #000000}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\n</style>\n'])):
(isColor=outputWindow.document,JAM.call(isColor.write,isColor,['<style type="text/css">\nbody.main {font-size: medium; font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF; margin: 0 auto; padding: 0}\ndiv.pre {font-size: medium; color: #000000; background-color: #FFFFFF; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.none, td.none {color: #000000; background-color: #FFFFFF}\nspan.one, td.one {color: #000000; text-decoration: underline; background-color: #FFFFFF}\nspan.two, td.two {color: #000000; font-style: italic; background-color: #FFFFFF}\nspan.three, td.three {color: #000000; background-color: #FFFFFF}\nspan.forward_primer, td.forward_primer {color: #000000; background-color: #FFFFFF}\nspan.reverse_primer, td.reverse_primer {color: #000000; background-color: #FFFFFF}\nspan.current_sequence {color: #000000; background-color: #FFFFFF}\nspan.mutated_sequence {color: #000000; text-decoration: underline; background-color: #FFFFFF}\ntd.many {color: #000000; background-color: #FFFFFF}\ntd.title {font-weight: bold; color: #000000; background-color: #FFFFFF}\nimg {display: none}\n</style>\n']));
isColor=outputWindow.document;JAM.call(isColor.write,isColor,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"]);outputWindow.status="Please Wait."}function openWindowAlign(title){_openWindowAlign(title)}
function _openWindowAlign(title){var isBackground=!0;outputWindow=JAM.call(JAM.get(window,"open",JAM.policy.p1),window,["","my_new_window","toolbar=no, location=no, directories=no, status=yes, menubar=yes, scrollbars=yes, resizable=yes, copyhistory=no, width=800, height=400"]);outputWindow.focus();var v119=outputWindow.document;JAM.call(v119.write,v119,['<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html lang="en">\n<head>\n<title>Sequence Manipulation Suite</title>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n']);
isBackground?(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {font-size: x-large; color: #000000; text-align: left; background-color: #FFFFFF}\ndiv.info {font-weight: bold}\nspan.ident {color: #FFFFFF; background-color: #000000}\nspan.sim {color: #FFFFFF; background-color: #666666}\nspan.g, span.a, span.v, span.l, span.i {color: #000000; background-color: #C0C0C0}\nspan.f, span.y, span.w {color: #000000; background-color: #FF6600}\nspan.c, span.m {color: #000000; background-color: #FFFF00}\nspan.s, span.t {color: #000000; background-color: #66FF00}\nspan.k, span.r, span.h {color: #000000; background-color: #FF0000}\nspan.d, span.e {color: #000000; background-color: #0066FF}\nspan.n, span.q {color: #000000; background-color: #996633}\nspan.p {color: #000000; background-color: #FF99FF}\n</style>\n'])):
(isBackground=outputWindow.document,JAM.call(isBackground.write,isBackground,['<style type="text/css">\nbody.main {font-family: arial, sans-serif; color: #000000; background-color: #FFFFFF}\ndiv.pre {font-size: medium; color: #000000; font-family: courier, sans-serif; white-space: pre}\ndiv.title {display: none}\ndiv.info {font-weight: bold}\nspan.ident {color: #000000; font-weight: bold; text-decoration: underline; background-color: #FFFFFF}\nspan.sim {color: #000000; font-weight: bold; background-color: #FFFFFF}\nspan.diff {color: #999999; background-color: #FFFFFF}\nspan.g, span.a, span.v, span.l, span.i {color: #CC33CC; background-color: #FFFFFF}\nspan.f, span.y, span.w {color: #FF6600; background-color: #FFFFFF}\nspan.c, span.m {color: #FFCC00; background-color: #FFFFFF}\nspan.s, span.t {color: #CCFF00; background-color: #FFFFFF}\nspan.k, span.r, span.h {color: #FF0000; background-color: #FFFFFF}\nspan.d, span.e {color: #0000FF; background-color: #FFFFFF}\nspan.n, span.q {color: #996633; background-color: #FFFFFF}\nspan.p {color: #00FFCC; background-color: #FFFFFF}\nimg {display: none}\n</style>\n']));
isBackground=outputWindow.document;JAM.call(isBackground.write,isBackground,['</head>\n<body class="main">\n<div class="title">'+title+" results</div>\n"]);outputWindow.status="Please Wait."}function removeFormatting(sequence){return sequence.replace(/[\d\s]/g,"")}function removeNonDna(sequence){return sequence.replace(/[^gatucryswkmbdhvnxGATUCRYSWKMBDHVNX]/g,"")}function removeNonDnaStrict(sequence){return sequence.replace(/[^gatucGATUC]/g,"")}
function removeNonProtein(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,"")}function removeNonProteinStrict(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZacdefghiklmnpqrstvwyz\*]/g,"")}function removeNonProteinAllowDegen(sequence){return sequence.replace(/[^ABCDEFGHIKLMNPQRSTVWYXZabcdefghiklmnpqrstvwyxz\*]/g,"")}function removeNonProteinAllowX(sequence){return sequence.replace(/[^ACDEFGHIKLMNPQRSTVWYZXacdefghiklmnpqrstvwyzx\*]/g,"")}
function removeWhiteSpace(text){return text.replace(/\s/g,"")}function removeNonLetters(sequence){return sequence.replace(/[^A-Z]/gi,"")}function reverse(dnaSequence){var tempDnaArray=[];-1!=dnaSequence.search(/./)&&(tempDnaArray=dnaSequence.match(/./g),tempDnaArray=tempDnaArray.reverse(),dnaSequence=tempDnaArray.join(""));return dnaSequence}
function rightNum(theNumber,sequenceToAppend,lengthOfColumn,tabIn){var j=0,tempString="";theNumber=theNumber.toString();for(var j=theNumber.length,v128=j<lengthOfColumn;v128;)tempString+=" ",j+=1,v128=j<lengthOfColumn;theNumber=tempString+theNumber+" ";return sequenceToAppend=sequenceToAppend+theNumber+tabIn}
function testScript(){function v1(str,p1,offset,s){return p1+"X"}var testArray=[],testString="1234567890";testArray.push(testString);if(testArray[0]!=testString)return alert("Array object push method not supported. See browser compatibility page."),!1;testString="1\n2\n3";testArray=/^2$/m;if(-1==testString.search(testArray))return alert("Regular expression 'm' flag not supported. See browser compatibility page."),!1;testString=!1;try{testArray=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { Exception handling not supported. Check browser compatibility page. }"):
JAM.call(eval,null,["Exception handling not supported. Check browser compatibility page."])}catch(e){testString=!0}testString||alert("Exception handling not supported. See browser compatibility page.");testString="123";testString=testString.replace(/(\d)/g,v1);if("1X2X3X"!=testString)return alert("Nested function in String replace method not supported. See browser compatibility page."),!1;testString=2489.8237;return 2489.824!=testString.toFixed(3)?(alert("Number toFixed() method not supported. See browser compatibility page."),
!1):2489.8!=testString.toPrecision(5)?(alert("Number toPrecision() method not supported. See browser compatibility page."),!1):!0}function verifyDigits(theNumber){if(-1==theNumber.search(/\d/))return alert("Please enter a number"),!1}function verifyEmbl(emblFile){var v432=-1==emblFile.search(/ID/);v432||(v432=-1==emblFile.search(/AC/),v432||(v432=-1==emblFile.search(/DE/))||(v432=-1==emblFile.search(/SQ/)));return v432?(alert("Please enter the contents of an EMBL file."),!1):!0}
function verifyMaxDigits(theNumber,maxInput){if(-1==theNumber.search(/\d/))return alert("Please enter a number."),!1;if(theNumber>maxInput)return alert("Please enter a number less than or equal to "+maxInput+"."),!1}function verifyDna(dnaSequence){-1!=dnaSequence.search(/[^gatucryswkmbdhvnx\s]/i)&&alert("The sequence contains non-DNA characters, which will be omitted.");return!0}
function verifyProtein(proteinSequence){-1!=proteinSequence.search(/[^acdefghiklmnpqrstvwyz\*\s]/i)&&alert("The sequence contains non-protein characters, which will be omitted.");return!0}function verifyGenBank(genBankFile){var v437=-1==genBankFile.search(/LOCUS/);v437||(v437=-1==genBankFile.search(/DEFINITION/),v437||(v437=-1==genBankFile.search(/ACCESSION/))||(v437=-1==genBankFile.search(/ORIGIN/)));return v437?(alert("Please enter the contents of a GenBank file."),!1):!0}
function verifyGenBankFeat(genBankFile){var v438=-1==genBankFile.search(/LOCUS/);v438||(v438=-1==genBankFile.search(/DEFINITION/),v438||(v438=-1==genBankFile.search(/ACCESSION/))||(v438=-1==genBankFile.search(/ORIGIN/)));return v438?(alert("Please enter the contents of a GenBank file."),!1):-1==genBankFile.search(/FEATURES {13}/)?(alert("The file has no defined features."),!1):!0}
function verifyEmblFeat(emblFile){var v440=-1==emblFile.search(/ID/);v440||(v440=-1==emblFile.search(/AC/),v440||(v440=-1==emblFile.search(/DE/))||(v440=-1==emblFile.search(/SQ/)));return v440?(alert("Please enter the contents of an EMBL file."),!1):-1==emblFile.search(/^FT/m)?(alert("The file has no defined features."),!1):!0}
function writeGroupNum(text,tabIn,groupSize,basePerLine,startBase,stopBase){startBase=parseInt(startBase);var k=0,lineOfText="",sepChar=" ";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(var v156=startBase<stopBase;v156;){for(var lineOfText=rightNum(startBase+1,lineOfText,8,tabIn),v156=1,v153=v156<=basePerLine/groupSize;v153;){for(v153=k<groupSize;v153;)lineOfText+=text.charAt(k+startBase),k+=1,v153=k<groupSize;startBase+=groupSize;k=0;lineOfText+=sepChar;v156+=1;v153=v156<=basePerLine/
groupSize}v156=outputWindow.document;JAM.call(v156.write,v156,[lineOfText+"\n"]);lineOfText="";v156=startBase<stopBase}return!0}function writeGroupNumDna(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition);return!0}
function writeGroupNumDnaSetStart(text,tabIn,groupSize,basePerLine,startBase,stopBase,strands,numberPosition){var numberingAdjustment=0;function adjustNumbering(original,adjustment){var adjusted=original+adjustment,v445=0>adjustment;v445&&(v445=0<=adjusted);v445&&(adjusted+=1);return adjusted}startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);numberingAdjustment=parseInt(numberingAdjustment);for(lineNum=
startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v166=j<=basePerLine/groupSize;v166;){for(v166=k<groupSize;v166&&!(startBase+k>=stopBase);)lineOfText+=text.charAt(k+startBase),k+=1,v166=k<groupSize;lineOfText+=sepChar;startBase+=k;"above"==numberPosition&&(aboveNum+=rightNum(adjustNumbering(startBase,numberingAdjustment),"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v166=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,
aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+lineOfText+"\n"]),"two"==strands&&(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(adjustNumbering(lineNum,numberingAdjustment),"",8,tabIn)+complement(lineOfText)+"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"]))):"right"==numberPosition?(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[lineOfText+adjustNumbering(startBase,numberingAdjustment)+"\n"]),
"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+adjustNumbering(startBase,numberingAdjustment)+"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"]))):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"]),lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[lineOfText+"\n"]),"two"==strands&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[complement(lineOfText)+
"\n"]),lineOfText=outputWindow.document,JAM.call(lineOfText.write,lineOfText,["\n"])));lineOfText=aboveNum="";lineNum=startBase<stopBase}}
function writeGroupNumProtein(text,tabIn,groupSize,basePerLine,startBase,stopBase,numberPosition){startBase=parseInt(startBase);var k=0,lineOfText="",lineNum="",sepChar=" ",aboveNum="";groupSize=parseInt(groupSize);basePerLine=parseInt(basePerLine);for(lineNum=startBase<stopBase;lineNum;){for(var lineNum=startBase+1,j=1,v199=j<=basePerLine/groupSize;v199;){for(v199=k<groupSize;v199&&!(startBase+k>=stopBase);)lineOfText+=text.charAt(k+startBase),k+=1,v199=k<groupSize;lineOfText+=sepChar;startBase+=
k;"above"==numberPosition&&(aboveNum+=rightNum(startBase,"",groupSize,tabIn));if(startBase>=stopBase)break;k=0;j+=1;v199=j<=basePerLine/groupSize}"left"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[rightNum(lineNum,"",8,tabIn)+lineOfText+"\n"])):"right"==numberPosition?(aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+startBase+"\n"])):"above"==numberPosition&&(lineNum=outputWindow.document,JAM.call(lineNum.write,lineNum,[aboveNum+"\n"]),
aboveNum=outputWindow.document,JAM.call(aboveNum.write,aboveNum,[lineOfText+"\n"]));lineOfText=aboveNum="";lineNum=startBase<stopBase}return!0}
function writeMutatedSequence(sequence,components,numMut,firstIndexToMutate,lastIndexToMutate){var currentChar="",randNum=0,randNum=0,needNewChar="",componentsIndex=0;numMut=parseInt(numMut);firstIndexToMutate=parseInt(firstIndexToMutate);lastIndexToMutate=parseInt(lastIndexToMutate);var v462=sequence.length<=firstIndexToMutate;v462||(v462=0>lastIndexToMutate)||(v462=lastIndexToMutate<=firstIndexToMutate);v462&&(numMut=0);v462=0;for(randNum=v462<numMut;randNum;){randNum=sequence.length;randNum=Math.floor(Math.random()*
randNum);(currentChar=randNum<firstIndexToMutate)||(currentChar=randNum>lastIndexToMutate);if(currentChar)numMut+=1;else{currentChar=sequence.charAt(randNum);for(needNewChar=!0;needNewChar;){componentsIndex=Math.round(Math.random()*components.length);componentsIndex==components.length&&(componentsIndex=0);introspect(JAM.policy.p5)var v468=components[componentsIndex];v468!=currentChar&&(needNewChar=!1)}currentChar=sequence.substring(0,randNum);introspect(JAM.policy.p5)needNewChar=components[componentsIndex];
sequence=currentChar+needNewChar+sequence.substring(randNum+1,sequence.length)}v462+=1;randNum=v462<numMut}components=outputWindow.document;JAM.call(components.write,components,[addReturns(sequence)]);return!0}
function writeRandomSequence(components,lengthOut){for(var sequence="",tempNum=0,tempNum="",j=0,tempNum=j<lengthOut;tempNum;)tempNum=Math.floor(Math.random()*components.length),tempNum=components[tempNum],sequence+=tempNum,60==sequence.length&&(tempNum=outputWindow.document,JAM.call(tempNum.write,tempNum,[sequence+"\n"]),sequence=""),j+=1,tempNum=j<lengthOut;j=outputWindow.document;JAM.call(j.write,j,[sequence+"\n"]);return!0}
function writeRestrictionSites(sequence,arrayOfItems,dnaConformation){var lookAhead=50,lowerLimit=0,upperLimit=sequence.length,shiftValue=0,cutDistance,matchExp,matchPosition,backGroundClass;backGroundClass=0;"circular"==dnaConformation&&(shiftValue=sequence.substring(0,lookAhead).length,sequence=sequence.substring(sequence.length-lookAhead,sequence.length)+sequence+sequence.substring(0,lookAhead),lowerLimit=0+shiftValue,upperLimit+=shiftValue);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,
dnaConformation,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n']);dnaConformation=outputWindow.document;JAM.call(dnaConformation.write,dnaConformation,['<tr><td class="title" width="200px">Site:</td><td class="title">Positions:</td></tr>\n']);dnaConformation=0;for(lookAhead=dnaConformation<arrayOfItems.length;lookAhead;){lookAhead="none";introspect(JAM.policy.p5)matchExp=arrayOfItems[dnaConformation];matchExp=matchExp.match(/\/.+\//)+"gi";matchExp=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+
matchExp+" }"):JAM.call(eval,null,[matchExp]);introspect(JAM.policy.p5)cutDistance=arrayOfItems[dnaConformation];cutDistance=parseFloat(cutDistance.match(/\)\D*\d+/).toString().replace(/\)\D*/,""));for(matchPosition=matchExp.exec(sequence);matchPosition;){matchPosition=matchExp.lastIndex-cutDistance;var v481=matchPosition>=lowerLimit;v481&&(v481=matchPosition<upperLimit);v481&&(backGroundClass+=1,lookAhead=lookAhead+", "+(matchPosition-shiftValue+1));matchExp.lastIndex=matchExp.lastIndex-RegExp.lastMatch.length+
1;matchPosition=matchExp.exec(sequence)}-1!=lookAhead.search(/\d/)&&(lookAhead=lookAhead.replace(/none,\s*/,""));backGroundClass=0==backGroundClass?"none":1==backGroundClass?"one":2==backGroundClass?"two":3==backGroundClass?"three":"many";matchExp=outputWindow.document;cutDistance='<tr><td class="'+backGroundClass+'">';introspect(JAM.policy.p5)matchPosition=arrayOfItems[dnaConformation];JAM.call(matchExp.write,matchExp,[cutDistance+matchPosition.match(/\([^\(]+\)/).toString().replace(/\(|\)/g,"")+
'</td><td class="'+backGroundClass+'">'+lookAhead+"</td></tr>\n"]);backGroundClass=0;dnaConformation+=1;lookAhead=dnaConformation<arrayOfItems.length}sequence=outputWindow.document;JAM.call(sequence.write,sequence,["</tbody></table>\n"]);return!0}
function writeSequenceStats(sequence,arrayOfItems){var originalLength=sequence.length,v254=outputWindow.document;JAM.call(v254.write,v254,['<table border="1" width="100%" cellspacing="0" cellpadding="2"><tbody>\n']);v254=outputWindow.document;JAM.call(v254.write,v254,['<tr><td class="title">Pattern:</td><td class="title">Times found:</td><td class="title">Percentage:</td></tr>\n']);for(var v254=0,v265=v254<arrayOfItems.length;v265;){v265=0;introspect(JAM.policy.p5)var v490=arrayOfItems[v254];v490=
v490.match(/\/[^\/]+\//)+"gi";v490=JAM.isEval(eval)?eval("introspect(JAM.policy.pFull) { "+v490+" }"):JAM.call(eval,null,[v490]);-1!=sequence.search(v490)&&(v265=sequence.match(v490).length);var v490=0,v587=originalLength+1;introspect(JAM.policy.p5)var v689=arrayOfItems[v254];if(0<v587-parseFloat(v689.match(/\d+/))){v490=100*v265;v587=originalLength+1;introspect(JAM.policy.p5)v689=arrayOfItems[v254];v490/=v587-parseFloat(v689.match(/\d+/))}v587=outputWindow.document;introspect(JAM.policy.p5)v689=
arrayOfItems[v254];JAM.call(v587.write,v587,["<tr><td>"+v689.match(/\([^\(]+\)\b/).toString().replace(/\(|\)/g,"")+"</td><td>"+v265+"</td><td>"+v490.toFixed(2)+"</td></tr>\n"]);v254+=1;v265=v254<arrayOfItems.length}originalLength=outputWindow.document;JAM.call(originalLength.write,originalLength,["</tbody></table>\n"]);return!0}
function writeShuffledSequence(sequence){for(var tempSeq="",tempChar="",tempString2=tempChar="",tempChar=tempString2=0,tempChar=0<sequence.length;tempChar;)tempChar=sequence.length,tempString2=Math.floor(Math.random()*tempChar),tempChar=sequence.charAt(tempString2),tempSeq+=tempChar,tempChar=sequence.substring(0,tempString2),tempString2=sequence.substring(tempString2+1,sequence.length),sequence=tempChar+tempString2,60==tempSeq.length&&(tempChar=outputWindow.document,JAM.call(tempChar.write,tempChar,
[tempSeq+"\n"]),tempSeq=""),tempChar=0<sequence.length;sequence=outputWindow.document;JAM.call(sequence.write,sequence,[tempSeq+"\n"]);return!0}
function dnaMw(){var theDocument=document,newDna="",maxInput=2E5;if(!1!=testScript()){var v502=!1==checkFormElement(theDocument.forms[0].elements[0]);v502||(v502=!1==checkSequenceLength(theDocument.forms[0].elements[0].value,maxInput));if(!v502){openWindow();maxInput=getArrayOfFasta(theDocument.forms[0].elements[0].value);v502=0;for(newDna=v502<maxInput.length;newDna;){introspect(JAM.policy.p5)newDna=maxInput[v502];newDna=getSequenceFromFasta(newDna);introspect(JAM.policy.p5)var v280=maxInput[v502];
title=getTitleFromFasta(v280);newDna=_removeNonPrimer(newDna);v280=outputWindow.document;JAM.call(v280.write,v280,[getInfoFromTitleAndSequence(newDna)]);var v280=theDocument.forms[0].elements[4].options,v597=theDocument.forms[0].elements[4].selectedIndex;introspect(JAM.policy.p5)v280=v280[v597];var v280=v280.value,v597=theDocument.forms[0].elements[5].options,v599=theDocument.forms[0].elements[5].selectedIndex;introspect(JAM.policy.p5)v597=v597[v599];writeDnaMw(newDna,v280,v597.value);newDna=outputWindow.document;
JAM.call(newDna.write,newDna,["<br />\n<br />\n"]);v502+=1;newDna=v502<maxInput.length}closeWindow()}}}
function writeDnaMw(sequence,strandType,topology){var OH=17.01;if("single"==strandType)strandType=_molecularWeight(sequence),1==strandType.length?(strandType=parseFloat(strandType[0]),"circular"==topology&&(strandType-=OH),strandType=strandType.toFixed(2),topology=outputWindow.document,JAM.call(topology.write,topology,[strandType+" Da"])):2==strandType.length&&(sequence=parseFloat(strandType[0]),strandType=parseFloat(strandType[1]),"circular"==topology&&(sequence-=OH,strandType-=OH),sequence=sequence.toFixed(2),
strandType=strandType.toFixed(2),topology=outputWindow.document,JAM.call(topology.write,topology,[sequence+" to "+strandType+" Da"]));else if("double"==strandType){strandType=_molecularWeight(sequence);sequence=_molecularWeight(reverse(complement(sequence)));var v512=1==strandType.length;v512&&(v512=1==sequence.length);if(v512)strandType=parseFloat(strandType[0]),sequence=parseFloat(sequence[0]),"circular"==topology&&(strandType-=OH,sequence-=OH),strandType+=sequence,strandType=strandType.toFixed(2),
topology=outputWindow.document,JAM.call(topology.write,topology,[strandType+" Da"]);else if((v512=2==strandType.length)&&(v512=2==sequence.length),v512){var v512=parseFloat(strandType[0]),mw_reverse_lower=parseFloat(sequence[0]);strandType=parseFloat(strandType[1]);var mw_reverse_upper=parseFloat(sequence[1]);"circular"==topology&&(v512-=OH,mw_reverse_lower-=OH,strandType-=OH,mw_reverse_upper-=OH);sequence=v512+mw_reverse_lower;strandType+=mw_reverse_upper;sequence=sequence.toFixed(2);strandType=
strandType.toFixed(2);topology=outputWindow.document;JAM.call(topology.write,topology,[sequence+" to "+strandType+" Da"])}}}function _containsOnlyNonDegenerates(sequence){return-1==sequence.search(/[^gatc]/i)?!0:!1}function _molecularWeight(sequence){return _containsOnlyNonDegenerates(sequence)?_molecularWeightNonDegen(sequence):_molecularWeightDegen(sequence)}function _molecularWeightNonDegen(sequence){var results=[];sequence=_mw(sequence);results[0]=sequence;return results}
function _mw(sequence){var g=_getBaseCount(sequence,"g"),a=_getBaseCount(sequence,"a"),t=_getBaseCount(sequence,"t");sequence=_getBaseCount(sequence,"c");return 329.21*g+313.21*a+304.2*t+289.18*sequence+17.01}
function _molecularWeightDegen(sequence){var lowerBoundsSequence=sequence,upperBoundsSequence=sequence,lowerBoundsSequence=lowerBoundsSequence.replace(/r/gi,"a"),lowerBoundsSequence=lowerBoundsSequence.replace(/y/gi,"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/s/gi,"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/w/gi,"t"),lowerBoundsSequence=lowerBoundsSequence.replace(/k/gi,"t"),lowerBoundsSequence=lowerBoundsSequence.replace(/m/gi,"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/b/gi,
"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/d/gi,"t"),lowerBoundsSequence=lowerBoundsSequence.replace(/h/gi,"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/v/gi,"c"),lowerBoundsSequence=lowerBoundsSequence.replace(/n/gi,"c"),upperBoundsSequence=upperBoundsSequence.replace(/r/gi,"g"),upperBoundsSequence=upperBoundsSequence.replace(/y/gi,"t"),upperBoundsSequence=upperBoundsSequence.replace(/s/gi,"g"),upperBoundsSequence=upperBoundsSequence.replace(/w/gi,"a"),upperBoundsSequence=upperBoundsSequence.replace(/k/gi,
"g"),upperBoundsSequence=upperBoundsSequence.replace(/m/gi,"a"),upperBoundsSequence=upperBoundsSequence.replace(/b/gi,"g"),upperBoundsSequence=upperBoundsSequence.replace(/d/gi,"g"),upperBoundsSequence=upperBoundsSequence.replace(/h/gi,"a"),upperBoundsSequence=upperBoundsSequence.replace(/v/gi,"g"),upperBoundsSequence=upperBoundsSequence.replace(/n/gi,"g");sequence=[];lowerBoundsSequence=_molecularWeightNonDegen(lowerBoundsSequence);sequence[0]=lowerBoundsSequence;lowerBoundsSequence=_molecularWeightNonDegen(upperBoundsSequence);
sequence[1]=lowerBoundsSequence;return sequence}function _getBaseCount(sequence,base){var basePattern=RegExp(base,"gi");return-1!=sequence.search(basePattern)?sequence.match(basePattern).length:0}function _removeNonPrimer(sequence){sequence.replace(/u/g,"t");sequence.replace(/U/g,"T");return sequence.replace(/[^gatcryswkmbdhvnGATCRYSWKMBDHVN]/g,"")}JAM.set(document,"onload",v2);JAM.set(document.getElementById("submitbtn"),"onclick",v3);JAM.set(document.getElementById("clearbtn"),"onclick",v4);

JAM.stopProfile('load');
